/**
 * Pipeline Capability Matrix
 * 
 * Maps 100+ transformation pipelines to product verticals and provider support
 * Based on the competitive landscape: Presentations, AI Avatar, Video, L&D, Marketing, etc.
 */

import type { ProviderId } from './types';

// ============================================
// PRODUCT VERTICALS (Column Headers)
// ============================================
export type ProductVertical =
  | 'presentations'      // Slide decks, pitch decks, training decks
  | 'ai_avatar'          // AI Avatar video generation
  | 'generative_video'   // Text/Image to video, animations
  | 'video_repurposing'  // Long-to-short, video editing
  | 'social_publishing'  // TikTok, Reels, YouTube, LinkedIn
  | 'ld_training'        // L&D, SCORM, compliance training
  | 'marketing_ads'      // Ads, campaigns, promotional content
  | 'localization'       // Multi-language dubbing, translation
  | 'enterprise'         // SSO, compliance, API access
  | 'data_analytics'     // Data visualization, reports
  | 'internal_comms'     // Town halls, announcements
  | 'customer_education' // Help videos, onboarding
  | 'sales_enablement'   // Demo videos, proposals
  | 'live_realtime';     // Live streaming, real-time

// ============================================
// PRICING TIERS
// ============================================
export type PricingTier = 'free' | 'starter' | 'pro' | 'enterprise';

// ============================================
// CAPABILITY SUPPORT LEVEL
// ============================================
export type SupportLevel = 
  | 'full'       // Fully supported
  | 'partial'    // Partially supported
  | 'planned'    // On roadmap
  | 'none';      // Not supported

// ============================================
// PIPELINE CAPABILITY ENTRY
// ============================================
export interface PipelineCapabilityEntry {
  pipelineId: string;
  displayName: string;
  description: string;
  category: PipelineCategory;
  
  // Product vertical support
  verticalSupport: Record<ProductVertical, SupportLevel>;
  
  // Provider support
  primaryProviders: ProviderId[];
  fallbackProviders: ProviderId[];
  
  // Tier requirements
  minimumTier: PricingTier;
  recommendedTier: PricingTier;
  
  // Capabilities required
  requiredCapabilities: string[];
  optionalCapabilities: string[];
  
  // Rich content considerations
  richContentFeatures: RichContentFeature[];
  previewSupport: PreviewSupport;
  
  // Metrics
  estimatedDurationSeconds: number;
  qualityScore: number; // 0-100
  automationLevel: number; // 0-100 (how automated vs manual)
}

// ============================================
// PIPELINE CATEGORIES
// ============================================
export type PipelineCategory =
  | 'presentation'
  | 'video_production'
  | 'content_repurposing'
  | 'training_ld'
  | 'marketing_advertising'
  | 'social_media'
  | 'sales_enablement'
  | 'customer_education'
  | 'localization'
  | 'data_analytics'
  | 'internal_comms'
  | 'live_realtime'
  | 'immersive_3d'
  | 'audio_sfx';

// ============================================
// RICH CONTENT FEATURES
// ============================================
export type RichContentFeature =
  | 'animated_charts'      // Animated data visualizations
  | 'ai_voiceover'         // AI-generated narration
  | 'background_music'     // Auto-generated/selected music
  | 'sfx_audio'            // Sound effects
  | 'motion_graphics'      // Animated text, transitions
  | 'ai_avatars'           // Digital presenters
  | 'lip_sync'             // Audio-video lip synchronization
  | 'captions_subtitles'   // Multi-language captions
  | 'interactive_elements' // Clickable, quizzes
  | '3d_models'            // 3D object rendering
  | 'vr_ar_content'        // VR/AR experiences
  | 'dynamic_data'         // Live data updates
  | 'brand_consistency'    // Brand kit enforcement
  | 'multi_language'       // Multi-language versions
  | 'responsive_design'    // Multi-device optimization
  | 'collaboration'        // Real-time collaboration
  | 'version_control'      // History and rollback
  | 'analytics_tracking';  // View/engagement analytics

// ============================================
// PREVIEW SUPPORT
// ============================================
export interface PreviewSupport {
  realTimePreview: boolean;      // Can preview while editing
  scrubbing: boolean;            // Timeline scrubbing for video
  multiDevice: boolean;          // Preview on different devices
  interactivePreview: boolean;   // Preview interactions
  audioPreview: boolean;         // Preview with audio
  exportPreview: boolean;        // Preview final export format
  collaborativePreview: boolean; // Share preview links
}

// ============================================
// PROVIDER VERTICAL SUPPORT MATRIX
// Maps providers to their vertical strengths
// ============================================
export const PROVIDER_VERTICAL_MATRIX: Record<ProviderId, {
  name: string;
  logo?: string;
  verticals: Partial<Record<ProductVertical, SupportLevel>>;
  pricingTier: PricingTier;
  strengths: string[];
}> = {
  openai: {
    name: 'OpenAI',
    verticals: {
      presentations: 'full',
      ai_avatar: 'partial',
      generative_video: 'full',
      ld_training: 'full',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'full',
    },
    pricingTier: 'pro',
    strengths: ['GPT-4o Vision', 'DALL-E 3', 'Whisper STT', 'Sora Video'],
  },
  claude: {
    name: 'Anthropic Claude',
    verticals: {
      presentations: 'full',
      ld_training: 'full',
      marketing_ads: 'full',
      enterprise: 'full',
      data_analytics: 'full',
      customer_education: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Long context', 'Healthcare compliance', 'Technical writing'],
  },
  gemini: {
    name: 'Google Gemini',
    verticals: {
      presentations: 'full',
      generative_video: 'full',
      video_repurposing: 'full',
      localization: 'full',
      data_analytics: 'full',
      enterprise: 'full',
    },
    pricingTier: 'starter',
    strengths: ['1M+ context', 'Veo video', 'Multi-modal', 'Translation'],
  },
  deepseek: {
    name: 'DeepSeek',
    verticals: {
      presentations: 'full',
      ld_training: 'full',
      localization: 'partial',
      data_analytics: 'full',
    },
    pricingTier: 'starter',
    strengths: ['CJK optimization', 'Cost-efficient', 'Technical content'],
  },
  alibaba: {
    name: 'Alibaba Cloud',
    verticals: {
      presentations: 'full',
      ai_avatar: 'full',
      generative_video: 'full',
      localization: 'full',
      enterprise: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Qwen-MT translation', 'CosyVoice TTS', 'WAN 2.2 video', 'Paraformer STT'],
  },
  azure: {
    name: 'Microsoft Azure',
    verticals: {
      presentations: 'full',
      ai_avatar: 'full',
      ld_training: 'full',
      enterprise: 'full',
      localization: 'full',
      internal_comms: 'full',
    },
    pricingTier: 'enterprise',
    strengths: ['Neural TTS', 'Visemes lip-sync', 'Form Recognizer OCR', 'HIPAA compliance'],
  },
  modelslab: {
    name: 'ModelsLab',
    verticals: {
      presentations: 'full',
      ai_avatar: 'full',
      generative_video: 'full',
      marketing_ads: 'full',
      social_publishing: 'full',
    },
    pricingTier: 'pro',
    strengths: ['FLUX Pro images', 'AnimateDiff video', '3D mesh', 'Fast generation'],
  },
  elevenlabs: {
    name: 'ElevenLabs',
    verticals: {
      presentations: 'full',
      ai_avatar: 'full',
      generative_video: 'full',
      ld_training: 'full',
      localization: 'full',
      marketing_ads: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Premium TTS', 'Voice cloning', 'Multi-language', 'SFX generation'],
  },
  deepl: {
    name: 'DeepL',
    verticals: {
      presentations: 'full',
      localization: 'full',
      ld_training: 'full',
      marketing_ads: 'full',
    },
    pricingTier: 'pro',
    strengths: ['European languages', 'Context-aware translation', 'Glossary support'],
  },
  replicate: {
    name: 'Replicate',
    verticals: {
      generative_video: 'full',
      ai_avatar: 'partial',
      immersive_3d: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Open-source models', 'Custom models', '3D generation'],
  },
  supabase: {
    name: 'Supabase',
    verticals: {
      enterprise: 'full',
      data_analytics: 'full',
      collaboration: 'full',
    },
    pricingTier: 'starter',
    strengths: ['Auth', 'Database', 'Storage', 'Edge Functions', 'Real-time'],
  },
  stripe: {
    name: 'Stripe',
    verticals: {
      enterprise: 'full',
    },
    pricingTier: 'starter',
    strengths: ['Payments', 'Subscriptions', 'Billing Portal', 'Usage metering'],
  },
  stability: {
    name: 'Stability AI',
    verticals: {
      presentations: 'full',
      generative_video: 'full',
      marketing_ads: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Stable Diffusion', 'SDXL', 'Stable Video'],
  },
  huggingface: {
    name: 'Hugging Face',
    verticals: {
      presentations: 'partial',
      generative_video: 'partial',
      immersive_3d: 'full',
    },
    pricingTier: 'free',
    strengths: ['Open-source models', 'Custom fine-tuning', '3D models'],
  },
  google: {
    name: 'Google Cloud',
    verticals: {
      presentations: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Cloud Translation', 'Speech-to-Text', 'Vision API'],
  },
  microsoft: {
    name: 'Microsoft',
    verticals: {
      presentations: 'full',
      localization: 'full',
      enterprise: 'full',
      internal_comms: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Translator API', 'Office integration', 'Teams integration'],
  },
  assemblyai: {
    name: 'AssemblyAI',
    verticals: {
      video_repurposing: 'full',
      ld_training: 'full',
      customer_education: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Transcription', 'Speaker diarization', 'Summarization'],
  },
  cohere: {
    name: 'Cohere',
    verticals: {
      presentations: 'partial',
      enterprise: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Embeddings', 'Semantic search', 'RAG optimization'],
  },
  runway: {
    name: 'Runway',
    verticals: {
      generative_video: 'full',
      ai_avatar: 'partial',
      marketing_ads: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Gen-2 video', 'Video editing', 'Motion brush'],
  },
  pika: {
    name: 'Pika Labs',
    verticals: {
      generative_video: 'full',
      social_publishing: 'full',
    },
    pricingTier: 'pro',
    strengths: ['Fast video generation', 'Social-optimized'],
  },
  suno: {
    name: 'Suno',
    verticals: {
      presentations: 'partial',
      generative_video: 'partial',
      marketing_ads: 'partial',
    },
    pricingTier: 'pro',
    strengths: ['AI music generation', 'Custom jingles'],
  },
  udio: {
    name: 'Udio',
    verticals: {
      presentations: 'partial',
      generative_video: 'partial',
      marketing_ads: 'partial',
    },
    pricingTier: 'pro',
    strengths: ['AI music generation', 'Instrumental tracks'],
  },
};

// ============================================
// COMPLETE PIPELINE CAPABILITY MATRIX
// ============================================
export const PIPELINE_CAPABILITY_MATRIX: PipelineCapabilityEntry[] = [
  // ═══════════════════════════════════════════════════════════════
  // PRESENTATION PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'idea-to-presentation',
    displayName: 'Idea → Presentation',
    description: 'Convert text prompt/topic into complete branded slide deck',
    category: 'presentation',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'partial',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'full',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'full',
      customer_education: 'full',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['openai', 'claude', 'gemini'],
    fallbackProviders: ['deepseek', 'alibaba'],
    minimumTier: 'starter',
    recommendedTier: 'pro',
    requiredCapabilities: ['ai_script_gen', 'slide_design', 'brand_kit'],
    optionalCapabilities: ['ai_images', 'data_viz', 'multi_language'],
    richContentFeatures: ['animated_charts', 'motion_graphics', 'brand_consistency'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 85,
    automationLevel: 90,
  },
  {
    pipelineId: 'document-to-presentation',
    displayName: 'Document → Presentation',
    description: 'Convert PDF, Word, or notes into branded presentation',
    category: 'presentation',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'partial',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'full',
      marketing_ads: 'partial',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'full',
      customer_education: 'full',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['azure', 'claude', 'gemini'],
    fallbackProviders: ['openai', 'deepseek'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['ocr_extraction', 'document_analysis', 'slide_design'],
    optionalCapabilities: ['ai_summarization', 'brand_kit'],
    richContentFeatures: ['animated_charts', 'motion_graphics', 'brand_consistency'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 240,
    qualityScore: 82,
    automationLevel: 85,
  },
  {
    pipelineId: 'data-to-presentation',
    displayName: 'Data → Presentation',
    description: 'Convert spreadsheets/analytics into data visualization deck',
    category: 'presentation',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'none',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'partial',
      marketing_ads: 'partial',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'full',
      internal_comms: 'full',
      customer_education: 'partial',
      sales_enablement: 'full',
      live_realtime: 'partial',
    },
    primaryProviders: ['openai', 'gemini', 'claude'],
    fallbackProviders: ['deepseek'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['data_analysis', 'chart_generation', 'slide_design'],
    optionalCapabilities: ['ai_narration', 'dynamic_data'],
    richContentFeatures: ['animated_charts', 'dynamic_data', 'brand_consistency'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 200,
    qualityScore: 88,
    automationLevel: 80,
  },
  {
    pipelineId: 'brand-to-templates',
    displayName: 'Brand → Templates',
    description: 'Convert brand guidelines into custom template library',
    category: 'presentation',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'none',
      generative_video: 'none',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'partial',
      marketing_ads: 'full',
      localization: 'none',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'full',
      customer_education: 'partial',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['gemini', 'deepseek'],
    fallbackProviders: ['openai'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['brand_analysis', 'style_extraction', 'template_generation'],
    optionalCapabilities: ['color_palette', 'font_matching'],
    richContentFeatures: ['brand_consistency', 'responsive_design'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 85,
    automationLevel: 75,
  },
  {
    pipelineId: 'presentation-to-video',
    displayName: 'Presentation → Video',
    description: 'Convert slide deck into narrated video presentation',
    category: 'presentation',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'partial',
      social_publishing: 'full',
      ld_training: 'full',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'full',
      customer_education: 'full',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['gemini', 'openai', 'elevenlabs'],
    fallbackProviders: ['azure', 'alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['slide_analysis', 'script_generation', 'tts_voice', 'video_composition'],
    optionalCapabilities: ['ai_avatar', 'background_music', 'captions'],
    richContentFeatures: ['ai_voiceover', 'motion_graphics', 'captions_subtitles', 'background_music'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 88,
    automationLevel: 85,
  },

  // ═══════════════════════════════════════════════════════════════
  // AI AVATAR VIDEO PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'script-to-talking-head',
    displayName: 'Script → Talking Head',
    description: 'Generate AI avatar video from written script',
    category: 'video_production',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'partial',
      social_publishing: 'full',
      ld_training: 'full',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'full',
      customer_education: 'full',
      sales_enablement: 'full',
      live_realtime: 'partial',
    },
    primaryProviders: ['modelslab', 'alibaba', 'azure'],
    fallbackProviders: ['replicate'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['avatar_generation', 'tts_voice', 'lip_sync'],
    optionalCapabilities: ['custom_avatar', 'gestures', 'background_replacement'],
    richContentFeatures: ['ai_avatars', 'lip_sync', 'ai_voiceover', 'captions_subtitles'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 90,
    automationLevel: 95,
  },
  {
    pipelineId: 'clone-to-personalized',
    displayName: 'Clone → Personalized Video',
    description: 'Use personal AI clone to create videos at scale',
    category: 'video_production',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'full',
      ld_training: 'partial',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'full',
      customer_education: 'partial',
      sales_enablement: 'full',
      live_realtime: 'partial',
    },
    primaryProviders: ['modelslab', 'alibaba'],
    fallbackProviders: ['replicate'],
    minimumTier: 'enterprise',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['avatar_cloning', 'voice_cloning', 'lip_sync'],
    optionalCapabilities: ['gesture_learning', 'style_transfer'],
    richContentFeatures: ['ai_avatars', 'lip_sync', 'ai_voiceover', 'multi_language'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 400,
    qualityScore: 92,
    automationLevel: 90,
  },
  {
    pipelineId: 'multilingual-dub',
    displayName: 'Multilingual Dubbing',
    description: 'Dub video into 50+ languages with lip-sync',
    category: 'localization',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'full',
      generative_video: 'partial',
      video_repurposing: 'full',
      social_publishing: 'full',
      ld_training: 'full',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'full',
      customer_education: 'full',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['elevenlabs', 'alibaba', 'azure'],
    fallbackProviders: ['deepl', 'google'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['translation', 'tts_multi_language', 'lip_sync', 'audio_mix'],
    optionalCapabilities: ['voice_cloning', 'accent_adaptation'],
    richContentFeatures: ['lip_sync', 'ai_voiceover', 'multi_language', 'captions_subtitles'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 360,
    qualityScore: 88,
    automationLevel: 85,
  },

  // ═══════════════════════════════════════════════════════════════
  // GENERATIVE VIDEO PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'text-to-full-video',
    displayName: 'Text → Full Video',
    description: 'Generate complete video from text description',
    category: 'video_production',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'partial',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'full',
      ld_training: 'partial',
      marketing_ads: 'full',
      localization: 'partial',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'partial',
      customer_education: 'partial',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'openai', 'gemini'],
    fallbackProviders: ['replicate', 'alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['video_generation', 'script_analysis', 'scene_composition'],
    optionalCapabilities: ['music_generation', 'sfx_auto', 'voiceover'],
    richContentFeatures: ['motion_graphics', 'ai_voiceover', 'background_music', 'sfx_audio'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 400,
    qualityScore: 85,
    automationLevel: 95,
  },
  {
    pipelineId: 'image-to-video',
    displayName: 'Image → Video',
    description: 'Animate still images into video content',
    category: 'video_production',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'partial',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'full',
      ld_training: 'partial',
      marketing_ads: 'full',
      localization: 'none',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'partial',
      customer_education: 'partial',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'alibaba', 'replicate'],
    fallbackProviders: ['stability'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['image_to_video', 'motion_estimation', 'interpolation'],
    optionalCapabilities: ['style_transfer', 'camera_motion'],
    richContentFeatures: ['motion_graphics', 'background_music'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 82,
    automationLevel: 95,
  },
  {
    pipelineId: 'vfx-composite',
    displayName: 'VFX Composite',
    description: 'Add visual effects and compositing to videos',
    category: 'video_production',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'partial',
      generative_video: 'full',
      video_repurposing: 'full',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'full',
      localization: 'none',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'replicate'],
    fallbackProviders: ['stability'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['vfx_generation', 'compositing', 'scene_analysis'],
    optionalCapabilities: ['green_screen', 'motion_tracking'],
    richContentFeatures: ['motion_graphics'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 80,
    automationLevel: 70,
  },

  // ═══════════════════════════════════════════════════════════════
  // VIDEO REPURPOSING PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'long-to-short-clips',
    displayName: 'Long → Short Clips',
    description: 'Extract TikTok/Reels/Shorts from long-form video',
    category: 'content_repurposing',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'none',
      generative_video: 'partial',
      video_repurposing: 'full',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'full',
      localization: 'partial',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'partial',
      customer_education: 'partial',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['gemini', 'openai'],
    fallbackProviders: ['claude'],
    minimumTier: 'starter',
    recommendedTier: 'pro',
    requiredCapabilities: ['video_analysis', 'scene_detection', 'highlight_extraction'],
    optionalCapabilities: ['auto_captions', 'aspect_ratio_crop'],
    richContentFeatures: ['captions_subtitles', 'responsive_design'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 120,
    qualityScore: 85,
    automationLevel: 90,
  },
  {
    pipelineId: 'video-to-blog',
    displayName: 'Video → Blog/Article',
    description: 'Convert video content into written blog posts',
    category: 'content_repurposing',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'none',
      generative_video: 'none',
      video_repurposing: 'full',
      social_publishing: 'full',
      ld_training: 'partial',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'partial',
      customer_education: 'full',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['gemini', 'claude', 'openai'],
    fallbackProviders: ['deepseek'],
    minimumTier: 'starter',
    recommendedTier: 'pro',
    requiredCapabilities: ['transcription', 'summarization', 'content_writing'],
    optionalCapabilities: ['seo_optimization', 'key_frame_extraction'],
    richContentFeatures: ['brand_consistency'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 88,
    automationLevel: 85,
  },
  {
    pipelineId: 'podcast-to-video',
    displayName: 'Podcast → Video',
    description: 'Convert audio podcast into video with visuals and captions',
    category: 'content_repurposing',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'partial',
      generative_video: 'full',
      video_repurposing: 'full',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'partial',
      localization: 'full',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['gemini', 'openai', 'modelslab'],
    fallbackProviders: ['alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['transcription', 'image_generation', 'video_composition'],
    optionalCapabilities: ['speaker_diarization', 'auto_chapters'],
    richContentFeatures: ['captions_subtitles', 'motion_graphics', 'background_music'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 82,
    automationLevel: 85,
  },
  {
    pipelineId: 'webinar-to-clips-deck',
    displayName: 'Webinar → Clips + Deck',
    description: 'Extract highlights and presentation from recorded webinar',
    category: 'content_repurposing',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'none',
      generative_video: 'partial',
      video_repurposing: 'full',
      social_publishing: 'full',
      ld_training: 'full',
      marketing_ads: 'full',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'full',
      customer_education: 'full',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['gemini', 'claude', 'openai'],
    fallbackProviders: ['assemblyai'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['transcription', 'highlight_extraction', 'slide_generation'],
    optionalCapabilities: ['qa_extraction', 'speaker_analysis'],
    richContentFeatures: ['captions_subtitles', 'animated_charts', 'brand_consistency'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 360,
    qualityScore: 85,
    automationLevel: 80,
  },

  // ═══════════════════════════════════════════════════════════════
  // L&D / TRAINING PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'course-to-interactive',
    displayName: 'Course → Interactive Modules',
    description: 'Convert course content into interactive training modules',
    category: 'training_ld',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'full',
      marketing_ads: 'none',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'partial',
      customer_education: 'full',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['openai', 'claude', 'elevenlabs'],
    fallbackProviders: ['gemini', 'azure'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['content_analysis', 'quiz_generation', 'scorm_export'],
    optionalCapabilities: ['ai_avatar', 'branching_logic'],
    richContentFeatures: ['interactive_elements', 'ai_avatars', 'captions_subtitles', 'analytics_tracking'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 400,
    qualityScore: 90,
    automationLevel: 75,
  },
  {
    pipelineId: 'sop-to-training',
    displayName: 'SOP → Training Video',
    description: 'Convert standard procedures into step-by-step training',
    category: 'training_ld',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'full',
      marketing_ads: 'none',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'partial',
      customer_education: 'full',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['claude', 'openai', 'elevenlabs'],
    fallbackProviders: ['azure', 'alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['document_analysis', 'script_generation', 'tts_voice'],
    optionalCapabilities: ['screen_recording_overlay', 'ai_avatar'],
    richContentFeatures: ['ai_voiceover', 'ai_avatars', 'captions_subtitles', 'interactive_elements'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 88,
    automationLevel: 85,
  },
  {
    pipelineId: 'compliance-to-certification',
    displayName: 'Compliance → SCORM Certification',
    description: 'Convert compliance requirements into SCORM-compliant modules',
    category: 'training_ld',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'full',
      marketing_ads: 'none',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'full',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['claude', 'openai', 'azure'],
    fallbackProviders: ['gemini'],
    minimumTier: 'enterprise',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['compliance_analysis', 'quiz_generation', 'scorm_export', 'certification_tracking'],
    optionalCapabilities: ['ai_avatar', 'multilingual'],
    richContentFeatures: ['interactive_elements', 'analytics_tracking', 'version_control'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 500,
    qualityScore: 92,
    automationLevel: 70,
  },
  {
    pipelineId: 'onboarding-personalized',
    displayName: 'Onboarding → Personalized Welcome',
    description: 'Create personalized onboarding videos for new hires',
    category: 'training_ld',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'full',
      marketing_ads: 'none',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'full',
      customer_education: 'partial',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'elevenlabs', 'openai'],
    fallbackProviders: ['azure', 'alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['personalization', 'ai_avatar', 'tts_voice'],
    optionalCapabilities: ['crm_integration', 'dynamic_content'],
    richContentFeatures: ['ai_avatars', 'ai_voiceover', 'dynamic_data', 'brand_consistency'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 240,
    qualityScore: 88,
    automationLevel: 90,
  },

  // ═══════════════════════════════════════════════════════════════
  // MARKETING & ADVERTISING PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'product-to-demo',
    displayName: 'Product → Demo Video',
    description: 'Generate product demo/explainer video from product info',
    category: 'marketing_advertising',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'full',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['openai', 'modelslab', 'elevenlabs'],
    fallbackProviders: ['gemini', 'alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['product_analysis', 'script_generation', 'video_generation'],
    optionalCapabilities: ['ai_avatar', 'screen_recording'],
    richContentFeatures: ['ai_voiceover', 'motion_graphics', 'ai_avatars', 'background_music'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 88,
    automationLevel: 85,
  },
  {
    pipelineId: 'brief-to-ad-creative',
    displayName: 'Brief → Ad Creatives',
    description: 'Generate multi-format ad variants from campaign brief',
    category: 'marketing_advertising',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'partial',
      generative_video: 'full',
      video_repurposing: 'partial',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['openai', 'modelslab', 'gemini'],
    fallbackProviders: ['stability', 'alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['creative_writing', 'image_generation', 'video_generation'],
    optionalCapabilities: ['a_b_variants', 'platform_optimization'],
    richContentFeatures: ['motion_graphics', 'background_music', 'responsive_design'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 240,
    qualityScore: 85,
    automationLevel: 90,
  },
  {
    pipelineId: 'brand-to-ugc',
    displayName: 'Brand → UGC-Style Ads',
    description: 'Generate authentic UGC-style testimonial ads',
    category: 'marketing_advertising',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'partial',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'elevenlabs', 'openai'],
    fallbackProviders: ['alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['ai_avatar', 'script_generation', 'authentic_style'],
    optionalCapabilities: ['voice_variety', 'location_diversity'],
    richContentFeatures: ['ai_avatars', 'lip_sync', 'ai_voiceover'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 82,
    automationLevel: 85,
  },
  {
    pipelineId: 'landing-to-video',
    displayName: 'Landing Page → Promo Video',
    description: 'Generate promotional video from landing page URL',
    category: 'marketing_advertising',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'partial',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'full',
      localization: 'partial',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['gemini', 'openai', 'modelslab'],
    fallbackProviders: ['alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['url_scraping', 'content_extraction', 'video_generation'],
    optionalCapabilities: ['brand_matching', 'cta_optimization'],
    richContentFeatures: ['motion_graphics', 'ai_voiceover', 'background_music'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 240,
    qualityScore: 80,
    automationLevel: 90,
  },
  {
    pipelineId: 'testimonial-to-video',
    displayName: 'Testimonial → Video Testimonials',
    description: 'Convert customer quotes into video testimonials',
    category: 'marketing_advertising',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'elevenlabs', 'openai'],
    fallbackProviders: ['alibaba', 'azure'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['ai_avatar', 'script_enhancement', 'tts_voice'],
    optionalCapabilities: ['diversity_avatars', 'brand_overlay'],
    richContentFeatures: ['ai_avatars', 'lip_sync', 'ai_voiceover', 'brand_consistency'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 200,
    qualityScore: 85,
    automationLevel: 90,
  },

  // ═══════════════════════════════════════════════════════════════
  // SOCIAL MEDIA PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'content-calendar-to-posts',
    displayName: 'Calendar → Scheduled Posts',
    description: 'Generate scheduled social content from content plan',
    category: 'social_media',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'none',
      generative_video: 'partial',
      video_repurposing: 'partial',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'full',
      localization: 'partial',
      enterprise: 'partial',
      data_analytics: 'partial',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['openai', 'claude', 'gemini'],
    fallbackProviders: ['deepseek'],
    minimumTier: 'starter',
    recommendedTier: 'pro',
    requiredCapabilities: ['content_writing', 'scheduling', 'platform_optimization'],
    optionalCapabilities: ['image_generation', 'hashtag_research'],
    richContentFeatures: ['brand_consistency', 'analytics_tracking'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 120,
    qualityScore: 85,
    automationLevel: 95,
  },
  {
    pipelineId: 'video-to-platform-optimized',
    displayName: 'Video → Platform-Optimized',
    description: 'Adapt video for TikTok, Reels, Shorts, etc.',
    category: 'social_media',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'none',
      generative_video: 'partial',
      video_repurposing: 'full',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'full',
      localization: 'partial',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['gemini', 'openai'],
    fallbackProviders: ['alibaba'],
    minimumTier: 'starter',
    recommendedTier: 'pro',
    requiredCapabilities: ['aspect_ratio_crop', 'caption_generation', 'platform_specs'],
    optionalCapabilities: ['trend_alignment', 'hook_optimization'],
    richContentFeatures: ['captions_subtitles', 'responsive_design'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 90,
    qualityScore: 88,
    automationLevel: 95,
  },
  {
    pipelineId: 'trend-to-viral',
    displayName: 'Trend → Viral Content',
    description: 'Generate trend-aligned viral content',
    category: 'social_media',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'partial',
      generative_video: 'full',
      video_repurposing: 'partial',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'full',
      localization: 'none',
      enterprise: 'none',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['openai', 'gemini', 'modelslab'],
    fallbackProviders: ['alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['trend_analysis', 'content_generation', 'video_generation'],
    optionalCapabilities: ['audio_trending', 'hashtag_optimization'],
    richContentFeatures: ['motion_graphics', 'background_music', 'captions_subtitles'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 75,
    automationLevel: 85,
  },
  {
    pipelineId: 'audio-to-music-video',
    displayName: 'Audio → Music Video/Visualizer',
    description: 'Generate music video or visualizer from audio track',
    category: 'social_media',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'none',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'partial',
      localization: 'none',
      enterprise: 'none',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'alibaba', 'replicate'],
    fallbackProviders: ['stability'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['audio_analysis', 'visual_generation', 'beat_sync'],
    optionalCapabilities: ['3d_visualization', 'particle_effects'],
    richContentFeatures: ['motion_graphics', '3d_models'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 80,
    automationLevel: 90,
  },

  // ═══════════════════════════════════════════════════════════════
  // SALES ENABLEMENT PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'proposal-to-video-pitch',
    displayName: 'Proposal → Video Pitch',
    description: 'Convert proposal document into personalized video pitch',
    category: 'sales_enablement',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'none',
      marketing_ads: 'none',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['claude', 'openai', 'modelslab'],
    fallbackProviders: ['elevenlabs', 'alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['document_analysis', 'script_generation', 'ai_avatar'],
    optionalCapabilities: ['crm_data_merge', 'personalization'],
    richContentFeatures: ['ai_avatars', 'ai_voiceover', 'dynamic_data', 'brand_consistency'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 88,
    automationLevel: 80,
  },
  {
    pipelineId: 'demo-to-personalized',
    displayName: 'Demo → Personalized Demo',
    description: 'Create prospect-specific demo videos',
    category: 'sales_enablement',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'partial',
      social_publishing: 'none',
      ld_training: 'none',
      marketing_ads: 'none',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'none',
      customer_education: 'partial',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'openai', 'elevenlabs'],
    fallbackProviders: ['alibaba', 'azure'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['personalization', 'ai_avatar', 'data_merge'],
    optionalCapabilities: ['industry_customization', 'use_case_matching'],
    richContentFeatures: ['ai_avatars', 'ai_voiceover', 'dynamic_data', 'analytics_tracking'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 240,
    qualityScore: 90,
    automationLevel: 85,
  },
  {
    pipelineId: 'crm-to-outreach',
    displayName: 'CRM → Outreach Videos',
    description: 'Generate personalized prospecting videos from CRM data',
    category: 'sales_enablement',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'none',
      marketing_ads: 'none',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'elevenlabs', 'openai'],
    fallbackProviders: ['alibaba', 'azure'],
    minimumTier: 'enterprise',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['crm_integration', 'personalization', 'ai_avatar', 'batch_generation'],
    optionalCapabilities: ['sequence_automation', 'engagement_tracking'],
    richContentFeatures: ['ai_avatars', 'ai_voiceover', 'dynamic_data', 'analytics_tracking'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 88,
    automationLevel: 95,
  },
  {
    pipelineId: 'battlecard-to-presentation',
    displayName: 'Battlecard → Sales Deck',
    description: 'Convert competitive intel into sales battle deck',
    category: 'sales_enablement',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'partial',
      generative_video: 'none',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'partial',
      marketing_ads: 'none',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'partial',
      customer_education: 'none',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['claude', 'openai', 'gemini'],
    fallbackProviders: ['deepseek'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['competitive_analysis', 'slide_design', 'data_visualization'],
    optionalCapabilities: ['objection_handling', 'win_rate_data'],
    richContentFeatures: ['animated_charts', 'brand_consistency', 'version_control'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 200,
    qualityScore: 85,
    automationLevel: 80,
  },

  // ═══════════════════════════════════════════════════════════════
  // CUSTOMER EDUCATION PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'docs-to-help-videos',
    displayName: 'Docs → Help Videos',
    description: 'Convert help documentation into tutorial videos',
    category: 'customer_education',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'partial',
      marketing_ads: 'none',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'none',
      customer_education: 'full',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['claude', 'openai', 'elevenlabs'],
    fallbackProviders: ['gemini', 'azure'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['document_analysis', 'script_generation', 'tts_voice'],
    optionalCapabilities: ['screen_capture_overlay', 'ai_avatar'],
    richContentFeatures: ['ai_voiceover', 'captions_subtitles', 'ai_avatars', 'interactive_elements'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 240,
    qualityScore: 88,
    automationLevel: 85,
  },
  {
    pipelineId: 'faq-to-video-library',
    displayName: 'FAQ → Video Answer Library',
    description: 'Convert FAQ content into searchable video library',
    category: 'customer_education',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'none',
      marketing_ads: 'none',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'none',
      customer_education: 'full',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'elevenlabs', 'openai'],
    fallbackProviders: ['alibaba', 'azure'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['content_chunking', 'ai_avatar', 'tts_voice', 'video_indexing'],
    optionalCapabilities: ['search_integration', 'chatbot_integration'],
    richContentFeatures: ['ai_avatars', 'ai_voiceover', 'captions_subtitles', 'multi_language'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 85,
    automationLevel: 90,
  },
  {
    pipelineId: 'onboarding-to-welcome-flow',
    displayName: 'Onboarding → Welcome Flow',
    description: 'Create personalized user onboarding journey',
    category: 'customer_education',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'partial',
      marketing_ads: 'none',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'full',
      internal_comms: 'none',
      customer_education: 'full',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'openai', 'elevenlabs'],
    fallbackProviders: ['alibaba', 'azure'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['personalization', 'ai_avatar', 'journey_logic', 'tts_voice'],
    optionalCapabilities: ['progress_tracking', 'adaptive_content'],
    richContentFeatures: ['ai_avatars', 'ai_voiceover', 'interactive_elements', 'analytics_tracking'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 90,
    automationLevel: 80,
  },
  {
    pipelineId: 'release-to-update-video',
    displayName: 'Release Notes → Update Video',
    description: 'Convert product updates into feature announcement videos',
    category: 'customer_education',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'full',
      ld_training: 'none',
      marketing_ads: 'partial',
      localization: 'full',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'full',
      customer_education: 'full',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['openai', 'modelslab', 'elevenlabs'],
    fallbackProviders: ['gemini', 'alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['content_analysis', 'script_generation', 'tts_voice'],
    optionalCapabilities: ['screen_capture', 'ai_avatar'],
    richContentFeatures: ['ai_voiceover', 'motion_graphics', 'captions_subtitles', 'brand_consistency'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 85,
    automationLevel: 90,
  },

  // ═══════════════════════════════════════════════════════════════
  // LOCALIZATION PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'video-to-multilanguage',
    displayName: 'Video → 50+ Languages',
    description: 'Dub English video into 50+ languages with lip-sync',
    category: 'localization',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'full',
      generative_video: 'partial',
      video_repurposing: 'full',
      social_publishing: 'full',
      ld_training: 'full',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'full',
      customer_education: 'full',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['elevenlabs', 'alibaba', 'azure'],
    fallbackProviders: ['deepl', 'google'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['transcription', 'translation', 'tts_multi_language', 'lip_sync'],
    optionalCapabilities: ['voice_cloning', 'cultural_adaptation'],
    richContentFeatures: ['lip_sync', 'ai_voiceover', 'multi_language', 'captions_subtitles'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 400,
    qualityScore: 88,
    automationLevel: 85,
  },
  {
    pipelineId: 'presentation-to-localized',
    displayName: 'Presentation → Localized Versions',
    description: 'Translate English deck into multiple languages',
    category: 'localization',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'none',
      generative_video: 'none',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'full',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'full',
      customer_education: 'full',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['deepl', 'alibaba', 'google'],
    fallbackProviders: ['gemini', 'microsoft'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['translation', 'layout_adjustment', 'font_handling'],
    optionalCapabilities: ['rtl_support', 'cultural_imagery'],
    richContentFeatures: ['multi_language', 'brand_consistency'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 90,
    automationLevel: 90,
  },
  {
    pipelineId: 'avatar-to-regional',
    displayName: 'Avatar → Regional Native',
    description: 'Generate native-looking avatar for each region',
    category: 'localization',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'full',
      marketing_ads: 'full',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'partial',
      customer_education: 'full',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'alibaba', 'azure'],
    fallbackProviders: ['replicate'],
    minimumTier: 'enterprise',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['avatar_diversity', 'native_tts', 'cultural_customization'],
    optionalCapabilities: ['accent_matching', 'gesture_localization'],
    richContentFeatures: ['ai_avatars', 'lip_sync', 'ai_voiceover', 'multi_language'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 360,
    qualityScore: 85,
    automationLevel: 80,
  },

  // ═══════════════════════════════════════════════════════════════
  // DATA & ANALYTICS PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'data-to-dashboard-video',
    displayName: 'Data → Dashboard Video',
    description: 'Generate narrated data story from analytics',
    category: 'data_analytics',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'partial',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'partial',
      marketing_ads: 'none',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'full',
      internal_comms: 'full',
      customer_education: 'none',
      sales_enablement: 'full',
      live_realtime: 'partial',
    },
    primaryProviders: ['openai', 'gemini', 'elevenlabs'],
    fallbackProviders: ['claude', 'azure'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['data_analysis', 'chart_animation', 'script_generation', 'tts_voice'],
    optionalCapabilities: ['live_data_connection', 'ai_avatar'],
    richContentFeatures: ['animated_charts', 'ai_voiceover', 'dynamic_data', 'motion_graphics'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 88,
    automationLevel: 80,
  },
  {
    pipelineId: 'report-to-executive-summary',
    displayName: 'Report → Executive Summary Video',
    description: 'Convert detailed report into video summary for execs',
    category: 'data_analytics',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'none',
      marketing_ads: 'none',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'full',
      internal_comms: 'full',
      customer_education: 'none',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['claude', 'openai', 'elevenlabs'],
    fallbackProviders: ['gemini', 'azure'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['document_analysis', 'summarization', 'tts_voice'],
    optionalCapabilities: ['ai_avatar', 'key_metrics_highlight'],
    richContentFeatures: ['ai_voiceover', 'animated_charts', 'ai_avatars', 'brand_consistency'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 240,
    qualityScore: 90,
    automationLevel: 85,
  },
  {
    pipelineId: 'survey-to-insights-video',
    displayName: 'Survey → Insights Presentation',
    description: 'Convert survey results into findings presentation',
    category: 'data_analytics',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'partial',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'none',
      marketing_ads: 'partial',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'full',
      internal_comms: 'full',
      customer_education: 'none',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['openai', 'claude', 'gemini'],
    fallbackProviders: ['deepseek'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['data_analysis', 'insight_extraction', 'visualization'],
    optionalCapabilities: ['sentiment_analysis', 'trend_identification'],
    richContentFeatures: ['animated_charts', 'brand_consistency', 'ai_voiceover'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 200,
    qualityScore: 85,
    automationLevel: 85,
  },

  // ═══════════════════════════════════════════════════════════════
  // INTERNAL COMMUNICATIONS PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'announcement-to-video',
    displayName: 'Announcement → Company Video',
    description: 'Convert company news into CEO/leadership video',
    category: 'internal_comms',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'none',
      marketing_ads: 'none',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'full',
      customer_education: 'none',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'elevenlabs', 'openai'],
    fallbackProviders: ['alibaba', 'azure'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['ai_avatar', 'script_generation', 'tts_voice'],
    optionalCapabilities: ['executive_clone', 'brand_overlay'],
    richContentFeatures: ['ai_avatars', 'lip_sync', 'ai_voiceover', 'brand_consistency'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 240,
    qualityScore: 88,
    automationLevel: 85,
  },
  {
    pipelineId: 'policy-to-training',
    displayName: 'Policy → Training Videos',
    description: 'Convert policy documents into explainer videos',
    category: 'internal_comms',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'full',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'full',
      marketing_ads: 'none',
      localization: 'full',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'full',
      customer_education: 'none',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['claude', 'openai', 'elevenlabs'],
    fallbackProviders: ['azure', 'alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['document_analysis', 'script_generation', 'tts_voice'],
    optionalCapabilities: ['ai_avatar', 'quiz_generation'],
    richContentFeatures: ['ai_voiceover', 'ai_avatars', 'captions_subtitles', 'interactive_elements'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 300,
    qualityScore: 85,
    automationLevel: 80,
  },
  {
    pipelineId: 'townhall-to-highlights',
    displayName: 'Town Hall → Highlights + Q&A',
    description: 'Extract key moments and Q&A from all-hands recording',
    category: 'internal_comms',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'none',
      generative_video: 'partial',
      video_repurposing: 'full',
      social_publishing: 'none',
      ld_training: 'none',
      marketing_ads: 'none',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'full',
      customer_education: 'none',
      sales_enablement: 'none',
      live_realtime: 'none',
    },
    primaryProviders: ['gemini', 'claude', 'openai'],
    fallbackProviders: ['assemblyai'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['transcription', 'highlight_extraction', 'qa_detection'],
    optionalCapabilities: ['sentiment_analysis', 'action_item_extraction'],
    richContentFeatures: ['captions_subtitles', 'version_control'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 85,
    automationLevel: 90,
  },

  // ═══════════════════════════════════════════════════════════════
  // LIVE & REAL-TIME PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'avatar-live-stream',
    displayName: 'Avatar → Live Stream',
    description: 'Real-time AI avatar live streaming',
    category: 'live_realtime',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'full',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'full',
      ld_training: 'partial',
      marketing_ads: 'partial',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'partial',
      customer_education: 'partial',
      sales_enablement: 'partial',
      live_realtime: 'full',
    },
    primaryProviders: ['modelslab', 'alibaba', 'azure'],
    fallbackProviders: ['replicate'],
    minimumTier: 'enterprise',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['real_time_avatar', 'low_latency_tts', 'streaming'],
    optionalCapabilities: ['audience_interaction', 'live_translation'],
    richContentFeatures: ['ai_avatars', 'lip_sync', 'ai_voiceover'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: true,
      exportPreview: false,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 0, // Real-time
    qualityScore: 82,
    automationLevel: 90,
  },
  {
    pipelineId: 'webinar-interactive',
    displayName: 'Webinar → Interactive',
    description: 'Live presentation with interactive Q&A',
    category: 'live_realtime',
    verticalSupport: {
      presentations: 'full',
      ai_avatar: 'partial',
      generative_video: 'none',
      video_repurposing: 'partial',
      social_publishing: 'none',
      ld_training: 'full',
      marketing_ads: 'partial',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'full',
      customer_education: 'full',
      sales_enablement: 'full',
      live_realtime: 'full',
    },
    primaryProviders: ['openai', 'gemini'],
    fallbackProviders: ['claude'],
    minimumTier: 'enterprise',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['real_time_qa', 'live_transcription', 'audience_polling'],
    optionalCapabilities: ['ai_moderation', 'sentiment_tracking'],
    richContentFeatures: ['interactive_elements', 'captions_subtitles', 'analytics_tracking'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: true,
      exportPreview: false,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 0, // Real-time
    qualityScore: 85,
    automationLevel: 75,
  },
  {
    pipelineId: 'meeting-to-summary',
    displayName: 'Meeting → Real-time Summary',
    description: 'Live meeting with real-time notes and action items',
    category: 'live_realtime',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'none',
      generative_video: 'none',
      video_repurposing: 'partial',
      social_publishing: 'none',
      ld_training: 'none',
      marketing_ads: 'none',
      localization: 'partial',
      enterprise: 'full',
      data_analytics: 'partial',
      internal_comms: 'full',
      customer_education: 'none',
      sales_enablement: 'partial',
      live_realtime: 'full',
    },
    primaryProviders: ['gemini', 'openai', 'assemblyai'],
    fallbackProviders: ['claude'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['live_transcription', 'summarization', 'action_item_extraction'],
    optionalCapabilities: ['speaker_diarization', 'task_integration'],
    richContentFeatures: ['collaboration', 'analytics_tracking'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 0, // Real-time
    qualityScore: 88,
    automationLevel: 95,
  },

  // ═══════════════════════════════════════════════════════════════
  // IMMERSIVE 3D / VR / AR PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'text-to-vr',
    displayName: 'Text → VR Experience',
    description: 'Generate immersive VR experience from description',
    category: 'immersive_3d',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'none',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'full',
      marketing_ads: 'partial',
      localization: 'none',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'partial',
      sales_enablement: 'partial',
      live_realtime: 'partial',
    },
    primaryProviders: ['modelslab', 'replicate', 'huggingface'],
    fallbackProviders: ['alibaba'],
    minimumTier: 'enterprise',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['3d_generation', 'spatial_audio', 'vr_packaging'],
    optionalCapabilities: ['interaction_scripting', 'hand_tracking'],
    richContentFeatures: ['vr_ar_content', '3d_models', 'interactive_elements'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: false,
    },
    estimatedDurationSeconds: 600,
    qualityScore: 80,
    automationLevel: 70,
  },
  {
    pipelineId: 'image-to-3d',
    displayName: 'Image → 3D Model',
    description: 'Generate 3D mesh from 2D image',
    category: 'immersive_3d',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'partial',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'partial',
      ld_training: 'partial',
      marketing_ads: 'partial',
      localization: 'none',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'partial',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'replicate', 'huggingface'],
    fallbackProviders: ['alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['image_to_3d', 'mesh_optimization', 'texture_mapping'],
    optionalCapabilities: ['animation_rigging', 'physics_simulation'],
    richContentFeatures: ['3d_models', 'interactive_elements'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 82,
    automationLevel: 90,
  },
  {
    pipelineId: 'floor-plan-to-vr',
    displayName: 'Floor Plan → VR Walkthrough',
    description: 'Convert 2D floor plan into VR walkthrough',
    category: 'immersive_3d',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'none',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'partial',
      marketing_ads: 'full',
      localization: 'none',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'none',
      sales_enablement: 'full',
      live_realtime: 'none',
    },
    primaryProviders: ['modelslab', 'replicate'],
    fallbackProviders: ['huggingface'],
    minimumTier: 'enterprise',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['floor_plan_analysis', '3d_extrusion', 'vr_packaging'],
    optionalCapabilities: ['furniture_placement', 'lighting_simulation'],
    richContentFeatures: ['vr_ar_content', '3d_models', 'interactive_elements'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: false,
      multiDevice: true,
      interactivePreview: true,
      audioPreview: false,
      exportPreview: true,
      collaborativePreview: false,
    },
    estimatedDurationSeconds: 400,
    qualityScore: 78,
    automationLevel: 75,
  },

  // ═══════════════════════════════════════════════════════════════
  // AUDIO / SFX PIPELINES
  // ═══════════════════════════════════════════════════════════════
  {
    pipelineId: 'scene-to-sfx',
    displayName: 'Scene → Auto SFX',
    description: 'Automatically add sound effects to video scenes',
    category: 'audio_sfx',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'partial',
      generative_video: 'full',
      video_repurposing: 'full',
      social_publishing: 'full',
      ld_training: 'partial',
      marketing_ads: 'full',
      localization: 'none',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'partial',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['elevenlabs', 'gemini', 'openai'],
    fallbackProviders: ['alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['scene_analysis', 'sfx_generation', 'audio_mixing'],
    optionalCapabilities: ['foley_matching', 'ambient_generation'],
    richContentFeatures: ['sfx_audio', 'background_music'],
    previewSupport: {
      realTimePreview: true,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 120,
    qualityScore: 82,
    automationLevel: 90,
  },
  {
    pipelineId: 'video-to-music-score',
    displayName: 'Video → Music Score',
    description: 'Generate original music score for video',
    category: 'audio_sfx',
    verticalSupport: {
      presentations: 'partial',
      ai_avatar: 'none',
      generative_video: 'full',
      video_repurposing: 'full',
      social_publishing: 'full',
      ld_training: 'partial',
      marketing_ads: 'full',
      localization: 'none',
      enterprise: 'partial',
      data_analytics: 'none',
      internal_comms: 'partial',
      customer_education: 'partial',
      sales_enablement: 'partial',
      live_realtime: 'none',
    },
    primaryProviders: ['elevenlabs', 'suno', 'udio'],
    fallbackProviders: ['alibaba'],
    minimumTier: 'pro',
    recommendedTier: 'pro',
    requiredCapabilities: ['mood_analysis', 'music_generation', 'audio_sync'],
    optionalCapabilities: ['genre_selection', 'tempo_matching'],
    richContentFeatures: ['background_music'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: true,
      interactivePreview: false,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: true,
    },
    estimatedDurationSeconds: 180,
    qualityScore: 80,
    automationLevel: 90,
  },
  {
    pipelineId: 'spatial-audio-3d',
    displayName: 'Scene → Spatial Audio',
    description: 'Generate 3D spatial audio for VR/AR content',
    category: 'audio_sfx',
    verticalSupport: {
      presentations: 'none',
      ai_avatar: 'none',
      generative_video: 'partial',
      video_repurposing: 'none',
      social_publishing: 'none',
      ld_training: 'partial',
      marketing_ads: 'none',
      localization: 'none',
      enterprise: 'full',
      data_analytics: 'none',
      internal_comms: 'none',
      customer_education: 'partial',
      sales_enablement: 'none',
      live_realtime: 'partial',
    },
    primaryProviders: ['azure', 'elevenlabs'],
    fallbackProviders: ['alibaba'],
    minimumTier: 'enterprise',
    recommendedTier: 'enterprise',
    requiredCapabilities: ['3d_scene_analysis', 'spatial_audio_design', 'binaural_rendering'],
    optionalCapabilities: ['head_tracking_support', 'ambisonic_mixing'],
    richContentFeatures: ['vr_ar_content'],
    previewSupport: {
      realTimePreview: false,
      scrubbing: true,
      multiDevice: false,
      interactivePreview: true,
      audioPreview: true,
      exportPreview: true,
      collaborativePreview: false,
    },
    estimatedDurationSeconds: 240,
    qualityScore: 85,
    automationLevel: 75,
  },
];

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Get all pipelines supporting a specific vertical
 */
export function getPipelinesByVertical(vertical: ProductVertical): PipelineCapabilityEntry[] {
  return PIPELINE_CAPABILITY_MATRIX.filter(
    p => p.verticalSupport[vertical] === 'full' || p.verticalSupport[vertical] === 'partial'
  );
}

/**
 * Get all pipelines for a specific category
 */
export function getPipelinesByCategory(category: PipelineCategory): PipelineCapabilityEntry[] {
  return PIPELINE_CAPABILITY_MATRIX.filter(p => p.category === category);
}

/**
 * Get all pipelines supported by a specific provider
 */
export function getPipelinesByProvider(providerId: ProviderId): PipelineCapabilityEntry[] {
  return PIPELINE_CAPABILITY_MATRIX.filter(
    p => p.primaryProviders.includes(providerId) || p.fallbackProviders.includes(providerId)
  );
}

/**
 * Get all pipelines available at a specific tier
 */
export function getPipelinesByTier(tier: PricingTier): PipelineCapabilityEntry[] {
  const tierOrder: PricingTier[] = ['free', 'starter', 'pro', 'enterprise'];
  const tierIndex = tierOrder.indexOf(tier);
  return PIPELINE_CAPABILITY_MATRIX.filter(
    p => tierOrder.indexOf(p.minimumTier) <= tierIndex
  );
}

/**
 * Get summary statistics for the capability matrix
 */
export function getPipelineMatrixSummary() {
  const totalPipelines = PIPELINE_CAPABILITY_MATRIX.length;
  
  const byCategory = PIPELINE_CAPABILITY_MATRIX.reduce((acc, p) => {
    acc[p.category] = (acc[p.category] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
  
  const byTier = PIPELINE_CAPABILITY_MATRIX.reduce((acc, p) => {
    acc[p.minimumTier] = (acc[p.minimumTier] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
  
  const averageQuality = PIPELINE_CAPABILITY_MATRIX.reduce((sum, p) => sum + p.qualityScore, 0) / totalPipelines;
  const averageAutomation = PIPELINE_CAPABILITY_MATRIX.reduce((sum, p) => sum + p.automationLevel, 0) / totalPipelines;
  
  return {
    totalPipelines,
    byCategory,
    byTier,
    averageQuality: Math.round(averageQuality),
    averageAutomation: Math.round(averageAutomation),
  };
}

// ============================================
// RICH CONTENT PREVIEW REQUIREMENTS
// ============================================
export const RICH_CONTENT_PREVIEW_REQUIREMENTS = {
  // What the frontend needs to support for rich content preview
  presentations: {
    slideRenderer: true,        // Render slides with animations
    chartAnimations: true,      // Animate data visualizations
    brandKitOverlay: true,      // Apply brand colors/fonts
    responsiveScale: true,      // Scale to different devices
    exportFormats: ['pptx', 'pdf', 'google_slides', 'keynote'],
  },
  video: {
    videoPlayer: true,          // HTML5 video with scrubbing
    captionOverlay: true,       // Display captions/subtitles
    audioWaveform: true,        // Show audio visualization
    thumbnailStrip: true,       // Timeline thumbnails
    qualitySelector: true,      // Multiple quality options
    exportFormats: ['mp4', 'webm', 'mov', 'gif'],
  },
  aiAvatar: {
    avatarRenderer: true,       // Real-time avatar preview
    lipSyncPreview: true,       // Preview lip-sync accuracy
    backgroundSwap: true,       // Preview different backgrounds
    gesturePreview: true,       // Preview avatar gestures
    exportFormats: ['mp4', 'webm'],
  },
  interactive: {
    quizPreview: true,          // Test quiz interactions
    branchingPreview: true,     // Navigate branching paths
    hotspotOverlay: true,       // Show clickable areas
    scormPreview: true,         // Test SCORM compliance
    exportFormats: ['scorm', 'html5', 'tincan'],
  },
  immersive: {
    threeDViewer: true,         // 3D model viewer
    vrEmulator: true,           // VR preview without headset
    spatialAudioPreview: true,  // 3D audio preview
    interactionPoints: true,    // Show VR interaction zones
    exportFormats: ['gltf', 'glb', 'fbx', 'usdz'],
  },
  data: {
    chartInteractivity: true,   // Interactive chart preview
    liveDataBinding: true,      // Preview with real data
    drilldownPreview: true,     // Test drill-down functionality
    exportFormats: ['png', 'svg', 'pdf', 'excel'],
  },
};

// ============================================
// GENERATION PIPELINE QUALITY GATES
// ============================================
export const GENERATION_QUALITY_GATES = {
  // Quality checkpoints during generation
  script: {
    minWords: 50,
    maxWords: 5000,
    grammarCheck: true,
    toneConsistency: true,
    brandVoiceAlignment: true,
  },
  voice: {
    minClarity: 0.8,        // 0-1 clarity score
    maxNoiseLevel: 0.1,     // Background noise threshold
    paceConsistency: true,  // Speaking pace uniformity
    emotionAlignment: true, // Voice matches content emotion
  },
  video: {
    minResolution: '720p',
    minFrameRate: 24,
    lipSyncAccuracy: 0.85,  // 0-1 sync accuracy
    transitionSmoothness: true,
    brandColorMatch: 0.9,   // Color accuracy to brand kit
  },
  avatar: {
    facialExpression: true,   // Natural expressions
    gestureNatural: true,     // Natural hand movements
    eyeContactRatio: 0.6,     // % time looking at camera
    lipSyncScore: 0.85,       // Lip-sync accuracy
  },
  localization: {
    translationAccuracy: 0.9,   // Translation quality
    culturalAdaptation: true,   // Cultural appropriateness
    timingPreservation: true,   // Keep original timing
    fontSupport: true,          // Font supports all characters
  },
};
