/**
 * DOGFOODING PROOF SECTION — "Built With Genie"
 * Demonstrates the platform's power by showing it builds its own marketing
 */
import React from 'react';
import { 
  Sparkles, 
  RefreshCw,
  Calendar,
  Globe,
  Video,
  Presentation,
  Music,
  Clock,
  Shield,
  CheckCircle2
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Link } from 'react-router-dom';

const PLATFORM_HIGHLIGHTS = [
  {
    type: 'AI Video Production',
    icon: Video,
    what: 'Every product demo and regional showcase — produced by Genie Vibe & Cast',
    provider: '19 AI Providers Orchestrated',
    confidence: 96,
  },
  {
    type: 'Regional Transcreation',
    icon: Globe,
    what: 'All 8 regional landing pages — transcreated, not translated, by Genie Mind',
    provider: '140+ Languages Supported',
    confidence: 94,
  },
  {
    type: 'Presentation Decks',
    icon: Presentation,
    what: 'Investor decks, sales collateral — auto-generated by Genie Deck',
    provider: 'Framework-Driven Messaging',
    confidence: 98,
  },
  {
    type: 'Audio & Music',
    icon: Music,
    what: 'Background scores and voiceovers — composed by Genie Spark',
    provider: 'Azure Neural + ElevenLabs',
    confidence: 95,
  },
];

const WHAT_WE_SUPPORT = [
  'End-to-end video production from script to screen',
  'Cultural transcreation across 140+ languages',
  'AI avatar presenters with native lip-sync',
  'Brand-consistent content at global scale',
  'Compliance-ready outputs for regulated industries',
  'Real-time collaboration for distributed teams',
];

export const DogfoodingProof: React.FC = () => {
  return (
    <section className="py-24 relative">
      <div className="absolute inset-0 bg-gradient-to-b from-accent/5 to-background" />
      
      <div className="relative max-w-7xl mx-auto px-4">
        {/* Header */}
        <div className="text-center mb-12">
          <Badge variant="outline" className="mb-4 border-primary/40 text-primary">
            <Sparkles className="h-3 w-3 mr-1" />
            Built With Genie Suite
          </Badge>
          <h2 className="text-4xl md:text-5xl font-bold mb-4 text-foreground">
            We Don't Just Build the Platform. We Use It.
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            This entire experience — every video, every regional page, every translated word — 
            was <span className="text-primary font-bold">produced by the same tools you'll use</span>. 
            That's our proof.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          {/* Left: What powers this page */}
          <div className="bg-card border border-border rounded-2xl p-6">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-bold text-foreground">Powering This Experience</h3>
              <Badge className="bg-green-500/20 text-green-600 border-0">
                <RefreshCw className="h-3 w-3 mr-1 animate-spin" style={{ animationDuration: '3s' }} />
                Live
              </Badge>
            </div>

            <div className="space-y-4">
              {PLATFORM_HIGHLIGHTS.map((content) => {
                const Icon = content.icon;
                return (
                  <div 
                    key={content.type}
                    className="flex items-start gap-3 p-4 bg-muted/50 rounded-xl"
                  >
                    <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5">
                      <Icon className="h-5 w-5 text-primary" />
                    </div>
                    <div className="flex-1">
                      <p className="font-medium text-foreground">{content.type}</p>
                      <p className="text-sm text-muted-foreground mt-0.5">{content.what}</p>
                      <p className="text-xs text-primary mt-1">{content.provider}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Right: What we support */}
          <div className="bg-card border border-border rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-6">
              <Shield className="h-5 w-5 text-primary" />
              <h3 className="text-xl font-bold text-foreground">What We Support</h3>
            </div>

            <p className="text-muted-foreground mb-6">
              Genie Suite is your complete production partner — from ideation to global distribution. 
              Here's what you get on day one:
            </p>

            <div className="space-y-3">
              {WHAT_WE_SUPPORT.map((item) => (
                <div key={item} className="flex items-start gap-3 p-3 bg-muted/30 rounded-lg">
                  <CheckCircle2 className="h-5 w-5 text-green-500 flex-shrink-0 mt-0.5" />
                  <p className="text-foreground text-sm font-medium">{item}</p>
                </div>
              ))}
            </div>

            <div className="mt-6">
              <Link to="/genie-studio-auth?tab=signup">
                <Button className="w-full bg-primary hover:bg-primary/90 text-primary-foreground">
                  Start Creating — It's Free
                  <Sparkles className="h-4 w-4 ml-2" />
                </Button>
              </Link>
            </div>
          </div>
        </div>

        {/* Bottom branded strip */}
        <div className="mt-8 p-6 bg-gradient-to-r from-primary/10 via-primary/5 to-accent/10 rounded-2xl border border-primary/20 text-center">
          <p className="text-lg text-foreground">
            🎯 <strong>7 Products · 206 Pipelines · 19 AI Providers · 140+ Languages</strong>
          </p>
          <p className="text-muted-foreground mt-2">
            One platform that speaks your language, understands your market, and scales with your ambition.
          </p>
        </div>
      </div>
    </section>
  );
};

export default DogfoodingProof;