/**
 * Video Style Registry Seed Data
 * 
 * 60+ styles across 8 categories with full provider routing chains.
 * Use seedVideoStyleRegistry() to populate the video_style_registry table.
 */

import { supabase } from '@/integrations/supabase/client';

interface StyleSeed {
  style_key: string;
  display_name: string;
  category: string;
  subcategory?: string;
  description: string;
  image_providers: string[];
  video_providers: string[];
  avatar_providers?: string[];
  three_d_providers?: string[];
  motion_providers?: string[];
  lipsync_providers?: string[];
  target_regions: string[];
  cultural_tags: string[];
  tone_modifier: string;
  aesthetic_keywords: string[];
  supported_formats: string[];
  is_system_default: boolean;
  sort_order: number;
}

const SEED_STYLES: StyleSeed[] = [
  // ====== CORE PRODUCTION (22 styles) ======
  { style_key: 'photorealistic', display_name: 'Photorealistic', category: 'core', description: 'Ultra-realistic photography-grade visuals', image_providers: ['gemini','vertex-imagen','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: [], tone_modifier: 'professional', aesthetic_keywords: ['realistic','high-fidelity','4K'], supported_formats: ['image','video'], is_system_default: true, sort_order: 1 },
  { style_key: 'cinematic', display_name: 'Cinematic', category: 'core', description: 'Film-grade cinematic look with dramatic lighting', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: [], tone_modifier: 'professional', aesthetic_keywords: ['filmic','dramatic','widescreen'], supported_formats: ['image','video'], is_system_default: true, sort_order: 2 },
  { style_key: 'anime', display_name: 'Anime / Manga', category: 'core', description: 'Japanese animation style', image_providers: ['modelslab','alibaba','replicate','huggingface'], video_providers: ['alibaba-wan','modelslab-animate','replicate','sora-2'], target_regions: ['cjk','sea'], cultural_tags: ['japanese','manga'], tone_modifier: 'playful', aesthetic_keywords: ['cel-shaded','vibrant','expressive'], supported_formats: ['image','video','avatar'], is_system_default: true, sort_order: 3 },
  { style_key: 'pixar-3d', display_name: 'Pixar / 3D Animation', category: 'core', description: '3D rendered Pixar-style characters and scenes', image_providers: ['alibaba','modelslab','gemini','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], three_d_providers: ['meshy','alibaba','replicate'], target_regions: [], cultural_tags: [], tone_modifier: 'playful', aesthetic_keywords: ['3d-render','cartoon','subsurface-scattering'], supported_formats: ['image','video','3d'], is_system_default: true, sort_order: 4 },
  { style_key: 'corporate', display_name: 'Corporate / Professional', category: 'core', description: 'Clean business-grade visuals', image_providers: ['gemini','vertex-imagen','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: [], tone_modifier: 'formal', aesthetic_keywords: ['clean','minimal','corporate'], supported_formats: ['image','video'], is_system_default: true, sort_order: 5 },
  { style_key: 'editorial', display_name: 'Editorial / Magazine', category: 'core', description: 'High-fashion magazine editorial style', image_providers: ['vertex-imagen','gemini','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: [], tone_modifier: 'luxury', aesthetic_keywords: ['editorial','fashion','glossy'], supported_formats: ['image','video'], is_system_default: true, sort_order: 6 },
  { style_key: 'product-hero', display_name: 'Product Hero Shot', category: 'core', description: 'E-commerce product showcase', image_providers: ['gemini','vertex-imagen','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: [], tone_modifier: 'professional', aesthetic_keywords: ['product','hero','showcase'], supported_formats: ['image','video','3d'], is_system_default: true, sort_order: 7 },
  { style_key: 'documentary', display_name: 'Documentary', category: 'core', description: 'Documentary-style authentic footage', image_providers: ['vertex-imagen','gemini','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: [], tone_modifier: 'warm', aesthetic_keywords: ['authentic','real','narrative'], supported_formats: ['image','video'], is_system_default: true, sort_order: 8 },
  { style_key: 'explainer', display_name: 'Explainer / Educational', category: 'core', description: 'Educational explainer content', image_providers: ['gemini','modelslab','huggingface','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], target_regions: [], cultural_tags: [], tone_modifier: 'casual', aesthetic_keywords: ['educational','clear','informative'], supported_formats: ['image','video','avatar'], is_system_default: true, sort_order: 9 },
  { style_key: 'ugc-authentic', display_name: 'UGC / Authentic', category: 'core', description: 'User-generated content style', image_providers: ['modelslab','gemini','alibaba','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], avatar_providers: ['alibaba-wan-s2v','azure-neural','modelslab'], target_regions: [], cultural_tags: [], tone_modifier: 'casual', aesthetic_keywords: ['raw','authentic','social-media'], supported_formats: ['image','video','avatar'], is_system_default: true, sort_order: 10 },
  { style_key: 'watercolor', display_name: 'Watercolor / Artistic', category: 'core', description: 'Soft watercolor painting style', image_providers: ['modelslab','gemini','alibaba','openai'], video_providers: ['modelslab-animate','alibaba-wan','sora-2','replicate'], target_regions: [], cultural_tags: [], tone_modifier: 'warm', aesthetic_keywords: ['painted','soft','artistic'], supported_formats: ['image','video'], is_system_default: true, sort_order: 11 },
  { style_key: 'minimalist', display_name: 'Minimalist', category: 'core', description: 'Clean minimal design', image_providers: ['gemini','modelslab','huggingface','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: [], tone_modifier: 'professional', aesthetic_keywords: ['clean','simple','whitespace'], supported_formats: ['image','video'], is_system_default: true, sort_order: 12 },
  { style_key: 'luxury-fashion', display_name: 'Luxury / Fashion', category: 'core', description: 'High-end luxury brand aesthetic', image_providers: ['vertex-imagen','gemini','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: [], tone_modifier: 'luxury', aesthetic_keywords: ['luxury','haute-couture','premium'], supported_formats: ['image','video'], is_system_default: true, sort_order: 13 },
  { style_key: 'tech-startup', display_name: 'Tech / Startup', category: 'core', description: 'Modern tech startup visuals', image_providers: ['gemini','modelslab','replicate','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: [], tone_modifier: 'casual', aesthetic_keywords: ['modern','gradient','tech'], supported_formats: ['image','video'], is_system_default: true, sort_order: 14 },
  { style_key: 'lifestyle', display_name: 'Lifestyle', category: 'core', description: 'Aspirational lifestyle imagery', image_providers: ['modelslab','gemini','replicate','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: [], cultural_tags: [], tone_modifier: 'warm', aesthetic_keywords: ['aspirational','warm','natural'], supported_formats: ['image','video'], is_system_default: true, sort_order: 15 },
  { style_key: 'technical-diagram', display_name: 'Technical Diagram', category: 'core', description: 'Technical diagrams and schematics', image_providers: ['deepseek','gemini','openai','modelslab'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: [], cultural_tags: [], tone_modifier: 'formal', aesthetic_keywords: ['schematic','blueprint','technical'], supported_formats: ['image'], is_system_default: true, sort_order: 16 },
  { style_key: 'avatar', display_name: 'Avatar / Talking Head', category: 'core', subcategory: 'avatar', description: 'AI avatar with speech and expressions', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], avatar_providers: ['alibaba-wan-s2v','azure-neural','modelslab'], lipsync_providers: ['azure-neural','alibaba-wan-s2v','modelslab'], target_regions: [], cultural_tags: [], tone_modifier: 'professional', aesthetic_keywords: ['avatar','talking-head','lipsync'], supported_formats: ['video','avatar','lipsync'], is_system_default: true, sort_order: 17 },
  { style_key: 'lipsync', display_name: 'Lipsync Video', category: 'core', subcategory: 'avatar', description: 'Lip-synced talking head video', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], lipsync_providers: ['azure-neural','alibaba-wan-s2v','modelslab'], target_regions: [], cultural_tags: [], tone_modifier: 'professional', aesthetic_keywords: ['lipsync','speech','viseme'], supported_formats: ['video','lipsync'], is_system_default: true, sort_order: 18 },
  { style_key: 'motion', display_name: 'Motion Graphics', category: 'core', description: 'Animated motion graphics and kinetic typography', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['modelslab-animate','alibaba-wan','sora-2','replicate'], motion_providers: ['modelslab-animate','alibaba-wan','replicate'], target_regions: [], cultural_tags: [], tone_modifier: 'professional', aesthetic_keywords: ['motion','kinetic','animated'], supported_formats: ['video','motion'], is_system_default: true, sort_order: 19 },
  { style_key: '3d-object', display_name: '3D Object', category: 'core', subcategory: '3d', description: '3D object generation and rendering', image_providers: ['alibaba','modelslab','gemini','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], three_d_providers: ['meshy','replicate','alibaba'], target_regions: [], cultural_tags: [], tone_modifier: 'professional', aesthetic_keywords: ['3d','object','render'], supported_formats: ['image','3d','video'], is_system_default: true, sort_order: 20 },
  { style_key: 'diffusion', display_name: 'Diffusion Art', category: 'core', description: 'AI diffusion model artistic style', image_providers: ['modelslab','replicate','huggingface','gemini'], video_providers: ['modelslab-animate','alibaba-wan','replicate','sora-2'], target_regions: [], cultural_tags: [], tone_modifier: 'playful', aesthetic_keywords: ['ai-art','generative','abstract'], supported_formats: ['image','video'], is_system_default: true, sort_order: 21 },
  { style_key: 'crayon', display_name: 'Crayon / Hand-Drawn', category: 'core', description: 'Hand-drawn crayon or sketch style', image_providers: ['modelslab','alibaba','gemini','huggingface'], video_providers: ['modelslab-animate','alibaba-wan','sora-2','replicate'], target_regions: [], cultural_tags: [], tone_modifier: 'playful', aesthetic_keywords: ['hand-drawn','sketch','childlike'], supported_formats: ['image','video'], is_system_default: true, sort_order: 22 },

  // ====== CULTURAL HERITAGE (15 styles) ======
  { style_key: 'islamic-geometric', display_name: 'Islamic Geometric', category: 'cultural-heritage', description: 'Islamic geometric patterns, arabesques, and tessellations', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['sora-2','alibaba-wan','vertex-veo','modelslab-animate'], target_regions: ['mena','sea','india'], cultural_tags: ['islamic','geometric','arabesque','tessellation'], tone_modifier: 'formal', aesthetic_keywords: ['geometric','ornate','symmetrical','gold'], supported_formats: ['image','video','motion'], is_system_default: true, sort_order: 30 },
  { style_key: 'hindu-mandala', display_name: 'Hindu Mandala', category: 'cultural-heritage', description: 'Sacred Hindu mandala patterns with rich colors', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['sora-2','alibaba-wan','vertex-veo','modelslab-animate'], target_regions: ['india','sea'], cultural_tags: ['hindu','mandala','sacred','rangoli'], tone_modifier: 'warm', aesthetic_keywords: ['mandala','intricate','sacred-geometry','vibrant'], supported_formats: ['image','video','motion'], is_system_default: true, sort_order: 31 },
  { style_key: 'celtic-knotwork', display_name: 'Celtic Knotwork', category: 'cultural-heritage', description: 'Celtic interlace patterns and knotwork designs', image_providers: ['modelslab','gemini','replicate','openai'], video_providers: ['sora-2','modelslab-animate','alibaba-wan','replicate'], target_regions: ['europe','western'], cultural_tags: ['celtic','irish','scottish','knotwork'], tone_modifier: 'warm', aesthetic_keywords: ['interlace','knot','medieval','green'], supported_formats: ['image','video'], is_system_default: true, sort_order: 32 },
  { style_key: 'african-tribal', display_name: 'African Tribal', category: 'cultural-heritage', description: 'Traditional African tribal art patterns and masks', image_providers: ['gemini','modelslab','replicate','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['africa'], cultural_tags: ['african','tribal','mask','kente'], tone_modifier: 'warm', aesthetic_keywords: ['earth-tones','bold-patterns','masks','textured'], supported_formats: ['image','video'], is_system_default: true, sort_order: 33 },
  { style_key: 'japanese-ukiyo-e', display_name: 'Japanese Ukiyo-e', category: 'cultural-heritage', description: 'Traditional Japanese woodblock print style', image_providers: ['alibaba','modelslab','replicate','huggingface'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], target_regions: ['cjk'], cultural_tags: ['japanese','ukiyo-e','woodblock','edo'], tone_modifier: 'formal', aesthetic_keywords: ['flat-color','wave','woodblock','ink-outline'], supported_formats: ['image','video'], is_system_default: true, sort_order: 34 },
  { style_key: 'chinese-ink-wash', display_name: 'Chinese Ink Wash', category: 'cultural-heritage', description: 'Traditional Chinese shan shui ink wash painting', image_providers: ['alibaba','modelslab','gemini','huggingface'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], target_regions: ['cjk'], cultural_tags: ['chinese','ink-wash','shan-shui','calligraphy'], tone_modifier: 'formal', aesthetic_keywords: ['monochrome','brushstroke','mountain','mist'], supported_formats: ['image','video'], is_system_default: true, sort_order: 35 },
  { style_key: 'persian-miniature', display_name: 'Persian Miniature', category: 'cultural-heritage', description: 'Persian miniature painting with gold leaf details', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['mena'], cultural_tags: ['persian','miniature','safavid','gold-leaf'], tone_modifier: 'luxury', aesthetic_keywords: ['detailed','gold-leaf','illuminated','garden'], supported_formats: ['image','video'], is_system_default: true, sort_order: 36 },
  { style_key: 'aboriginal-dot-art', display_name: 'Aboriginal Dot Art', category: 'cultural-heritage', description: 'Australian Aboriginal dot painting tradition', image_providers: ['modelslab','gemini','replicate','huggingface'], video_providers: ['sora-2','modelslab-animate','alibaba-wan','replicate'], target_regions: ['western'], cultural_tags: ['aboriginal','australian','dot-painting','dreamtime'], tone_modifier: 'warm', aesthetic_keywords: ['dots','earth-tones','concentric','dreaming'], supported_formats: ['image','video'], is_system_default: true, sort_order: 37 },
  { style_key: 'mayan-aztec', display_name: 'Mayan / Aztec', category: 'cultural-heritage', description: 'Pre-Columbian Mesoamerican art and glyphs', image_providers: ['modelslab','gemini','alibaba','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['latam'], cultural_tags: ['mayan','aztec','mesoamerican','glyph'], tone_modifier: 'formal', aesthetic_keywords: ['stone-carved','glyph','jaguar','pyramid'], supported_formats: ['image','video'], is_system_default: true, sort_order: 38 },
  { style_key: 'nordic-viking', display_name: 'Nordic / Viking', category: 'cultural-heritage', description: 'Norse Viking rune art and mythology', image_providers: ['modelslab','gemini','replicate','openai'], video_providers: ['sora-2','modelslab-animate','alibaba-wan','replicate'], target_regions: ['europe'], cultural_tags: ['norse','viking','rune','mythology'], tone_modifier: 'formal', aesthetic_keywords: ['runes','dark-wood','iron','longship'], supported_formats: ['image','video'], is_system_default: true, sort_order: 39 },
  { style_key: 'ottoman-calligraphy', display_name: 'Ottoman Calligraphy', category: 'cultural-heritage', description: 'Ottoman Turkish calligraphy and tulip motifs', image_providers: ['alibaba','gemini','modelslab','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], target_regions: ['mena','europe'], cultural_tags: ['ottoman','turkish','calligraphy','tulip'], tone_modifier: 'luxury', aesthetic_keywords: ['calligraphy','gold','iznik','tulip'], supported_formats: ['image','video'], is_system_default: true, sort_order: 40 },
  { style_key: 'thai-temple', display_name: 'Thai Temple Art', category: 'cultural-heritage', description: 'Traditional Thai temple murals and art', image_providers: ['gemini','alibaba','modelslab','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], target_regions: ['sea'], cultural_tags: ['thai','temple','buddhist','mural'], tone_modifier: 'formal', aesthetic_keywords: ['gold','ornate','lotus','deity'], supported_formats: ['image','video'], is_system_default: true, sort_order: 41 },
  { style_key: 'korean-celadon', display_name: 'Korean Celadon', category: 'cultural-heritage', description: 'Korean celadon pottery and traditional art', image_providers: ['alibaba','modelslab','gemini','huggingface'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], target_regions: ['cjk'], cultural_tags: ['korean','celadon','joseon','hanbok'], tone_modifier: 'formal', aesthetic_keywords: ['jade-green','crackle','crane','bamboo'], supported_formats: ['image','video'], is_system_default: true, sort_order: 42 },
  { style_key: 'moroccan-zellige', display_name: 'Moroccan Zellige', category: 'cultural-heritage', description: 'Moroccan zellige tilework and riads', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['mena','africa'], cultural_tags: ['moroccan','zellige','riad','berber'], tone_modifier: 'warm', aesthetic_keywords: ['mosaic','tile','cobalt-blue','terracotta'], supported_formats: ['image','video'], is_system_default: true, sort_order: 43 },
  { style_key: 'byzantine-mosaic', display_name: 'Byzantine Mosaic', category: 'cultural-heritage', description: 'Byzantine gold mosaic and iconography', image_providers: ['gemini','modelslab','replicate','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['europe','mena'], cultural_tags: ['byzantine','mosaic','orthodox','icon'], tone_modifier: 'formal', aesthetic_keywords: ['gold-mosaic','halo','tesserae','dome'], supported_formats: ['image','video'], is_system_default: true, sort_order: 44 },

  // ====== NATURE & ENVIRONMENT (12 styles) ======
  { style_key: 'tropical-paradise', display_name: 'Tropical Paradise', category: 'nature', description: 'Lush tropical island scenery', image_providers: ['gemini','modelslab','vertex-imagen','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: ['sea','latam','africa'], cultural_tags: ['tropical','island','beach'], tone_modifier: 'warm', aesthetic_keywords: ['palm-trees','turquoise','sunset','paradise'], supported_formats: ['image','video'], is_system_default: true, sort_order: 50 },
  { style_key: 'arctic-aurora', display_name: 'Arctic Aurora', category: 'nature', description: 'Northern lights and Arctic landscapes', image_providers: ['gemini','vertex-imagen','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: ['europe','western'], cultural_tags: ['arctic','aurora','nordic'], tone_modifier: 'professional', aesthetic_keywords: ['aurora-borealis','ice','tundra','stars'], supported_formats: ['image','video'], is_system_default: true, sort_order: 51 },
  { style_key: 'desert-dunes', display_name: 'Desert Dunes', category: 'nature', description: 'Desert sand dunes and arid landscapes', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['sora-2','alibaba-wan','vertex-veo','modelslab-animate'], target_regions: ['mena','africa'], cultural_tags: ['desert','sahara','dunes'], tone_modifier: 'warm', aesthetic_keywords: ['golden-sand','dunes','mirage','caravan'], supported_formats: ['image','video'], is_system_default: true, sort_order: 52 },
  { style_key: 'rainforest', display_name: 'Rainforest', category: 'nature', description: 'Dense tropical rainforest canopy', image_providers: ['gemini','modelslab','vertex-imagen','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: ['latam','sea','africa'], cultural_tags: ['rainforest','amazon','biodiversity'], tone_modifier: 'warm', aesthetic_keywords: ['green','canopy','mist','wildlife'], supported_formats: ['image','video'], is_system_default: true, sort_order: 53 },
  { style_key: 'underwater-ocean', display_name: 'Underwater Ocean', category: 'nature', description: 'Deep sea and coral reef scenes', image_providers: ['vertex-imagen','gemini','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: ['ocean','coral','marine'], tone_modifier: 'professional', aesthetic_keywords: ['deep-blue','coral','bioluminescent','fish'], supported_formats: ['image','video'], is_system_default: true, sort_order: 54 },
  { style_key: 'volcanic', display_name: 'Volcanic', category: 'nature', description: 'Volcanic eruptions and lava landscapes', image_providers: ['gemini','modelslab','replicate','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: [], cultural_tags: ['volcanic','lava','geothermal'], tone_modifier: 'professional', aesthetic_keywords: ['lava','eruption','magma','dramatic'], supported_formats: ['image','video'], is_system_default: true, sort_order: 55 },
  { style_key: 'savanna-wildlife', display_name: 'Savanna Wildlife', category: 'nature', description: 'African savanna with wildlife', image_providers: ['gemini','vertex-imagen','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: ['africa'], cultural_tags: ['savanna','safari','wildlife'], tone_modifier: 'warm', aesthetic_keywords: ['golden-hour','acacia','lion','elephant'], supported_formats: ['image','video'], is_system_default: true, sort_order: 56 },
  { style_key: 'himalayan', display_name: 'Himalayan', category: 'nature', description: 'Himalayan mountain peaks and monasteries', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['sora-2','alibaba-wan','vertex-veo','modelslab-animate'], target_regions: ['india','cjk'], cultural_tags: ['himalaya','mountain','monastery'], tone_modifier: 'formal', aesthetic_keywords: ['snow-peak','monastery','prayer-flags','altitude'], supported_formats: ['image','video'], is_system_default: true, sort_order: 57 },
  { style_key: 'mediterranean', display_name: 'Mediterranean', category: 'nature', description: 'Mediterranean coast and architecture', image_providers: ['vertex-imagen','gemini','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: ['europe','mena'], cultural_tags: ['mediterranean','coast','olive'], tone_modifier: 'warm', aesthetic_keywords: ['white-blue','terrace','olive-grove','azure'], supported_formats: ['image','video'], is_system_default: true, sort_order: 58 },
  { style_key: 'cherry-blossom', display_name: 'Cherry Blossom', category: 'nature', description: 'Japanese cherry blossom season', image_providers: ['alibaba','gemini','modelslab','openai'], video_providers: ['alibaba-wan','sora-2','vertex-veo','modelslab-animate'], target_regions: ['cjk'], cultural_tags: ['sakura','japanese','spring'], tone_modifier: 'warm', aesthetic_keywords: ['pink','petals','spring','serene'], supported_formats: ['image','video'], is_system_default: true, sort_order: 59 },
  { style_key: 'monsoon', display_name: 'Monsoon', category: 'nature', description: 'South Asian monsoon rain and lush greens', image_providers: ['gemini','alibaba','modelslab','openai'], video_providers: ['sora-2','alibaba-wan','vertex-veo','modelslab-animate'], target_regions: ['india','sea'], cultural_tags: ['monsoon','rain','tropical'], tone_modifier: 'warm', aesthetic_keywords: ['rain','lush-green','puddles','thunder'], supported_formats: ['image','video'], is_system_default: true, sort_order: 60 },
  { style_key: 'saharan-golden', display_name: 'Saharan Golden', category: 'nature', description: 'Saharan golden light and vast landscapes', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['sora-2','alibaba-wan','vertex-veo','modelslab-animate'], target_regions: ['africa','mena'], cultural_tags: ['sahara','golden','nomadic'], tone_modifier: 'warm', aesthetic_keywords: ['golden-hour','vast','nomad','tent'], supported_formats: ['image','video'], is_system_default: true, sort_order: 61 },

  // ====== RELIGIOUS & SPIRITUAL (8 styles) ======
  { style_key: 'zen-meditation', display_name: 'Zen Meditation', category: 'religious-spiritual', description: 'Zen Buddhist minimalist tranquility', image_providers: ['alibaba','gemini','modelslab','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], target_regions: ['cjk'], cultural_tags: ['zen','buddhist','meditation','japanese'], tone_modifier: 'formal', aesthetic_keywords: ['stone-garden','bamboo','minimal','water'], supported_formats: ['image','video'], is_system_default: true, sort_order: 70 },
  { style_key: 'sufi-mystical', display_name: 'Sufi Mystical', category: 'religious-spiritual', description: 'Sufi mysticism with whirling dervish imagery', image_providers: ['gemini','alibaba','modelslab','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['mena','india'], cultural_tags: ['sufi','mystical','dervish','rumi'], tone_modifier: 'warm', aesthetic_keywords: ['whirling','cosmic','calligraphy','light'], supported_formats: ['image','video'], is_system_default: true, sort_order: 71 },
  { style_key: 'cathedral-gothic', display_name: 'Cathedral Gothic', category: 'religious-spiritual', description: 'Gothic cathedral architecture with stained glass', image_providers: ['vertex-imagen','gemini','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: ['europe','western'], cultural_tags: ['gothic','cathedral','stained-glass','christian'], tone_modifier: 'formal', aesthetic_keywords: ['stained-glass','vault','rose-window','stone'], supported_formats: ['image','video'], is_system_default: true, sort_order: 72 },
  { style_key: 'temple-sacred', display_name: 'Temple Sacred', category: 'religious-spiritual', description: 'Sacred temple architecture across traditions', image_providers: ['gemini','alibaba','modelslab','openai'], video_providers: ['alibaba-wan','sora-2','vertex-veo','modelslab-animate'], target_regions: ['india','sea','cjk'], cultural_tags: ['temple','sacred','hindu','buddhist'], tone_modifier: 'formal', aesthetic_keywords: ['carved-stone','deity','incense','prayer'], supported_formats: ['image','video'], is_system_default: true, sort_order: 73 },
  { style_key: 'mosque-arabesque', display_name: 'Mosque Arabesque', category: 'religious-spiritual', description: 'Mosque architecture with arabesque patterns', image_providers: ['gemini','alibaba','modelslab','openai'], video_providers: ['sora-2','alibaba-wan','vertex-veo','modelslab-animate'], target_regions: ['mena','sea','india'], cultural_tags: ['mosque','arabesque','islamic','minaret'], tone_modifier: 'formal', aesthetic_keywords: ['dome','minaret','arabesque','marble'], supported_formats: ['image','video'], is_system_default: true, sort_order: 74 },
  { style_key: 'buddhist-serene', display_name: 'Buddhist Serene', category: 'religious-spiritual', description: 'Serene Buddhist monastery and nature', image_providers: ['alibaba','gemini','modelslab','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], target_regions: ['sea','cjk','india'], cultural_tags: ['buddhist','serene','monastery','lotus'], tone_modifier: 'warm', aesthetic_keywords: ['golden-buddha','lotus','incense','peaceful'], supported_formats: ['image','video'], is_system_default: true, sort_order: 75 },
  { style_key: 'spiritual-cosmic', display_name: 'Spiritual Cosmic', category: 'religious-spiritual', description: 'Cosmic spiritual and astral imagery', image_providers: ['modelslab','gemini','replicate','openai'], video_providers: ['sora-2','modelslab-animate','alibaba-wan','replicate'], target_regions: [], cultural_tags: ['cosmic','spiritual','astral','universal'], tone_modifier: 'warm', aesthetic_keywords: ['nebula','chakra','energy','cosmic'], supported_formats: ['image','video','motion'], is_system_default: true, sort_order: 76 },
  { style_key: 'synagogue-traditional', display_name: 'Synagogue Traditional', category: 'religious-spiritual', description: 'Traditional synagogue art and Judaica', image_providers: ['gemini','modelslab','vertex-imagen','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: ['western','europe','mena'], cultural_tags: ['jewish','synagogue','judaica','menorah'], tone_modifier: 'formal', aesthetic_keywords: ['menorah','star-of-david','scroll','gold'], supported_formats: ['image','video'], is_system_default: true, sort_order: 77 },

  // ====== REGIONAL MODERN (10 styles) ======
  { style_key: 'bollywood-vibrant', display_name: 'Bollywood Vibrant', category: 'regional-modern', description: 'Bollywood-inspired vibrant colors and drama', image_providers: ['gemini','modelslab','alibaba','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['india'], cultural_tags: ['bollywood','indian','vibrant','dance'], tone_modifier: 'playful', aesthetic_keywords: ['saturated','glitter','dance','festival'], supported_formats: ['image','video','avatar'], is_system_default: true, sort_order: 80 },
  { style_key: 'k-pop-neon', display_name: 'K-Pop Neon', category: 'regional-modern', description: 'K-Pop inspired neon-lit aesthetic', image_providers: ['alibaba','modelslab','gemini','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], target_regions: ['cjk'], cultural_tags: ['k-pop','korean','neon','idol'], tone_modifier: 'playful', aesthetic_keywords: ['neon','pastel','holographic','stage'], supported_formats: ['image','video','avatar'], is_system_default: true, sort_order: 81 },
  { style_key: 'latin-fiesta', display_name: 'Latin Fiesta', category: 'regional-modern', description: 'Latin American fiesta and carnival energy', image_providers: ['gemini','modelslab','replicate','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['latam'], cultural_tags: ['latin','fiesta','carnival','salsa'], tone_modifier: 'playful', aesthetic_keywords: ['colorful','dance','tropical','rhythmic'], supported_formats: ['image','video'], is_system_default: true, sort_order: 82 },
  { style_key: 'afrobeats-urban', display_name: 'Afrobeats Urban', category: 'regional-modern', description: 'Afrobeats music scene and urban African culture', image_providers: ['gemini','modelslab','replicate','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['africa'], cultural_tags: ['afrobeats','urban','lagos','nairobi'], tone_modifier: 'casual', aesthetic_keywords: ['neon','street','fashion','beats'], supported_formats: ['image','video','avatar'], is_system_default: true, sort_order: 83 },
  { style_key: 'dubai-futuristic', display_name: 'Dubai Futuristic', category: 'regional-modern', description: 'Dubai ultra-modern architecture and luxury', image_providers: ['gemini','vertex-imagen','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: ['mena'], cultural_tags: ['dubai','futuristic','luxury','skyline'], tone_modifier: 'luxury', aesthetic_keywords: ['skyscraper','gold','desert-modern','glass'], supported_formats: ['image','video'], is_system_default: true, sort_order: 84 },
  { style_key: 'tokyo-cyberpunk', display_name: 'Tokyo Cyberpunk', category: 'regional-modern', description: 'Tokyo neon-lit cyberpunk streetscape', image_providers: ['alibaba','modelslab','gemini','openai'], video_providers: ['alibaba-wan','sora-2','modelslab-animate','replicate'], target_regions: ['cjk'], cultural_tags: ['tokyo','cyberpunk','neon','shibuya'], tone_modifier: 'casual', aesthetic_keywords: ['neon-rain','hologram','kanji','night'], supported_formats: ['image','video'], is_system_default: true, sort_order: 85 },
  { style_key: 'scandinavian-hygge', display_name: 'Scandinavian Hygge', category: 'regional-modern', description: 'Cozy Scandinavian minimalism and warmth', image_providers: ['gemini','modelslab','vertex-imagen','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: ['europe'], cultural_tags: ['scandinavian','hygge','nordic','cozy'], tone_modifier: 'warm', aesthetic_keywords: ['candles','wood','knit','minimal-warm'], supported_formats: ['image','video'], is_system_default: true, sort_order: 86 },
  { style_key: 'mediterranean-rustic', display_name: 'Mediterranean Rustic', category: 'regional-modern', description: 'Rustic Mediterranean village life', image_providers: ['vertex-imagen','gemini','modelslab','openai'], video_providers: ['sora-2','vertex-veo','alibaba-wan','modelslab-animate'], target_regions: ['europe','mena'], cultural_tags: ['mediterranean','rustic','village','olive'], tone_modifier: 'warm', aesthetic_keywords: ['stone-wall','olive-grove','terracotta','vineyard'], supported_formats: ['image','video'], is_system_default: true, sort_order: 87 },
  { style_key: 'brazilian-carnival', display_name: 'Brazilian Carnival', category: 'regional-modern', description: 'Rio Carnival samba and celebration', image_providers: ['gemini','modelslab','replicate','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['latam'], cultural_tags: ['brazilian','carnival','samba','rio'], tone_modifier: 'playful', aesthetic_keywords: ['feathers','sequins','dance','parade'], supported_formats: ['image','video','avatar'], is_system_default: true, sort_order: 88 },
  { style_key: 'nigerian-nollywood', display_name: 'Nigerian Nollywood', category: 'regional-modern', description: 'Nollywood cinema and Nigerian urban culture', image_providers: ['gemini','modelslab','replicate','openai'], video_providers: ['sora-2','alibaba-wan','modelslab-animate','replicate'], target_regions: ['africa'], cultural_tags: ['nigerian','nollywood','lagos','yoruba'], tone_modifier: 'casual', aesthetic_keywords: ['dramatic','urban','fashion','storytelling'], supported_formats: ['image','video','avatar'], is_system_default: true, sort_order: 89 },
];

/**
 * Seed the video_style_registry table with all styles.
 * Uses upsert to avoid duplicates on re-seed.
 */
export async function seedVideoStyleRegistry(): Promise<{ inserted: number; errors: string[] }> {
  let inserted = 0;
  const errors: string[] = [];

  // Batch upsert in chunks of 10
  for (let i = 0; i < SEED_STYLES.length; i += 10) {
    const batch = SEED_STYLES.slice(i, i + 10).map(s => ({
      style_key: s.style_key,
      display_name: s.display_name,
      category: s.category,
      subcategory: s.subcategory || null,
      description: s.description,
      image_providers: s.image_providers,
      video_providers: s.video_providers,
      avatar_providers: s.avatar_providers || [],
      three_d_providers: s.three_d_providers || [],
      motion_providers: s.motion_providers || [],
      lipsync_providers: s.lipsync_providers || [],
      target_regions: s.target_regions,
      cultural_tags: s.cultural_tags,
      tone_modifier: s.tone_modifier,
      aesthetic_keywords: s.aesthetic_keywords,
      supported_formats: s.supported_formats,
      is_system_default: s.is_system_default,
      is_active: true,
      sort_order: s.sort_order,
    }));

    const { error, count } = await supabase
      .from('video_style_registry')
      .upsert(batch as any, { onConflict: 'style_key' });

    if (error) {
      errors.push(`Batch ${i}: ${error.message}`);
    } else {
      inserted += batch.length;
    }
  }

  console.log(`[StyleRegistry] Seeded ${inserted} styles, ${errors.length} errors`);
  return { inserted, errors };
}

export { SEED_STYLES };
