
/**
 * Module Registry Types and Interfaces
 */

import { ModuleConfig } from '../moduleValidation';

export interface ComponentServiceInfo {
  name: string;
  type: 'component' | 'service' | 'hook';
  filePath: string;
  permissions: string[];
  isProtected: boolean;
  lastModified: string;
  note?: string; // Optional note for auto-generated or likely components
}

export interface RegisteredModule extends ModuleConfig {
  version: string;
  lastUpdated: string;
  dependencies: string[];
  status: 'active' | 'deprecated' | 'development';
  isAutoGenerated?: boolean;
  confidence?: number;
  description?: string;
  components?: ComponentServiceInfo[];
  services?: ComponentServiceInfo[];
  hooks?: ComponentServiceInfo[];
}

export interface AutoRegistrationConfig {
  enabled: boolean;
  confidenceThreshold: number;
  scanIntervalMs: number;
  autoGenerateCode: boolean;
  trackComponents: boolean;
  trackServices: boolean;
}

export interface RegistryStats {
  total: number;
  active: number;
  deprecated: number;
  development: number;
  autoGenerated: number;
  totalComponents: number;
  totalServices: number;
  totalHooks: number;
  protectedComponents: number;
  lastUpdated: Date;
}
