
/**
 * Module Registry Types - Consolidated Type Definitions
 */

export interface ComponentServiceInfo {
  name: string;
  type: 'component' | 'service' | 'hook';
  path?: string; // Added missing path property
  filePath?: string; // Alternative path property name
  isProtected: boolean;
  lastModified: string;
  permissions?: string[];
}

export interface RegisteredModule {
  moduleName: string;
  tableName: string;
  requiredFields: string[];
  optionalFields?: string[];
  version: string;
  lastUpdated: Date;
  status: 'active' | 'deprecated' | 'development';
  description?: string;
  isAutoGenerated?: boolean;
  confidenceScore?: number;
  components?: ComponentServiceInfo[];
  services?: ComponentServiceInfo[];
  hooks?: ComponentServiceInfo[];
}

export interface AutoRegistrationConfig {
  enabled: boolean;
  confidenceThreshold: number;
  scanIntervalMs: number;
  autoGenerateCode: boolean;
  trackComponents: boolean;
  trackServices: boolean;
}

export interface RegistryStats {
  total: number;
  active: number;
  deprecated: number;
  development: number;
  autoGenerated: number;
  totalComponents: number;
  totalServices: number;
  totalHooks: number;
  protectedComponents: number;
  lastUpdated: Date;
  totalModules: number;
  activeModules: number;
  tablesUsed: number;
  lastRegistration: number | null;
}
