
/**
 * Module Registry Types - Enhanced Type Safety
 */

export interface ComponentServiceInfo {
  name: string;
  type: 'component' | 'service' | 'hook';
  path: string;
  filePath?: string; // Optional for backward compatibility
  description?: string;
  isProtected?: boolean;
  dependencies?: string[];
  version?: string;
  permissions?: string[]; // Added for RBAC functionality
  lastModified?: string; // Added for tracking changes
}

export interface RegisteredModule {
  moduleName: string;
  version: string;
  description?: string;
  status: 'active' | 'deprecated' | 'development';
  tableName?: string;
  requiredFields?: string[];
  optionalFields?: string[]; // Added missing property
  components?: ComponentServiceInfo[];
  services?: ComponentServiceInfo[];
  hooks?: ComponentServiceInfo[];
  isAutoGenerated?: boolean;
  confidenceScore?: number;
  lastUpdated: Date;
  createdBy?: string;
  customValidation?: (data: any) => boolean | string;
}

export interface AutoRegistrationConfig {
  enabled: boolean;
  confidenceThreshold: number;
  scanIntervalMs: number;
  autoGenerateCode: boolean;
  trackComponents: boolean;
  trackServices: boolean;
}

export interface RegistryStats {
  total: number;
  active: number;
  deprecated: number;
  development: number;
  autoGenerated: number;
  totalComponents: number;
  totalServices: number;
  totalHooks: number;
  protectedComponents: number;
  lastUpdated: Date;
}
