// Sprint Tracker — Task Definitions (41 tasks from GENIESUITE_PROJECT_PLAN.csv)

import type { SprintTask } from './types';

export const SPRINT_TASKS: SprintTask[] = [
  // ── Day 1: Foundation & Assessment ──
  { id: 'L-101', title: 'Audit RegionalLandingPage.tsx for broken regional content', developer: 'lovable', day: 1, priority: 'high', module: 'Landing Page', filesInvolved: ['src/components/landing/RegionalLandingPage.tsx'], acceptanceCriteria: 'All 14 regions render without errors', estimatedHours: 4, notes: 'Main landing page - 70KB file' },
  { id: 'L-102', title: 'Audit GenieExplorePage - verify explore journey', developer: 'lovable', day: 1, priority: 'high', module: 'Landing Page', filesInvolved: ['src/pages/GenieExplorePage.tsx'], acceptanceCriteria: 'Explore steps 1-N complete without errors', estimatedHours: 2 },
  { id: 'L-103', title: 'Fix broken hero sections and demos', developer: 'lovable', day: 1, priority: 'medium', module: 'Landing Page', filesInvolved: ['src/components/landing/HeroLandingVideo.tsx', 'src/components/landing/HeroInteractiveVideo.tsx'], acceptanceCriteria: 'Hero videos play and interactive elements respond', estimatedHours: 3 },
  { id: 'L-104', title: 'Verify all legal pages render correctly', developer: 'lovable', day: 1, priority: 'low', module: 'Legal Pages', filesInvolved: ['src/pages/TermsOfServicePage.tsx', 'src/pages/PrivacyPolicyPage.tsx'], acceptanceCriteria: 'All 6 legal pages load and display content', estimatedHours: 1 },
  { id: 'C-101', title: 'Read and diagnose GenieSpark.tsx - trace creation flow', developer: 'claude', day: 1, priority: 'high', module: 'Genie Spark', filesInvolved: ['src/pages/GenieSpark.tsx', 'src/components/genie-spark/SparkGuidedWizard.tsx'], acceptanceCriteria: 'Issues documented with root causes identified', estimatedHours: 2 },
  { id: 'C-102', title: 'Read and diagnose GenieMind.tsx - trace editing flow', developer: 'claude', day: 1, priority: 'high', module: 'Genie Mind', filesInvolved: ['src/pages/GenieMind.tsx', 'src/components/genie-studio/ScriptEditorTab.tsx'], acceptanceCriteria: 'Issues documented with root causes identified', estimatedHours: 2 },
  { id: 'C-103', title: 'Read and diagnose GenieDeck.tsx - trace presentation flow', developer: 'claude', day: 1, priority: 'high', module: 'Genie Deck', filesInvolved: ['src/pages/GenieDeck.tsx', 'src/components/genie-studio/presentation-generator/PresentationWizard.tsx'], acceptanceCriteria: 'Issues documented with root causes identified', estimatedHours: 2 },
  { id: 'C-104', title: 'Document all issues found across Spark/Mind/Deck', developer: 'claude', day: 1, priority: 'high', module: 'All', filesInvolved: [], acceptanceCriteria: 'Written diagnosis with fix plan for each module', estimatedHours: 1 },
  { id: 'S-101', title: 'End of Day 1 build check and sync', developer: 'claude', day: 1, priority: 'high', module: 'Sync', filesInvolved: [], acceptanceCriteria: 'Build passes for both branches', estimatedHours: 0.5 },

  // ── Day 2: Genie Deck + Landing Products ──
  { id: 'L-201', title: 'Fix/enhance GenieProductsPage.tsx - product catalog', developer: 'lovable', day: 2, priority: 'high', module: 'Products', filesInvolved: ['src/pages/GenieProductsPage.tsx'], acceptanceCriteria: 'Product catalog renders all products with correct info', estimatedHours: 3 },
  { id: 'L-202', title: 'Fix pricing section in landing page', developer: 'lovable', day: 2, priority: 'high', module: 'Pricing', filesInvolved: ['src/components/landing/RegionalPricingSection.tsx'], acceptanceCriteria: 'Pricing tiers display correctly per region', estimatedHours: 2 },
  { id: 'L-203', title: 'Verify Explore demo pages work', developer: 'lovable', day: 2, priority: 'medium', module: 'Explore', filesInvolved: ['src/pages/GenieExploreDemoPage.tsx'], acceptanceCriteria: 'Demo flows complete without errors', estimatedHours: 2 },
  { id: 'L-204', title: 'Add any missing landing page sections', developer: 'lovable', day: 2, priority: 'medium', module: 'Landing Page', filesInvolved: ['src/components/landing/**'], acceptanceCriteria: 'All planned sections present and rendering', estimatedHours: 2 },
  { id: 'C-201', title: 'Fix GenieDeck creation flow - PresentationWizard', developer: 'claude', day: 2, priority: 'high', module: 'Genie Deck', filesInvolved: ['src/pages/GenieDeck.tsx', 'src/components/genie-studio/presentation-generator/PresentationWizard.tsx'], acceptanceCriteria: 'Deck creates presentations end-to-end', estimatedHours: 4 },
  { id: 'C-202', title: 'Fix presentation-generator sub-components', developer: 'claude', day: 2, priority: 'high', module: 'Genie Deck', filesInvolved: ['src/components/genie-studio/presentation-generator/**'], acceptanceCriteria: 'All 6 wizard steps complete without errors', estimatedHours: 3 },
  { id: 'C-203', title: 'Verify Deck end-to-end: input → slides → preview → save', developer: 'claude', day: 2, priority: 'high', module: 'Genie Deck', filesInvolved: ['src/pages/GenieDeck.tsx'], acceptanceCriteria: 'Full presentation generation workflow works', estimatedHours: 1 },
  { id: 'S-201', title: 'End of Day 2 build check and sync', developer: 'claude', day: 2, priority: 'high', module: 'Sync', filesInvolved: [], acceptanceCriteria: 'Build passes; Deck working', estimatedHours: 0.5 },

  // ── Day 3: Genie Spark + Landing Demos ──
  { id: 'L-301', title: 'Fix interactive demos - InteractiveTryGenieDemo & STTDemo', developer: 'lovable', day: 3, priority: 'high', module: 'Landing Page', filesInvolved: ['src/components/landing/InteractiveTryGenieDemo.tsx', 'src/components/landing/STTDemo.tsx'], acceptanceCriteria: 'Demos respond to user interaction correctly', estimatedHours: 3 },
  { id: 'L-302', title: 'Fix DeepLTranslationDemo', developer: 'lovable', day: 3, priority: 'medium', module: 'Landing Page', filesInvolved: ['src/components/landing/DeepLTranslationDemo.tsx'], acceptanceCriteria: 'Translation demo works with sample text', estimatedHours: 2 },
  { id: 'L-303', title: 'Fix video showcases - GenieVideoShowcase & HeroLandingVideo', developer: 'lovable', day: 3, priority: 'high', module: 'Landing Page', filesInvolved: ['src/components/landing/GenieVideoShowcase.tsx', 'src/components/landing/HeroLandingVideo.tsx'], acceptanceCriteria: 'Videos play and showcase sections render', estimatedHours: 2 },
  { id: 'L-304', title: 'Verify region switching across all 14 regions', developer: 'lovable', day: 3, priority: 'medium', module: 'Landing Page', filesInvolved: ['src/components/landing/RegionSwitcherNav.tsx', 'src/config/regionalLandingConfig.ts'], acceptanceCriteria: 'All regions selectable and content changes correctly', estimatedHours: 2 },
  { id: 'C-301', title: 'Fix SmartContentPipeline AI generation', developer: 'claude', day: 3, priority: 'high', module: 'Genie Spark', filesInvolved: ['src/components/genie-studio/SmartContentPipeline.tsx'], acceptanceCriteria: 'AI generates script content from user prompts', estimatedHours: 3 },
  { id: 'C-302', title: 'Fix SparkGuidedWizard step-by-step flow', developer: 'claude', day: 3, priority: 'high', module: 'Genie Spark', filesInvolved: ['src/components/genie-spark/SparkGuidedWizard.tsx'], acceptanceCriteria: 'All wizard steps complete and advance correctly', estimatedHours: 2 },
  { id: 'C-303', title: 'Fix script save via useGenieScripts', developer: 'claude', day: 3, priority: 'high', module: 'Genie Spark', filesInvolved: ['src/components/genie-studio/useGenieScripts.ts'], acceptanceCriteria: 'Scripts save to Supabase genie_scripts table', estimatedHours: 2 },
  { id: 'C-304', title: 'Verify Spark end-to-end: prompt → generate → save', developer: 'claude', day: 3, priority: 'high', module: 'Genie Spark', filesInvolved: ['src/pages/GenieSpark.tsx'], acceptanceCriteria: 'Full Spark workflow creates and persists a script', estimatedHours: 1 },
  { id: 'S-301', title: 'End of Day 3 build check and sync', developer: 'claude', day: 3, priority: 'high', module: 'Sync', filesInvolved: [], acceptanceCriteria: 'Build passes; Deck + Spark working', estimatedHours: 0.5 },

  // ── Day 4: Genie Mind + Landing Polish ──
  { id: 'L-401', title: 'Mobile responsiveness polish', developer: 'lovable', day: 4, priority: 'high', module: 'Landing Page', filesInvolved: ['src/components/landing/**'], acceptanceCriteria: 'Landing page renders correctly on mobile viewports', estimatedHours: 3 },
  { id: 'L-402', title: 'SEO verification - meta tags and social sharing', developer: 'lovable', day: 4, priority: 'medium', module: 'Landing Page', filesInvolved: ['src/components/landing/RegionalLandingPage.tsx'], acceptanceCriteria: 'OG tags and meta descriptions present per region', estimatedHours: 2 },
  { id: 'L-403', title: 'Performance optimization - lazy loading and images', developer: 'lovable', day: 4, priority: 'medium', module: 'Landing Page', filesInvolved: ['src/components/landing/**'], acceptanceCriteria: 'Lighthouse score improved', estimatedHours: 2 },
  { id: 'L-404', title: 'Cross-browser testing of landing page', developer: 'lovable', day: 4, priority: 'low', module: 'Landing Page', filesInvolved: ['src/components/landing/**'], acceptanceCriteria: 'Landing works on Chrome Firefox Safari Edge', estimatedHours: 1 },
  { id: 'C-401', title: 'Fix ScriptEditorTab - script loading and editing', developer: 'claude', day: 4, priority: 'high', module: 'Genie Mind', filesInvolved: ['src/components/genie-studio/ScriptEditorTab.tsx'], acceptanceCriteria: 'Scripts load from DB and can be edited', estimatedHours: 3 },
  { id: 'C-402', title: 'Fix SavedAudioCard voiceover display', developer: 'claude', day: 4, priority: 'medium', module: 'Genie Mind', filesInvolved: ['src/components/genie-studio/SavedAudioCard.tsx'], acceptanceCriteria: 'Voiceovers display with playback controls', estimatedHours: 1 },
  { id: 'C-403', title: 'Fix CrossFunctionalMusic generation', developer: 'claude', day: 4, priority: 'medium', module: 'Genie Mind', filesInvolved: ['src/components/genie-studio/CrossFunctionalMusic.tsx'], acceptanceCriteria: 'Music generation UI works and audio saves', estimatedHours: 2 },
  { id: 'C-404', title: 'Verify Spark → Mind flow: script appears in Mind', developer: 'claude', day: 4, priority: 'high', module: 'Genie Mind', filesInvolved: ['src/pages/GenieMind.tsx', 'src/pages/GenieSpark.tsx'], acceptanceCriteria: 'Navigate from Spark to Mind; script is loaded and editable', estimatedHours: 1 },
  { id: 'S-401', title: 'End of Day 4 build check and sync', developer: 'claude', day: 4, priority: 'high', module: 'Sync', filesInvolved: [], acceptanceCriteria: 'Build passes; all 3 CREATE modules working', estimatedHours: 0.5 },

  // ── Day 5: Integration & Merge ──
  { id: 'L-501', title: 'Final verification: all landing routes work', developer: 'lovable', day: 5, priority: 'high', module: 'All', filesInvolved: [], acceptanceCriteria: 'All 4 landing routes load without errors', estimatedHours: 1 },
  { id: 'L-502', title: 'Verify navigation: landing → auth → genie-studio', developer: 'lovable', day: 5, priority: 'high', module: 'All', filesInvolved: [], acceptanceCriteria: 'User can navigate from landing to login to studio', estimatedHours: 1 },
  { id: 'L-503', title: 'Run npm run build and prepare merge', developer: 'lovable', day: 5, priority: 'high', module: 'All', filesInvolved: [], acceptanceCriteria: 'Build passes; branch ready for merge', estimatedHours: 0.5 },
  { id: 'L-504', title: 'Rebase onto main and merge', developer: 'lovable', day: 5, priority: 'high', module: 'All', filesInvolved: [], acceptanceCriteria: 'Clean merge with no conflicts', estimatedHours: 0.5, notes: 'Lovable merges AFTER Claude' },
  { id: 'C-501', title: 'Final verification: all GenieSuite CREATE routes work', developer: 'claude', day: 5, priority: 'high', module: 'All', filesInvolved: [], acceptanceCriteria: 'All 3 CREATE routes load without errors', estimatedHours: 1 },
  { id: 'C-502', title: 'Verify QuadrantNavigation between Spark/Mind/Deck', developer: 'claude', day: 5, priority: 'high', module: 'All', filesInvolved: ['src/components/navigation/QuadrantNavigation.tsx'], acceptanceCriteria: 'Navigation tabs switch between modules correctly', estimatedHours: 0.5 },
  { id: 'C-503', title: 'Verify full pipeline: Spark → Mind → Deck standalone', developer: 'claude', day: 5, priority: 'high', module: 'All', filesInvolved: [], acceptanceCriteria: 'End-to-end workflow completes', estimatedHours: 1 },
  { id: 'C-504', title: 'Run npm run build and merge to main', developer: 'claude', day: 5, priority: 'high', module: 'All', filesInvolved: [], acceptanceCriteria: 'Build passes; merged to main cleanly', estimatedHours: 0.5, notes: 'Claude merges FIRST' },
  { id: 'S-501', title: 'Final build check on main after both merges', developer: 'claude', day: 5, priority: 'high', module: 'Sync', filesInvolved: [], acceptanceCriteria: 'Main branch builds; all routes work', estimatedHours: 0.5 },
];
