import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import "https://deno.land/x/xhr@0.1.0/mod.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const GOOGLE_API_KEY = Deno.env.get('GOOGLE_API_KEY');
    if (!GOOGLE_API_KEY) {
      throw new Error('GOOGLE_API_KEY is not set');
    }

    const body = await req.json();
    const { prompt, duration = 5, aspectRatio = '16:9', fps = 24 } = body;

    if (!prompt) {
      return new Response(
        JSON.stringify({ error: 'Prompt is required' }), 
        { 
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      );
    }

    console.log('🎬 Generating video with Gemini API:', { prompt, duration, aspectRatio, fps });

    // Enhanced prompt for better video generation
    const enhancedPrompt = `Create a ${duration}-second video: ${prompt}. ${aspectRatio} aspect ratio, ${fps} fps. High quality, smooth motion, professional cinematography.`;

    const startTime = Date.now();

    // Use Google's Gemini API for video generation
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/veo-001:generateVideo?key=${GOOGLE_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: enhancedPrompt,
        config: {
          aspectRatio: aspectRatio,
          duration: `${duration}s`,
          frameRate: fps,
          safetyFilterLevel: 'MODERATE'
        }
      }),
    });

    const data = await response.json();
    console.log('🔍 Gemini video API response:', { status: response.status, hasVideo: !!data.generatedVideos });

    if (!response.ok) {
      console.error('❌ Gemini video API error:', data);
      
      // If video generation is not available, fallback to creating multiple images as frames
      if (data.error?.message?.includes('video') || data.error?.message?.includes('not available')) {
        console.log('📸 Falling back to image sequence generation...');
        
        // Generate a sequence of images to simulate video
        const imagePrompts = [
          `${prompt} - beginning scene, wide shot`,
          `${prompt} - middle action, medium shot`,  
          `${prompt} - final result, close-up`
        ];

        const images = [];
        for (const imagePrompt of imagePrompts) {
          try {
            const imgResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:generateImage?key=${GOOGLE_API_KEY}`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                prompt: imagePrompt,
                config: { aspectRatio, safetyFilterLevel: 'MODERATE' }
              }),
            });

            const imgData = await imgResponse.json();
            if (imgData.generatedImages?.[0]) {
              images.push(`data:image/png;base64,${imgData.generatedImages[0].imageBytes}`);
            }
          } catch (err) {
            console.warn('⚠️ Failed to generate frame:', err);
          }
        }

        if (images.length > 0) {
          const processingTime = Date.now() - startTime;
          return new Response(JSON.stringify({ 
            success: true,
            videoUrl: images[0], // Return first image as primary
            mediaUrl: images[0],
            imageSequence: images,
            isImageSequence: true,
            processingTime,
            metadata: {
              prompt,
              duration,
              aspectRatio,
              fps,
              model: 'imagen-3.0-generate-001-sequence',
              timestamp: new Date().toISOString(),
              note: 'Generated as image sequence due to video API limitations'
            }
          }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          });
        }
      }
      
      throw new Error(data.error?.message || `Gemini Video API error: ${response.status}`);
    }

    if (!data.generatedVideos || data.generatedVideos.length === 0) {
      throw new Error('No videos generated by Gemini API');
    }

    const videoBytes = data.generatedVideos[0].videoBytes;
    const videoUrl = `data:video/mp4;base64,${videoBytes}`;
    
    const processingTime = Date.now() - startTime;

    console.log('✅ Video generated successfully in', processingTime, 'ms');

    return new Response(JSON.stringify({ 
      success: true,
      videoUrl,
      mediaUrl: videoUrl,
      processingTime,
      metadata: {
        prompt,
        duration,
        aspectRatio,
        fps,
        model: 'veo-001',
        timestamp: new Date().toISOString()
      }
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('💥 Error in gemini-generate-video function:', error);
    return new Response(JSON.stringify({ 
      success: false,
      error: error.message || 'Unknown error occurred',
      timestamp: new Date().toISOString()
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});