/**
 * Feature Discovery Service
 * 
 * Automatically detects and registers new features, pipelines, and categories
 * for the dogfooding marketing engine. Configurable for custom messaging.
 */

import { PIPELINE_MARKETING_CATALOG, CATEGORY_METADATA, type PipelineCategory, type ContentFormat } from '../marketingContentManager';
import { GENIE_PRODUCT_POSITIONING, FEATURE_SHOWCASE_TOPICS } from '../dogfoodingMarketingEngine';

// ============================================================================
// TYPES
// ============================================================================

export interface DiscoveredFeature {
  id: string;
  name: string;
  category: PipelineCategory;
  product: string;
  discoveredAt: Date;
  status: 'new' | 'pending_messaging' | 'active' | 'deprecated';
  
  // Auto-generated messaging
  autoGeneratedHook?: string;
  autoGeneratedDescription?: string;
  
  // Custom messaging (overrides auto-generated)
  customMessaging?: CustomMessaging;
  
  // Stats
  timesUsed: number;
  lastUsed?: Date;
  performanceScore?: number;
}

export interface CustomMessaging {
  headline: string;
  hook: string;
  description: string;
  painPoints?: string[];
  benefits?: string[];
  targetAudience?: string[];
  hashtags?: string[];
  avoidWords?: string[];
}

export interface FeatureCategory {
  id: PipelineCategory;
  name: string;
  features: DiscoveredFeature[];
  isActive: boolean;
  customMessaging?: Partial<CustomMessaging>;
  priority: number;
  rotationWeight: number; // 0-100, higher = more frequent in marketing
}

export interface MessagingTemplate {
  id: string;
  name: string;
  type: 'headline' | 'hook' | 'body' | 'cta';
  template: string; // Uses placeholders like {{feature_name}}, {{benefit}}
  category?: PipelineCategory;
  format?: ContentFormat;
  region?: string;
  usageCount: number;
  performanceScore?: number;
}

export interface PositioningStatement {
  id: string;
  product: string;
  region: string;
  statement: string;
  isActive: boolean;
  createdAt: Date;
  lastUsed?: Date;
}

// ============================================================================
// DEFAULT MESSAGING TEMPLATES
// ============================================================================

export const MESSAGING_TEMPLATES: MessagingTemplate[] = [
  // Headlines
  { id: 'headline_transform', name: 'Transformation', type: 'headline', template: 'Transform {{input}} into {{output}} in seconds', usageCount: 0 },
  { id: 'headline_stop', name: 'Stop Doing', type: 'headline', template: 'Stop wasting hours on {{pain_point}}', usageCount: 0 },
  { id: 'headline_question', name: 'Question', type: 'headline', template: 'What if {{benefit}} was just one click away?', usageCount: 0 },
  { id: 'headline_stat', name: 'Statistic', type: 'headline', template: '{{stat}}% faster {{action}} with AI', usageCount: 0 },
  { id: 'headline_announce', name: 'Announcement', type: 'headline', template: 'Introducing {{feature_name}}: {{one_liner}}', usageCount: 0 },
  
  // Hooks
  { id: 'hook_problem', name: 'Problem Hook', type: 'hook', template: 'Tired of {{pain_point}}? You\'re not alone.', usageCount: 0 },
  { id: 'hook_result', name: 'Result Hook', type: 'hook', template: 'In 30 seconds, I\'ll show you how to {{benefit}}', usageCount: 0 },
  { id: 'hook_before_after', name: 'Before/After', type: 'hook', template: 'Watch {{input}} become {{output}} in real time', usageCount: 0 },
  { id: 'hook_secret', name: 'Secret', type: 'hook', template: 'The secret to {{benefit}} that {{audience}} don\'t want you to know', usageCount: 0 },
  { id: 'hook_mistake', name: 'Mistake', type: 'hook', template: 'Stop making this common {{action}} mistake', usageCount: 0 },
  
  // Body
  { id: 'body_features', name: 'Feature List', type: 'body', template: 'With {{feature_name}}, you can:\n✓ {{benefit_1}}\n✓ {{benefit_2}}\n✓ {{benefit_3}}', usageCount: 0 },
  { id: 'body_story', name: 'Mini Story', type: 'body', template: 'We built {{feature_name}} because {{audience}} told us they were struggling with {{pain_point}}. Now they can {{benefit}}.', usageCount: 0 },
  { id: 'body_comparison', name: 'Comparison', type: 'body', template: 'Before: {{before}}\nAfter: {{after}}\nThe difference? {{feature_name}}.', usageCount: 0 },
  
  // CTAs
  { id: 'cta_try', name: 'Try Now', type: 'cta', template: 'Try {{feature_name}} free → {{url}}', usageCount: 0 },
  { id: 'cta_discover', name: 'Discover', type: 'cta', template: 'Discover what {{benefit}} looks like for you', usageCount: 0 },
  { id: 'cta_join', name: 'Join', type: 'cta', template: 'Join {{number}}+ creators already using {{feature_name}}', usageCount: 0 },
  { id: 'cta_start', name: 'Get Started', type: 'cta', template: 'Start your {{benefit}} journey today', usageCount: 0 },
];

// ============================================================================
// FEATURE DISCOVERY SERVICE
// ============================================================================

class FeatureDiscoveryService {
  private static instance: FeatureDiscoveryService;
  private discoveredFeatures: Map<string, DiscoveredFeature> = new Map();
  private categories: Map<PipelineCategory, FeatureCategory> = new Map();
  private positioningStatements: Map<string, PositioningStatement> = new Map();
  private messagingTemplates: MessagingTemplate[] = [...MESSAGING_TEMPLATES];

  static getInstance(): FeatureDiscoveryService {
    if (!this.instance) {
      this.instance = new FeatureDiscoveryService();
      this.instance.initialize();
    }
    return this.instance;
  }

  /**
   * Initialize with existing catalog
   */
  private initialize(): void {
    // Register all known pipelines
    PIPELINE_MARKETING_CATALOG.forEach(pipeline => {
      this.discoveredFeatures.set(pipeline.id, {
        id: pipeline.id,
        name: pipeline.name,
        category: pipeline.category,
        product: this.inferProduct(pipeline.category),
        discoveredAt: new Date(),
        status: 'active',
        autoGeneratedHook: pipeline.hook,
        timesUsed: 0,
      });
    });

    // Register feature showcase topics
    FEATURE_SHOWCASE_TOPICS.forEach(topic => {
      const id = `${topic.product}_${topic.feature.toLowerCase().replace(/\s+/g, '_')}`;
      if (!this.discoveredFeatures.has(id)) {
        this.discoveredFeatures.set(id, {
          id,
          name: topic.feature,
          category: this.inferCategory(topic.product),
          product: topic.product,
          discoveredAt: new Date(),
          status: 'active',
          autoGeneratedHook: topic.hook,
          timesUsed: 0,
        });
      }
    });

    // Initialize categories
    for (const [categoryId, metadata] of Object.entries(CATEGORY_METADATA)) {
      const category = categoryId as PipelineCategory;
      const features = Array.from(this.discoveredFeatures.values())
        .filter(f => f.category === category);

      this.categories.set(category, {
        id: category,
        name: metadata.displayName,
        features,
        isActive: true,
        priority: 1,
        rotationWeight: 50,
      });
    }

    // Initialize positioning from existing catalog
    for (const [productId, positioning] of Object.entries(GENIE_PRODUCT_POSITIONING)) {
      const id = `${productId}_default`;
      this.positioningStatements.set(id, {
        id,
        product: productId,
        region: 'global',
        statement: positioning.valueProposition,
        isActive: true,
        createdAt: new Date(),
      });
    }

    console.log(`[FeatureDiscovery] Initialized with ${this.discoveredFeatures.size} features across ${this.categories.size} categories`);
  }

  /**
   * Infer product from category
   */
  private inferProduct(category: PipelineCategory): string {
    const categoryToProduct: Record<PipelineCategory, string> = {
      text_based: 'spark',
      image_based: 'spark',
      voice_audio: 'vibe',
      document_ppt: 'deck',
      video_based: 'arc',
      '3d_based': 'arc',
      ar_vr_scene: 'arc',
      complex_multimodal: 'arc',
      presentation: 'deck',
      repurposing: 'arc',
      training_ld: 'mind',
      marketing_sales: 'arc',
      localization: 'arc',
      social_publishing: 'hub',
    };
    return categoryToProduct[category] || 'spark';
  }

  /**
   * Infer category from product
   */
  private inferCategory(product: string): PipelineCategory {
    const productToCategory: Record<string, PipelineCategory> = {
      spark: 'text_based',
      mind: 'training_ld',
      vibe: 'voice_audio',
      deck: 'presentation',
      arc: 'video_based',
      hub: 'social_publishing',
    };
    return productToCategory[product] || 'complex_multimodal';
  }

  /**
   * Register new feature (auto-discovered or manual)
   */
  registerFeature(feature: Omit<DiscoveredFeature, 'discoveredAt' | 'status' | 'timesUsed'>): DiscoveredFeature {
    const newFeature: DiscoveredFeature = {
      ...feature,
      discoveredAt: new Date(),
      status: feature.customMessaging ? 'active' : 'pending_messaging',
      timesUsed: 0,
    };

    this.discoveredFeatures.set(feature.id, newFeature);

    // Update category
    const category = this.categories.get(feature.category);
    if (category) {
      category.features.push(newFeature);
    }

    console.log(`[FeatureDiscovery] Registered new feature: ${feature.name}`);
    return newFeature;
  }

  /**
   * Update feature messaging
   */
  updateFeatureMessaging(featureId: string, messaging: CustomMessaging): void {
    const feature = this.discoveredFeatures.get(featureId);
    if (!feature) return;

    feature.customMessaging = messaging;
    feature.status = 'active';

    console.log(`[FeatureDiscovery] Updated messaging for: ${feature.name}`);
  }

  /**
   * Add custom positioning statement
   */
  addPositioningStatement(
    product: string,
    region: string,
    statement: string
  ): PositioningStatement {
    const id = `${product}_${region}_${Date.now()}`;
    const positioning: PositioningStatement = {
      id,
      product,
      region,
      statement,
      isActive: true,
      createdAt: new Date(),
    };

    this.positioningStatements.set(id, positioning);
    console.log(`[FeatureDiscovery] Added positioning for ${product} in ${region}`);

    return positioning;
  }

  /**
   * Get positioning for product/region
   */
  getPositioning(product: string, region: string = 'global'): string {
    // Try region-specific first
    const regionSpecific = Array.from(this.positioningStatements.values())
      .find(p => p.product === product && p.region === region && p.isActive);
    
    if (regionSpecific) return regionSpecific.statement;

    // Fall back to global
    const global = Array.from(this.positioningStatements.values())
      .find(p => p.product === product && p.region === 'global' && p.isActive);

    return global?.statement || GENIE_PRODUCT_POSITIONING[product]?.valueProposition || '';
  }

  /**
   * Add custom messaging template
   */
  addMessagingTemplate(template: Omit<MessagingTemplate, 'usageCount' | 'performanceScore'>): MessagingTemplate {
    const newTemplate: MessagingTemplate = {
      ...template,
      usageCount: 0,
    };

    this.messagingTemplates.push(newTemplate);
    console.log(`[FeatureDiscovery] Added messaging template: ${template.name}`);

    return newTemplate;
  }

  /**
   * Get random template by type
   */
  getTemplate(type: MessagingTemplate['type'], category?: PipelineCategory): MessagingTemplate | null {
    const candidates = this.messagingTemplates.filter(t => {
      if (t.type !== type) return false;
      if (category && t.category && t.category !== category) return false;
      return true;
    });

    if (candidates.length === 0) return null;

    // Weighted random based on performance (if available)
    const weighted = candidates.map(t => ({
      template: t,
      weight: t.performanceScore || 1,
    }));

    const totalWeight = weighted.reduce((sum, w) => sum + w.weight, 0);
    let random = Math.random() * totalWeight;

    for (const { template, weight } of weighted) {
      random -= weight;
      if (random <= 0) return template;
    }

    return candidates[0];
  }

  /**
   * Generate messaging from template
   */
  generateFromTemplate(
    templateId: string,
    placeholders: Record<string, string>
  ): string {
    const template = this.messagingTemplates.find(t => t.id === templateId);
    if (!template) return '';

    let result = template.template;
    for (const [key, value] of Object.entries(placeholders)) {
      result = result.replace(new RegExp(`{{${key}}}`, 'g'), value);
    }

    template.usageCount++;
    return result;
  }

  /**
   * Get features for marketing rotation
   */
  getFeaturesForRotation(
    category?: PipelineCategory,
    limit: number = 10
  ): DiscoveredFeature[] {
    let features = Array.from(this.discoveredFeatures.values())
      .filter(f => f.status === 'active');

    if (category) {
      features = features.filter(f => f.category === category);
    }

    // Sort by least used first (for variety)
    features.sort((a, b) => a.timesUsed - b.timesUsed);

    return features.slice(0, limit);
  }

  /**
   * Get new features (recently discovered, less than 7 days)
   */
  getNewFeatures(): DiscoveredFeature[] {
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    
    return Array.from(this.discoveredFeatures.values())
      .filter(f => f.discoveredAt > sevenDaysAgo && f.status === 'active')
      .sort((a, b) => b.discoveredAt.getTime() - a.discoveredAt.getTime());
  }

  /**
   * Get features pending messaging
   */
  getFeaturesPendingMessaging(): DiscoveredFeature[] {
    return Array.from(this.discoveredFeatures.values())
      .filter(f => f.status === 'pending_messaging');
  }

  /**
   * Mark feature as used
   */
  markFeatureUsed(featureId: string): void {
    const feature = this.discoveredFeatures.get(featureId);
    if (feature) {
      feature.timesUsed++;
      feature.lastUsed = new Date();
    }
  }

  /**
   * Update category priority/weight
   */
  updateCategoryPriority(
    categoryId: PipelineCategory,
    updates: { priority?: number; rotationWeight?: number }
  ): void {
    const category = this.categories.get(categoryId);
    if (category) {
      if (updates.priority !== undefined) category.priority = updates.priority;
      if (updates.rotationWeight !== undefined) category.rotationWeight = updates.rotationWeight;
    }
  }

  /**
   * Get all categories with stats
   */
  getCategories(): FeatureCategory[] {
    return Array.from(this.categories.values())
      .sort((a, b) => b.priority - a.priority);
  }

  /**
   * Get all features
   */
  getAllFeatures(): DiscoveredFeature[] {
    return Array.from(this.discoveredFeatures.values());
  }

  /**
   * Get all positioning statements
   */
  getAllPositioning(): PositioningStatement[] {
    return Array.from(this.positioningStatements.values());
  }

  /**
   * Get all messaging templates
   */
  getAllTemplates(): MessagingTemplate[] {
    return this.messagingTemplates;
  }

  /**
   * Update template performance score
   */
  updateTemplatePerformance(templateId: string, score: number): void {
    const template = this.messagingTemplates.find(t => t.id === templateId);
    if (template) {
      template.performanceScore = score;
    }
  }

  /**
   * Auto-generate hook for new feature
   */
  autoGenerateHook(featureName: string, category: PipelineCategory): string {
    const categoryMeta = CATEGORY_METADATA[category];
    const templates = [
      `${featureName} made simple`,
      `Unlock the power of ${featureName.toLowerCase()}`,
      `${categoryMeta.marketingAngle} with ${featureName}`,
      `Transform your workflow with ${featureName}`,
      `${featureName}: Your new superpower`,
    ];

    return templates[Math.floor(Math.random() * templates.length)];
  }
}

export const featureDiscoveryService = FeatureDiscoveryService.getInstance();
