import React from 'react';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Download, FileText, Table, Code, FileImage, Presentation, FileType } from 'lucide-react';
import { comprehensiveExportService } from '@/services/comprehensiveExportService';

interface ContentDownloaderProps {
  content: string;
  contentType: 'html' | 'table' | 'text' | 'code' | 'markdown';
  filename?: string;
  language?: string; // Support 120+ languages from comprehensive service
}

export const ContentDownloader: React.FC<ContentDownloaderProps> = ({
  content,
  contentType,
  filename = 'genie-content',
  language = 'en'
}) => {
  const downloadAsFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const convertToCSV = (htmlTable: string) => {
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlTable, 'text/html');
    const rows = doc.querySelectorAll('tr');
    const csv: string[] = [];

    rows.forEach(row => {
      const cells = row.querySelectorAll('td, th');
      const rowData = Array.from(cells).map(cell => {
        const text = cell.textContent || '';
        return text.includes(',') ? `"${text.replace(/"/g, '""')}"` : text;
      });
      csv.push(rowData.join(','));
    });

    return csv.join('\n');
  };

  const generateHTMLDocument = (content: string) => {
    // Get RTL direction from comprehensive service language support
    const isRTL = ['ar', 'he', 'fa', 'ur', 'ps', 'ks', 'sd'].some(rtl => language.startsWith(rtl));
    
    return `<!DOCTYPE html>
<html lang="${language}" dir="${isRTL ? 'rtl' : 'ltr'}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GENIE AI Generated Content</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;600&family=Noto+Sans+Arabic:wght@400;600&family=Noto+Sans+SC:wght@400;600&family=Noto+Sans+JP:wght@400;600&family=Noto+Sans+KR:wght@400;600&family=Noto+Sans+Devanagari:wght@400;600&family=Noto+Sans+Bengali:wght@400;600&family=Noto+Sans+Tamil:wght@400;600&family=Noto+Sans+Thai:wght@400;600&family=Noto+Sans+Hebrew:wght@400;600&family=Noto+Sans+Ethiopic:wght@400;600&display=swap');
        
        body {
            font-family: 'Noto Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
            direction: ${isRTL ? 'rtl' : 'ltr'};
        }
        .header {
            border-bottom: 2px solid #8b5cf6;
            padding-bottom: 15px;
            margin-bottom: 30px;
        }
        .disclaimer {
            background-color: #fef3c7;
            border: 1px solid #f59e0b;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 20px;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: ${isRTL ? 'right' : 'left'};
        }
        th {
            background-color: #f8fafc;
            font-weight: 600;
        }
        tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 14px;
        }
        code {
            background-color: #1e293b;
            color: #e2e8f0;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: 'Fira Code', monospace;
        }
        pre {
            background-color: #1e293b;
            color: #e2e8f0;
            padding: 16px;
            border-radius: 8px;
            overflow-x: auto;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🧞‍♂️ GENIE AI Generated Content</h1>
        <p>Generated on: ${new Date().toLocaleString(language)}</p>
        <p>Language: ${language.toUpperCase()}</p>
    </div>
    
    <div class="disclaimer">
        <strong>⚠️ AI-Generated Content Disclaimer:</strong> This content was generated by GENIE AI. 
        Please verify all information with appropriate healthcare providers or professional sources. 
        This information is for educational purposes only and should not replace professional consultation.
    </div>
    
    <div class="content">
        ${content}
    </div>
    
    <div class="footer">
        <p><strong>Generated by:</strong> GENIE AI Assistant</p>
        <p><strong>Content Type:</strong> ${contentType.toUpperCase()}</p>
        <p><strong>Note:</strong> Always consult with qualified Healthcare Providers (HCPs) for medical advice.</p>
    </div>
</body>
</html>`;
  };

  // Export as PPTX using comprehensive service (for structured content)
  const handlePPTXExport = async () => {
    try {
      const slides = [{
        id: `slide-${Date.now()}`,
        slideNumber: 1,
        title: filename,
        subtitle: `Generated by GENIE AI - ${new Date().toLocaleDateString()}`,
        type: 'content' as const,
        content: {
          type: 'bullets' as const,
          bullets: content.split('\n').filter(line => line.trim()),
          paragraph: content
        },
        speakerNotes: 'AI-generated content for review'
      }];

      const result = await comprehensiveExportService.exportToPPTX(slides, filename, { language });
      
      if (result.success && result.blob) {
        const url = URL.createObjectURL(result.blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${filename}.pptx`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      }
    } catch (error) {
      console.error('[ContentDownloader] PPTX export failed:', error);
    }
  };

  // Export as PDF using comprehensive service
  const handlePDFExport = async () => {
    try {
      const slides = [{
        id: `slide-${Date.now()}`,
        slideNumber: 1,
        title: filename,
        subtitle: `Generated by GENIE AI`,
        type: 'content' as const,
        content: {
          type: 'bullets' as const,
          bullets: content.split('\n').filter(line => line.trim()),
          paragraph: content
        }
      }];

      const result = await comprehensiveExportService.exportToPDF(slides, filename, { language });
      
      if (result.success && result.blob) {
        const url = URL.createObjectURL(result.blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${filename}.pdf`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      }
    } catch (error) {
      console.error('[ContentDownloader] PDF export failed:', error);
    }
  };

  const downloadOptions = [
    {
      label: 'Download as TXT',
      icon: <FileText className="h-4 w-4" />,
      action: () => {
        const parser = new DOMParser();
        const doc = parser.parseFromString(content, 'text/html');
        const textContent = doc.body?.textContent || content;
        downloadAsFile(textContent, `${filename}.txt`, 'text/plain');
      }
    },
    {
      label: 'Download as HTML',
      icon: <Code className="h-4 w-4" />,
      action: () => {
        const htmlDoc = generateHTMLDocument(content);
        downloadAsFile(htmlDoc, `${filename}.html`, 'text/html');
      }
    },
    {
      label: 'Download as PDF',
      icon: <FileType className="h-4 w-4" />,
      action: handlePDFExport
    },
    {
      label: 'Download as PPTX',
      icon: <Presentation className="h-4 w-4" />,
      action: handlePPTXExport
    }
  ];

  // Add CSV option for tables
  if (contentType === 'table' || content.includes('<table')) {
    downloadOptions.push({
      label: 'Download as CSV',
      icon: <Table className="h-4 w-4" />,
      action: () => {
        const csv = convertToCSV(content);
        downloadAsFile(csv, `${filename}.csv`, 'text/csv');
      }
    });
  }

  // Add Markdown option
  if (contentType === 'markdown' || contentType === 'text') {
    downloadOptions.push({
      label: 'Download as MD',
      icon: <FileText className="h-4 w-4" />,
      action: () => {
        downloadAsFile(content, `${filename}.md`, 'text/markdown');
      }
    });
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Download className="h-4 w-4" />
          Download
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-48">
        {downloadOptions.map((option, index) => (
          <DropdownMenuItem key={index} onClick={option.action} className="gap-2">
            {option.icon}
            {option.label}
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
};