/**
 * CONTENT DOWNLOADER - Universal Export Integration
 * Used across Ask Genie, Conversation UI, and all products
 * Supports: 120+ languages, PPTX, PDF, TXT, HTML, CSV, MD
 * Unified with useUniversalExport hook for consistency across 100+ pipelines
 */
import React, { useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuTrigger, 
  DropdownMenuSeparator, 
  DropdownMenuLabel 
} from '@/components/ui/dropdown-menu';
import { Download, FileText, Table, Presentation, FileType, Loader2, Code } from 'lucide-react';
import { useUniversalExport } from '@/hooks/useUniversalExport';
import type { GeneratedSlide } from '@/services/universalPresentationService';

interface ContentDownloaderProps {
  content: string;
  contentType: 'html' | 'table' | 'text' | 'code' | 'markdown';
  filename?: string;
  language?: string; // Support 120+ languages from comprehensive service
}

export const ContentDownloader: React.FC<ContentDownloaderProps> = ({
  content,
  contentType,
  filename = 'genie-content',
  language = 'en'
}) => {
  const { 
    isExporting, 
    exportToPPTX, 
    exportToPDF, 
    exportToText, 
    exportToMarkdown,
    exportToCSV,
    exportToHTML,
  } = useUniversalExport();

  // Convert content to slides for PPTX/PDF export
  const contentToSlides = useCallback((): GeneratedSlide[] => {
    return [{
      id: `slide-${Date.now()}`,
      slideNumber: 1,
      title: filename,
      subtitle: `Generated by GENIE AI - ${new Date().toLocaleDateString()}`,
      type: 'content' as const,
      content: {
        type: 'bullets' as const,
        bullets: content.split('\n').filter(line => line.trim()),
        paragraphs: [content],
      },
      speakerNotes: 'AI-generated content for review'
    }];
  }, [content, filename]);

  // PPTX Export using Universal Export
  const handlePPTXExport = useCallback(async () => {
    const slides = contentToSlides();
    await exportToPPTX(
      { slides, title: filename },
      { language, quality: 'high' }
    );
  }, [contentToSlides, exportToPPTX, filename, language]);

  // PDF Export using Universal Export
  const handlePDFExport = useCallback(async () => {
    const slides = contentToSlides();
    await exportToPDF(
      { slides, title: filename },
      { language, quality: 'high' }
    );
  }, [contentToSlides, exportToPDF, filename, language]);

  // TXT Export
  const handleTXTExport = useCallback(() => {
    // Parse HTML if needed
    const parser = new DOMParser();
    const doc = parser.parseFromString(content, 'text/html');
    const textContent = doc.body?.textContent || content;
    
    exportToText(
      { content: textContent, title: filename },
      { format: 'txt' }
    );
  }, [content, exportToText, filename]);

  // HTML Export
  const handleHTMLExport = useCallback(() => {
    exportToHTML(
      { content, title: filename },
      { format: 'html', language }
    );
  }, [content, exportToHTML, filename, language]);

  // CSV Export (for tables)
  const handleCSVExport = useCallback(() => {
    exportToCSV(
      { content, title: filename },
      { format: 'csv' }
    );
  }, [content, exportToCSV, filename]);

  // MD Export
  const handleMDExport = useCallback(() => {
    const slides = contentToSlides();
    exportToMarkdown(
      { slides, title: filename },
      { format: 'md' }
    );
  }, [contentToSlides, exportToMarkdown, filename]);

  // Build menu options based on content type
  const showCSV = contentType === 'table' || content.includes('<table');
  const showMarkdown = contentType === 'markdown' || contentType === 'text';

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2" disabled={isExporting}>
          {isExporting ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <Download className="h-4 w-4" />
          )}
          Download
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-52">
        <DropdownMenuLabel className="text-xs text-muted-foreground">
          Export Formats
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        
        {/* Document Formats */}
        <DropdownMenuItem onClick={handleTXTExport} className="gap-2">
          <FileText className="h-4 w-4" />
          Plain Text (.txt)
        </DropdownMenuItem>
        
        <DropdownMenuItem onClick={handleHTMLExport} className="gap-2">
          <Code className="h-4 w-4" />
          HTML Document (.html)
        </DropdownMenuItem>
        
        <DropdownMenuItem onClick={handlePDFExport} className="gap-2">
          <FileType className="h-4 w-4" />
          PDF Document (.pdf)
        </DropdownMenuItem>
        
        <DropdownMenuItem onClick={handlePPTXExport} className="gap-2">
          <Presentation className="h-4 w-4" />
          PowerPoint (.pptx)
        </DropdownMenuItem>
        
        {/* Conditional formats */}
        {showCSV && (
          <>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={handleCSVExport} className="gap-2">
              <Table className="h-4 w-4" />
              CSV Spreadsheet (.csv)
            </DropdownMenuItem>
          </>
        )}
        
        {showMarkdown && (
          <>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={handleMDExport} className="gap-2">
              <FileText className="h-4 w-4" />
              Markdown (.md)
            </DropdownMenuItem>
          </>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  );
};
