import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { AlertTriangle, Shield, Info, Brain } from 'lucide-react';

interface DisclaimerModalProps {
  isOpen: boolean;
  onAccept: (userInfo: { firstName: string; email: string }) => void;
  onDecline: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({
  isOpen,
  onAccept,
  onDecline
}) => {
  const [firstName, setFirstName] = useState('');
  const [email, setEmail] = useState('');
  const [acceptedDisclaimer, setAcceptedDisclaimer] = useState(false);
  const [acceptedCookies, setAcceptedCookies] = useState(false);
  const [acceptedAI, setAcceptedAI] = useState(false);

  const canProceed = firstName.trim() && email.trim() && acceptedDisclaimer && acceptedCookies && acceptedAI;

  const handleAccept = () => {
    if (canProceed) {
      onAccept({ firstName: firstName.trim(), email: email.trim() });
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={() => {}}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Brain className="h-6 w-6 text-primary" />
            GENIE AI Assistant - Important Information
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          {/* User Information */}
          <div className="space-y-4">
            <h3 className="text-lg font-semibold">User Information</h3>
            <p className="text-sm text-muted-foreground">
              Please provide your information to personalize your AI experience and improve our knowledge base.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="firstName">First Name *</Label>
                <Input
                  id="firstName"
                  value={firstName}
                  onChange={(e) => setFirstName(e.target.value)}
                  placeholder="Enter your first name"
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="email">Email Address *</Label>
                <Input
                  id="email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter your email"
                  required
                />
              </div>
            </div>
          </div>

          {/* AI Information Disclaimer */}
          <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <div className="flex items-start gap-3">
              <AlertTriangle className="h-5 w-5 text-yellow-600 flex-shrink-0 mt-0.5" />
              <div className="space-y-2">
                <h4 className="font-semibold text-yellow-800">AI-Generated Information</h4>
                <div className="text-sm text-yellow-700 space-y-2">
                  <p>
                    <strong>This is an AI-powered assistant.</strong> All responses are generated by artificial intelligence and should be used for informational purposes only.
                  </p>
                  <p>
                    <strong>Please verify all information:</strong> Always cross-check AI-generated content with official sources, medical professionals, or regulatory authorities.
                  </p>
                  <p>
                    <strong>Not a substitute for professional advice:</strong> This AI does not replace consultation with qualified healthcare providers, regulatory experts, or other professionals.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Medical Disclaimer */}
          <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
            <div className="flex items-start gap-3">
              <Shield className="h-5 w-5 text-red-600 flex-shrink-0 mt-0.5" />
              <div className="space-y-2">
                <h4 className="font-semibold text-red-800">Healthcare Information Disclaimer</h4>
                <div className="text-sm text-red-700 space-y-2">
                  <p>
                    <strong>For informational purposes only:</strong> Medical or healthcare-related responses are general information and not personalized medical advice.
                  </p>
                  <p>
                    <strong>Consult Healthcare Providers:</strong> Always consult with qualified Healthcare Providers (HCPs), physicians, or medical professionals for:
                  </p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Diagnosis, treatment, or medical decisions</li>
                    <li>Drug interactions or side effects</li>
                    <li>Clinical trial participation</li>
                    <li>Regulatory compliance questions</li>
                  </ul>
                  <p>
                    <strong>Emergency situations:</strong> In case of medical emergencies, contact emergency services immediately.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Data Usage */}
          <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
            <div className="flex items-start gap-3">
              <Info className="h-5 w-5 text-blue-600 flex-shrink-0 mt-0.5" />
              <div className="space-y-2">
                <h4 className="font-semibold text-blue-800">Data Usage & Privacy</h4>
                <div className="text-sm text-blue-700 space-y-2">
                  <p>
                    <strong>Conversation Data:</strong> Your conversations help improve our AI system and knowledge base through RAG (Retrieval-Augmented Generation).
                  </p>
                  <p>
                    <strong>Knowledge Enhancement:</strong> Interactions contribute to our curated knowledge repository for better future responses.
                  </p>
                  <p>
                    <strong>Privacy:</strong> We handle your data securely and in accordance with privacy regulations.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Consent Checkboxes */}
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <Checkbox
                id="disclaimer"
                checked={acceptedDisclaimer}
                onCheckedChange={(checked) => setAcceptedDisclaimer(!!checked)}
              />
              <Label htmlFor="disclaimer" className="text-sm leading-relaxed">
                I understand this is AI-generated information for educational purposes only and I will verify all information with appropriate healthcare providers and professionals.
              </Label>
            </div>

            <div className="flex items-start space-x-3">
              <Checkbox
                id="cookies"
                checked={acceptedCookies}
                onCheckedChange={(checked) => setAcceptedCookies(!!checked)}
              />
              <Label htmlFor="cookies" className="text-sm leading-relaxed">
                I accept the use of cookies and data collection to improve the AI experience and contribute to the knowledge base.
              </Label>
            </div>

            <div className="flex items-start space-x-3">
              <Checkbox
                id="ai-terms"
                checked={acceptedAI}
                onCheckedChange={(checked) => setAcceptedAI(!!checked)}
              />
              <Label htmlFor="ai-terms" className="text-sm leading-relaxed">
                I acknowledge that responses may vary between single, multi-model, or system-generated modes and I will always verify AI-generated content.
              </Label>
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-4">
            <Button variant="outline" onClick={onDecline} className="flex-1">
              Decline & Exit
            </Button>
            <Button 
              onClick={handleAccept} 
              disabled={!canProceed}
              className="flex-1"
            >
              Accept & Continue
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};