import React, { useState, useEffect } from 'react';
import { SaveAsTemplateModal } from '@/components/workflow-builder/SaveAsTemplateModal';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { 
  ArrowRight,
  Database,
  ArrowLeft,
  Play,
  Save as SaveIcon,
  Sparkles,
  X,
  Brain
} from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';

// Import existing components
import { ModeSelector, type AgentMode } from '@/components/agent-builder/ModeSelector';
import { AgentBuilderProvider, useAgentBuilder } from '@/components/agent-builder/AgentBuilderProvider';
import { IntelligentQuestionnaire } from '@/components/agent-builder/IntelligentQuestionnaire';
import { PromptBasedAgentGenerator } from '@/components/agent-builder/PromptBasedAgentGenerator';
import { FixedAdvancedReactFlow } from '@/components/workflow-builder/FixedAdvancedReactFlow';
import { StreamlinedCanvasView } from '@/components/workflow-builder/StreamlinedCanvasView';
import AppLayout from '@/components/layout/AppLayout';
import { useMasterAuth } from '@/hooks/useMasterAuth';
import { useWorkflowNodes } from '@/hooks/useWorkflowNodes';
import { SidebarProvider } from '@/components/ui/sidebar';
import { useTemplateIntegration } from '@/components/workflow-builder/TemplateIntegrationManager';
import { useAIServiceHealth } from '@/hooks/useAIServiceHealth';
import { TemplateGallery } from '@/components/unified-workflow/TemplateGallery';
import { EnhancedDeploymentManager } from '@/components/deployment/EnhancedDeploymentManager';
import { ObservabilityDashboard } from '@/components/observability/ObservabilityDashboard';
import { UnifiedAgentAssist } from '@/components/unified/UnifiedAgentAssist';

import { useAgentSession } from '@/hooks/useAgentSession';
import { supabase } from '@/integrations/supabase/client';
import { Node } from '@xyflow/react';
import { ErrorBoundary } from '@/components/ui/ErrorBoundary';

const AgentsInner = () => {
  // Core state - simplified
  const [selectedMode, setSelectedMode] = useState<AgentMode | null>(() => {
    try {
      return (localStorage.getItem('agentBuilder_selectedMode') as AgentMode) || 'unified';
    } catch {
      return 'unified';
    }
  });
  const [showModeSelector, setShowModeSelector] = useState(false);
  const [showQuestionnaire, setShowQuestionnaire] = useState(false);
  const [hasCompletedQuestionnaire, setHasCompletedQuestionnaire] = useState(false);
  const [visualWorkflowSubTab, setVisualWorkflowSubTab] = useState<'builder' | 'ai-prompt'>('ai-prompt');
  const [selectedNode, setSelectedNode] = useState<Node | null>(null);
  const [rightPanelTab, setRightPanelTab] = useState<'config' | 'libraries' | 'assistant'>('config');
  const [workflowNodes, setWorkflowNodes] = useState<any[]>([]);
  const [workflowEdges, setWorkflowEdges] = useState<any[]>([]);
  const [showUnifiedAssist, setShowUnifiedAssist] = useState(false);
  const [showTemplateGallery, setShowTemplateGallery] = useState(false);
  const [showSaveAsTemplate, setShowSaveAsTemplate] = useState(false);
  const [showDeploymentManager, setShowDeploymentManager] = useState(false);

  const location = useLocation();
  const navigate = useNavigate();
  
  // Get prefill context from navigation state (from admin dashboard or document processing)
  const locationState = location.state as { 
    prefillPrompt?: string; 
    agentContext?: any; 
    agentId?: string;
    autoGenerated?: boolean;
    generatedNodes?: any[];
    generatedEdges?: any[];
    fromDocumentProcessing?: boolean; // Track if user came from document processing
    documentType?: string; // Track which document type was being processed
    prefillContext?: {
      name: string;
      useCase: string;
      description: string;
      architecture: string;
      suggestedNodes: string[];
      mcpTargets: string[];
      includeHumanInLoop: boolean;
      multiChannelDeploy?: boolean;
      enableMCPSync?: boolean;
      subAgents?: Array<{
        id: string;
        name: string;
        useCase: string;
        triggerCondition: string;
        icon: string;
        architectureType: string;
      }>;
    };
  } | null;
  
  const fromDocumentProcessing = locationState?.fromDocumentProcessing || false;
  const [prefillPrompt, setPrefillPrompt] = useState<string>(locationState?.prefillPrompt || '');
  const agentContext = locationState?.agentContext;
  const prefillContext = locationState?.prefillContext;
  const autoGenerated = locationState?.autoGenerated;
  const [showStreamlinedView, setShowStreamlinedView] = useState(Boolean(agentContext));

  // Only redirect to admin if NO context is provided at all
  // Don't redirect if we have prefillContext, autoGenerated, prefillPrompt, agentContext, agentId, or fromDocumentProcessing
  useEffect(() => {
    const hasContext = agentContext || prefillContext || autoGenerated || locationState?.prefillPrompt || locationState?.agentId || fromDocumentProcessing;
    if (!hasContext) {
      console.log('📋 No agent context - redirecting to admin for proper agent creation flow');
      toast.info('Please create an agent from the Admin Dashboard');
      navigate('/admin', { replace: true });
    }
  }, [agentContext, prefillContext, autoGenerated, locationState, navigate, fromDocumentProcessing]);

  const { status: aiHealth, checkHealth, checking } = useAIServiceHealth();
  const isAIHealthy = aiHealth.overallHealthy;
  const aiCheckComplete = Boolean(aiHealth.lastChecked);
  const disableAssist = aiCheckComplete ? !isAIHealthy : false;
  const assistTitle = checking ? 'Checking AI services health...' : (!isAIHealthy && aiCheckComplete ? 'AI services are unavailable. Check health status.' : undefined);

  useEffect(() => {
    checkHealth();
  }, [checkHealth]);

  // Handle navigation from admin with prefill context
  useEffect(() => {
    if (locationState?.prefillPrompt) {
      console.log('📋 Received prefill from admin:', locationState.prefillPrompt);
      setPrefillPrompt(locationState.prefillPrompt);
      // Auto-navigate to generate tab with context
      setSelectedMode('visual' as AgentMode);
      setShowModeSelector(false);
      setVisualWorkflowSubTab('ai-prompt');
      toast.success('Agent context loaded - ready to generate workflow');
    }
    if (agentContext) {
      console.log('📋 Agent context:', agentContext);
    }
  }, [locationState?.prefillPrompt, agentContext]);

  // Honor deep-links like /agents?from=enrollment&module=patient&open=builder
  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const open = params.get('open');
    const from = params.get('from');
    const moduleParam = params.get('module');

    if (open === 'builder') {
      setVisualWorkflowSubTab('builder');
      setShowModeSelector(false);
      if (!selectedMode) {
        setSelectedMode('visual' as AgentMode);
      }
      
      if (from === 'enrollment' && moduleParam === 'patient') {
        toast.success('Loading Patient Enrollment Workflow...');
      } else {
        toast.success('AI Agent Builder is ready');
      }
    }

    if (from === 'enrollment') {
      if (moduleParam) {
        toast.info(`Enrollment context: ${moduleParam}`);
      } else {
        toast.info('Enrollment context detected');
      }
    }
  }, [location.search, selectedMode]);

  // Pick up any pending workflow generated outside /agents
  useEffect(() => {
    try {
      const pending = localStorage.getItem('pendingWorkflow');
      if (pending) {
        const agent = JSON.parse(pending);
        localStorage.removeItem('pendingWorkflow');
        const nodesSource: any[] = (agent?.nodes || agent?.workflow?.nodes || agent?.data?.nodes || agent?.result?.nodes || []);
        const edgesSource: any[] = (agent?.edges || agent?.workflow?.edges || agent?.data?.edges || agent?.result?.edges || []);
        if (Array.isArray(nodesSource) && nodesSource.length) {
          const rawNodes = nodesSource.map((n: any, idx: number) => ({
            id: String(n.id || `node-${idx}-${Date.now()}`),
            type: 'enhanced',
            position: n.position || { x: 100 + (idx % 3) * 280, y: 120 + Math.floor(idx / 3) * 160 },
            data: {
              ...(n.data || {}),
              label: n.data?.label || n.label || n.name || n.display_name || `Node ${idx + 1}`,
              type_key: n.data?.type_key || (typeof n.type === 'string' ? n.type : 'node'),
              configuration: { ...(n.data?.configuration || n.configuration || {}) },
              isWorkflowNode: true,
            }
          }));
          let rawEdges = Array.isArray(edgesSource) ? edgesSource : [];
          if (!rawEdges.length && rawNodes.length > 1) {
            rawEdges = rawNodes.slice(0, -1).map((n: any, i: number) => ({
              id: `e-${n.id}-${rawNodes[i + 1].id}`,
              source: n.id,
              target: rawNodes[i + 1].id,
              type: 'smoothstep',
              animated: true,
            }));
          }
          setWorkflowNodes(rawNodes);
          setWorkflowEdges(rawEdges);
          setVisualWorkflowSubTab('builder');
          toast.success(`Loaded ${rawNodes.length} nodes to canvas`);
        }
      }
    } catch (e) {
      console.warn('Pending workflow load failed:', e);
    }
  }, []);

  // Global listener for generated workflows dispatched from anywhere
  useEffect(() => {
    const handler = (e: any) => {
      try {
        const agent = e?.detail;
        if (!agent) return;
        const nodesSource: any[] = (agent?.nodes || agent?.workflow?.nodes || agent?.data?.nodes || agent?.result?.nodes || []);
        const edgesSource: any[] = (agent?.edges || agent?.workflow?.edges || agent?.data?.edges || agent?.result?.edges || []);
        if (Array.isArray(nodesSource) && nodesSource.length) {
          const rawNodes = nodesSource.map((n: any, idx: number) => ({
            id: String(n.id || `node-${idx}-${Date.now()}`),
            type: 'enhanced',
            position: n.position || { x: 100 + (idx % 3) * 280, y: 120 + Math.floor(idx / 3) * 160 },
            data: {
              ...(n.data || {}),
              label: n.data?.label || n.label || n.name || n.display_name || `Node ${idx + 1}`,
              type_key: n.data?.type_key || (typeof n.type === 'string' ? n.type : 'node'),
              configuration: { ...(n.data?.configuration || n.configuration || {}) },
              isWorkflowNode: true,
            }
          }));
          let rawEdges = Array.isArray(edgesSource) ? edgesSource : [];
          if (!rawEdges.length && rawNodes.length > 1) {
            rawEdges = rawNodes.slice(0, -1).map((n: any, i: number) => ({
              id: `e-${n.id}-${rawNodes[i + 1].id}`,
              source: n.id,
              target: rawNodes[i + 1].id,
              type: 'smoothstep',
              animated: true,
            }));
          }
          setWorkflowNodes(rawNodes);
          setWorkflowEdges(rawEdges);
          setVisualWorkflowSubTab('builder');
          toast.success(`Loaded ${rawNodes.length} nodes to canvas`);
        }
      } catch (err) {
        console.warn('workflow-generated handler failed:', err);
      }
    };
    window.addEventListener('workflow-generated', handler as any);
    return () => window.removeEventListener('workflow-generated', handler as any);
  }, []);

  const { userSessions, currentSession } = useAgentBuilder();
  const { userRoles, user } = useMasterAuth();
  const { nodeTypes } = useWorkflowNodes();

  // Handle auto-generated workflow from sub-agent selection (document processing)
  useEffect(() => {
    if (autoGenerated && locationState?.generatedNodes && locationState?.generatedEdges) {
      console.log('📋 Auto-generated workflow received:', {
        nodes: locationState.generatedNodes.length,
        edges: locationState.generatedEdges.length
      });
      
      // Load the auto-generated workflow directly
      setWorkflowNodes(locationState.generatedNodes);
      setWorkflowEdges(locationState.generatedEdges);
      
      // Skip mode selector, go directly to Build tab
      setSelectedMode('visual' as AgentMode);
      setShowModeSelector(false);
      setShowQuestionnaire(false);
      setVisualWorkflowSubTab('builder'); // Go directly to canvas
      
      toast.success(`Workflow generated with ${locationState.generatedNodes.length} nodes`);
    } else if (prefillContext && prefillContext.subAgents && prefillContext.subAgents.length > 0) {
      // Fallback: Convert sub-agent context to a prompt if no auto-generation
      const subAgentNames = prefillContext.subAgents.map(a => a.name).join(', ');
      const generatedPrompt = `Build a ${prefillContext.name || 'workflow'} that includes the following sub-agents:

${prefillContext.subAgents.map(a => `- ${a.name}: ${a.triggerCondition || 'Automated trigger'}`).join('\n')}

Use case: ${prefillContext.useCase || 'General processing'}
${prefillContext.description ? `Description: ${prefillContext.description}` : ''}

Create a multi-agent workflow that coordinates these agents for optimal processing.`;
      
      console.log('📋 Received sub-agent context (fallback to prompt):', prefillContext);
      setPrefillPrompt(generatedPrompt);
      
      setSelectedMode('visual' as AgentMode);
      setShowModeSelector(false);
      setShowQuestionnaire(false);
      setVisualWorkflowSubTab('ai-prompt');
      
      toast.success(`${prefillContext.subAgents.length} sub-agent(s) loaded - ready to generate workflow`);
    } else if (prefillContext && !prefillContext.subAgents) {
      // Handle prefillContext without subAgents (just name, description, useCase)
      const generatedPrompt = `Build a ${prefillContext.name || 'workflow'} for ${prefillContext.useCase || 'general'} use case.
${prefillContext.description ? `\nDescription: ${prefillContext.description}` : ''}`;
      
      setPrefillPrompt(generatedPrompt);
      setSelectedMode('visual' as AgentMode);
      setShowModeSelector(false);
      setShowQuestionnaire(false);
      setVisualWorkflowSubTab('ai-prompt');
      
      toast.success('Agent context loaded - ready to generate workflow');
    }
  }, [autoGenerated, prefillContext, locationState?.generatedNodes, locationState?.generatedEdges]);

  // Use Template Integration to map templates to real nodes/edges and ensure connectors
  const templateManager = useTemplateIntegration({
    onWorkflowUpdate: (nodes, edges) => {
      const normalizedNodes = (nodes || []).map((n: any) => ({ ...n, type: 'enhanced' }));
      setWorkflowNodes(normalizedNodes);
      setWorkflowEdges(edges || []);
      toast.success(`Template applied: ${normalizedNodes.length} nodes`);
    },
    onTemplateLoaded: () => {
      setShowTemplateGallery(false);
      setVisualWorkflowSubTab('builder');
    }
  });

  const handleFlowSave = async (flowData: any) => {
    try {
      if (!user) {
        toast.error('Please sign in to save your canvas');
        return;
      }

      const currentSessionId = currentSession?.id;
      if (currentSessionId) {
        const { error } = await supabase
          .from('agent_sessions')
          .update({ canvas: flowData })
          .eq('id', currentSessionId)
          .eq('user_id', user.id);
        if (error) throw error;
        toast.success('Workflow saved');
      } else {
        const { error } = await supabase
          .from('agent_sessions')
          .insert({
            name: 'Genie Flow',
            user_id: user.id,
            canvas: flowData,
            status: 'draft'
          });
        if (error) throw error;
        toast.success('Workflow saved');
      }
    } catch (e: any) {
      toast.error(e?.message || 'Failed to save workflow');
    }
  };

  // Initialize questionnaire/mode only once or when not chosen
  // Skip if we have prefillContext or autoGenerated (from sub-agent selection)
  useEffect(() => {
    // Don't modify mode if we have context from sub-agent selection or auto-generated workflow
    if (prefillContext || autoGenerated) return;
    
    const completed = localStorage.getItem('agentBuilder_questionnaireCompleted') === 'true';
    setHasCompletedQuestionnaire(completed);
    
    const storedMode = localStorage.getItem('agentBuilder_selectedMode') as AgentMode | null;
    if (!selectedMode && storedMode) {
      setSelectedMode(storedMode as any);
      setShowModeSelector(false);
      return;
    }

    if (!selectedMode) {
      if (!completed && (userSessions?.length ?? 0) === 0) {
        setShowQuestionnaire(true);
        setShowModeSelector(false);
      } else {
        setShowQuestionnaire(false);
        setShowModeSelector(true);
      }
    }
  }, [userSessions, selectedMode, prefillContext, autoGenerated]);

  const handleQuestionnaireComplete = () => {
    setHasCompletedQuestionnaire(true);
    setShowQuestionnaire(false);
    setShowModeSelector(true);
    localStorage.setItem('agentBuilder_questionnaireCompleted', 'true');
    toast.success('Great! Now choose your building approach.');
  };

  const handleModeSelect = (mode: AgentMode) => {
    setSelectedMode(mode);
    try { localStorage.setItem('agentBuilder_selectedMode', mode as any); } catch {}
    setShowModeSelector(false);
    
    if (mode === 'visual') {
      setVisualWorkflowSubTab('ai-prompt');
      setShowTemplateGallery(true);
    }
    
    const modeText = mode === 'unified' ? 'AI-Assisted Builder' : 
                     mode === 'visual' ? 'Visual Canvas' : 
                     mode === 'observability' ? 'Observability' : 'Builder';
    toast.success(`Switched to ${modeText} mode`);
  };

  // Allow toolbar mode switcher to control this page
  useEffect(() => {
    const handler = (e: any) => {
      const mode = e?.detail as AgentMode;
      if (!mode) return;
      setSelectedMode(mode);
      try { localStorage.setItem('agentBuilder_selectedMode', mode as any); } catch {}
      const modeText = mode === 'unified' ? 'AI-Assisted Builder' : 
                       mode === 'visual' ? 'Visual Canvas' : 
                       mode === 'observability' ? 'Observability' : 'Builder';
      toast.success(`Switched to ${modeText} mode`);
    };
    window.addEventListener('switch-agent-mode', handler as any);
    return () => window.removeEventListener('switch-agent-mode', handler as any);
  }, []);

  const handleNodeGenerated = (node: any) => {
    if (node.nodes) {
      setWorkflowNodes(prev => [...prev, ...node.nodes]);
    } else {
      setWorkflowNodes(prev => [...prev, node]);
    }
    if (node && !node._successShown) {
      toast.success('Node generated!');
    }
  };

  const handleWorkflowUpdate = (nodes: any[], edges: any[]) => {
    setWorkflowNodes(nodes || []);
    setWorkflowEdges(edges || []);
  };

  // Clean Visual Workflow Builder Layout
  const renderFlowiseLayout = () => {
    return (
      <div className="h-screen flex flex-col bg-background">
        {/* Clean Header */}
        <div className="h-12 border-b bg-card flex items-center justify-between px-4">
          <div className="flex items-center gap-3">
            {/* Context-aware back button */}
            {fromDocumentProcessing ? (
              <Button 
                variant="ghost" 
                size="sm"
                onClick={() => navigate('/document-processing')}
                className="flex items-center gap-1 text-xs h-8 px-2"
              >
                <ArrowLeft className="h-3 w-3" />
                Back to Documents
              </Button>
            ) : (
              <Button 
                variant="ghost" 
                size="sm"
                onClick={() => setShowModeSelector(true)}
                className="flex items-center gap-1 text-xs h-8 px-2"
              >
                <ArrowLeft className="h-3 w-3" />
                Back
              </Button>
            )}
            <div className="h-4 w-px bg-border" />
            <h1 className="text-sm font-semibold">Workflow Builder</h1>
            <Badge variant={isAIHealthy ? 'secondary' : 'destructive'} className="text-xs">
              AI {isAIHealthy ? '●' : '○'}
            </Badge>
          </div>
          
          <div className="flex items-center gap-2">
            <Button 
              variant="outline" 
              size="sm" 
              className="h-8 px-3 text-xs" 
              onClick={() => setShowTemplateGallery(true)}
            >
              <Database className="w-3 h-3 mr-1.5" />
              Templates
            </Button>
            <Button 
              variant="outline" 
              size="sm" 
              className="h-8 px-3 text-xs" 
              onClick={() => setShowSaveAsTemplate(true)} 
              disabled={workflowNodes.length === 0}
            >
              <SaveIcon className="w-3 h-3 mr-1.5" />
              Save
            </Button>
            <Button 
              size="sm" 
              className="h-8 px-3 text-xs bg-primary hover:bg-primary/90" 
              onClick={() => setShowDeploymentManager(true)}
              disabled={workflowNodes.length === 0}
            >
              <Play className="w-3 h-3 mr-1.5" />
              Deploy
            </Button>
            <div className="h-4 w-px bg-border" />
            <Button 
              size="sm" 
              className="h-8 px-3 text-xs bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white" 
              onClick={() => setShowUnifiedAssist(!showUnifiedAssist)} 
              disabled={disableAssist} 
              title={assistTitle}
            >
              <Sparkles className="w-3 h-3 mr-1.5" />
              AI Assist
            </Button>
          </div>
        </div>

        {/* Simple 2-Step Navigation */}
        <div className="border-b bg-muted/30 px-4">
          <div className="flex items-center gap-1 py-1">
            <Button 
              variant={visualWorkflowSubTab === 'ai-prompt' ? 'default' : 'ghost'} 
              size="sm" 
              className="h-8 px-4 text-xs rounded-full"
              onClick={() => setVisualWorkflowSubTab('ai-prompt')}
            >
              <Sparkles className="w-3 h-3 mr-1.5" />
              1. Generate
            </Button>
            <ArrowRight className="w-3 h-3 text-muted-foreground" />
            <Button 
              variant={visualWorkflowSubTab === 'builder' ? 'default' : 'ghost'} 
              size="sm" 
              className="h-8 px-4 text-xs rounded-full"
              onClick={() => setVisualWorkflowSubTab('builder')}
            >
              <Brain className="w-3 h-3 mr-1.5" />
              2. Build
            </Button>
            {workflowNodes.length > 0 && (
              <Badge variant="secondary" className="ml-2 text-xs">
                {workflowNodes.length} nodes
              </Badge>
            )}
          </div>
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-hidden">
          {visualWorkflowSubTab === 'ai-prompt' && (
            <div className="h-full p-6 overflow-auto">
              <div className="max-w-4xl mx-auto">
                <div className="text-center mb-6">
                  <h2 className="text-xl font-semibold mb-2">Generate Your Workflow</h2>
                  <p className="text-sm text-muted-foreground">
                    Describe what you want to build and AI will create the workflow
                  </p>
                </div>
                
                <Card>
                  <CardContent className="pt-6">
                    <PromptBasedAgentGenerator 
                      prefillPrompt={prefillPrompt}
                      onGenerate={(agent) => {
                        const nodesSource: any[] = (agent?.nodes || agent?.workflow?.nodes || agent?.data?.nodes || agent?.result?.nodes || []);
                        const edgesSource: any[] = (agent?.edges || agent?.workflow?.edges || agent?.data?.edges || agent?.result?.edges || []);

                        if (!Array.isArray(nodesSource) || nodesSource.length === 0) {
                          toast.error('No nodes generated. Try a different prompt.');
                          return;
                        }

                        const rawNodes = nodesSource.map((n: any, idx: number) => ({
                          id: String(n.id || `node-${idx}-${Date.now()}`),
                          type: 'enhanced',
                          position: n.position || { x: 100 + (idx % 3) * 280, y: 120 + Math.floor(idx / 3) * 160 },
                          data: {
                            ...(n.data || {}),
                            label: n.data?.label || n.label || n.name || n.display_name || `Node ${idx + 1}`,
                            type_key: n.data?.type_key || (typeof n.type === 'string' ? n.type : 'node'),
                            configuration: { ...(n.data?.configuration || n.configuration || {}) },
                            isWorkflowNode: true,
                          }
                        }));

                        let rawEdges = Array.isArray(edgesSource) ? edgesSource : [];
                        if (!rawEdges.length && rawNodes.length > 1) {
                          rawEdges = rawNodes.slice(0, -1).map((n: any, i: number) => ({
                            id: `e-${n.id}-${rawNodes[i + 1].id}`,
                            source: n.id,
                            target: rawNodes[i + 1].id,
                            type: 'smoothstep',
                            animated: true,
                          }));
                        }
                        
                        setWorkflowNodes(rawNodes);
                        setWorkflowEdges(rawEdges);
                        setVisualWorkflowSubTab('builder');
                        toast.success(`Generated ${rawNodes.length} nodes`);
                      }}
                    />
                  </CardContent>
                </Card>

                <div className="mt-6 flex items-center justify-center gap-4">
                  <Button 
                    variant="outline" 
                    size="sm"
                    onClick={() => setShowTemplateGallery(true)}
                    className="gap-2"
                  >
                    <Database className="h-4 w-4" />
                    Start from Template
                  </Button>
                  <Button 
                    variant="outline" 
                    size="sm"
                    onClick={() => setVisualWorkflowSubTab('builder')}
                    className="gap-2"
                  >
                    <Brain className="h-4 w-4" />
                    Build from Scratch
                  </Button>
                </div>
              </div>
            </div>
          )}

          {visualWorkflowSubTab === 'builder' && (
            <div className="h-full flex overflow-hidden">
              <ErrorBoundary fallbackComponent={({ error, retry }) => (
                <div className="flex-1 flex items-center justify-center p-4">
                  <div className="text-center space-y-3">
                    <div className="text-sm font-medium">Canvas failed to load</div>
                    <div className="text-xs text-muted-foreground max-w-md">{error?.message}</div>
                    <Button size="sm" variant="outline" onClick={retry}>Retry</Button>
                  </div>
                </div>
              )}>
                <SidebarProvider className="w-full h-full min-h-0">
                  <div className="min-h-0 h-full flex w-full">
                    <FixedAdvancedReactFlow
                      key={`rf-${workflowNodes.length}-${workflowEdges.length}`}
                      initialNodes={workflowNodes}
                      initialEdges={workflowEdges}
                      workflowType="visual"
                      sessionId={currentSession?.id}
                      fitParent={true}
                      embedded={true}
                      onNodeSelect={(node) => {
                        setSelectedNode(node);
                        setRightPanelTab('config');
                      }}
                      onSave={handleFlowSave}
                      onWorkflowUpdate={handleWorkflowUpdate}
                      onNodeAdd={handleNodeGenerated}
                      onNodeConfigSave={(nodes, edges) => {
                        handleFlowSave({ nodes, edges });
                      }}
                      isAIHealthy={isAIHealthy}
                    />
                  </div>
                </SidebarProvider>
              </ErrorBoundary>
            </div>
          )}
        </div>

        {/* Template Gallery Modal */}
        <TemplateGallery
          isOpen={showTemplateGallery}
          onClose={() => setShowTemplateGallery(false)}
          onTemplateSelect={(template) => {
            templateManager.handleTemplateLoad(template);
          }}
        />

        {/* Save as Template Modal */}
        <SaveAsTemplateModal
          isOpen={showSaveAsTemplate}
          onClose={() => setShowSaveAsTemplate(false)}
          nodes={workflowNodes}
          edges={workflowEdges}
          onSave={() => {
            toast.success('Template saved!');
          }}
        />

        {/* Deployment Manager Modal */}
        {showDeploymentManager && (
          <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4">
            <div className="w-full max-w-4xl max-h-[90vh] overflow-y-auto bg-card rounded-lg border shadow-lg">
              <div className="p-4 border-b flex items-center justify-between">
                <h3 className="font-semibold">Deploy Workflow</h3>
                <Button variant="ghost" size="sm" onClick={() => setShowDeploymentManager(false)}>
                  <X className="h-4 w-4" />
                </Button>
              </div>
              <EnhancedDeploymentManager
                onDeploy={() => {
                  setShowDeploymentManager(false);
                  toast.success('Workflow deployed!');
                }}
              />
            </div>
          </div>
        )}

        {/* AI Assist Slide-over Panel */}
        {showUnifiedAssist && (
          <aside className="fixed inset-y-0 right-0 z-50 w-[min(480px,100vw)] border-l bg-card shadow-xl flex flex-col animate-slide-in-right">
            <div className="p-3 border-b flex items-center justify-between">
              <h3 className="font-semibold text-sm flex items-center gap-2">
                <Sparkles className="w-4 h-4" />
                AI Assistant
              </h3>
              <Button variant="ghost" size="sm" onClick={() => setShowUnifiedAssist(false)} className="h-7 w-7 p-0">
                <X className="w-4 h-4" />
              </Button>
            </div>
            <div className="flex-1 overflow-auto p-3">
              <UnifiedAgentAssist
                workflowNodes={workflowNodes}
                workflowEdges={workflowEdges}
                selectedNode={selectedNode}
                onAgentGenerated={(finalAgent: any) => {
                  const nodesSource: any[] = (finalAgent?.nodes || finalAgent?.workflow?.nodes || finalAgent?.data?.nodes || finalAgent?.result?.nodes || []);
                  const edgesSource: any[] = (finalAgent?.edges || finalAgent?.workflow?.edges || finalAgent?.data?.edges || finalAgent?.result?.edges || []);

                  if (!Array.isArray(nodesSource) || nodesSource.length === 0) {
                    toast.error('No nodes generated');
                    return;
                  }

                  const toEnhanced = (nodes: any[]) => (nodes || []).map((n, idx) => {
                    if (n.type === 'enhanced') return n;
                    const label = n.data?.label || n.label || n.name || 'Node';
                    return {
                      id: String(n.id || `node-${Date.now()}-${idx}`),
                      type: 'enhanced',
                      position: n.position || { x: 100 + (idx % 3) * 280, y: 120 + Math.floor(idx / 3) * 160 },
                      data: {
                        ...(n.data || {}),
                        label,
                        type_key: n.data?.type_key || 'node',
                        configuration: { ...(n.data?.configuration || {}) },
                        isWorkflowNode: true
                      }
                    } as any;
                  });

                  const enhancedNodes = toEnhanced(nodesSource);
                  let finalEdges = Array.isArray(edgesSource) ? edgesSource : [];
                  if (!finalEdges.length && enhancedNodes.length > 1) {
                    finalEdges = enhancedNodes.slice(0, -1).map((n: any, i: number) => ({
                      id: `e-${n.id}-${enhancedNodes[i + 1].id}`,
                      source: n.id,
                      target: enhancedNodes[i + 1].id,
                      type: 'smoothstep',
                      animated: true,
                    }));
                  }
                  
                  setWorkflowNodes(enhancedNodes);
                  setWorkflowEdges(finalEdges);
                  setVisualWorkflowSubTab('builder');
                  setShowUnifiedAssist(false);
                  toast.success(`Applied ${enhancedNodes.length} nodes`);
                }}
                onClose={() => setShowUnifiedAssist(false)}
              />
            </div>
          </aside>
        )}
      </div>
    );
  };

  // Show questionnaire if needed
  if (showQuestionnaire) {
    return (
      <AppLayout>
        <div className="p-6">
          <IntelligentQuestionnaire 
            onComplete={handleQuestionnaireComplete} 
          />
        </div>
      </AppLayout>
    );
  }

  // Mode selector
  if (showModeSelector) {
    return (
      <AppLayout>
        <div className="p-6">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h1 className="text-2xl font-bold">Choose Your Building Approach</h1>
              <p className="text-muted-foreground">Select how you'd like to build your agent</p>
            </div>
            <Button variant="outline" onClick={() => handleModeSelect('visual' as any)}>
              Quick Start
            </Button>
          </div>

          <ModeSelector 
            selectedMode={selectedMode}
            onModeSelect={(mode) => handleModeSelect(mode as any)}
            layout={userRoles.includes('onboardingTeam') ? 'horizontal-scroll' : 'grid'}
            userRole={userRoles[0]}
          />
        </div>
      </AppLayout>
    );
  }

  // Streamlined view when coming from Admin Dashboard
  if (showStreamlinedView && agentContext) {
    return (
      <StreamlinedCanvasView 
        agentContext={agentContext}
        prefillPrompt={prefillPrompt}
        onBack={() => {
          setShowStreamlinedView(false);
          navigate('/admin');
        }}
      />
    );
  }

  // Unified mode - just show canvas directly
  if (selectedMode === 'unified') {
    return renderFlowiseLayout();
  }

  // AI Observability mode
  if (selectedMode === 'observability') {
    return (
      <AppLayout>
        <div className="p-4">
          <div className="flex items-center justify-between mb-6">
            <h1 className="text-2xl font-bold">AI Observability Dashboard</h1>
            <Button 
              variant="outline" 
              onClick={() => setShowModeSelector(true)}
              className="flex items-center gap-2"
            >
              <ArrowLeft className="h-4 w-4" />
              Back
            </Button>
          </div>
          <ObservabilityDashboard />
        </div>
      </AppLayout>
    );
  }

  // Main render - Visual Canvas (default)
  return renderFlowiseLayout();
};

const Agents: React.FC = () => (
  <AgentBuilderProvider>
    <AgentsInner />
  </AgentBuilderProvider>
);

export default Agents;
