/**
 * useVideoTimeline — Universal Timeline State Manager
 *
 * Style-agnostic, outcome-agnostic timeline engine.
 * Works for ANY content: avatar video, 3D render, anime, cinematic, offline import,
 * screen recording, presentation slides, podcast audio, or plain text overlay.
 *
 * Core concepts:
 *   - Track: a layer (video, audio, overlay, subtitle, music)
 *   - Clip: a segment on a track (any media type, any style)
 *   - Scene: a group of clips across tracks that play together
 *   - Chapter: a group of scenes with a title and narration
 *   - Marker: a named point in time (intro, hook, CTA, outro)
 *
 * All operations are style-independent. The timeline doesn't know
 * if a clip was generated by Veo3, Wan2.6, ModelsLab, or uploaded offline.
 */

import { useState, useCallback, useMemo, useRef } from 'react';

// ─── Core Types ─────────────────────────────────────────────────────────────

export type ClipMediaType =
  | 'video'           // Any video (AI-generated, offline import, screen recording)
  | 'image'           // Static image (AI-generated, uploaded, screenshot)
  | 'audio'           // Audio (TTS, voice recording, music, SFX)
  | 'text_overlay'    // Text/title/subtitle overlay
  | 'animation'       // Lottie, CSS, motion graphics
  | '3d_scene'        // 3D render (GLB, USDZ)
  | 'transition'      // Transition effect between clips
  | 'empty';          // Placeholder / gap

export type TrackType =
  | 'primary_video'   // Main video track
  | 'b_roll'          // B-roll overlay track
  | 'avatar'          // Avatar overlay (PIP or full)
  | 'audio_voice'     // Voiceover / narration track
  | 'audio_music'     // Background music track
  | 'audio_sfx'       // Sound effects track
  | 'subtitle'        // Subtitle / caption track
  | 'overlay';        // Graphics / logo / watermark overlay

export type ClipStatus =
  | 'ready'           // Clip has media, ready to play
  | 'generating'      // AI is generating this clip
  | 'failed'          // Generation failed (can retry)
  | 'placeholder'     // Empty placeholder, needs content
  | 'importing'       // Uploading from offline source
  | 'trimming'        // Being trimmed/edited
  | 'queued';         // Queued for generation

export interface TimelineClip {
  id: string;
  trackId: string;
  mediaType: ClipMediaType;
  status: ClipStatus;

  // Timing (in milliseconds)
  startMs: number;       // Position on timeline
  durationMs: number;    // Duration of clip
  trimStartMs: number;   // Trim from beginning (0 = no trim)
  trimEndMs: number;     // Trim from end (0 = no trim)

  // Content
  label: string;
  sourceUrl?: string;      // URL to media (video URL, audio URL, image URL)
  thumbnailUrl?: string;
  sourceFile?: File;       // For offline imports

  // Generation metadata (style-agnostic — any provider, any style)
  generationParams?: {
    styleId?: string;        // Any of the 93 styles
    provider?: string;       // Any provider
    prompt?: string;         // Generation prompt
    model?: string;          // Specific model
    quality?: string;        // preview / production / cinematic
    regenerateCount?: number;
  };

  // Clip properties
  volume?: number;         // 0-100 for audio clips
  opacity?: number;        // 0-100 for video/overlay clips
  position?: { x: number; y: number; width: number; height: number }; // For PIP/overlay
  speed?: number;          // Playback speed multiplier (0.25-4x)
  transition?: {
    type: 'cut' | 'crossfade' | 'fade_black' | 'fade_white' | 'slide_left' | 'slide_right' | 'slide_up' | 'zoom_in' | 'zoom_out' | 'wipe' | 'dissolve';
    durationMs: number;
  };

  // Locked = can't be edited/moved (e.g., approved clips)
  locked: boolean;
}

export interface TimelineTrack {
  id: string;
  type: TrackType;
  label: string;
  muted: boolean;
  locked: boolean;
  visible: boolean;
  volume: number;        // 0-100 (for audio tracks)
  clips: string[];       // Ordered clip IDs
}

export interface TimelineScene {
  id: string;
  label: string;
  startMs: number;
  durationMs: number;
  chapterId?: string;
  approved: boolean;
}

export interface TimelineChapter {
  id: string;
  title: string;
  description: string;
  sceneIds: string[];    // Ordered scene IDs in this chapter
  narrationClipId?: string; // Linked narration clip
  thumbnailUrl?: string;
}

export interface TimelineMarker {
  id: string;
  label: string;
  timeMs: number;
  type: 'intro' | 'hook' | 'cta' | 'outro' | 'chapter_start' | 'custom';
  color: string;
}

export interface TimelineState {
  // Data
  tracks: TimelineTrack[];
  clips: Record<string, TimelineClip>;
  scenes: TimelineScene[];
  chapters: TimelineChapter[];
  markers: TimelineMarker[];

  // Playback
  playheadMs: number;
  isPlaying: boolean;
  playbackSpeed: number;
  loopRegion: { startMs: number; endMs: number } | null;

  // View
  zoomLevel: number;       // 1 = 1px per 100ms, 2 = 2px per 100ms, etc.
  scrollOffsetMs: number;
  selectedClipIds: string[];
  selectedTrackId: string | null;

  // Total
  totalDurationMs: number;

  // History (undo/redo)
  undoStack: TimelineAction[];
  redoStack: TimelineAction[];
}

// ─── Actions ────────────────────────────────────────────────────────────────

export type TimelineAction =
  | { type: 'ADD_CLIP'; clip: TimelineClip }
  | { type: 'REMOVE_CLIP'; clipId: string }
  | { type: 'UPDATE_CLIP'; clipId: string; updates: Partial<TimelineClip> }
  | { type: 'MOVE_CLIP'; clipId: string; newTrackId: string; newStartMs: number }
  | { type: 'TRIM_CLIP'; clipId: string; trimStartMs: number; trimEndMs: number }
  | { type: 'SPLIT_CLIP'; clipId: string; splitAtMs: number }
  | { type: 'MERGE_CLIPS'; clipIds: string[] }
  | { type: 'REPLACE_CLIP'; clipId: string; newClip: TimelineClip }
  | { type: 'ADD_TRACK'; track: TimelineTrack }
  | { type: 'REMOVE_TRACK'; trackId: string }
  | { type: 'ADD_SCENE'; scene: TimelineScene }
  | { type: 'REMOVE_SCENE'; sceneId: string }
  | { type: 'ADD_CHAPTER'; chapter: TimelineChapter }
  | { type: 'ADD_MARKER'; marker: TimelineMarker }
  | { type: 'REORDER_CLIPS'; trackId: string; clipIds: string[] }
  | { type: 'REORDER_SCENES'; sceneIds: string[] }
  | { type: 'SET_PLAYHEAD'; timeMs: number }
  | { type: 'BATCH'; actions: TimelineAction[] };

// ─── Default State Factory ──────────────────────────────────────────────────

function createDefaultState(): TimelineState {
  return {
    tracks: [
      { id: 'track-video', type: 'primary_video', label: 'Video', muted: false, locked: false, visible: true, volume: 100, clips: [] },
      { id: 'track-broll', type: 'b_roll', label: 'B-Roll', muted: false, locked: false, visible: true, volume: 100, clips: [] },
      { id: 'track-voice', type: 'audio_voice', label: 'Voiceover', muted: false, locked: false, visible: true, volume: 100, clips: [] },
      { id: 'track-music', type: 'audio_music', label: 'Music', muted: false, locked: false, visible: true, volume: 30, clips: [] },
      { id: 'track-subtitle', type: 'subtitle', label: 'Subtitles', muted: false, locked: false, visible: true, volume: 100, clips: [] },
    ],
    clips: {},
    scenes: [],
    chapters: [],
    markers: [],
    playheadMs: 0,
    isPlaying: false,
    playbackSpeed: 1,
    loopRegion: null,
    zoomLevel: 1,
    scrollOffsetMs: 0,
    selectedClipIds: [],
    selectedTrackId: null,
    totalDurationMs: 0,
    undoStack: [],
    redoStack: [],
  };
}

// ─── Hook ───────────────────────────────────────────────────────────────────

export function useVideoTimeline() {
  const [state, setState] = useState<TimelineState>(createDefaultState);
  const idCounter = useRef(0);

  const genId = useCallback((prefix: string) => {
    idCounter.current += 1;
    return `${prefix}-${Date.now()}-${idCounter.current}`;
  }, []);

  // ── Recalculate total duration ──────────────────────────────────────────

  const recalcDuration = useCallback((clips: Record<string, TimelineClip>) => {
    let max = 0;
    Object.values(clips).forEach(c => {
      const end = c.startMs + c.durationMs - c.trimStartMs - c.trimEndMs;
      if (end > max) max = end;
    });
    return max;
  }, []);

  // ── Clip Operations ─────────────────────────────────────────────────────

  const addClip = useCallback((trackId: string, clip: Omit<TimelineClip, 'id'>) => {
    const id = genId('clip');
    const newClip: TimelineClip = { ...clip, id };
    setState(prev => {
      const newClips = { ...prev.clips, [id]: newClip };
      const newTracks = prev.tracks.map(t =>
        t.id === trackId ? { ...t, clips: [...t.clips, id] } : t
      );
      return {
        ...prev,
        clips: newClips,
        tracks: newTracks,
        totalDurationMs: recalcDuration(newClips),
        undoStack: [...prev.undoStack, { type: 'ADD_CLIP', clip: newClip }],
        redoStack: [],
      };
    });
    return id;
  }, [genId, recalcDuration]);

  const removeClip = useCallback((clipId: string) => {
    setState(prev => {
      const { [clipId]: removed, ...rest } = prev.clips;
      const newTracks = prev.tracks.map(t => ({
        ...t,
        clips: t.clips.filter(id => id !== clipId),
      }));
      return {
        ...prev,
        clips: rest,
        tracks: newTracks,
        selectedClipIds: prev.selectedClipIds.filter(id => id !== clipId),
        totalDurationMs: recalcDuration(rest),
        undoStack: [...prev.undoStack, { type: 'REMOVE_CLIP', clipId }],
        redoStack: [],
      };
    });
  }, [recalcDuration]);

  const updateClip = useCallback((clipId: string, updates: Partial<TimelineClip>) => {
    setState(prev => {
      const clip = prev.clips[clipId];
      if (!clip || clip.locked) return prev;
      const updated = { ...clip, ...updates };
      const newClips = { ...prev.clips, [clipId]: updated };
      return {
        ...prev,
        clips: newClips,
        totalDurationMs: recalcDuration(newClips),
        undoStack: [...prev.undoStack, { type: 'UPDATE_CLIP', clipId, updates }],
        redoStack: [],
      };
    });
  }, [recalcDuration]);

  const moveClip = useCallback((clipId: string, newTrackId: string, newStartMs: number) => {
    setState(prev => {
      const clip = prev.clips[clipId];
      if (!clip || clip.locked) return prev;
      const newClips = { ...prev.clips, [clipId]: { ...clip, trackId: newTrackId, startMs: newStartMs } };
      // Remove from old track, add to new
      const newTracks = prev.tracks.map(t => {
        if (t.clips.includes(clipId) && t.id !== newTrackId) {
          return { ...t, clips: t.clips.filter(id => id !== clipId) };
        }
        if (t.id === newTrackId && !t.clips.includes(clipId)) {
          return { ...t, clips: [...t.clips, clipId] };
        }
        return t;
      });
      return { ...prev, clips: newClips, tracks: newTracks, totalDurationMs: recalcDuration(newClips) };
    });
  }, [recalcDuration]);

  const trimClip = useCallback((clipId: string, trimStartMs: number, trimEndMs: number) => {
    updateClip(clipId, { trimStartMs, trimEndMs });
  }, [updateClip]);

  const splitClip = useCallback((clipId: string, splitAtMs: number) => {
    setState(prev => {
      const clip = prev.clips[clipId];
      if (!clip || clip.locked) return prev;

      const relativeMs = splitAtMs - clip.startMs;
      if (relativeMs <= 0 || relativeMs >= clip.durationMs) return prev;

      const clipA: TimelineClip = {
        ...clip,
        id: genId('clip'),
        durationMs: relativeMs,
        trimEndMs: clip.trimEndMs + (clip.durationMs - relativeMs),
      };
      const clipB: TimelineClip = {
        ...clip,
        id: genId('clip'),
        startMs: clip.startMs + relativeMs,
        durationMs: clip.durationMs - relativeMs,
        trimStartMs: clip.trimStartMs + relativeMs,
      };

      const { [clipId]: _, ...restClips } = prev.clips;
      const newClips = { ...restClips, [clipA.id]: clipA, [clipB.id]: clipB };

      const newTracks = prev.tracks.map(t => {
        const idx = t.clips.indexOf(clipId);
        if (idx === -1) return t;
        const newClipIds = [...t.clips];
        newClipIds.splice(idx, 1, clipA.id, clipB.id);
        return { ...t, clips: newClipIds };
      });

      return {
        ...prev,
        clips: newClips,
        tracks: newTracks,
        selectedClipIds: [clipA.id],
        undoStack: [...prev.undoStack, { type: 'SPLIT_CLIP', clipId, splitAtMs }],
        redoStack: [],
      };
    });
  }, [genId]);

  const mergeClips = useCallback((clipIds: string[]) => {
    if (clipIds.length < 2) return;
    setState(prev => {
      const clips = clipIds.map(id => prev.clips[id]).filter(Boolean).sort((a, b) => a.startMs - b.startMs);
      if (clips.length < 2) return prev;

      const first = clips[0];
      const last = clips[clips.length - 1];
      const merged: TimelineClip = {
        ...first,
        id: genId('clip'),
        durationMs: (last.startMs + last.durationMs) - first.startMs,
        trimStartMs: first.trimStartMs,
        trimEndMs: last.trimEndMs,
        label: `${first.label} + ${clips.length - 1} more`,
      };

      const removeIds = new Set(clipIds);
      const newClips: Record<string, TimelineClip> = { [merged.id]: merged };
      Object.entries(prev.clips).forEach(([id, c]) => {
        if (!removeIds.has(id)) newClips[id] = c;
      });

      const newTracks = prev.tracks.map(t => {
        const firstIdx = t.clips.findIndex(id => removeIds.has(id));
        if (firstIdx === -1) return t;
        const remaining = t.clips.filter(id => !removeIds.has(id));
        remaining.splice(firstIdx, 0, merged.id);
        return { ...t, clips: remaining };
      });

      return {
        ...prev,
        clips: newClips,
        tracks: newTracks,
        selectedClipIds: [merged.id],
        totalDurationMs: recalcDuration(newClips),
        undoStack: [...prev.undoStack, { type: 'MERGE_CLIPS', clipIds }],
        redoStack: [],
      };
    });
  }, [genId, recalcDuration]);

  const replaceClip = useCallback((clipId: string, newClipData: Partial<TimelineClip>) => {
    setState(prev => {
      const old = prev.clips[clipId];
      if (!old) return prev;
      const replaced: TimelineClip = { ...old, ...newClipData, id: clipId };
      return { ...prev, clips: { ...prev.clips, [clipId]: replaced } };
    });
  }, []);

  const regenerateClip = useCallback((clipId: string) => {
    updateClip(clipId, {
      status: 'queued',
      generationParams: {
        ...state.clips[clipId]?.generationParams,
        regenerateCount: (state.clips[clipId]?.generationParams?.regenerateCount || 0) + 1,
      },
    });
  }, [updateClip, state.clips]);

  // ── Track Operations ────────────────────────────────────────────────────

  const addTrack = useCallback((type: TrackType, label: string) => {
    const id = genId('track');
    const track: TimelineTrack = { id, type, label, muted: false, locked: false, visible: true, volume: 100, clips: [] };
    setState(prev => ({ ...prev, tracks: [...prev.tracks, track] }));
    return id;
  }, [genId]);

  const removeTrack = useCallback((trackId: string) => {
    setState(prev => ({
      ...prev,
      tracks: prev.tracks.filter(t => t.id !== trackId),
    }));
  }, []);

  const toggleTrackMute = useCallback((trackId: string) => {
    setState(prev => ({
      ...prev,
      tracks: prev.tracks.map(t => t.id === trackId ? { ...t, muted: !t.muted } : t),
    }));
  }, []);

  const toggleTrackLock = useCallback((trackId: string) => {
    setState(prev => ({
      ...prev,
      tracks: prev.tracks.map(t => t.id === trackId ? { ...t, locked: !t.locked } : t),
    }));
  }, []);

  // ── Scene Operations ────────────────────────────────────────────────────

  const addScene = useCallback((label: string, startMs: number, durationMs: number, chapterId?: string) => {
    const id = genId('scene');
    const scene: TimelineScene = { id, label, startMs, durationMs, chapterId, approved: false };
    setState(prev => ({ ...prev, scenes: [...prev.scenes, scene] }));
    return id;
  }, [genId]);

  const removeScene = useCallback((sceneId: string) => {
    setState(prev => ({
      ...prev,
      scenes: prev.scenes.filter(s => s.id !== sceneId),
      chapters: prev.chapters.map(ch => ({
        ...ch,
        sceneIds: ch.sceneIds.filter(id => id !== sceneId),
      })),
    }));
  }, []);

  const reorderScenes = useCallback((sceneIds: string[]) => {
    setState(prev => {
      const sceneMap = new Map(prev.scenes.map(s => [s.id, s]));
      const reordered = sceneIds.map(id => sceneMap.get(id)).filter(Boolean) as TimelineScene[];
      return { ...prev, scenes: reordered };
    });
  }, []);

  const approveScene = useCallback((sceneId: string) => {
    setState(prev => ({
      ...prev,
      scenes: prev.scenes.map(s => s.id === sceneId ? { ...s, approved: true } : s),
    }));
  }, []);

  // ── Chapter Operations ──────────────────────────────────────────────────

  const addChapter = useCallback((title: string, sceneIds: string[]) => {
    const id = genId('chapter');
    const chapter: TimelineChapter = { id, title, description: '', sceneIds };
    setState(prev => ({ ...prev, chapters: [...prev.chapters, chapter] }));
    return id;
  }, [genId]);

  const removeChapter = useCallback((chapterId: string) => {
    setState(prev => ({
      ...prev,
      chapters: prev.chapters.filter(ch => ch.id !== chapterId),
    }));
  }, []);

  const updateChapter = useCallback((chapterId: string, updates: Partial<TimelineChapter>) => {
    setState(prev => ({
      ...prev,
      chapters: prev.chapters.map(ch => ch.id === chapterId ? { ...ch, ...updates } : ch),
    }));
  }, []);

  // ── Marker Operations ───────────────────────────────────────────────────

  const addMarker = useCallback((label: string, timeMs: number, type: TimelineMarker['type']) => {
    const id = genId('marker');
    const colors: Record<string, string> = {
      intro: '#3b82f6', hook: '#f59e0b', cta: '#ef4444', outro: '#8b5cf6',
      chapter_start: '#10b981', custom: '#6b7280',
    };
    const marker: TimelineMarker = { id, label, timeMs, type, color: colors[type] || '#6b7280' };
    setState(prev => ({ ...prev, markers: [...prev.markers, marker] }));
    return id;
  }, [genId]);

  // ── Playback Controls ───────────────────────────────────────────────────

  const setPlayhead = useCallback((timeMs: number) => {
    setState(prev => ({ ...prev, playheadMs: Math.max(0, Math.min(timeMs, prev.totalDurationMs)) }));
  }, []);

  const play = useCallback(() => setState(prev => ({ ...prev, isPlaying: true })), []);
  const pause = useCallback(() => setState(prev => ({ ...prev, isPlaying: false })), []);
  const stop = useCallback(() => setState(prev => ({ ...prev, isPlaying: false, playheadMs: 0 })), []);
  const setSpeed = useCallback((speed: number) => setState(prev => ({ ...prev, playbackSpeed: speed })), []);

  // ── View Controls ───────────────────────────────────────────────────────

  const setZoom = useCallback((level: number) => {
    setState(prev => ({ ...prev, zoomLevel: Math.max(0.1, Math.min(10, level)) }));
  }, []);

  const selectClips = useCallback((clipIds: string[]) => {
    setState(prev => ({ ...prev, selectedClipIds: clipIds }));
  }, []);

  // ── Selection Helpers ───────────────────────────────────────────────────

  const selectedClips = useMemo(
    () => state.selectedClipIds.map(id => state.clips[id]).filter(Boolean),
    [state.selectedClipIds, state.clips],
  );

  const getClipsForTrack = useCallback((trackId: string) => {
    const track = state.tracks.find(t => t.id === trackId);
    if (!track) return [];
    return track.clips.map(id => state.clips[id]).filter(Boolean);
  }, [state.tracks, state.clips]);

  const getClipsInRange = useCallback((startMs: number, endMs: number) => {
    return Object.values(state.clips).filter(c =>
      c.startMs < endMs && (c.startMs + c.durationMs) > startMs
    );
  }, [state.clips]);

  // ── Computed Stats ──────────────────────────────────────────────────────

  const stats = useMemo(() => ({
    totalClips: Object.keys(state.clips).length,
    totalTracks: state.tracks.length,
    totalScenes: state.scenes.length,
    totalChapters: state.chapters.length,
    totalMarkers: state.markers.length,
    totalDurationMs: state.totalDurationMs,
    totalDurationFormatted: formatMs(state.totalDurationMs),
    readyClips: Object.values(state.clips).filter(c => c.status === 'ready').length,
    generatingClips: Object.values(state.clips).filter(c => c.status === 'generating').length,
    failedClips: Object.values(state.clips).filter(c => c.status === 'failed').length,
    approvedScenes: state.scenes.filter(s => s.approved).length,
  }), [state]);

  // ── Undo/Redo ───────────────────────────────────────────────────────────

  const canUndo = state.undoStack.length > 0;
  const canRedo = state.redoStack.length > 0;

  // ── Import from offline video ───────────────────────────────────────────

  const importOfflineClip = useCallback((
    trackId: string,
    file: File,
    startMs: number,
    durationMs: number,
  ) => {
    return addClip(trackId, {
      trackId,
      mediaType: 'video',
      status: 'importing',
      startMs,
      durationMs,
      trimStartMs: 0,
      trimEndMs: 0,
      label: file.name,
      sourceFile: file,
      sourceUrl: URL.createObjectURL(file),
      locked: false,
    });
  }, [addClip]);

  // ── Reset ───────────────────────────────────────────────────────────────

  const reset = useCallback(() => setState(createDefaultState()), []);

  return {
    state,
    stats,
    selectedClips,

    // Clip ops
    addClip,
    removeClip,
    updateClip,
    moveClip,
    trimClip,
    splitClip,
    mergeClips,
    replaceClip,
    regenerateClip,
    importOfflineClip,

    // Track ops
    addTrack,
    removeTrack,
    toggleTrackMute,
    toggleTrackLock,

    // Scene ops
    addScene,
    removeScene,
    reorderScenes,
    approveScene,

    // Chapter ops
    addChapter,
    removeChapter,
    updateChapter,

    // Markers
    addMarker,

    // Playback
    setPlayhead,
    play,
    pause,
    stop,
    setSpeed,

    // View
    setZoom,
    selectClips,
    getClipsForTrack,
    getClipsInRange,

    // Undo
    canUndo,
    canRedo,

    // Reset
    reset,
  };
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatMs(ms: number): string {
  const secs = Math.floor(ms / 1000);
  const mins = Math.floor(secs / 60);
  const hrs = Math.floor(mins / 60);
  if (hrs > 0) return `${hrs}:${(mins % 60).toString().padStart(2, '0')}:${(secs % 60).toString().padStart(2, '0')}`;
  return `${mins}:${(secs % 60).toString().padStart(2, '0')}`;
}

export type VideoTimelineHook = ReturnType<typeof useVideoTimeline>;
