/**
 * Regional Creative Expansion — 33 expanded regional variants
 * Extends the 9 core regions in castCreativeStylesRegistry.ts with global coverage.
 */
import type { RegionalStyleVariant } from './castCreativeStylesRegistry';

const v = (r: RegionalStyleVariant) => r;

export const REGIONAL_EXPANSION: Record<string, RegionalStyleVariant> = {
  EUROPE_UK: v({
    regionCode: 'EUROPE_UK', regionName: 'United Kingdom',
    colorOverrides: ['#00247D', '#CF142B', '#FFFFFF', '#2E8B57'],
    lightingOverride: 'overcast_london_soft_diffused',
    environmentStyle: 'charming british high street with red phone boxes, cobblestones, and pub signs',
    wardrobe: { traditional: 'tweed jacket, flat cap, tartan scarf', modern: 'smart casual — oxford shirt, chinos, brogues', business: 'savile row suit, understated tie' },
    companionCreature: { name: 'Winston', species: 'Corgi', description: 'Dignified corgi with a tiny bowler hat, loyal and witty', culturalSignificance: 'Corgis are iconic British royal companions' },
    culturalElements: { architecture: 'georgian townhouses, thatched cottages, modern city glass towers', vegetation: 'rose gardens, rolling green hills, hedgerows, oak trees', patterns: 'tartan, houndstooth, william morris floral, pinstripe', symbolism: ['cup of tea', 'red double-decker bus', 'crown', 'big ben clock'], avoidSymbols: ['colonial imagery', 'negative brexit references'] },
    music: { genre: 'Britpop meets orchestral indie', instruments: ['acoustic guitar', 'piano', 'strings', 'drums', 'brass'], bpmRange: { min: 100, max: 130 }, moodDescription: 'witty and understated with warmth beneath the dry exterior' },
    narrative: { storytellingApproach: 'dry_wit_understatement', humorStyle: 'self-deprecating and dry wit', formalityLevel: 3, emotionalTone: 'reserved warmth, dry humor, quiet confidence' },
  }),
  EUROPE_FRANCE: v({
    regionCode: 'EUROPE_FRANCE', regionName: 'France',
    colorOverrides: ['#002395', '#FFFFFF', '#ED2939', '#C4A35A'],
    lightingOverride: 'parisian_golden_afternoon',
    environmentStyle: 'elegant parisian boulevard with café terraces, wrought-iron balconies, and plane trees',
    wardrobe: { traditional: 'breton stripe shirt, beret, tailored trousers', modern: 'effortlessly chic — well-cut blazer, silk scarf', business: 'impeccably tailored suit with subtle flair' },
    companionCreature: { name: 'Renard', species: 'Red Fox', description: 'Elegant fox with a small silk scarf, clever and charming', culturalSignificance: 'The fox features in French fables (Le Petit Prince, Roman de Renart)' },
    culturalElements: { architecture: 'haussmann buildings, mansard roofs, art nouveau metro, gothic cathedrals', vegetation: 'lavender fields, plane trees, grapevines, sunflowers', patterns: 'toile de jouy, fleur-de-lis, art deco geometric', symbolism: ['croissant and café', 'eiffel tower silhouette', 'baguette', 'wine glass'], avoidSymbols: ['surrender jokes', 'negative stereotypes'] },
    music: { genre: 'French chanson meets electronic', instruments: ['accordion', 'piano', 'violin', 'electronic beats', 'upright bass'], bpmRange: { min: 85, max: 120 }, moodDescription: 'romantic sophistication with intellectual edge' },
    narrative: { storytellingApproach: 'philosophical_elegant', humorStyle: 'witty intellectual wordplay', formalityLevel: 4, emotionalTone: 'sophisticated, passionate, intellectually curious' },
  }),
  EUROPE_GERMANY: v({
    regionCode: 'EUROPE_GERMANY', regionName: 'Germany',
    colorOverrides: ['#000000', '#DD0000', '#FFCC00', '#4A7C59'],
    lightingOverride: 'clean_northern_european_daylight',
    environmentStyle: 'orderly german town with half-timbered houses, modern engineering, and beer gardens',
    wardrobe: { traditional: 'lederhosen, dirndl (Bavaria), loden coat', modern: 'functional minimalism — quality fabrics, clean lines', business: 'precise tailoring, conservative colors' },
    culturalElements: { architecture: 'half-timbered fachwerk, bauhaus modern, gothic churches, industrial lofts', vegetation: 'black forest pines, linden trees, hops fields, apple orchards', patterns: 'bauhaus geometric, bavarian blue-white diamonds, clean industrial lines', symbolism: ['beer stein', 'cuckoo clock', 'autobahn', 'engineering precision'], avoidSymbols: ['WWII imagery', 'nazi references'] },
    music: { genre: 'Electronic-classical fusion (Kraftwerk meets Bach)', instruments: ['synthesizer', 'piano', 'cello', 'electronic beats', 'accordion'], bpmRange: { min: 110, max: 140 }, moodDescription: 'precise and powerful with unexpected warmth' },
    narrative: { storytellingApproach: 'logical_structured_thorough', humorStyle: 'dry factual humor', formalityLevel: 4, emotionalTone: 'reliable, thorough, quality-focused, efficient' },
  }),
  EUROPE_SPAIN: v({
    regionCode: 'EUROPE_SPAIN', regionName: 'Spain',
    colorOverrides: ['#AA151B', '#F1BF00', '#FF6B00', '#2E4057'],
    lightingOverride: 'warm_mediterranean_golden_hour',
    environmentStyle: 'vibrant spanish plaza with terracotta buildings, bougainvillea, and tapas bars',
    wardrobe: { traditional: 'flamenco dress, matador-inspired vest, mantilla shawl', modern: 'mediterranean casual — linen shirt, espadrilles', business: 'sharp european cut suit with pocket square' },
    companionCreature: { name: 'Toro', species: 'Small Bull', description: 'Friendly miniature bull with flower garlands, spirited but gentle', culturalSignificance: 'The bull is the enduring symbol of Spanish spirit' },
    culturalElements: { architecture: 'moorish arches, gaudi mosaics, whitewashed pueblos', vegetation: 'olive groves, orange trees, bougainvillea, cork oaks', patterns: 'azulejo tiles, moorish geometric, flamenco polka dots', symbolism: ['flamenco fan', 'guitar', 'olive branch', 'sun and siesta'], avoidSymbols: ['bullfighting cruelty', 'political tensions'] },
    music: { genre: 'Flamenco meets modern pop', instruments: ['spanish guitar', 'cajón', 'palmas (clapping)', 'castanets', 'violin'], bpmRange: { min: 90, max: 140 }, moodDescription: 'passionate and fiery with rhythmic intensity' },
    narrative: { storytellingApproach: 'passionate_dramatic', humorStyle: 'playful and warm', formalityLevel: 2, emotionalTone: 'passionate, warm, family-centered, life-affirming' },
  }),
  EUROPE_ITALY: v({
    regionCode: 'EUROPE_ITALY', regionName: 'Italy',
    colorOverrides: ['#008C45', '#FFFFFF', '#CD212A', '#D4AF37'],
    lightingOverride: 'tuscan_golden_afternoon',
    environmentStyle: 'charming italian piazza with renaissance architecture, vespa scooters, and gelato shops',
    wardrobe: { traditional: 'renaissance-inspired formal wear', modern: 'impeccable italian fashion — fitted blazer, quality leather shoes', business: 'designer suit, silk tie, artisan leather briefcase' },
    culturalElements: { architecture: 'renaissance palazzos, roman columns, venetian gothic, tuscan villas', vegetation: 'cypress trees, vineyards, lemon groves, olive trees, wisteria', patterns: 'renaissance motifs, venetian damask, florentine fleur-de-lis', symbolism: ['espresso cup', 'vespa scooter', 'colosseum arch', 'hand gestures'], avoidSymbols: ['mafia references', 'negative stereotyping'] },
    music: { genre: 'Opera meets modern Italian pop', instruments: ['mandolin', 'accordion', 'violin', 'piano', 'tenor voice'], bpmRange: { min: 85, max: 130 }, moodDescription: 'dramatic and beautiful with operatic flair, la dolce vita meets innovation' },
    narrative: { storytellingApproach: 'expressive_storytelling', humorStyle: 'theatrical and warm', formalityLevel: 3, emotionalTone: 'expressive, passionate, design-conscious' },
  }),
  EUROPE_NORDIC: v({
    regionCode: 'EUROPE_NORDIC', regionName: 'Nordics (Sweden, Norway, Denmark, Finland)',
    colorOverrides: ['#003897', '#FECC02', '#FFFFFF', '#5B8C5A'],
    lightingOverride: 'scandinavian_clean_natural_light',
    environmentStyle: 'minimalist scandinavian space with fjord views, birch forests, and hygge interiors',
    wardrobe: { traditional: 'folk costume (bunad/folkdräkt), woolen knitwear', modern: 'clean scandinavian minimalism — neutral tones', business: 'understated smart casual, no-tie culture' },
    companionCreature: { name: 'Björn', species: 'Bear Cub', description: 'Small brown bear with a knitted scarf, calm and dependable', culturalSignificance: 'The bear symbolizes strength and nature in Nordic culture' },
    culturalElements: { architecture: 'wooden stave churches, modern minimalist, glass and timber, cozy cabins', vegetation: 'birch forests, pine trees, wildflowers, moss, lingonberry', patterns: 'nordic knit patterns, dalarna horse motifs, marimekko-style bold prints', symbolism: ['northern lights', 'viking ship', 'midsummer maypole', 'candle in winter'], avoidSymbols: ['viking violence stereotypes'] },
    music: { genre: 'Nordic folk meets electronic ambient', instruments: ['nyckelharpa', 'hardanger fiddle', 'synth pads', 'piano', 'drums'], bpmRange: { min: 90, max: 125 }, moodDescription: 'serene and luminous with deep emotional undercurrents' },
    narrative: { storytellingApproach: 'understated_authentic', humorStyle: 'deadpan and understated', formalityLevel: 2, emotionalTone: 'calm, authentic, egalitarian, nature-connected' },
  }),
  EUROPE_POLAND: v({
    regionCode: 'EUROPE_POLAND', regionName: 'Poland',
    colorOverrides: ['#DC143C', '#FFFFFF', '#0047AB', '#228B22'],
    lightingOverride: 'central_european_soft_daylight',
    environmentStyle: 'historic polish old town with colorful tenements, cobblestones, and modern tech hubs',
    wardrobe: { traditional: 'folk costume with floral embroidery, krakowska cap', modern: 'smart european casual, quality streetwear', business: 'well-fitted suit, conservative and professional' },
    culturalElements: { architecture: 'gothic old towns, baroque churches, modern glass offices', vegetation: 'silver birch, wildflower meadows, apple orchards', patterns: 'łowicz folk paper cuts (wycinanki), floral embroidery', symbolism: ['white eagle', 'amber jewelry', 'pierogi', 'stork on rooftop'], avoidSymbols: ['WWII trauma imagery', 'soviet stereotypes'] },
    music: { genre: 'Chopin-inspired piano with modern electronic', instruments: ['piano', 'violin', 'accordion', 'electronic synth', 'drums'], bpmRange: { min: 100, max: 135 }, moodDescription: 'resilient and creative with romantic depth' },
    narrative: { storytellingApproach: 'resilient_creative', humorStyle: 'dry self-deprecating with sharp wit', formalityLevel: 3, emotionalTone: 'resilient, creative, determined, warmly hospitable' },
  }),
  EUROPE_TURKEY: v({
    regionCode: 'EUROPE_TURKEY', regionName: 'Turkey',
    colorOverrides: ['#E30A17', '#FFFFFF', '#1E3A5F', '#C4A35A'],
    lightingOverride: 'warm_bosphorus_sunset',
    environmentStyle: 'istanbul grand bazaar meets modern city, minarets alongside glass towers',
    wardrobe: { traditional: 'kaftan, embroidered vest, regional dress', modern: 'mediterranean smart casual with quality fabrics', business: 'sharp european-cut suit with ottoman-inspired accessories' },
    companionCreature: { name: 'Van', species: 'Van Cat', description: 'Pure white cat with one blue and one amber eye, graceful', culturalSignificance: 'The Turkish Van cat is a national treasure' },
    culturalElements: { architecture: 'ottoman mosques, grand bazaar arches, modern istanbul skyline, cappadocia caves', vegetation: 'tulip gardens, olive groves, pomegranate trees, cypress', patterns: 'iznik tile motifs, ottoman tulip designs, kilim geometric, ebru marbling', symbolism: ['turkish tea glass', 'evil eye (nazar)', 'tulip', 'crescent moon'], avoidSymbols: ['political tensions', 'armenian genocide denial'] },
    music: { genre: 'Turkish classical meets Anatolian rock', instruments: ['oud', 'bağlama/saz', 'ney', 'darbuka', 'kanun'], bpmRange: { min: 95, max: 130 }, moodDescription: 'mystical and warm, east meets west bridge energy' },
    narrative: { storytellingApproach: 'bridge_between_worlds', humorStyle: 'warm observational with hospitality', formalityLevel: 3, emotionalTone: 'hospitable, proud, bridge-between-cultures' },
  }),
  LATAM_BRAZIL: v({
    regionCode: 'LATAM_BRAZIL', regionName: 'Brazil',
    colorOverrides: ['#009C3B', '#FFDF00', '#002776', '#FF6B00'],
    lightingOverride: 'tropical_rio_carnival_glow',
    environmentStyle: 'colorful rio streetscape with copacabana mosaic, tropical fruit stands, and samba rhythms',
    wardrobe: { traditional: 'carnival costume, baiana dress with turban', modern: 'tropical casual — havaianas, bermuda shorts, colorful shirts', business: 'smart casual with tropical flair, open collar' },
    companionCreature: { name: 'Arara', species: 'Scarlet Macaw', description: 'Brilliant macaw with rainbow plumage, exuberant and social', culturalSignificance: 'The macaw symbolizes Brazil\'s tropical biodiversity' },
    culturalElements: { architecture: 'oscar niemeyer curves, colonial churches, favela colorful walls', vegetation: 'amazon rainforest, palm trees, tropical flowers, açaí palms', patterns: 'copacabana wave mosaic, carnival feather motifs, indigenous geometric', symbolism: ['football/soccer', 'carnival mask', 'christ the redeemer', 'açaí bowl'], avoidSymbols: ['favela poverty exploitation', 'deforestation imagery'] },
    music: { genre: 'Bossa nova meets Brazilian funk and samba', instruments: ['berimbau', 'pandeiro', 'cavaquinho', 'surdo drum', 'acoustic guitar'], bpmRange: { min: 95, max: 140 }, moodDescription: 'infectious joy and rhythm, samba swing meets optimism' },
    narrative: { storytellingApproach: 'joyful_communal_rhythm', humorStyle: 'playful and warm with physical comedy', formalityLevel: 1, emotionalTone: 'joyful, rhythmic, communal, passionately optimistic' },
  }),
  LATAM_COLOMBIA: v({
    regionCode: 'LATAM_COLOMBIA', regionName: 'Colombia',
    colorOverrides: ['#FCD116', '#003893', '#CE1126', '#00A86B'],
    lightingOverride: 'warm_andean_highland_light',
    environmentStyle: 'colorful cartagena streets with colonial balconies, flower carts, and salsa rhythms',
    wardrobe: { traditional: 'poncho, ruana, vueltiao hat', modern: 'colorful casual with latin flair', business: 'smart casual, regional textile accents' },
    culturalElements: { architecture: 'colonial cartagena walls, colorful pueblitos, modern medellín metrocable', vegetation: 'coffee plants, orchids, palm wax trees, tropical flowers', patterns: 'wayuu mochila weave, pre-columbian gold motifs', symbolism: ['coffee cup', 'orchid (national flower)', 'emerald', 'salsa dancers'], avoidSymbols: ['drug cartel references', 'violence stereotypes'] },
    music: { genre: 'Cumbia meets reggaeton and vallenato', instruments: ['accordion', 'guacharaca', 'caja drum', 'gaita flute', 'bass'], bpmRange: { min: 95, max: 135 }, moodDescription: 'warm and rhythmic with cumbia swing' },
    narrative: { storytellingApproach: 'warm_resilient_optimistic', humorStyle: 'warm situational with regional humor', formalityLevel: 2, emotionalTone: 'warm, resilient, creative, community-minded' },
  }),
  LATAM_ARGENTINA: v({
    regionCode: 'LATAM_ARGENTINA', regionName: 'Argentina',
    colorOverrides: ['#74ACDF', '#FFFFFF', '#F6B40E', '#2E4057'],
    lightingOverride: 'buenos_aires_tango_evening',
    environmentStyle: 'elegant buenos aires with european architecture, tango cafes, and jacaranda trees',
    wardrobe: { traditional: 'gaucho bombacha pants, boina beret, pañuelo', modern: 'european-influenced smart casual, leather jacket', business: 'well-tailored italian-inspired suit' },
    culturalElements: { architecture: 'art deco buenos aires, european boulevards, estancia ranches, la boca houses', vegetation: 'pampas grass, jacaranda trees, ombu, vineyards', patterns: 'gaucho leather tooling, fileteado porteño, art deco geometric', symbolism: ['mate gourd', 'tango dancers', 'asado grill', 'gaucho'], avoidSymbols: ['falklands/malvinas tensions', 'economic crisis mocking'] },
    music: { genre: 'Tango meets electronic and rock nacional', instruments: ['bandoneón', 'piano', 'violin', 'electric guitar', 'double bass'], bpmRange: { min: 85, max: 130 }, moodDescription: 'dramatic tango passion meets intellectual depth' },
    narrative: { storytellingApproach: 'intellectual_passionate', humorStyle: 'sharp ironic wit', formalityLevel: 3, emotionalTone: 'passionate, intellectual, proud, dramatically expressive' },
  }),
  NAM_CANADA: v({
    regionCode: 'NAM_CANADA', regionName: 'Canada',
    colorOverrides: ['#FF0000', '#FFFFFF', '#003DA5', '#2E8B57'],
    lightingOverride: 'clean_northern_natural_light',
    environmentStyle: 'multicultural canadian cityscape with mountains, lakes, and modern architecture',
    wardrobe: { traditional: 'plaid flannel, tuque, mukluks, parka', modern: 'outdoor-meets-urban — quality outerwear, casual layering', business: 'smart casual, less formal than US' },
    companionCreature: { name: 'Maple', species: 'Beaver', description: 'Friendly beaver with a maple leaf cap, industrious and kind', culturalSignificance: 'The beaver is Canada\'s national animal' },
    culturalElements: { architecture: 'log cabins, modern glass towers, victorian parliament', vegetation: 'maple trees, boreal forest, rocky mountain wildflowers', patterns: 'hudson bay stripes, first nations art, maple leaf motifs, plaid', symbolism: ['maple leaf', 'hockey stick', 'canoe', 'totem pole'], avoidSymbols: ['indigenous cultural appropriation'] },
    music: { genre: 'Indie folk meets electronic', instruments: ['acoustic guitar', 'fiddle', 'synth', 'piano', 'drums'], bpmRange: { min: 95, max: 125 }, moodDescription: 'warm and inclusive with wilderness wonder' },
    narrative: { storytellingApproach: 'inclusive_multicultural', humorStyle: 'gentle self-deprecating', formalityLevel: 2, emotionalTone: 'inclusive, kind, multicultural, quietly confident' },
  }),
  CARIBBEAN_JAMAICA: v({
    regionCode: 'CARIBBEAN_JAMAICA', regionName: 'Jamaica & Caribbean',
    colorOverrides: ['#009B3A', '#FED100', '#000000', '#FF6B00'],
    lightingOverride: 'tropical_caribbean_golden_hour',
    environmentStyle: 'vibrant jamaican beach town with colorful buildings, palm trees, and reggae vibes',
    wardrobe: { traditional: 'rastafari colors, dashiki, head wrap', modern: 'tropical casual — bright colors, sandals, relaxed fit', business: 'tropical business — short-sleeve button-up, light fabrics' },
    culturalElements: { architecture: 'colorful colonial buildings, beach shacks, tropical modern', vegetation: 'coconut palms, hibiscus, banana trees, blue mountain coffee', patterns: 'rastafari stripes, tropical prints, dancehall graphics', symbolism: ['reggae music notes', 'palm tree', 'coffee bean', 'sprint runner'], avoidSymbols: ['drug culture stereotypes'] },
    music: { genre: 'Reggae meets dancehall and soca', instruments: ['steel drums', 'bass guitar', 'organ', 'drums', 'horn section'], bpmRange: { min: 80, max: 120 }, moodDescription: 'laid-back island rhythm with infectious optimism' },
    narrative: { storytellingApproach: 'rhythmic_storytelling', humorStyle: 'playful patois wordplay', formalityLevel: 1, emotionalTone: 'joyful, rhythmic, resilient, spiritually grounded' },
  }),
  LATAM_PERU: v({
    regionCode: 'LATAM_PERU', regionName: 'Peru',
    colorOverrides: ['#D91023', '#FFFFFF', '#C4A35A', '#4A7C59'],
    lightingOverride: 'andean_highland_clear_light',
    environmentStyle: 'peruvian andean landscape with inca ruins, colorful textiles, and bustling lima streets',
    wardrobe: { traditional: 'poncho with andean patterns, chullo knit hat, pollera skirt', modern: 'casual with alpaca wool accents', business: 'smart casual with peruvian textile accessories' },
    culturalElements: { architecture: 'inca stone walls, colonial churches, modern lima, adobe villages', vegetation: 'quinoa fields, potato terraces, eucalyptus, cactus', patterns: 'inca geometric textiles, nazca lines motifs, andean cross (chakana)', symbolism: ['llama/alpaca', 'machu picchu', 'chakana cross', 'ceviche bowl'], avoidSymbols: ['inca exploitation', 'poverty stereotypes'] },
    music: { genre: 'Andean folk meets criolla fusion', instruments: ['charango', 'pan flute (zampoña)', 'cajón', 'guitar', 'quena'], bpmRange: { min: 90, max: 130 }, moodDescription: 'soaring andean melodies with earthy warmth' },
    narrative: { storytellingApproach: 'heritage_meets_innovation', humorStyle: 'gentle and food-centered', formalityLevel: 3, emotionalTone: 'proud, warm, heritage-conscious' },
  }),
  CJK_CHINA: v({
    regionCode: 'CJK_CHINA', regionName: 'China',
    colorOverrides: ['#DE2910', '#FFDE00', '#000000', '#8B0000'],
    lightingOverride: 'warm_lantern_glow_with_modern_neon',
    environmentStyle: 'shanghai skyline blending with traditional courtyard, red lanterns and glass towers',
    wardrobe: { traditional: 'qipao/cheongsam, tang suit, hanfu revival', modern: 'trendy streetwear, tech-forward casual', business: 'well-tailored dark suit, conservative' },
    companionCreature: { name: 'Long', species: 'Baby Dragon', description: 'Playful chinese dragon hatchling with golden whiskers', culturalSignificance: 'The dragon symbolizes power and good fortune in Chinese culture' },
    culturalElements: { architecture: 'hutong courtyards, pagoda towers, modern supertall skyscrapers', vegetation: 'bamboo, plum blossoms, lotus, pine, chrysanthemum', patterns: 'cloud scrolls, dragon motifs, chinese knot, silk brocade', symbolism: ['red envelope', 'dragon dance', 'tea ceremony', 'great wall'], avoidSymbols: ['number 4 prominently', 'political sensitivity'] },
    music: { genre: 'Chinese orchestral meets C-pop electronic', instruments: ['erhu', 'pipa', 'guzheng', 'dizi flute', 'electronic beats'], bpmRange: { min: 95, max: 135 }, moodDescription: 'grand and ambitious with ancient elegance' },
    narrative: { storytellingApproach: 'grand_narrative_ambitious', humorStyle: 'clever wordplay and situational', formalityLevel: 4, emotionalTone: 'ambitious, heritage-proud, innovative' },
  }),
  CJK_KOREA: v({
    regionCode: 'CJK_KOREA', regionName: 'South Korea',
    colorOverrides: ['#003478', '#CD2E3A', '#FFFFFF', '#FFB7C5'],
    lightingOverride: 'k_drama_soft_glow',
    environmentStyle: 'trendy seoul neighborhood with hanok houses among neon signs, cherry blossoms, and k-pop',
    wardrobe: { traditional: 'hanbok with jeogori and chima', modern: 'k-fashion — oversized blazer, sneakers, idol-inspired', business: 'sharp dark suit, conservative, well-groomed' },
    companionCreature: { name: 'Horangi', species: 'Tiger Cub', description: 'Adorable tiger cub with a traditional norigae charm, brave and playful', culturalSignificance: 'The tiger is Korea\'s guardian spirit' },
    culturalElements: { architecture: 'hanok houses, gyeongbokgung palace, gangnam glass towers', vegetation: 'cherry blossoms, mugunghwa, pine, ginkgo', patterns: 'dancheong painted beams, celadon patterns, taegeuk symbol', symbolism: ['kimchi jar', 'K-drama heart gesture', 'soju bottle', 'PC bang'], avoidSymbols: ['north korea conflation', 'japan-korea tensions'] },
    music: { genre: 'K-pop meets traditional gugak', instruments: ['gayageum', 'synth', 'electric guitar', 'drums', 'samulnori percussion'], bpmRange: { min: 110, max: 150 }, moodDescription: 'polished K-pop energy with dramatic emotional arcs' },
    narrative: { storytellingApproach: 'dramatic_arc_with_twist', humorStyle: 'variety show style with aegyo', formalityLevel: 4, emotionalTone: 'dynamic, trend-setting, emotionally dramatic' },
  }),
  SEA_THAILAND: v({
    regionCode: 'SEA_THAILAND', regionName: 'Thailand',
    colorOverrides: ['#A51931', '#F4F5F8', '#2D2A4A', '#FFD700'],
    lightingOverride: 'warm_temple_golden_glow',
    environmentStyle: 'bangkok street with golden temples, tuk-tuks, floating markets, and modern malls',
    wardrobe: { traditional: 'thai silk sarong, chut thai formal, sabai drape', modern: 'tropical casual with thai silk accents', business: 'conservative suit, pastel shirts' },
    companionCreature: { name: 'Chang', species: 'Baby Elephant', description: 'Small thai elephant with flower garland, gentle and joyful', culturalSignificance: 'The elephant is Thailand\'s national symbol' },
    culturalElements: { architecture: 'golden temple spires, traditional teak houses, modern bangkok towers', vegetation: 'orchids, lotus, coconut palms, frangipani, bamboo', patterns: 'kanok flame motifs, lai thai patterns, temple mural art', symbolism: ['wai greeting', 'lotus flower', 'spirit house', 'floating lantern'], avoidSymbols: ['disrespect to monarchy', 'buddha merchandise'] },
    music: { genre: 'Thai pop meets traditional piphat', instruments: ['ranat xylophone', 'khim', 'pi oboe', 'drums', 'synth'], bpmRange: { min: 90, max: 125 }, moodDescription: 'gentle and warm with temple bell serenity' },
    narrative: { storytellingApproach: 'gentle_harmonious', humorStyle: 'gentle and fun-loving (sanuk)', formalityLevel: 4, emotionalTone: 'warm, respectful, joyful, harmonious' },
  }),
  SEA_VIETNAM: v({
    regionCode: 'SEA_VIETNAM', regionName: 'Vietnam',
    colorOverrides: ['#DA251D', '#FFCD00', '#00A86B', '#8B4513'],
    lightingOverride: 'warm_lantern_festival_glow',
    environmentStyle: 'hoi an ancient town with silk lanterns, motorbike streets, and pho stalls',
    wardrobe: { traditional: 'ao dai (long tunic), non la (conical hat)', modern: 'casual with ao dai-inspired modern fashion', business: 'conservative suit or modern ao dai for women' },
    culturalElements: { architecture: 'french colonial, ancient town shophouses, pagodas, modern towers', vegetation: 'rice paddies, lotus ponds, bamboo, jackfruit trees', patterns: 'silk lantern motifs, lotus flower designs, dong ho folk prints', symbolism: ['pho bowl', 'silk lantern', 'conical hat', 'motorbike culture'], avoidSymbols: ['war imagery', 'political sensitivity'] },
    music: { genre: 'Vietnamese traditional meets V-pop', instruments: ['dan bau', 'dan tranh', 'sao flute', 'drums', 'synth'], bpmRange: { min: 85, max: 120 }, moodDescription: 'lyrical and poetic with resilient spirit' },
    narrative: { storytellingApproach: 'poetic_resilient', humorStyle: 'gentle and family-oriented', formalityLevel: 3, emotionalTone: 'resilient, poetic, family-focused' },
  }),
  SEA_PHILIPPINES: v({
    regionCode: 'SEA_PHILIPPINES', regionName: 'Philippines',
    colorOverrides: ['#0038A8', '#CE1126', '#FFFFFF', '#FCD116'],
    lightingOverride: 'tropical_island_golden_hour',
    environmentStyle: 'colorful filipino barangay with jeepneys, tropical beaches, and fiesta decorations',
    wardrobe: { traditional: 'barong tagalog, terno dress, malong wrap', modern: 'casual tropical — jeans and tee, flip flops', business: 'barong tagalog (accepted as formal businesswear)' },
    culturalElements: { architecture: 'spanish colonial churches, bahay kubo nipa hut, modern manila towers', vegetation: 'coconut palms, sampaguita jasmine, mango trees', patterns: 'jeepney art style, t\'nalak weave, banig mat patterns', symbolism: ['jeepney', 'carabao', 'sampaguita garland', 'karaoke microphone'], avoidSymbols: ['colonial exploitation'] },
    music: { genre: 'OPM meets ballad pop', instruments: ['guitar', 'ukulele', 'drums', 'keyboard', 'bamboo instruments'], bpmRange: { min: 90, max: 130 }, moodDescription: 'heartfelt and melodic with fiesta energy' },
    narrative: { storytellingApproach: 'warm_family_fiesta', humorStyle: 'self-deprecating and joyful (hugot)', formalityLevel: 2, emotionalTone: 'warm, family-centered, resilient' },
  }),
  INDIA_WEST: v({
    regionCode: 'INDIA_WEST', regionName: 'West India (Maharashtra, Gujarat, Rajasthan)',
    colorOverrides: ['#FF6B00', '#FFD700', '#DC143C', '#4A7C59'],
    lightingOverride: 'warm_desert_sunset_to_vibrant_market',
    environmentStyle: 'rajasthani desert palace meets bustling mumbai street, vibrant textiles everywhere',
    wardrobe: { traditional: 'rajasthani pagri turban, bandhani saree, ghagra choli', modern: 'bollywood-influenced casual, cotton kurta', business: 'bandhgala/nehru jacket, formal saree' },
    companionCreature: { name: 'Mor', species: 'Peacock', description: 'Magnificent peacock with iridescent feathers, proud and beautiful', culturalSignificance: 'The peacock is India\'s national bird' },
    culturalElements: { architecture: 'rajasthani havelis, marine drive art deco, stepwells, temple complexes', vegetation: 'desert scrub, neem trees, jasmine, cotton fields, mango orchards', patterns: 'bandhani tie-dye, block print, warli tribal art, meenakari enamel', symbolism: ['ganpati/ganesha', 'dandiya sticks', 'dabba lunch box', 'autorickshaw'], avoidSymbols: ['communal tension imagery'] },
    music: { genre: 'Rajasthani folk meets Bollywood pop', instruments: ['ravanhatta', 'dholak', 'harmonium', 'manjeera', 'morchang'], bpmRange: { min: 100, max: 145 }, moodDescription: 'colorful and celebratory with desert mystique' },
    narrative: { storytellingApproach: 'entrepreneurial_with_heritage', humorStyle: 'warm business humor with food references', formalityLevel: 3, emotionalTone: 'entrepreneurial, colorful, community-driven' },
  }),
  INDIA_EAST: v({
    regionCode: 'INDIA_EAST', regionName: 'East India (Bengal, Odisha, Northeast)',
    colorOverrides: ['#FFFFFF', '#DC143C', '#FFD700', '#006400'],
    lightingOverride: 'soft_bengali_monsoon_light',
    environmentStyle: 'kolkata literary café meets tea gardens, durga puja pandals, and riverside ghats',
    wardrobe: { traditional: 'dhoti-kurta with shawl, tant/jamdani saree, mekhela chador', modern: 'intellectual casual — cotton kurta, kolhapuri sandals', business: 'formal dhoti-kurta or western suit' },
    companionCreature: { name: 'Bagha', species: 'Royal Bengal Tiger Cub', description: 'Small bengal tiger with wise eyes', culturalSignificance: 'The Royal Bengal Tiger represents eastern India\'s fierce beauty' },
    culturalElements: { architecture: 'colonial kolkata, terracotta temples, durga puja pandals', vegetation: 'tea gardens, rice paddies, sundari trees, bamboo groves', patterns: 'kantha embroidery, baluchari silk weave, patachitra scroll art', symbolism: ['durga idol', 'rosogolla', 'adda conversation', 'boat on river'], avoidSymbols: ['partition trauma', 'flood disaster imagery'] },
    music: { genre: 'Rabindra Sangeet meets baul folk', instruments: ['ektara', 'dotara', 'tabla', 'flute', 'harmonium'], bpmRange: { min: 80, max: 120 }, moodDescription: 'intellectual and poetic with deep emotional undercurrent' },
    narrative: { storytellingApproach: 'literary_intellectual', humorStyle: 'cerebral and satirical', formalityLevel: 3, emotionalTone: 'intellectual, artistic, passionately cultured' },
  }),
  SOUTH_ASIA_BANGLADESH: v({
    regionCode: 'SOUTH_ASIA_BANGLADESH', regionName: 'Bangladesh',
    colorOverrides: ['#006A4E', '#F42A41', '#FFD700', '#FFFFFF'],
    lightingOverride: 'monsoon_green_diffused_light',
    environmentStyle: 'dhaka garment district meets riverine landscape with green rice paddies',
    wardrobe: { traditional: 'jamdani saree, lungi, panjabi kurta', modern: 'casual with local fabric accents', business: 'formal panjabi or western suit' },
    culturalElements: { architecture: 'louis kahn national assembly, mughal mosques, tin-roof villages', vegetation: 'rice paddies, water lily, mango trees, jute fields, mangroves', patterns: 'jamdani muslin weave, nakshi kantha embroidery, rickshaw art', symbolism: ['water lily', 'rickshaw art', 'hilsa fish', 'cricket bat'], avoidSymbols: ['flood disaster exploitation', 'garment tragedy imagery'] },
    music: { genre: 'Baul folk meets Bengali modern', instruments: ['ektara', 'dotara', 'dhol', 'flute', 'harmonium'], bpmRange: { min: 85, max: 120 }, moodDescription: 'resilient and melodic with river-flowing grace' },
    narrative: { storytellingApproach: 'resilient_poetic', humorStyle: 'gentle and community-focused', formalityLevel: 3, emotionalTone: 'resilient, poetic, hardworking' },
  }),
  SOUTH_ASIA_PAKISTAN: v({
    regionCode: 'SOUTH_ASIA_PAKISTAN', regionName: 'Pakistan',
    colorOverrides: ['#006233', '#FFFFFF', '#C4A35A', '#1C3D5A'],
    lightingOverride: 'warm_lahori_evening_glow',
    environmentStyle: 'lahore food street with mughal architecture, truck art, and bustling bazaars',
    wardrobe: { traditional: 'shalwar kameez with waistcoat, sherwani, dupatta', modern: 'western-influenced casual with shalwar kameez elements', business: 'formal shalwar kameez or western suit' },
    culturalElements: { architecture: 'mughal forts and mosques, walled city lahore, modern islamabad', vegetation: 'jasmine (motia), roses, chinar trees, apricot orchards', patterns: 'truck art style, mughal floral, sindhi ajrak, phulkari embroidery', symbolism: ['truck art', 'crescent and star', 'cricket passion', 'biryani pot'], avoidSymbols: ['terrorism stereotypes', 'india-pakistan tensions'] },
    music: { genre: 'Qawwali meets Coke Studio fusion', instruments: ['harmonium', 'tabla', 'dholak', 'rabab', 'sitar'], bpmRange: { min: 90, max: 140 }, moodDescription: 'soulful and powerful with qawwali intensity' },
    narrative: { storytellingApproach: 'poetic_passionate', humorStyle: 'warm family humor with urdu wordplay', formalityLevel: 3, emotionalTone: 'passionate, poetic, hospitable' },
  }),
  SOUTH_ASIA_SRI_LANKA: v({
    regionCode: 'SOUTH_ASIA_SRI_LANKA', regionName: 'Sri Lanka',
    colorOverrides: ['#8B0000', '#FFB300', '#006233', '#FF6B00'],
    lightingOverride: 'tropical_island_warm_glow',
    environmentStyle: 'sri lankan tea country hills with buddhist temples and ocean views',
    wardrobe: { traditional: 'sarong (sarama), osariya saree drape', modern: 'tropical casual with local batik', business: 'national dress or western suit' },
    culturalElements: { architecture: 'buddhist dagobas, colonial galle fort, kandyan architecture', vegetation: 'tea plantations, tropical rainforest, coconut palms, cinnamon trees', patterns: 'kandyan art motifs, batik prints, moonstone carvings', symbolism: ['lion symbol', 'tea leaf', 'lotus', 'mask dance'], avoidSymbols: ['civil war imagery', 'ethnic tensions'] },
    music: { genre: 'Baila meets Sinhalese pop', instruments: ['rabana drum', 'sitar', 'guitar', 'keyboard', 'percussion'], bpmRange: { min: 95, max: 130 }, moodDescription: 'warm island rhythm with Buddhist serenity' },
    narrative: { storytellingApproach: 'gentle_island_wisdom', humorStyle: 'warm and self-aware', formalityLevel: 3, emotionalTone: 'warm, spiritual, resilient' },
  }),
  OCEANIA_AUSTRALIA: v({
    regionCode: 'OCEANIA_AUSTRALIA', regionName: 'Australia',
    colorOverrides: ['#00008B', '#FFFFFF', '#FF0000', '#FFD700'],
    lightingOverride: 'harsh_outback_sun_meets_coastal_glow',
    environmentStyle: 'australian beach meets outback red desert, modern sydney skyline with indigenous art',
    wardrobe: { traditional: 'akubra hat, moleskin trousers, R.M. Williams boots', modern: 'beach casual — boardshorts, thongs, relaxed fit', business: 'smart casual, no-tie culture, open collar' },
    companionCreature: { name: 'Joey', species: 'Baby Kangaroo', description: 'Small kangaroo joey peeking from a pouch, curious and bouncy', culturalSignificance: 'The kangaroo is Australia\'s national emblem' },
    culturalElements: { architecture: 'sydney opera house, colonial verandah houses, modern glass', vegetation: 'eucalyptus, banksia, waratah, desert spinifex', patterns: 'aboriginal dot painting, indigenous line art, surf culture graphics', symbolism: ['boomerang', 'surfboard', 'harbour bridge', 'uluru silhouette'], avoidSymbols: ['stolen generation insensitivity', 'indigenous appropriation'] },
    music: { genre: 'Indie rock meets didgeridoo ambient', instruments: ['didgeridoo', 'acoustic guitar', 'drums', 'synth', 'clap sticks'], bpmRange: { min: 100, max: 130 }, moodDescription: 'laid-back confidence with ancient land energy' },
    narrative: { storytellingApproach: 'direct_no_nonsense', humorStyle: 'dry laconic humor, self-deprecating', formalityLevel: 1, emotionalTone: 'relaxed, direct, egalitarian, adventurous' },
  }),
  AFRICA_SOUTH: v({
    regionCode: 'AFRICA_SOUTH', regionName: 'South Africa',
    colorOverrides: ['#007A4D', '#FFB612', '#DE3831', '#002395'],
    lightingOverride: 'warm_cape_town_sunset',
    environmentStyle: 'cape town table mountain vista, township entrepreneurship, and modern african city',
    wardrobe: { traditional: 'madiba shirt, shweshwe dress, zulu beadwork, xhosa blanket', modern: 'trendy afro-urban fashion, local designer labels', business: 'smart casual with african fabric accents' },
    companionCreature: { name: 'Simba', species: 'Lion Cub', description: 'Young lion cub with a playful mane, courageous and proud', culturalSignificance: 'The lion represents courage, part of the Big Five' },
    culturalElements: { architecture: 'cape dutch gables, township vibrancy, modern johannesburg, ndebele painted houses', vegetation: 'protea (national flower), fynbos, jacaranda trees, vineyard rows', patterns: 'ndebele geometric, shweshwe prints, zulu beadwork, madiba motifs', symbolism: ['rainbow nation', 'protea flower', 'braai (BBQ)', 'rugby/cricket'], avoidSymbols: ['apartheid exploitation', 'crime stereotypes'] },
    music: { genre: 'Amapiano meets gqom and jazz', instruments: ['log drum', 'synth bass', 'piano', 'shaker', 'vocal chants'], bpmRange: { min: 110, max: 125 }, moodDescription: 'infectious amapiano groove with rainbow nation pride' },
    narrative: { storytellingApproach: 'ubuntu_communal', humorStyle: 'diverse multilingual humor', formalityLevel: 2, emotionalTone: 'diverse, resilient, ubuntu-spirited' },
  }),
  AFRICA_NORTH: v({
    regionCode: 'AFRICA_NORTH', regionName: 'North Africa (Morocco, Egypt, Tunisia)',
    colorOverrides: ['#C1272D', '#006233', '#FFD700', '#1E90FF'],
    lightingOverride: 'warm_medina_lantern_glow',
    environmentStyle: 'moroccan medina with zellige tiles, market spice stalls, and desert dunes beyond',
    wardrobe: { traditional: 'djellaba, kaftan, fez hat, takchita gown', modern: 'mediterranean casual with north african accents', business: 'french-influenced formal with local touches' },
    culturalElements: { architecture: 'riad courtyards, moorish arches, pyramids, blue city chefchaouen', vegetation: 'date palms, argan trees, orange groves, desert roses', patterns: 'zellige mosaic tiles, berber carpet geometric, calligraphic art', symbolism: ['hand of fatima (hamsa)', 'mint tea glass', 'tagine pot', 'desert caravan'], avoidSymbols: ['orientalist stereotypes', 'political instability'] },
    music: { genre: 'Gnawa meets rai and chaabi', instruments: ['oud', 'sintir', 'darbuka', 'bendir drum', 'ney flute'], bpmRange: { min: 90, max: 125 }, moodDescription: 'mystical and warm with desert depth' },
    narrative: { storytellingApproach: 'storytelling_through_hospitality', humorStyle: 'warm and story-based', formalityLevel: 3, emotionalTone: 'hospitable, proud, culturally rich' },
  }),
  AFRICA_CENTRAL: v({
    regionCode: 'AFRICA_CENTRAL', regionName: 'Central Africa (Congo, Cameroon)',
    colorOverrides: ['#007A4D', '#FFD700', '#CE1126', '#0033A0'],
    lightingOverride: 'lush_tropical_forest_filtered_light',
    environmentStyle: 'vibrant central african market with tropical forest backdrop, kinshasa energy, and sapeur style',
    wardrobe: { traditional: 'pagne wrapper, sapeur haute couture', modern: 'la sape — impeccable european suits with african flair', business: 'sapeur-influenced formal — immaculate suits' },
    culturalElements: { architecture: 'colonial-era buildings, tropical market stalls, modern kinshasa towers', vegetation: 'congo rainforest, tropical hardwoods, palm oil trees, banana groves', patterns: 'kuba cloth raffia weave, mangbetu geometric, pagne prints', symbolism: ['sapeur style', 'congo river', 'forest canopy', 'ndombolo dance'], avoidSymbols: ['conflict minerals imagery', 'war zone stereotypes'] },
    music: { genre: 'Congolese rumba meets ndombolo', instruments: ['likembe', 'drums', 'electric guitar', 'bass', 'brass section'], bpmRange: { min: 100, max: 135 }, moodDescription: 'irresistible congolese rumba rhythm with elegant swagger' },
    narrative: { storytellingApproach: 'communal_with_elegance', humorStyle: 'playful and dance-oriented', formalityLevel: 2, emotionalTone: 'elegant, rhythmic, communal, stylish' },
  }),
  AFRICA_HORN: v({
    regionCode: 'AFRICA_HORN', regionName: 'Horn of Africa (Ethiopia, Somalia)',
    colorOverrides: ['#009A44', '#FCDD09', '#DA121A', '#0F47AF'],
    lightingOverride: 'highland_morning_clear_light',
    environmentStyle: 'ethiopian highland with rock-hewn churches, coffee ceremony, and addis ababa modernity',
    wardrobe: { traditional: 'habesha kemis, shamma/netela shawl, gabi wrap', modern: 'casual with traditional embroidery accents', business: 'formal habesha kemis or western suit' },
    culturalElements: { architecture: 'rock-hewn lalibela churches, tukul round houses, modern addis, harar walled city', vegetation: 'coffee plants (birthplace), teff fields, eucalyptus, enset', patterns: 'ethiopian cross motifs, habesha embroidery (tilf), basket weave', symbolism: ['coffee ceremony', 'lion of judah', 'injera plate', 'ethiopian cross'], avoidSymbols: ['famine imagery', 'conflict stereotypes'] },
    music: { genre: 'Ethio-jazz meets traditional azmari', instruments: ['masinko', 'krar', 'kebero drum', 'washint flute', 'brass'], bpmRange: { min: 85, max: 120 }, moodDescription: 'soulful ethio-jazz groove with ancient highland depth' },
    narrative: { storytellingApproach: 'ancient_wisdom_modern_vision', humorStyle: 'gentle and proverb-based', formalityLevel: 3, emotionalTone: 'proud, ancient, coffee-culture warmth' },
  }),
  AFRICA_SOUTHERN: v({
    regionCode: 'AFRICA_SOUTHERN', regionName: 'Southern Africa (Zimbabwe, Mozambique, Zambia)',
    colorOverrides: ['#006400', '#FFD700', '#FF0000', '#000000'],
    lightingOverride: 'warm_savanna_afternoon',
    environmentStyle: 'victoria falls mist meets harare innovation hub and maputo coastal markets',
    wardrobe: { traditional: 'chitenge wrap, shona traditional, capulana', modern: 'casual african print with modern cuts', business: 'smart casual with african textile accents' },
    culturalElements: { architecture: 'great zimbabwe ruins, colonial buildings, thatched rondavels', vegetation: 'baobab trees, miombo woodland, mopane, flame trees', patterns: 'shona stone sculpture motifs, chitenge prints, tonga basket weave', symbolism: ['victoria falls', 'zimbabwe bird', 'copper (zambia)', 'dhow sailing'], avoidSymbols: ['political crisis stereotypes', 'hyperinflation jokes'] },
    music: { genre: 'Chimurenga meets marrabenta and kalindula', instruments: ['mbira', 'hosho shakers', 'guitar', 'drums', 'marimba'], bpmRange: { min: 95, max: 125 }, moodDescription: 'grounding mbira tones with rhythmic energy' },
    narrative: { storytellingApproach: 'heritage_resilience', humorStyle: 'warm communal humor', formalityLevel: 2, emotionalTone: 'resilient, heritage-proud, communal' },
  }),
  MENA_LEVANT: v({
    regionCode: 'MENA_LEVANT', regionName: 'Levant (Lebanon, Jordan)',
    colorOverrides: ['#C8102E', '#FFFFFF', '#006233', '#C4A35A'],
    lightingOverride: 'warm_mediterranean_levantine_glow',
    environmentStyle: 'beirut café culture meets amman ancient ruins, cedar mountains and modern startups',
    wardrobe: { traditional: 'lebanese kaftan, jordanian hatta, embroidered thobe', modern: 'french-influenced chic mediterranean fashion', business: 'european-style formal with levantine elegance' },
    culturalElements: { architecture: 'roman ruins, crusader castles, ottoman houses, beirut art deco', vegetation: 'cedar trees, olive groves, grape vines, jasmine', patterns: 'phoenician motifs, levantine embroidery, petra carvings', symbolism: ['cedar tree', 'olive branch', 'mezze spread', 'café culture'], avoidSymbols: ['conflict imagery', 'sectarian references'] },
    music: { genre: 'Arabic pop meets traditional dabke', instruments: ['oud', 'buzuq', 'tablah', 'ney', 'keyboard'], bpmRange: { min: 100, max: 140 }, moodDescription: 'sophisticated and warm with dabke energy' },
    narrative: { storytellingApproach: 'cosmopolitan_cultural', humorStyle: 'sharp and sophisticated', formalityLevel: 3, emotionalTone: 'sophisticated, resilient, cosmopolitan' },
  }),
  MENA_IRAN: v({
    regionCode: 'MENA_IRAN', regionName: 'Iran (Persia)',
    colorOverrides: ['#239F40', '#FFFFFF', '#DA0000', '#1E3F66'],
    lightingOverride: 'persian_garden_golden_light',
    environmentStyle: 'persian garden with intricate tilework, bazaar alleys, and isfahan bridges at sunset',
    wardrobe: { traditional: 'chador, aba cloak, regional tribal dress', modern: 'modest fashion-forward with persian design elements', business: 'formal suit (men), modest professional with design flair (women)' },
    culturalElements: { architecture: 'persian tile mosques, bazaar vaulted ceilings, persepolis columns, windcatchers', vegetation: 'persian roses, pomegranate trees, saffron fields, pistachio groves', patterns: 'persian miniature art, islamic tilework, paisley (boteh), carpet medallion', symbolism: ['nowruz haft-sin table', 'persian carpet', 'saffron threads', 'nightingale and rose'], avoidSymbols: ['political regime imagery', 'sanctions references'] },
    music: { genre: 'Persian classical meets modern pop', instruments: ['tar', 'setar', 'santur', 'tombak', 'ney'], bpmRange: { min: 80, max: 120 }, moodDescription: 'poetic and refined with deep emotional resonance' },
    narrative: { storytellingApproach: 'poetic_philosophical', humorStyle: 'subtle intellectual with literary references', formalityLevel: 4, emotionalTone: 'poetic, intellectually rich, hospitable' },
  }),

  // ─── Europe (additional) ────────────────────────────────────────────────
  EU_NL: v({
    regionCode: 'EU_NL', regionName: 'Netherlands',
    colorOverrides: ['#AE1C28', '#FFFFFF', '#21468B', '#FF8C00'],
    lightingOverride: 'soft_dutch_overcast_with_golden_canal_light',
    environmentStyle: 'dutch canal houses with bicycles, tulip fields, and modern design studios',
    wardrobe: { traditional: 'klompen clogs, delft blue accents', modern: 'minimalist cycling casual — clean lines, practical', business: 'smart casual, no-tie, direct and functional' },
    culturalElements: { architecture: 'canal houses, windmills, de stijl modern, glass-walled offices', vegetation: 'tulip fields, polders, water lilies, dune grass', patterns: 'delft blue pottery, mondrian geometric, dutch golden age', symbolism: ['bicycle', 'tulip', 'windmill', 'orange crown'], avoidSymbols: ['drug tourism stereotypes', 'colonial exploitation'] },
    music: { genre: 'Dutch electronic (EDM) meets classical', instruments: ['synth', 'DJ decks', 'piano', 'cello', 'organ'], bpmRange: { min: 120, max: 150 }, moodDescription: 'clean electronic precision with golden age warmth' },
    narrative: { storytellingApproach: 'direct_practical', humorStyle: 'blunt and matter-of-fact', formalityLevel: 2, emotionalTone: 'direct, pragmatic, tolerant, innovative' },
  }),
  EU_CH: v({
    regionCode: 'EU_CH', regionName: 'Switzerland',
    colorOverrides: ['#FF0000', '#FFFFFF', '#1E3A5F', '#4A7C59'],
    lightingOverride: 'crisp_alpine_morning_light',
    environmentStyle: 'swiss alpine village with chalets, precision watches, and modern banking towers',
    wardrobe: { traditional: 'trachten folk costume, alphorn player', modern: 'luxury understated — quality fabrics, swiss watches', business: 'impeccable conservative suit, precision accessories' },
    culturalElements: { architecture: 'wooden chalets, medieval old towns, modern glass banking, mountain hotels', vegetation: 'edelweiss, alpine meadows, swiss pines, vineyard terraces', patterns: 'swiss cross, watch mechanism motifs, alpine folk embroidery', symbolism: ['swiss watch', 'chocolate bar', 'matterhorn', 'swiss army knife'], avoidSymbols: ['banking secrecy negativity', 'nazi gold references'] },
    music: { genre: 'Alpine folk meets precision electronic', instruments: ['alphorn', 'accordion', 'zither', 'cowbell', 'synth'], bpmRange: { min: 90, max: 125 }, moodDescription: 'precision craftsmanship meets mountain serenity' },
    narrative: { storytellingApproach: 'precise_multilingual', humorStyle: 'subtle and understated', formalityLevel: 4, emotionalTone: 'precise, multilingual, quality-obsessed, neutral' },
  }),
  EU_AT: v({
    regionCode: 'EU_AT', regionName: 'Austria',
    colorOverrides: ['#ED2939', '#FFFFFF', '#C4A35A', '#2E4057'],
    lightingOverride: 'vienna_golden_concert_hall_glow',
    environmentStyle: 'vienna coffee house with baroque architecture, alpine valleys, and sound of music landscapes',
    wardrobe: { traditional: 'dirndl, lederhosen, loden jacket', modern: 'elegant european casual', business: 'conservative well-tailored suit, cultural refinement' },
    culturalElements: { architecture: 'baroque palaces, gothic cathedrals, alpine chalets, jugendstil buildings', vegetation: 'alpine meadows, edelweiss, vineyards, linden trees', patterns: 'baroque scrollwork, alpine folk motifs, secession art', symbolism: ['coffee and sachertorte', 'violin/orchestra', 'alpine peak', 'waltz dancers'], avoidSymbols: ['nazi annexation references'] },
    music: { genre: 'Viennese waltz meets modern classical', instruments: ['violin', 'piano', 'cello', 'clarinet', 'accordion'], bpmRange: { min: 85, max: 130 }, moodDescription: 'elegant waltz grace with alpine freshness' },
    narrative: { storytellingApproach: 'cultured_elegant', humorStyle: 'witty viennese coffee-house style', formalityLevel: 4, emotionalTone: 'cultured, musical, elegantly witty' },
  }),
  EU_BE: v({
    regionCode: 'EU_BE', regionName: 'Belgium',
    colorOverrides: ['#000000', '#FFD700', '#ED2939', '#8B4513'],
    lightingOverride: 'soft_flemish_masterpiece_light',
    environmentStyle: 'bruges medieval squares with chocolate shops, art nouveau brussels, and beer breweries',
    wardrobe: { traditional: 'flemish folk costume', modern: 'understated european chic, comic culture t-shirts', business: 'conservative EU-institution style' },
    culturalElements: { architecture: 'gothic belfries, art nouveau, medieval guild houses, EU quarter modern', vegetation: 'hop fields, beech forests, canal-side willows', patterns: 'flemish tapestry, art nouveau curves, tintin/comic art style', symbolism: ['belgian chocolate', 'beer glass', 'manneken pis', 'tintin'], avoidSymbols: ['flemish-walloon tensions', 'colonial congo exploitation'] },
    music: { genre: 'Belgian electronic (Tomorrowland) meets chanson', instruments: ['synth', 'DJ controller', 'accordion', 'guitar', 'saxophone'], bpmRange: { min: 120, max: 145 }, moodDescription: 'tomorrowland festival energy meets flemish coziness' },
    narrative: { storytellingApproach: 'surrealist_creative', humorStyle: 'absurdist and self-deprecating', formalityLevel: 3, emotionalTone: 'creative, surrealist, multilingual, cozy' },
  }),
  EU_CZ: v({
    regionCode: 'EU_CZ', regionName: 'Czech Republic',
    colorOverrides: ['#11457E', '#D7141A', '#FFFFFF', '#C4A35A'],
    lightingOverride: 'prague_golden_spire_afternoon',
    environmentStyle: 'prague old town with gothic spires, beer halls, and art nouveau cafés',
    wardrobe: { traditional: 'moravian folk costume with embroidery', modern: 'pragmatic central european casual', business: 'conservative suit, understated' },
    culturalElements: { architecture: 'gothic prague castle, baroque churches, art nouveau, cubist houses', vegetation: 'bohemian forests, hops fields, linden trees', patterns: 'bohemian crystal motifs, moravian embroidery, cubist geometric', symbolism: ['prague castle', 'beer mug', 'crystal glass', 'astronomical clock'], avoidSymbols: ['soviet occupation imagery'] },
    music: { genre: 'Czech classical meets indie rock', instruments: ['piano', 'violin', 'guitar', 'drums', 'cimbalom'], bpmRange: { min: 95, max: 130 }, moodDescription: 'dvořák\'s romanticism meets prague underground energy' },
    narrative: { storytellingApproach: 'literary_ironic', humorStyle: 'kafka-esque absurdist, dry', formalityLevel: 3, emotionalTone: 'literary, ironic, pragmatic, beer-culture warmth' },
  }),
  EU_RO: v({
    regionCode: 'EU_RO', regionName: 'Romania',
    colorOverrides: ['#002B7F', '#FCD116', '#CE1126', '#006400'],
    lightingOverride: 'carpathian_mountain_morning',
    environmentStyle: 'transylvanian village with painted monasteries, carpathian forests, and bucharest art deco',
    wardrobe: { traditional: 'ie blouse with embroidery, opinci sandals', modern: 'smart european casual with folk accents', business: 'conservative suit' },
    culturalElements: { architecture: 'painted monasteries, fortified churches, art deco bucharest, wooden village houses', vegetation: 'carpathian forests, sunflower fields, wild orchards', patterns: 'romanian cross-stitch, painted egg motifs, maramureș wood carving', symbolism: ['painted easter egg', 'carpathian bear', 'dracula castle (with humor)', 'hora dance circle'], avoidSymbols: ['ceausescu regime', 'negative roma stereotypes'] },
    music: { genre: 'Romanian folk meets electronic (manele fusion)', instruments: ['pan flute (nai)', 'cimbalom', 'violin', 'accordion', 'synth'], bpmRange: { min: 100, max: 140 }, moodDescription: 'passionate folk melodies with electronic undercurrent' },
    narrative: { storytellingApproach: 'folk_tale_mystical', humorStyle: 'warm and self-deprecating', formalityLevel: 3, emotionalTone: 'warm, mystical, resilient, creatively resourceful' },
  }),
  EU_HU: v({
    regionCode: 'EU_HU', regionName: 'Hungary',
    colorOverrides: ['#CE2939', '#FFFFFF', '#477050', '#C4A35A'],
    lightingOverride: 'budapest_danube_golden_hour',
    environmentStyle: 'budapest thermal baths, danube riverfront, ruin bars, and paprika-scented markets',
    wardrobe: { traditional: 'magyar folk costume with embroidered vest', modern: 'central european smart casual', business: 'conservative professional' },
    culturalElements: { architecture: 'parliament gothic, thermal bath neo-baroque, ruin bar industrial, ottoman remnants', vegetation: 'great plains (puszta), sunflower fields, vineyards, acacia', patterns: 'magyar folk embroidery, kalocsa floral, matyo colorful motifs', symbolism: ['thermal bath', 'paprika string', 'rubik\'s cube', 'hungarian horse'], avoidSymbols: ['trianon treaty sensitivity', 'soviet era trauma'] },
    music: { genre: 'Hungarian folk (csárdás) meets electronic', instruments: ['cimbalom', 'violin', 'clarinet', 'synth', 'tambura'], bpmRange: { min: 95, max: 140 }, moodDescription: 'fiery csárdás passion meets ruin bar electronic' },
    narrative: { storytellingApproach: 'passionate_intellectual', humorStyle: 'dark humor with intellectual edge', formalityLevel: 3, emotionalTone: 'passionate, intellectual, proud, inventive' },
  }),
  EU_GR: v({
    regionCode: 'EU_GR', regionName: 'Greece',
    colorOverrides: ['#0D5EAF', '#FFFFFF', '#C4A35A', '#FF6B00'],
    lightingOverride: 'aegean_bright_mediterranean_sun',
    environmentStyle: 'santorini white-blue clifftop village with ancient ruins, tavernas, and azure sea',
    wardrobe: { traditional: 'fustanella, evzone costume', modern: 'relaxed mediterranean — linen, sandals, sun-washed colors', business: 'european suit with mediterranean ease' },
    culturalElements: { architecture: 'ancient columns, byzantine churches, cycladic white-blue, neoclassical athens', vegetation: 'olive groves, bougainvillea, cypress, oregano hillsides', patterns: 'greek key (meander), ancient pottery motifs, byzantine mosaics', symbolism: ['olive branch', 'greek column', 'evil eye (mati)', 'ouzo glass'], avoidSymbols: ['economic crisis mocking', 'elgin marbles controversy'] },
    music: { genre: 'Bouzouki meets rebetiko and modern pop', instruments: ['bouzouki', 'baglamas', 'lyra', 'guitar', 'drums'], bpmRange: { min: 90, max: 130 }, moodDescription: 'mediterranean warmth with zorba energy and philosophical depth' },
    narrative: { storytellingApproach: 'philosophical_mediterranean', humorStyle: 'warm and fatalistic', formalityLevel: 2, emotionalTone: 'philosophical, warm, proud of heritage, life-celebrating' },
  }),
  EU_FI: v({
    regionCode: 'EU_FI', regionName: 'Finland',
    colorOverrides: ['#003580', '#FFFFFF', '#4A7C59', '#FFD700'],
    lightingOverride: 'finnish_midnight_sun_or_aurora',
    environmentStyle: 'finnish lakeside sauna with birch forests, modern helsinki design, and northern lights',
    wardrobe: { traditional: 'sami-influenced folk dress', modern: 'functional minimalism — marimekko-style bold prints', business: 'understated, no-nonsense professional' },
    culturalElements: { architecture: 'alvar aalto modernism, wooden lake cabins, helsinki functionalism', vegetation: 'birch and pine forests, blueberry bushes, arctic lichens, lake reeds', patterns: 'marimekko bold prints, karelian embroidery, sami geometric', symbolism: ['sauna', 'nokia/tech', 'northern lights', 'reindeer'], avoidSymbols: ['depression/darkness stereotypes'] },
    music: { genre: 'Finnish metal meets folk and electronic', instruments: ['kantele (zither)', 'electric guitar', 'synth', 'drums', 'joik vocals'], bpmRange: { min: 100, max: 145 }, moodDescription: 'sisu resilience — quiet power erupting into metal energy' },
    narrative: { storytellingApproach: 'minimal_authentic', humorStyle: 'dry finnish sisu humor', formalityLevel: 2, emotionalTone: 'reserved, authentic, sisu-driven, tech-savvy' },
  }),
  EU_IRELAND: v({
    regionCode: 'EU_IRELAND', regionName: 'Ireland',
    colorOverrides: ['#009A49', '#FFFFFF', '#FF8200', '#2E4057'],
    lightingOverride: 'irish_soft_green_misty_light',
    environmentStyle: 'irish pub village with green rolling hills, stone walls, and modern dublin tech hub',
    wardrobe: { traditional: 'aran knit sweater, tweed cap, celtic jewelry', modern: 'casual layers for changeable weather', business: 'smart casual, tech-startup culture' },
    culturalElements: { architecture: 'stone cottages, celtic crosses, georgian dublin, modern tech campuses', vegetation: 'green hills, clover, bog heather, wildflowers, hedgerows', patterns: 'celtic knot, aran cable knit, book of kells illumination', symbolism: ['shamrock', 'celtic harp', 'pint of stout', 'claddagh ring'], avoidSymbols: ['leprechaun clichés', 'the troubles violence'] },
    music: { genre: 'Celtic folk meets indie rock', instruments: ['fiddle', 'bodhrán', 'tin whistle', 'uilleann pipes', 'guitar'], bpmRange: { min: 95, max: 135 }, moodDescription: 'rousing celtic session energy with lyrical storytelling' },
    narrative: { storytellingApproach: 'storytelling_tradition', humorStyle: 'witty craic and self-deprecating', formalityLevel: 1, emotionalTone: 'warm, storytelling, witty, community-spirited' },
  }),
  EU_BALKANS: v({
    regionCode: 'EU_BALKANS', regionName: 'Balkans (Serbia, Croatia, Bosnia)',
    colorOverrides: ['#C6363C', '#FFFFFF', '#003DA5', '#FFD700'],
    lightingOverride: 'warm_adriatic_to_continental_mix',
    environmentStyle: 'balkan town with ottoman bridges, adriatic coastline, kafana cafes, and fortress cities',
    wardrobe: { traditional: 'folk vest with embroidery, šajkača cap', modern: 'mediterranean-continental casual mix', business: 'european-style professional' },
    culturalElements: { architecture: 'ottoman bridges, austrian-hungarian facades, medieval fortresses, adriatic stone towns', vegetation: 'adriatic pine, plum orchards, vineyards, wildflower meadows', patterns: 'pirot kilim weave, croatian lace, bosnian brass etching', symbolism: ['ćevapi/grilled meat', 'turkish coffee pot', 'adriatic sunset', 'tambura instrument'], avoidSymbols: ['ethnic conflict exploitation', 'war imagery'] },
    music: { genre: 'Balkan brass meets turbo-folk and sevdah', instruments: ['trumpet', 'accordion', 'guitar', 'drums', 'saz'], bpmRange: { min: 100, max: 150 }, moodDescription: 'irresistible balkan brass energy with sevdah melancholy depth' },
    narrative: { storytellingApproach: 'passionate_communal', humorStyle: 'dark humor with warm hospitality', formalityLevel: 2, emotionalTone: 'passionate, hospitable, resilient, fiercely proud' },
  }),
  EU_UKRAINE: v({
    regionCode: 'EU_UKRAINE', regionName: 'Ukraine',
    colorOverrides: ['#005BBB', '#FFD500', '#FFFFFF', '#228B22'],
    lightingOverride: 'ukrainian_golden_wheat_field_light',
    environmentStyle: 'ukrainian sunflower fields, kyiv golden domes, and vibrant vyshyvanka embroidery',
    wardrobe: { traditional: 'vyshyvanka embroidered shirt, vinok flower crown', modern: 'european casual with vyshyvanka-inspired fashion', business: 'smart professional with cultural pride accents' },
    culturalElements: { architecture: 'kyiv golden-domed churches, lviv austro-hungarian buildings, wooden village houses', vegetation: 'sunflower fields, wheat plains, cherry orchards, birch forests', patterns: 'vyshyvanka cross-stitch embroidery, petrykivka painting, pysanka egg art', symbolism: ['sunflower', 'tryzub trident', 'vyshyvanka shirt', 'wheat sheaf'], avoidSymbols: ['war exploitation', 'soviet nostalgia'] },
    music: { genre: 'Ukrainian folk meets electronic and pop', instruments: ['bandura', 'sopilka flute', 'tsymbaly', 'drums', 'synth'], bpmRange: { min: 100, max: 140 }, moodDescription: 'defiant beauty and resilient spirit, folk soul meets modern determination' },
    narrative: { storytellingApproach: 'resilient_defiant', humorStyle: 'sharp and resilient', formalityLevel: 3, emotionalTone: 'resilient, proud, creative, defiantly optimistic' },
  }),

  // ─── India per-language sub-regions ─────────────────────────────────────
  INDIA_PAN: v({
    regionCode: 'INDIA_PAN', regionName: 'Pan-India (English)',
    colorOverrides: ['#FF9933', '#FFFFFF', '#138808', '#000080'],
    lightingOverride: 'warm_diverse_indian_golden_hour',
    environmentStyle: 'modern indian metro city with diverse architecture, street food, tech parks, and ancient temples',
    wardrobe: { traditional: 'diverse — saree, kurta, sherwani depending on region', modern: 'indo-western fusion — kurta with jeans, sneakers', business: 'formal indian or western suit with subtle desi touches' },
    companionCreature: { name: 'Genie', species: 'Mythical Peacock-Phoenix Hybrid', description: 'Iridescent creature combining peacock beauty with phoenix rebirth energy', culturalSignificance: 'Represents India\'s unity in diversity — many traditions, one spirit' },
    culturalElements: { architecture: 'mix of mughal domes, dravidian gopurams, modern glass towers, colonial heritage', vegetation: 'banyan trees, neem, tulsi, diverse regional flora', patterns: 'paisley, mandala, rangoli, block print — pan-Indian fusion', symbolism: ['tricolor flag', 'namaste gesture', 'diya lamp', 'chai cup'], avoidSymbols: ['communal tension', 'caste discrimination'] },
    music: { genre: 'Bollywood-indie fusion with pan-Indian instruments', instruments: ['tabla', 'sitar', 'flute', 'electric guitar', 'synth'], bpmRange: { min: 100, max: 140 }, moodDescription: 'bollywood energy meets indie soul — aspirational and inclusive' },
    narrative: { storytellingApproach: 'inclusive_aspirational', humorStyle: 'bollywood-style situational with chai references', formalityLevel: 2, emotionalTone: 'aspirational, inclusive, proudly diverse, tech-forward' },
  }),
  INDIA_PAN_EN: v({
    regionCode: 'INDIA_PAN_EN', regionName: 'Pan-India English',
    colorOverrides: ['#FF9933', '#FFFFFF', '#138808', '#3B82F6'],
    lightingOverride: 'modern_indian_tech_hub_lighting',
    environmentStyle: 'bangalore/hyderabad tech corridor with modern offices, craft coffee, and startup culture',
    wardrobe: { traditional: 'indo-western smart casual', modern: 'tech casual — hoodie, sneakers, laptop bag', business: 'startup smart casual — blazer without tie' },
    culturalElements: { architecture: 'modern tech parks, co-working spaces, craft café interiors', vegetation: 'urban landscaping, rooftop gardens, indoor plants', patterns: 'minimal geometric, tech-inspired clean design', symbolism: ['laptop and chai', 'startup pitch', 'unicorn horn', 'co-working desk'], avoidSymbols: ['elitist imagery', 'tech-bro stereotypes'] },
    music: { genre: 'Indie pop meets lo-fi and electronic', instruments: ['acoustic guitar', 'synth', 'drums', 'piano', 'bass'], bpmRange: { min: 105, max: 135 }, moodDescription: 'indie coffee-shop vibe meets startup hustle energy' },
    narrative: { storytellingApproach: 'startup_narrative', humorStyle: 'self-aware millennial/gen-z humor', formalityLevel: 1, emotionalTone: 'ambitious, globally-minded, self-aware, entrepreneurial' },
  }),
  INDIA_NORTH_HI: v({
    regionCode: 'INDIA_NORTH_HI', regionName: 'North India — Hindi',
    colorOverrides: ['#FF6B00', '#FFD700', '#8B0000', '#228B22'],
    lightingOverride: 'warm_golden_diwali_glow',
    environmentStyle: 'hindi heartland — lucknow nawabi elegance, delhi bustle, varanasi ghats',
    wardrobe: { traditional: 'kurta pajama, nehru jacket, saree with sindoor', modern: 'jeans-kurta combo', business: 'formal kurta or western suit' },
    culturalElements: { architecture: 'mughal monuments, varanasi ghats, lucknow imambaras, delhi modern', vegetation: 'banyan, peepal, marigold, mango trees', patterns: 'chikankari embroidery, mughal jali, lucknowi zardozi', symbolism: ['ganga aarti', 'chai tapri', 'rickshaw', 'diwali diya'], avoidSymbols: ['communal violence', 'caste discrimination'] },
    music: { genre: 'Bollywood meets folk (bhojpuri, rajasthani)', instruments: ['tabla', 'harmonium', 'dholak', 'shehnai', 'flute'], bpmRange: { min: 100, max: 145 }, moodDescription: 'bollywood energy with hindi heartland warmth' },
    narrative: { storytellingApproach: 'parable_with_family_wisdom', humorStyle: 'situational with chai-shop philosophy', formalityLevel: 3, emotionalTone: 'warm, family-oriented, aspirational' },
  }),
  INDIA_NORTH_UR: v({
    regionCode: 'INDIA_NORTH_UR', regionName: 'North India — Urdu',
    colorOverrides: ['#006233', '#FFFFFF', '#C4A35A', '#8B0000'],
    lightingOverride: 'warm_lucknowi_shaam_glow',
    environmentStyle: 'lucknow-hyderabad nawabi culture with shayari, biryani, and tehzeeb elegance',
    wardrobe: { traditional: 'sherwani, achkan, salwar kameez with dupatta', modern: 'indo-islamic fusion fashion', business: 'formal sherwani or western suit' },
    culturalElements: { architecture: 'mughal arches, lucknow imambaras, hyderabad charminar, dargah shrines', vegetation: 'rose gardens, jasmine, chinar trees, gulab in courtyards', patterns: 'mughal floral, urdu calligraphy, zardozi gold embroidery', symbolism: ['shayari couplet', 'biryani handi', 'attar perfume bottle', 'ghazal singer'], avoidSymbols: ['partition violence', 'communal stereotypes'] },
    music: { genre: 'Ghazal meets qawwali and sufi rock', instruments: ['harmonium', 'tabla', 'sarangi', 'sitar', 'tanpura'], bpmRange: { min: 80, max: 120 }, moodDescription: 'ghazal elegance with sufi depth — tehzeeb (refinement) in every note' },
    narrative: { storytellingApproach: 'poetic_tehzeeb', humorStyle: 'gentle shayari-laced wordplay', formalityLevel: 4, emotionalTone: 'poetic, refined, culturally sophisticated, deeply hospitable' },
  }),
  INDIA_NORTH_PA: v({
    regionCode: 'INDIA_NORTH_PA', regionName: 'North India — Punjabi',
    colorOverrides: ['#FF6B00', '#FFD700', '#006400', '#DC143C'],
    lightingOverride: 'golden_punjab_wheat_field_sunset',
    environmentStyle: 'punjabi wheat fields, golden temple amritsar, bustling ludhiana markets, bhangra energy',
    wardrobe: { traditional: 'patiala salwar, phulkari dupatta, turban (pagg)', modern: 'bold casual — branded, gym-fit, flashy', business: 'power dressing with punjabi confidence' },
    culturalElements: { architecture: 'golden temple, haveli courtyards, modern chandigarh le corbusier', vegetation: 'wheat fields, mustard (sarson), sugarcane, mango orchards', patterns: 'phulkari embroidery, jatt motifs, agricultural patterns', symbolism: ['lassi glass', 'tractor', 'bhangra dancer', 'golden temple'], avoidSymbols: ['partition trauma', '1984 sensitivity'] },
    music: { genre: 'Bhangra meets hip-hop and pop', instruments: ['dhol', 'tumbi', 'algoza', 'chimta', 'electronic beats'], bpmRange: { min: 110, max: 150 }, moodDescription: 'pure bhangra energy — infectious, celebratory, unstoppable' },
    narrative: { storytellingApproach: 'bold_celebratory', humorStyle: 'loud, warm, self-confident with food references', formalityLevel: 1, emotionalTone: 'bold, generous, celebratory, larger-than-life' },
  }),
  INDIA_SOUTH_TA: v({
    regionCode: 'INDIA_SOUTH_TA', regionName: 'South India — Tamil',
    colorOverrides: ['#8B4513', '#FFD700', '#006400', '#FF4500'],
    lightingOverride: 'warm_tropical_temple_glow',
    environmentStyle: 'tamil nadu temple town with dravidian gopurams, filter coffee, and chennai tech corridor',
    wardrobe: { traditional: 'veshti-shirt, kanjeevaram saree with temple jewelry', modern: 'casual cotton lungi, tech casual', business: 'formal saree or western suit with subtle silk' },
    culturalElements: { architecture: 'dravidian temple gopurams, chettinad mansions, chennai art deco', vegetation: 'coconut palms, jasmine, banana, tamarind trees', patterns: 'kolam/rangoli, temple pillar carvings, kanjeevaram silk motifs', symbolism: ['filter coffee', 'kolam at doorstep', 'temple elephant', 'banana leaf meal'], avoidSymbols: ['hindi imposition references', 'caste discrimination'] },
    music: { genre: 'Carnatic classical meets tamil cinema', instruments: ['veena', 'mridangam', 'violin (carnatic)', 'nadaswaram', 'ghatam'], bpmRange: { min: 90, max: 130 }, moodDescription: 'carnatic precision with tamil cinema emotional depth' },
    narrative: { storytellingApproach: 'logical_pride_driven', humorStyle: 'self-deprecating and cerebral', formalityLevel: 3, emotionalTone: 'intellectually proud, culturally rooted, tech-savvy' },
  }),
  INDIA_SOUTH_TE: v({
    regionCode: 'INDIA_SOUTH_TE', regionName: 'South India — Telugu',
    colorOverrides: ['#FFD700', '#FF6B00', '#006400', '#8B0000'],
    lightingOverride: 'hyderabadi_pearl_glow',
    environmentStyle: 'hyderabad tech city with charminar, biryani culture, and tollywood glamour',
    wardrobe: { traditional: 'pancha (dhoti), pattu saree with pearl jewelry', modern: 'flashy tollywood-influenced fashion', business: 'formal with telugu cultural pride' },
    culturalElements: { architecture: 'charminar, golconda fort, hitech city glass towers, tirupati temple', vegetation: 'neem, tamarind, cotton fields, mango orchards', patterns: 'pochampally ikat, kalamkari, bidri metalwork', symbolism: ['biryani handi', 'charminar', 'pearl necklace', 'tollywood star'], avoidSymbols: ['telangana-andhra division sensitivity'] },
    music: { genre: 'Telugu cinema meets folk (bathukamma, kolatam)', instruments: ['dappu drum', 'sitar', 'flute', 'veena', 'synth'], bpmRange: { min: 100, max: 140 }, moodDescription: 'tollywood blockbuster energy with folk festival joy' },
    narrative: { storytellingApproach: 'grand_cinematic', humorStyle: 'larger-than-life, food-centered', formalityLevel: 3, emotionalTone: 'grand, cinematic, hospitable, proudly telugu' },
  }),
  INDIA_SOUTH_KN: v({
    regionCode: 'INDIA_SOUTH_KN', regionName: 'South India — Kannada',
    colorOverrides: ['#FFD700', '#DC143C', '#006400', '#8B4513'],
    lightingOverride: 'bangalore_garden_city_soft_light',
    environmentStyle: 'bangalore tech hub meets mysore palace grandeur, coffee plantations, and hampi ruins',
    wardrobe: { traditional: 'panche (dhoti), ilkal saree', modern: 'bangalore tech casual — startup culture', business: 'professional with south indian subtlety' },
    culturalElements: { architecture: 'mysore palace, hampi ruins, bangalore modern tech parks, hoysala temples', vegetation: 'coffee plantations, sandalwood, jacaranda (bangalore), coconut palms', patterns: 'mysore silk motifs, bidriware, hoysala sculpture patterns', symbolism: ['mysore pak sweet', 'sandalwood', 'nandi bull', 'filter coffee'], avoidSymbols: ['cauvery water dispute sensitivity'] },
    music: { genre: 'Kannada folk meets bangalore indie', instruments: ['shruti box', 'mridangam', 'flute', 'guitar', 'synth'], bpmRange: { min: 95, max: 130 }, moodDescription: 'garden city serenity meets startup energy' },
    narrative: { storytellingApproach: 'balanced_progressive', humorStyle: 'gentle and tech-aware', formalityLevel: 3, emotionalTone: 'progressive, tech-savvy, culturally grounded' },
  }),
  INDIA_SOUTH_ML: v({
    regionCode: 'INDIA_SOUTH_ML', regionName: 'South India — Malayalam',
    colorOverrides: ['#006400', '#FFD700', '#DC143C', '#8B4513'],
    lightingOverride: 'kerala_backwater_golden_hour',
    environmentStyle: 'kerala backwaters with houseboats, coconut groves, kathakali performers, and communist posters',
    wardrobe: { traditional: 'mundu-veshti, kasavu saree with gold border', modern: 'casual lungi, intellectual casual', business: 'formal with kerala gold jewelry accents' },
    culturalElements: { architecture: 'kerala traditional (nalukettu), backwater houseboats, colonial fort kochi, churches', vegetation: 'coconut palms, rubber trees, spice gardens, backwater mangroves', patterns: 'kasavu gold border, mural painting style, aranmula mirror craft', symbolism: ['onam pookkalam', 'snake boat race', 'kathakali mask', 'banana chip'], avoidSymbols: ['political party exploitation'] },
    music: { genre: 'Malayalam cinema meets chenda melam', instruments: ['chenda drum', 'edakka', 'timila', 'flute', 'guitar'], bpmRange: { min: 85, max: 125 }, moodDescription: 'kerala cinema emotional depth with chenda percussion power' },
    narrative: { storytellingApproach: 'intellectual_literary', humorStyle: 'sharp satirical with political awareness', formalityLevel: 3, emotionalTone: 'intellectual, politically aware, culturally proud, literate' },
  }),
  INDIA_WEST_MR: v({
    regionCode: 'INDIA_WEST_MR', regionName: 'West India — Marathi',
    colorOverrides: ['#FF6B00', '#FFD700', '#006400', '#8B0000'],
    lightingOverride: 'warm_sahyadri_mountain_glow',
    environmentStyle: 'maharashtra — mumbai skyline, pune tech parks, konkan coast, and shivaji forts',
    wardrobe: { traditional: 'nauvari saree (9-yard), pheta turban, dhoti', modern: 'mumbai cosmopolitan casual', business: 'formal with maharashtrian cultural pride' },
    culturalElements: { architecture: 'shivaji forts, mumbai gothic-victorian, pune wada mansions, ajanta-ellora caves', vegetation: 'sahyadri forests, alphonso mango orchards, sugarcane fields', patterns: 'paithani silk weave, warli tribal art, kolhapuri leather work', symbolism: ['ganpati bappa', 'vada pav', 'shivaji statue', 'dabba/tiffin box'], avoidSymbols: ['communal tension', 'political extremism'] },
    music: { genre: 'Marathi lavani meets powada and film music', instruments: ['dholki', 'tuntuna', 'harmonium', 'tabla', 'electric guitar'], bpmRange: { min: 100, max: 140 }, moodDescription: 'lavani dance energy with powada battle cry strength' },
    narrative: { storytellingApproach: 'proud_warrior_spirit', humorStyle: 'warm with vada-pav and dabba humor', formalityLevel: 3, emotionalTone: 'proud, entrepreneurial, community-driven, warrior-spirited' },
  }),
  INDIA_WEST_GU: v({
    regionCode: 'INDIA_WEST_GU', regionName: 'West India — Gujarati',
    colorOverrides: ['#FF6B00', '#FFD700', '#FFFFFF', '#DC143C'],
    lightingOverride: 'warm_navratri_garba_lights',
    environmentStyle: 'gujarat — ahmedabad textile markets, kutch desert crafts, navratri garba grounds, diamond hub surat',
    wardrobe: { traditional: 'chaniya choli, kediyu-dhoti, bandhani dupatta', modern: 'business-casual with gujarati flair', business: 'formal with gujarati entrepreneurial confidence' },
    culturalElements: { architecture: 'stepwells (vav), ranki vav, textile mill heritage, modern ahmedabad', vegetation: 'desert scrub, cotton fields, mango, neem', patterns: 'bandhani tie-dye, patola double ikat, kutchi mirror embroidery', symbolism: ['garba dance', 'dhokla-fafda', 'diamond', 'textile roll'], avoidSymbols: ['communal riot references'] },
    music: { genre: 'Garba meets gujarati pop', instruments: ['dhol', 'ras sticks', 'harmonium', 'manjeera', 'synth'], bpmRange: { min: 110, max: 150 }, moodDescription: 'navratri garba energy — pure celebration and business confidence' },
    narrative: { storytellingApproach: 'business_minded_warm', humorStyle: 'entrepreneur jokes and food-centered', formalityLevel: 2, emotionalTone: 'entrepreneurial, festive, family-business proud, food-loving' },
  }),
  INDIA_EAST_BN: v({
    regionCode: 'INDIA_EAST_BN', regionName: 'East India — Bengali',
    colorOverrides: ['#FFFFFF', '#DC143C', '#FFD700', '#006400'],
    lightingOverride: 'soft_pujo_pandal_glow',
    environmentStyle: 'kolkata — victoria memorial, durga puja pandals, college street bookshops, park street nightlife',
    wardrobe: { traditional: 'dhoti-panjabi, tant/jamdani saree with red border', modern: 'intellectual casual — cotton kurta, jhola bag', business: 'formal with bengali cultural refinement' },
    culturalElements: { architecture: 'colonial kolkata, durga puja pandals, terracotta temples, rabindranath\'s shantiniketan', vegetation: 'rice paddies, jute fields, shiuli flowers, water hyacinth', patterns: 'kantha embroidery, baluchari silk, alpona floor art', symbolism: ['durga idol', 'rosogolla', 'adda (intellectual chat)', 'yellow taxi'], avoidSymbols: ['partition trauma', 'political violence'] },
    music: { genre: 'Rabindra Sangeet meets bengali rock', instruments: ['esraj', 'tabla', 'sitar', 'guitar', 'harmonium'], bpmRange: { min: 80, max: 125 }, moodDescription: 'rabindranath\'s poetry meets bengali rock rebellion — intellectually passionate' },
    narrative: { storytellingApproach: 'literary_passionate', humorStyle: 'cerebral, satirical, food-obsessed', formalityLevel: 3, emotionalTone: 'intellectual, artistic, passionately cultured, food-loving' },
  }),
  INDIA_EAST_OR: v({
    regionCode: 'INDIA_EAST_OR', regionName: 'East India — Odia',
    colorOverrides: ['#FFD700', '#DC143C', '#FFFFFF', '#006400'],
    lightingOverride: 'warm_jagannath_temple_glow',
    environmentStyle: 'odisha — puri jagannath temple, konark sun temple, chilika lake, bhubaneswar modern',
    wardrobe: { traditional: 'sambalpuri saree, dhoti with gamchha', modern: 'casual with odia craft accents', business: 'formal with understated elegance' },
    culturalElements: { architecture: 'kalinga temple architecture, konark sun temple, puri jagannath, tribal villages', vegetation: 'rice paddies, mango orchards, casuarina coast, sal forests', patterns: 'sambalpuri ikat, pattachitra painting, dhokra metal craft, pipili appliqué', symbolism: ['jagannath rath yatra', 'rasgulla (odia origin!)', 'konark wheel', 'pattachitra art'], avoidSymbols: ['cyclone disaster exploitation', 'poverty stereotypes'] },
    music: { genre: 'Odia folk meets odissi classical', instruments: ['mardala drum', 'flute', 'sitar', 'harmonium', 'manjira'], bpmRange: { min: 85, max: 120 }, moodDescription: 'odissi dance grace with folk festival energy' },
    narrative: { storytellingApproach: 'gentle_artistic', humorStyle: 'gentle and self-deprecating', formalityLevel: 3, emotionalTone: 'artistic, gentle, temple-culture warmth, quietly proud' },
  }),

  // ─── MENA (additional) ─────────────────────────────────────────────────
  MENA_EGYPT: v({
    regionCode: 'MENA_EGYPT', regionName: 'Egypt',
    colorOverrides: ['#CE1126', '#FFFFFF', '#000000', '#C4A35A'],
    lightingOverride: 'warm_nile_sunset_with_pyramid_silhouette',
    environmentStyle: 'cairo street with pharaonic monuments, nile corniche, bustling khan el-khalili bazaar',
    wardrobe: { traditional: 'galabeya (men), abaya with colorful hijab (women)', modern: 'cairo street fashion — jeans and trendy tops', business: 'formal suit, conservative professional' },
    companionCreature: { name: 'Bastet', species: 'Egyptian Cat', description: 'Sleek black cat with golden eyes and tiny pharaonic collar', culturalSignificance: 'Cats were sacred in ancient Egypt, Bastet was goddess of protection' },
    culturalElements: { architecture: 'pyramids, pharaonic temples, islamic cairo mosques, modern towers', vegetation: 'nile palms, lotus, papyrus, bougainvillea', patterns: 'pharaonic hieroglyphs, islamic arabesque, lotus motifs, scarab designs', symbolism: ['pyramid', 'sphinx', 'ankh', 'nile felucca boat'], avoidSymbols: ['political revolution imagery', 'military sensitivity'] },
    music: { genre: 'Egyptian shaabi meets mahraganat and umm kulthum classical', instruments: ['oud', 'tabla', 'ney', 'keyboard', 'electronic beats'], bpmRange: { min: 95, max: 135 }, moodDescription: 'cairo street energy with ancient nile soul — umm kulthum meets mahraganat' },
    narrative: { storytellingApproach: 'warm_humorous_storytelling', humorStyle: 'egyptian wit — sharp, warm, self-deprecating', formalityLevel: 2, emotionalTone: 'warm, humorous, proud of ancient heritage, street-smart' },
  }),
  MENA_MAGHREB: v({
    regionCode: 'MENA_MAGHREB', regionName: 'Maghreb (Morocco, Algeria, Tunisia)',
    colorOverrides: ['#006233', '#C1272D', '#FFD700', '#FFFFFF'],
    lightingOverride: 'warm_medina_afternoon_with_sea_breeze',
    environmentStyle: 'moroccan medina with zellige tiles, tunisian blue-white sidi bou said, algerian casbah',
    wardrobe: { traditional: 'djellaba, kaftan, burnous cloak, chechia hat', modern: 'french-north african fusion fashion', business: 'french-influenced formal with maghrebi touches' },
    culturalElements: { architecture: 'riad courtyards, zellige mosaics, french colonial, casbah alleys', vegetation: 'argan trees, date palms, olive groves, cork oak forests', patterns: 'zellige geometric tiles, berber carpet motifs, henna art, calligraphy', symbolism: ['mint tea tray', 'tagine', 'hamsa hand', 'couscous bowl'], avoidSymbols: ['colonial exploitation', 'berber marginalization'] },
    music: { genre: 'Rai meets gnawa and chaabi', instruments: ['darbuka', 'guembri', 'oud', 'accordion', 'bendir'], bpmRange: { min: 90, max: 130 }, moodDescription: 'rai passion with gnawa spiritual depth — maghreb street meets sufi trance' },
    narrative: { storytellingApproach: 'hospitality_centered', humorStyle: 'warm, communal, food-centered', formalityLevel: 3, emotionalTone: 'hospitable, proud, francophone-arabic bilingual, food-loving' },
  }),
  MENA_MSA: v({
    regionCode: 'MENA_MSA', regionName: 'Modern Standard Arabic (Pan-Arab)',
    colorOverrides: ['#006233', '#FFFFFF', '#CE1126', '#C4A35A'],
    lightingOverride: 'neutral_professional_arabic_setting',
    environmentStyle: 'pan-arab professional setting — modern arabic office, news studio, or university',
    wardrobe: { traditional: 'varied by country — respects all arabic dress codes', modern: 'professional arabic fashion', business: 'formal arab professional — thobe or western suit' },
    culturalElements: { architecture: 'modern arabic architecture, islamic geometric, conference halls', vegetation: 'date palms, desert landscaping, garden courtyards', patterns: 'islamic geometric, arabic calligraphy, crescent motifs', symbolism: ['arabic calligraphy', 'crescent moon', 'coffee dallah', 'open book'], avoidSymbols: ['sectarian imagery', 'country-specific political tension'] },
    music: { genre: 'Pan-Arab orchestral meets modern pop', instruments: ['oud', 'qanun', 'violin', 'ney', 'keyboard'], bpmRange: { min: 85, max: 120 }, moodDescription: 'dignified and universal arabic elegance — professional and pan-arab' },
    narrative: { storytellingApproach: 'formal_dignified', humorStyle: 'light and respectful', formalityLevel: 5, emotionalTone: 'dignified, professional, pan-arab unity, formally eloquent' },
  }),

  // ─── CJK (additional) ──────────────────────────────────────────────────
  CJK_TW: v({
    regionCode: 'CJK_TW', regionName: 'Taiwan',
    colorOverrides: ['#FE0000', '#FFFFFF', '#000095', '#FFD700'],
    lightingOverride: 'warm_taipei_night_market_neon',
    environmentStyle: 'taipei night market energy, jiufen lanterns, modern tech industry, and bubble tea culture',
    wardrobe: { traditional: 'traditional chinese (modified), aboriginal tribal dress', modern: 'casual streetwear, japanese-influenced fashion', business: 'smart professional, less formal than mainland' },
    culturalElements: { architecture: 'traditional temples, japanese colonial, taipei 101 modern, night market stalls', vegetation: 'camphor trees, bamboo, tea plantations, tropical palms', patterns: 'traditional chinese motifs, hakka floral, aboriginal weave patterns', symbolism: ['bubble tea', 'night market', 'temple incense', 'taipei 101'], avoidSymbols: ['cross-strait political tension'] },
    music: { genre: 'Mandopop meets indie and electronic', instruments: ['erhu', 'piano', 'guitar', 'synth', 'drums'], bpmRange: { min: 100, max: 135 }, moodDescription: 'mandopop sweetness with indie creative energy and night market bustle' },
    narrative: { storytellingApproach: 'creative_warm', humorStyle: 'cute and self-deprecating', formalityLevel: 3, emotionalTone: 'creative, warm, tech-savvy, foodie culture' },
  }),

  // ─── SEA (additional) ──────────────────────────────────────────────────
  INDONESIA: v({
    regionCode: 'INDONESIA', regionName: 'Indonesia',
    colorOverrides: ['#FF0000', '#FFFFFF', '#006400', '#FFD700'],
    lightingOverride: 'warm_tropical_bali_temple_glow',
    environmentStyle: 'jakarta modern skyline, bali temple offerings, java batik workshops, and street food warungs',
    wardrobe: { traditional: 'batik shirt (national), kebaya, sarong, peci cap', modern: 'casual tropical with batik elements', business: 'batik shirt (accepted formal businesswear)' },
    companionCreature: { name: 'Garuda', species: 'Garuda Bird', description: 'Golden eagle-like mythical bird, majestic and protective', culturalSignificance: 'Garuda is Indonesia\'s national emblem and Vishnu\'s mount in mythology' },
    culturalElements: { architecture: 'borobudur temple, balinese gates, javanese pendopo, jakarta modern towers', vegetation: 'rice terraces, frangipani, clove trees, palm oil, tropical jungle', patterns: 'batik (parang, kawung, mega mendung), ikat weave, wayang kulit shadow', symbolism: ['batik fabric', 'wayang puppet', 'nasi goreng', 'gamelan gongs'], avoidSymbols: ['left hand for giving', 'pork in muslim contexts', 'separatism'] },
    music: { genre: 'Gamelan meets dangdut pop', instruments: ['gamelan', 'angklung', 'suling flute', 'kendang drum', 'synth'], bpmRange: { min: 90, max: 125 }, moodDescription: 'gamelan shimmer with dangdut groove — archipelago diversity in sound' },
    narrative: { storytellingApproach: 'harmonious_diverse', humorStyle: 'gentle, communal humor with food references', formalityLevel: 3, emotionalTone: 'harmonious, diverse, communal, warmly respectful' },
  }),

  // ─── Oceania (additional) ──────────────────────────────────────────────
  OCEANIA_NZ: v({
    regionCode: 'OCEANIA_NZ', regionName: 'New Zealand',
    colorOverrides: ['#000000', '#FFFFFF', '#C8102E', '#00843D'],
    lightingOverride: 'clean_nz_mountain_lake_light',
    environmentStyle: 'new zealand — hobbiton green hills, maori meeting house, wellington creative scene',
    wardrobe: { traditional: 'maori piupiu skirt, korowai cloak, pounamu pendant', modern: 'outdoor casual — merino wool, barefoot culture', business: 'relaxed professional, environmental awareness' },
    companionCreature: { name: 'Kiwi', species: 'Kiwi Bird', description: 'Small flightless bird, nocturnal and endearing, national icon', culturalSignificance: 'The kiwi is NZ\'s national symbol, representing uniqueness' },
    culturalElements: { architecture: 'maori wharenui meeting house, art deco napier, modern wellington, hobbit-inspired', vegetation: 'silver fern, pohutukawa, kauri trees, tussock grassland', patterns: 'maori ta moko (tattoo art), koru spiral, tukutuku weaving', symbolism: ['silver fern', 'haka dance', 'koru spiral', 'pounamu greenstone'], avoidSymbols: ['maori cultural appropriation without respect', 'australia conflation'] },
    music: { genre: 'NZ indie meets maori waiata', instruments: ['pūtātara (conch)', 'guitar', 'ukulele', 'drums', 'synth'], bpmRange: { min: 90, max: 125 }, moodDescription: 'kiwi indie warmth with maori spiritual depth and mountain air freshness' },
    narrative: { storytellingApproach: 'humble_authentic', humorStyle: 'dry kiwi self-deprecating humor', formalityLevel: 1, emotionalTone: 'humble, authentic, environmentally conscious, maori-respecting' },
  }),

  // ─── South Asia (additional) ───────────────────────────────────────────
  SA_NEPAL: v({
    regionCode: 'SA_NEPAL', regionName: 'Nepal',
    colorOverrides: ['#DC143C', '#003893', '#FFFFFF', '#FFD700'],
    lightingOverride: 'himalayan_golden_morning_light',
    environmentStyle: 'kathmandu temple squares, himalayan mountain backdrop, prayer flags, and bustling bazaars',
    wardrobe: { traditional: 'daura suruwal, dhaka topi cap, gunyu cholo sari', modern: 'trekking casual with nepali elements', business: 'formal daura suruwal or western suit' },
    culturalElements: { architecture: 'pagoda temples, durbar squares, tibetan monasteries, mountain lodges', vegetation: 'rhododendron (national flower), himalayan pine, terraced rice paddies', patterns: 'thangka painting, mandala art, dhaka fabric weave, metalwork', symbolism: ['everest/sagarmatha', 'prayer flags', 'namaste greeting', 'momo dumplings'], avoidSymbols: ['political instability', 'earthquake exploitation'] },
    music: { genre: 'Nepali folk meets modern pop', instruments: ['madal drum', 'sarangi', 'bansuri flute', 'guitar', 'harmonium'], bpmRange: { min: 85, max: 120 }, moodDescription: 'himalayan serenity with warm valley community spirit' },
    narrative: { storytellingApproach: 'mountain_wisdom', humorStyle: 'gentle and warm', formalityLevel: 3, emotionalTone: 'warm, humble, spiritually grounded, mountain-resilient' },
  }),

  // ─── Caribbean (additional) ────────────────────────────────────────────
  CARIBBEAN_FR: v({
    regionCode: 'CARIBBEAN_FR', regionName: 'French Caribbean (Haiti, Martinique, Guadeloupe)',
    colorOverrides: ['#00209F', '#FFFFFF', '#D21034', '#FFD700'],
    lightingOverride: 'tropical_caribbean_french_colonial_glow',
    environmentStyle: 'haitian art-filled streets, martinique beach markets, creole architecture, and carnival',
    wardrobe: { traditional: 'madras cloth dress, creole jewelry, headwrap (tignon)', modern: 'tropical casual with french-caribbean flair', business: 'french-influenced professional with caribbean color' },
    culturalElements: { architecture: 'french colonial, creole gingerbread houses, art-covered walls (haiti)', vegetation: 'tropical palms, breadfruit, mango, bougainvillea, rum sugarcane', patterns: 'madras plaid, haitian vodou art, carnival sequin motifs', symbolism: ['rum barrel', 'carnival mask', 'haitian metal art', 'creole spice'], avoidSymbols: ['vodou stereotypes', 'poverty exploitation', 'disaster tourism'] },
    music: { genre: 'Zouk meets kompa and soca', instruments: ['steel drums', 'guitar', 'bass', 'drums', 'ka drum'], bpmRange: { min: 90, max: 130 }, moodDescription: 'zouk sensuality with kompa groove and carnival liberation energy' },
    narrative: { storytellingApproach: 'rhythmic_resilient', humorStyle: 'warm creole wordplay', formalityLevel: 2, emotionalTone: 'resilient, rhythmic, culturally rich, joyfully defiant' },
  }),

  // ─── Africa (additional) ───────────────────────────────────────────────
  AFRICA_FRANCO: v({
    regionCode: 'AFRICA_FRANCO', regionName: 'Francophone Africa (Senegal, Ivory Coast, Mali)',
    colorOverrides: ['#009639', '#FFD700', '#CE1126', '#FF6B00'],
    lightingOverride: 'warm_sahelian_sunset',
    environmentStyle: 'dakar seaside vibrancy, abidjan modern skyline, bamako market bustle, and baobab landscapes',
    wardrobe: { traditional: 'boubou grand (grand boubou), basin riche fabric, head wrap', modern: 'franco-african fashion fusion — paris meets dakar', business: 'elegant boubou or french-style suit with african fabric' },
    culturalElements: { architecture: 'colonial french, adobe mosques (djenne), modern dakar, beach towns', vegetation: 'baobab trees, mango, cashew, sahel scrub, tropical coast', patterns: 'wax print (pagne), bogolan (mud cloth), kente-inspired', symbolism: ['baobab tree', 'teranga hospitality', 'djembe drum', 'thieboudienne fish dish'], avoidSymbols: ['french colonial exploitation', 'poverty stereotypes'] },
    music: { genre: 'Mbalax meets afrobeats and griot tradition', instruments: ['sabar drum', 'kora', 'balafon', 'guitar', 'djembe'], bpmRange: { min: 100, max: 130 }, moodDescription: 'mbalax dance energy with griot storytelling wisdom — teranga hospitality in sound' },
    narrative: { storytellingApproach: 'griot_storytelling', humorStyle: 'warm communal with french-wolof wordplay', formalityLevel: 3, emotionalTone: 'warm, hospitable (teranga), proudly francophone-african, rhythmic' },
  }),

  // ─── Central Asia & Caucasus ───────────────────────────────────────────
  ASIA_CENTRAL_KZ: v({
    regionCode: 'ASIA_CENTRAL_KZ', regionName: 'Kazakhstan',
    colorOverrides: ['#00AFCA', '#FFD700', '#FFFFFF', '#006400'],
    lightingOverride: 'vast_steppe_golden_light',
    environmentStyle: 'kazakh steppe meets nur-sultan modern architecture, yurt camps, and silk road heritage',
    wardrobe: { traditional: 'chapan robe, kalpak felt hat, taqiya cap', modern: 'central asian-russian fusion casual', business: 'conservative formal, russo-asian blend' },
    culturalElements: { architecture: 'nur-sultan futuristic towers, traditional yurts, silk road caravanserais', vegetation: 'steppe grassland, tulips (origin), apple orchards (almaty=father of apples)', patterns: 'kazakh felt carpet (syrmak), ram horn motifs, tribal geometric', symbolism: ['yurt', 'golden eagle (berkut)', 'baursak bread', 'dombra instrument'], avoidSymbols: ['soviet nuclear testing', 'political sensitivity'] },
    music: { genre: 'Kazakh folk meets modern pop', instruments: ['dombra', 'kobyz', 'sybyzgy flute', 'drums', 'synth'], bpmRange: { min: 90, max: 125 }, moodDescription: 'vast steppe freedom with dombra soul and modern ambition' },
    narrative: { storytellingApproach: 'nomadic_wisdom', humorStyle: 'warm hospitality humor', formalityLevel: 3, emotionalTone: 'vast, hospitable, nomadic heritage, modernizing' },
  }),
  ASIA_CENTRAL_UZ: v({
    regionCode: 'ASIA_CENTRAL_UZ', regionName: 'Uzbekistan',
    colorOverrides: ['#1EB53A', '#FFFFFF', '#0099B5', '#CE1126'],
    lightingOverride: 'silk_road_samarkand_golden_glow',
    environmentStyle: 'samarkand registan square, bukhara old town, tashkent modern, and silk road bazaars',
    wardrobe: { traditional: 'chapan robe, doppi cap, atlas ikat dress', modern: 'central asian casual with ikat accents', business: 'formal with uzbek textile touches' },
    culturalElements: { architecture: 'registan madrasas, bukhara minarets, tashkent metro art, silk road architecture', vegetation: 'cotton fields, mulberry trees, pomegranate, vineyard oases', patterns: 'atlas ikat silk, suzani embroidery, islamic tilework, miniature painting', symbolism: ['registan square', 'plov rice dish', 'suzani embroidery', 'cotton boll'], avoidSymbols: ['cotton forced labor history', 'soviet regime'] },
    music: { genre: 'Uzbek maqam meets pop (estrada)', instruments: ['dutar', 'rubab', 'doira drum', 'chang', 'ney'], bpmRange: { min: 85, max: 120 }, moodDescription: 'silk road elegance with maqam emotional depth' },
    narrative: { storytellingApproach: 'silk_road_heritage', humorStyle: 'warm and hospitality-centered', formalityLevel: 4, emotionalTone: 'hospitable, heritage-proud, silk-road romantic, modernizing' },
  }),
  EU_CAUCASUS: v({
    regionCode: 'EU_CAUCASUS', regionName: 'Caucasus (Georgia, Armenia, Azerbaijan)',
    colorOverrides: ['#DA291C', '#FFD700', '#FFFFFF', '#006400'],
    lightingOverride: 'warm_caucasus_mountain_vineyard_light',
    environmentStyle: 'georgian wine country, armenian monasteries on cliffs, azerbaijani flame towers and old city',
    wardrobe: { traditional: 'chokha (georgian), taraz (armenian), national dress with dagger', modern: 'european-eastern fusion casual', business: 'formal with caucasian cultural pride' },
    culturalElements: { architecture: 'georgian churches, armenian monasteries, azerbaijani flame towers, silk road caravanserais', vegetation: 'vineyards (8000yr wine heritage), walnut trees, pomegranate, mountain herbs', patterns: 'armenian khachkar cross-stone carving, georgian calligraphy, azerbaijani carpet motifs', symbolism: ['wine qvevri', 'armenian pomegranate', 'azeri flame', 'georgian supra feast'], avoidSymbols: ['territorial conflicts', 'genocide sensitivity'] },
    music: { genre: 'Georgian polyphonic chanting meets mugham and duduk', instruments: ['panduri', 'duduk', 'tar', 'doli drum', 'zurna'], bpmRange: { min: 85, max: 125 }, moodDescription: 'georgian harmony with armenian duduk melancholy and azeri fire — mountain soul' },
    narrative: { storytellingApproach: 'feast_and_hospitality', humorStyle: 'warm toast-making tradition', formalityLevel: 3, emotionalTone: 'hospitable, ancient, wine-loving, fiercely proud' },
  }),
};

// ─── Lookup Functions ───────────────────────────────────────────────────────

export function getExpandedRegionalVariant(regionCode: string): RegionalStyleVariant | undefined {
  return REGIONAL_EXPANSION[regionCode];
}

export function getAllExpandedRegionCodes(): string[] {
  return Object.keys(REGIONAL_EXPANSION);
}

export function searchExpandedRegions(query: string): RegionalStyleVariant[] {
  const lower = query.toLowerCase();
  return Object.values(REGIONAL_EXPANSION).filter(
    v => v.regionName.toLowerCase().includes(lower) || v.regionCode.toLowerCase().includes(lower)
  );
}
