/**
 * Regional Creative Expansion — 33 expanded regional variants
 * Extends the 9 core regions in castCreativeStylesRegistry.ts with global coverage.
 */
import type { RegionalStyleVariant } from './castCreativeStylesRegistry';

const v = (r: RegionalStyleVariant) => r;

export const REGIONAL_EXPANSION: Record<string, RegionalStyleVariant> = {
  EUROPE_UK: v({
    regionCode: 'EUROPE_UK', regionName: 'United Kingdom',
    colorOverrides: ['#00247D', '#CF142B', '#FFFFFF', '#2E8B57'],
    lightingOverride: 'overcast_london_soft_diffused',
    environmentStyle: 'charming british high street with red phone boxes, cobblestones, and pub signs',
    wardrobe: { traditional: 'tweed jacket, flat cap, tartan scarf', modern: 'smart casual — oxford shirt, chinos, brogues', business: 'savile row suit, understated tie' },
    companionCreature: { name: 'Winston', species: 'Corgi', description: 'Dignified corgi with a tiny bowler hat, loyal and witty', culturalSignificance: 'Corgis are iconic British royal companions' },
    culturalElements: { architecture: 'georgian townhouses, thatched cottages, modern city glass towers', vegetation: 'rose gardens, rolling green hills, hedgerows, oak trees', patterns: 'tartan, houndstooth, william morris floral, pinstripe', symbolism: ['cup of tea', 'red double-decker bus', 'crown', 'big ben clock'], avoidSymbols: ['colonial imagery', 'negative brexit references'] },
    music: { genre: 'Britpop meets orchestral indie', instruments: ['acoustic guitar', 'piano', 'strings', 'drums', 'brass'], bpmRange: { min: 100, max: 130 }, moodDescription: 'witty and understated with warmth beneath the dry exterior' },
    narrative: { storytellingApproach: 'dry_wit_understatement', humorStyle: 'self-deprecating and dry wit', formalityLevel: 3, emotionalTone: 'reserved warmth, dry humor, quiet confidence' },
  }),
  EUROPE_FRANCE: v({
    regionCode: 'EUROPE_FRANCE', regionName: 'France',
    colorOverrides: ['#002395', '#FFFFFF', '#ED2939', '#C4A35A'],
    lightingOverride: 'parisian_golden_afternoon',
    environmentStyle: 'elegant parisian boulevard with café terraces, wrought-iron balconies, and plane trees',
    wardrobe: { traditional: 'breton stripe shirt, beret, tailored trousers', modern: 'effortlessly chic — well-cut blazer, silk scarf', business: 'impeccably tailored suit with subtle flair' },
    companionCreature: { name: 'Renard', species: 'Red Fox', description: 'Elegant fox with a small silk scarf, clever and charming', culturalSignificance: 'The fox features in French fables (Le Petit Prince, Roman de Renart)' },
    culturalElements: { architecture: 'haussmann buildings, mansard roofs, art nouveau metro, gothic cathedrals', vegetation: 'lavender fields, plane trees, grapevines, sunflowers', patterns: 'toile de jouy, fleur-de-lis, art deco geometric', symbolism: ['croissant and café', 'eiffel tower silhouette', 'baguette', 'wine glass'], avoidSymbols: ['surrender jokes', 'negative stereotypes'] },
    music: { genre: 'French chanson meets electronic', instruments: ['accordion', 'piano', 'violin', 'electronic beats', 'upright bass'], bpmRange: { min: 85, max: 120 }, moodDescription: 'romantic sophistication with intellectual edge' },
    narrative: { storytellingApproach: 'philosophical_elegant', humorStyle: 'witty intellectual wordplay', formalityLevel: 4, emotionalTone: 'sophisticated, passionate, intellectually curious' },
  }),
  EUROPE_GERMANY: v({
    regionCode: 'EUROPE_GERMANY', regionName: 'Germany',
    colorOverrides: ['#000000', '#DD0000', '#FFCC00', '#4A7C59'],
    lightingOverride: 'clean_northern_european_daylight',
    environmentStyle: 'orderly german town with half-timbered houses, modern engineering, and beer gardens',
    wardrobe: { traditional: 'lederhosen, dirndl (Bavaria), loden coat', modern: 'functional minimalism — quality fabrics, clean lines', business: 'precise tailoring, conservative colors' },
    culturalElements: { architecture: 'half-timbered fachwerk, bauhaus modern, gothic churches, industrial lofts', vegetation: 'black forest pines, linden trees, hops fields, apple orchards', patterns: 'bauhaus geometric, bavarian blue-white diamonds, clean industrial lines', symbolism: ['beer stein', 'cuckoo clock', 'autobahn', 'engineering precision'], avoidSymbols: ['WWII imagery', 'nazi references'] },
    music: { genre: 'Electronic-classical fusion (Kraftwerk meets Bach)', instruments: ['synthesizer', 'piano', 'cello', 'electronic beats', 'accordion'], bpmRange: { min: 110, max: 140 }, moodDescription: 'precise and powerful with unexpected warmth' },
    narrative: { storytellingApproach: 'logical_structured_thorough', humorStyle: 'dry factual humor', formalityLevel: 4, emotionalTone: 'reliable, thorough, quality-focused, efficient' },
  }),
  EUROPE_SPAIN: v({
    regionCode: 'EUROPE_SPAIN', regionName: 'Spain',
    colorOverrides: ['#AA151B', '#F1BF00', '#FF6B00', '#2E4057'],
    lightingOverride: 'warm_mediterranean_golden_hour',
    environmentStyle: 'vibrant spanish plaza with terracotta buildings, bougainvillea, and tapas bars',
    wardrobe: { traditional: 'flamenco dress, matador-inspired vest, mantilla shawl', modern: 'mediterranean casual — linen shirt, espadrilles', business: 'sharp european cut suit with pocket square' },
    companionCreature: { name: 'Toro', species: 'Small Bull', description: 'Friendly miniature bull with flower garlands, spirited but gentle', culturalSignificance: 'The bull is the enduring symbol of Spanish spirit' },
    culturalElements: { architecture: 'moorish arches, gaudi mosaics, whitewashed pueblos', vegetation: 'olive groves, orange trees, bougainvillea, cork oaks', patterns: 'azulejo tiles, moorish geometric, flamenco polka dots', symbolism: ['flamenco fan', 'guitar', 'olive branch', 'sun and siesta'], avoidSymbols: ['bullfighting cruelty', 'political tensions'] },
    music: { genre: 'Flamenco meets modern pop', instruments: ['spanish guitar', 'cajón', 'palmas (clapping)', 'castanets', 'violin'], bpmRange: { min: 90, max: 140 }, moodDescription: 'passionate and fiery with rhythmic intensity' },
    narrative: { storytellingApproach: 'passionate_dramatic', humorStyle: 'playful and warm', formalityLevel: 2, emotionalTone: 'passionate, warm, family-centered, life-affirming' },
  }),
  EUROPE_ITALY: v({
    regionCode: 'EUROPE_ITALY', regionName: 'Italy',
    colorOverrides: ['#008C45', '#FFFFFF', '#CD212A', '#D4AF37'],
    lightingOverride: 'tuscan_golden_afternoon',
    environmentStyle: 'charming italian piazza with renaissance architecture, vespa scooters, and gelato shops',
    wardrobe: { traditional: 'renaissance-inspired formal wear', modern: 'impeccable italian fashion — fitted blazer, quality leather shoes', business: 'designer suit, silk tie, artisan leather briefcase' },
    culturalElements: { architecture: 'renaissance palazzos, roman columns, venetian gothic, tuscan villas', vegetation: 'cypress trees, vineyards, lemon groves, olive trees, wisteria', patterns: 'renaissance motifs, venetian damask, florentine fleur-de-lis', symbolism: ['espresso cup', 'vespa scooter', 'colosseum arch', 'hand gestures'], avoidSymbols: ['mafia references', 'negative stereotyping'] },
    music: { genre: 'Opera meets modern Italian pop', instruments: ['mandolin', 'accordion', 'violin', 'piano', 'tenor voice'], bpmRange: { min: 85, max: 130 }, moodDescription: 'dramatic and beautiful with operatic flair, la dolce vita meets innovation' },
    narrative: { storytellingApproach: 'expressive_storytelling', humorStyle: 'theatrical and warm', formalityLevel: 3, emotionalTone: 'expressive, passionate, design-conscious' },
  }),
  EUROPE_NORDIC: v({
    regionCode: 'EUROPE_NORDIC', regionName: 'Nordics (Sweden, Norway, Denmark, Finland)',
    colorOverrides: ['#003897', '#FECC02', '#FFFFFF', '#5B8C5A'],
    lightingOverride: 'scandinavian_clean_natural_light',
    environmentStyle: 'minimalist scandinavian space with fjord views, birch forests, and hygge interiors',
    wardrobe: { traditional: 'folk costume (bunad/folkdräkt), woolen knitwear', modern: 'clean scandinavian minimalism — neutral tones', business: 'understated smart casual, no-tie culture' },
    companionCreature: { name: 'Björn', species: 'Bear Cub', description: 'Small brown bear with a knitted scarf, calm and dependable', culturalSignificance: 'The bear symbolizes strength and nature in Nordic culture' },
    culturalElements: { architecture: 'wooden stave churches, modern minimalist, glass and timber, cozy cabins', vegetation: 'birch forests, pine trees, wildflowers, moss, lingonberry', patterns: 'nordic knit patterns, dalarna horse motifs, marimekko-style bold prints', symbolism: ['northern lights', 'viking ship', 'midsummer maypole', 'candle in winter'], avoidSymbols: ['viking violence stereotypes'] },
    music: { genre: 'Nordic folk meets electronic ambient', instruments: ['nyckelharpa', 'hardanger fiddle', 'synth pads', 'piano', 'drums'], bpmRange: { min: 90, max: 125 }, moodDescription: 'serene and luminous with deep emotional undercurrents' },
    narrative: { storytellingApproach: 'understated_authentic', humorStyle: 'deadpan and understated', formalityLevel: 2, emotionalTone: 'calm, authentic, egalitarian, nature-connected' },
  }),
  EUROPE_POLAND: v({
    regionCode: 'EUROPE_POLAND', regionName: 'Poland',
    colorOverrides: ['#DC143C', '#FFFFFF', '#0047AB', '#228B22'],
    lightingOverride: 'central_european_soft_daylight',
    environmentStyle: 'historic polish old town with colorful tenements, cobblestones, and modern tech hubs',
    wardrobe: { traditional: 'folk costume with floral embroidery, krakowska cap', modern: 'smart european casual, quality streetwear', business: 'well-fitted suit, conservative and professional' },
    culturalElements: { architecture: 'gothic old towns, baroque churches, modern glass offices', vegetation: 'silver birch, wildflower meadows, apple orchards', patterns: 'łowicz folk paper cuts (wycinanki), floral embroidery', symbolism: ['white eagle', 'amber jewelry', 'pierogi', 'stork on rooftop'], avoidSymbols: ['WWII trauma imagery', 'soviet stereotypes'] },
    music: { genre: 'Chopin-inspired piano with modern electronic', instruments: ['piano', 'violin', 'accordion', 'electronic synth', 'drums'], bpmRange: { min: 100, max: 135 }, moodDescription: 'resilient and creative with romantic depth' },
    narrative: { storytellingApproach: 'resilient_creative', humorStyle: 'dry self-deprecating with sharp wit', formalityLevel: 3, emotionalTone: 'resilient, creative, determined, warmly hospitable' },
  }),
  EUROPE_TURKEY: v({
    regionCode: 'EUROPE_TURKEY', regionName: 'Turkey',
    colorOverrides: ['#E30A17', '#FFFFFF', '#1E3A5F', '#C4A35A'],
    lightingOverride: 'warm_bosphorus_sunset',
    environmentStyle: 'istanbul grand bazaar meets modern city, minarets alongside glass towers',
    wardrobe: { traditional: 'kaftan, embroidered vest, regional dress', modern: 'mediterranean smart casual with quality fabrics', business: 'sharp european-cut suit with ottoman-inspired accessories' },
    companionCreature: { name: 'Van', species: 'Van Cat', description: 'Pure white cat with one blue and one amber eye, graceful', culturalSignificance: 'The Turkish Van cat is a national treasure' },
    culturalElements: { architecture: 'ottoman mosques, grand bazaar arches, modern istanbul skyline, cappadocia caves', vegetation: 'tulip gardens, olive groves, pomegranate trees, cypress', patterns: 'iznik tile motifs, ottoman tulip designs, kilim geometric, ebru marbling', symbolism: ['turkish tea glass', 'evil eye (nazar)', 'tulip', 'crescent moon'], avoidSymbols: ['political tensions', 'armenian genocide denial'] },
    music: { genre: 'Turkish classical meets Anatolian rock', instruments: ['oud', 'bağlama/saz', 'ney', 'darbuka', 'kanun'], bpmRange: { min: 95, max: 130 }, moodDescription: 'mystical and warm, east meets west bridge energy' },
    narrative: { storytellingApproach: 'bridge_between_worlds', humorStyle: 'warm observational with hospitality', formalityLevel: 3, emotionalTone: 'hospitable, proud, bridge-between-cultures' },
  }),
  LATAM_BRAZIL: v({
    regionCode: 'LATAM_BRAZIL', regionName: 'Brazil',
    colorOverrides: ['#009C3B', '#FFDF00', '#002776', '#FF6B00'],
    lightingOverride: 'tropical_rio_carnival_glow',
    environmentStyle: 'colorful rio streetscape with copacabana mosaic, tropical fruit stands, and samba rhythms',
    wardrobe: { traditional: 'carnival costume, baiana dress with turban', modern: 'tropical casual — havaianas, bermuda shorts, colorful shirts', business: 'smart casual with tropical flair, open collar' },
    companionCreature: { name: 'Arara', species: 'Scarlet Macaw', description: 'Brilliant macaw with rainbow plumage, exuberant and social', culturalSignificance: 'The macaw symbolizes Brazil\'s tropical biodiversity' },
    culturalElements: { architecture: 'oscar niemeyer curves, colonial churches, favela colorful walls', vegetation: 'amazon rainforest, palm trees, tropical flowers, açaí palms', patterns: 'copacabana wave mosaic, carnival feather motifs, indigenous geometric', symbolism: ['football/soccer', 'carnival mask', 'christ the redeemer', 'açaí bowl'], avoidSymbols: ['favela poverty exploitation', 'deforestation imagery'] },
    music: { genre: 'Bossa nova meets Brazilian funk and samba', instruments: ['berimbau', 'pandeiro', 'cavaquinho', 'surdo drum', 'acoustic guitar'], bpmRange: { min: 95, max: 140 }, moodDescription: 'infectious joy and rhythm, samba swing meets optimism' },
    narrative: { storytellingApproach: 'joyful_communal_rhythm', humorStyle: 'playful and warm with physical comedy', formalityLevel: 1, emotionalTone: 'joyful, rhythmic, communal, passionately optimistic' },
  }),
  LATAM_COLOMBIA: v({
    regionCode: 'LATAM_COLOMBIA', regionName: 'Colombia',
    colorOverrides: ['#FCD116', '#003893', '#CE1126', '#00A86B'],
    lightingOverride: 'warm_andean_highland_light',
    environmentStyle: 'colorful cartagena streets with colonial balconies, flower carts, and salsa rhythms',
    wardrobe: { traditional: 'poncho, ruana, vueltiao hat', modern: 'colorful casual with latin flair', business: 'smart casual, regional textile accents' },
    culturalElements: { architecture: 'colonial cartagena walls, colorful pueblitos, modern medellín metrocable', vegetation: 'coffee plants, orchids, palm wax trees, tropical flowers', patterns: 'wayuu mochila weave, pre-columbian gold motifs', symbolism: ['coffee cup', 'orchid (national flower)', 'emerald', 'salsa dancers'], avoidSymbols: ['drug cartel references', 'violence stereotypes'] },
    music: { genre: 'Cumbia meets reggaeton and vallenato', instruments: ['accordion', 'guacharaca', 'caja drum', 'gaita flute', 'bass'], bpmRange: { min: 95, max: 135 }, moodDescription: 'warm and rhythmic with cumbia swing' },
    narrative: { storytellingApproach: 'warm_resilient_optimistic', humorStyle: 'warm situational with regional humor', formalityLevel: 2, emotionalTone: 'warm, resilient, creative, community-minded' },
  }),
  LATAM_ARGENTINA: v({
    regionCode: 'LATAM_ARGENTINA', regionName: 'Argentina',
    colorOverrides: ['#74ACDF', '#FFFFFF', '#F6B40E', '#2E4057'],
    lightingOverride: 'buenos_aires_tango_evening',
    environmentStyle: 'elegant buenos aires with european architecture, tango cafes, and jacaranda trees',
    wardrobe: { traditional: 'gaucho bombacha pants, boina beret, pañuelo', modern: 'european-influenced smart casual, leather jacket', business: 'well-tailored italian-inspired suit' },
    culturalElements: { architecture: 'art deco buenos aires, european boulevards, estancia ranches, la boca houses', vegetation: 'pampas grass, jacaranda trees, ombu, vineyards', patterns: 'gaucho leather tooling, fileteado porteño, art deco geometric', symbolism: ['mate gourd', 'tango dancers', 'asado grill', 'gaucho'], avoidSymbols: ['falklands/malvinas tensions', 'economic crisis mocking'] },
    music: { genre: 'Tango meets electronic and rock nacional', instruments: ['bandoneón', 'piano', 'violin', 'electric guitar', 'double bass'], bpmRange: { min: 85, max: 130 }, moodDescription: 'dramatic tango passion meets intellectual depth' },
    narrative: { storytellingApproach: 'intellectual_passionate', humorStyle: 'sharp ironic wit', formalityLevel: 3, emotionalTone: 'passionate, intellectual, proud, dramatically expressive' },
  }),
  NAM_CANADA: v({
    regionCode: 'NAM_CANADA', regionName: 'Canada',
    colorOverrides: ['#FF0000', '#FFFFFF', '#003DA5', '#2E8B57'],
    lightingOverride: 'clean_northern_natural_light',
    environmentStyle: 'multicultural canadian cityscape with mountains, lakes, and modern architecture',
    wardrobe: { traditional: 'plaid flannel, tuque, mukluks, parka', modern: 'outdoor-meets-urban — quality outerwear, casual layering', business: 'smart casual, less formal than US' },
    companionCreature: { name: 'Maple', species: 'Beaver', description: 'Friendly beaver with a maple leaf cap, industrious and kind', culturalSignificance: 'The beaver is Canada\'s national animal' },
    culturalElements: { architecture: 'log cabins, modern glass towers, victorian parliament', vegetation: 'maple trees, boreal forest, rocky mountain wildflowers', patterns: 'hudson bay stripes, first nations art, maple leaf motifs, plaid', symbolism: ['maple leaf', 'hockey stick', 'canoe', 'totem pole'], avoidSymbols: ['indigenous cultural appropriation'] },
    music: { genre: 'Indie folk meets electronic', instruments: ['acoustic guitar', 'fiddle', 'synth', 'piano', 'drums'], bpmRange: { min: 95, max: 125 }, moodDescription: 'warm and inclusive with wilderness wonder' },
    narrative: { storytellingApproach: 'inclusive_multicultural', humorStyle: 'gentle self-deprecating', formalityLevel: 2, emotionalTone: 'inclusive, kind, multicultural, quietly confident' },
  }),
  CARIBBEAN_JAMAICA: v({
    regionCode: 'CARIBBEAN_JAMAICA', regionName: 'Jamaica & Caribbean',
    colorOverrides: ['#009B3A', '#FED100', '#000000', '#FF6B00'],
    lightingOverride: 'tropical_caribbean_golden_hour',
    environmentStyle: 'vibrant jamaican beach town with colorful buildings, palm trees, and reggae vibes',
    wardrobe: { traditional: 'rastafari colors, dashiki, head wrap', modern: 'tropical casual — bright colors, sandals, relaxed fit', business: 'tropical business — short-sleeve button-up, light fabrics' },
    culturalElements: { architecture: 'colorful colonial buildings, beach shacks, tropical modern', vegetation: 'coconut palms, hibiscus, banana trees, blue mountain coffee', patterns: 'rastafari stripes, tropical prints, dancehall graphics', symbolism: ['reggae music notes', 'palm tree', 'coffee bean', 'sprint runner'], avoidSymbols: ['drug culture stereotypes'] },
    music: { genre: 'Reggae meets dancehall and soca', instruments: ['steel drums', 'bass guitar', 'organ', 'drums', 'horn section'], bpmRange: { min: 80, max: 120 }, moodDescription: 'laid-back island rhythm with infectious optimism' },
    narrative: { storytellingApproach: 'rhythmic_storytelling', humorStyle: 'playful patois wordplay', formalityLevel: 1, emotionalTone: 'joyful, rhythmic, resilient, spiritually grounded' },
  }),
  LATAM_PERU: v({
    regionCode: 'LATAM_PERU', regionName: 'Peru',
    colorOverrides: ['#D91023', '#FFFFFF', '#C4A35A', '#4A7C59'],
    lightingOverride: 'andean_highland_clear_light',
    environmentStyle: 'peruvian andean landscape with inca ruins, colorful textiles, and bustling lima streets',
    wardrobe: { traditional: 'poncho with andean patterns, chullo knit hat, pollera skirt', modern: 'casual with alpaca wool accents', business: 'smart casual with peruvian textile accessories' },
    culturalElements: { architecture: 'inca stone walls, colonial churches, modern lima, adobe villages', vegetation: 'quinoa fields, potato terraces, eucalyptus, cactus', patterns: 'inca geometric textiles, nazca lines motifs, andean cross (chakana)', symbolism: ['llama/alpaca', 'machu picchu', 'chakana cross', 'ceviche bowl'], avoidSymbols: ['inca exploitation', 'poverty stereotypes'] },
    music: { genre: 'Andean folk meets criolla fusion', instruments: ['charango', 'pan flute (zampoña)', 'cajón', 'guitar', 'quena'], bpmRange: { min: 90, max: 130 }, moodDescription: 'soaring andean melodies with earthy warmth' },
    narrative: { storytellingApproach: 'heritage_meets_innovation', humorStyle: 'gentle and food-centered', formalityLevel: 3, emotionalTone: 'proud, warm, heritage-conscious' },
  }),
  CJK_CHINA: v({
    regionCode: 'CJK_CHINA', regionName: 'China',
    colorOverrides: ['#DE2910', '#FFDE00', '#000000', '#8B0000'],
    lightingOverride: 'warm_lantern_glow_with_modern_neon',
    environmentStyle: 'shanghai skyline blending with traditional courtyard, red lanterns and glass towers',
    wardrobe: { traditional: 'qipao/cheongsam, tang suit, hanfu revival', modern: 'trendy streetwear, tech-forward casual', business: 'well-tailored dark suit, conservative' },
    companionCreature: { name: 'Long', species: 'Baby Dragon', description: 'Playful chinese dragon hatchling with golden whiskers', culturalSignificance: 'The dragon symbolizes power and good fortune in Chinese culture' },
    culturalElements: { architecture: 'hutong courtyards, pagoda towers, modern supertall skyscrapers', vegetation: 'bamboo, plum blossoms, lotus, pine, chrysanthemum', patterns: 'cloud scrolls, dragon motifs, chinese knot, silk brocade', symbolism: ['red envelope', 'dragon dance', 'tea ceremony', 'great wall'], avoidSymbols: ['number 4 prominently', 'political sensitivity'] },
    music: { genre: 'Chinese orchestral meets C-pop electronic', instruments: ['erhu', 'pipa', 'guzheng', 'dizi flute', 'electronic beats'], bpmRange: { min: 95, max: 135 }, moodDescription: 'grand and ambitious with ancient elegance' },
    narrative: { storytellingApproach: 'grand_narrative_ambitious', humorStyle: 'clever wordplay and situational', formalityLevel: 4, emotionalTone: 'ambitious, heritage-proud, innovative' },
  }),
  CJK_KOREA: v({
    regionCode: 'CJK_KOREA', regionName: 'South Korea',
    colorOverrides: ['#003478', '#CD2E3A', '#FFFFFF', '#FFB7C5'],
    lightingOverride: 'k_drama_soft_glow',
    environmentStyle: 'trendy seoul neighborhood with hanok houses among neon signs, cherry blossoms, and k-pop',
    wardrobe: { traditional: 'hanbok with jeogori and chima', modern: 'k-fashion — oversized blazer, sneakers, idol-inspired', business: 'sharp dark suit, conservative, well-groomed' },
    companionCreature: { name: 'Horangi', species: 'Tiger Cub', description: 'Adorable tiger cub with a traditional norigae charm, brave and playful', culturalSignificance: 'The tiger is Korea\'s guardian spirit' },
    culturalElements: { architecture: 'hanok houses, gyeongbokgung palace, gangnam glass towers', vegetation: 'cherry blossoms, mugunghwa, pine, ginkgo', patterns: 'dancheong painted beams, celadon patterns, taegeuk symbol', symbolism: ['kimchi jar', 'K-drama heart gesture', 'soju bottle', 'PC bang'], avoidSymbols: ['north korea conflation', 'japan-korea tensions'] },
    music: { genre: 'K-pop meets traditional gugak', instruments: ['gayageum', 'synth', 'electric guitar', 'drums', 'samulnori percussion'], bpmRange: { min: 110, max: 150 }, moodDescription: 'polished K-pop energy with dramatic emotional arcs' },
    narrative: { storytellingApproach: 'dramatic_arc_with_twist', humorStyle: 'variety show style with aegyo', formalityLevel: 4, emotionalTone: 'dynamic, trend-setting, emotionally dramatic' },
  }),
  SEA_THAILAND: v({
    regionCode: 'SEA_THAILAND', regionName: 'Thailand',
    colorOverrides: ['#A51931', '#F4F5F8', '#2D2A4A', '#FFD700'],
    lightingOverride: 'warm_temple_golden_glow',
    environmentStyle: 'bangkok street with golden temples, tuk-tuks, floating markets, and modern malls',
    wardrobe: { traditional: 'thai silk sarong, chut thai formal, sabai drape', modern: 'tropical casual with thai silk accents', business: 'conservative suit, pastel shirts' },
    companionCreature: { name: 'Chang', species: 'Baby Elephant', description: 'Small thai elephant with flower garland, gentle and joyful', culturalSignificance: 'The elephant is Thailand\'s national symbol' },
    culturalElements: { architecture: 'golden temple spires, traditional teak houses, modern bangkok towers', vegetation: 'orchids, lotus, coconut palms, frangipani, bamboo', patterns: 'kanok flame motifs, lai thai patterns, temple mural art', symbolism: ['wai greeting', 'lotus flower', 'spirit house', 'floating lantern'], avoidSymbols: ['disrespect to monarchy', 'buddha merchandise'] },
    music: { genre: 'Thai pop meets traditional piphat', instruments: ['ranat xylophone', 'khim', 'pi oboe', 'drums', 'synth'], bpmRange: { min: 90, max: 125 }, moodDescription: 'gentle and warm with temple bell serenity' },
    narrative: { storytellingApproach: 'gentle_harmonious', humorStyle: 'gentle and fun-loving (sanuk)', formalityLevel: 4, emotionalTone: 'warm, respectful, joyful, harmonious' },
  }),
  SEA_VIETNAM: v({
    regionCode: 'SEA_VIETNAM', regionName: 'Vietnam',
    colorOverrides: ['#DA251D', '#FFCD00', '#00A86B', '#8B4513'],
    lightingOverride: 'warm_lantern_festival_glow',
    environmentStyle: 'hoi an ancient town with silk lanterns, motorbike streets, and pho stalls',
    wardrobe: { traditional: 'ao dai (long tunic), non la (conical hat)', modern: 'casual with ao dai-inspired modern fashion', business: 'conservative suit or modern ao dai for women' },
    culturalElements: { architecture: 'french colonial, ancient town shophouses, pagodas, modern towers', vegetation: 'rice paddies, lotus ponds, bamboo, jackfruit trees', patterns: 'silk lantern motifs, lotus flower designs, dong ho folk prints', symbolism: ['pho bowl', 'silk lantern', 'conical hat', 'motorbike culture'], avoidSymbols: ['war imagery', 'political sensitivity'] },
    music: { genre: 'Vietnamese traditional meets V-pop', instruments: ['dan bau', 'dan tranh', 'sao flute', 'drums', 'synth'], bpmRange: { min: 85, max: 120 }, moodDescription: 'lyrical and poetic with resilient spirit' },
    narrative: { storytellingApproach: 'poetic_resilient', humorStyle: 'gentle and family-oriented', formalityLevel: 3, emotionalTone: 'resilient, poetic, family-focused' },
  }),
  SEA_PHILIPPINES: v({
    regionCode: 'SEA_PHILIPPINES', regionName: 'Philippines',
    colorOverrides: ['#0038A8', '#CE1126', '#FFFFFF', '#FCD116'],
    lightingOverride: 'tropical_island_golden_hour',
    environmentStyle: 'colorful filipino barangay with jeepneys, tropical beaches, and fiesta decorations',
    wardrobe: { traditional: 'barong tagalog, terno dress, malong wrap', modern: 'casual tropical — jeans and tee, flip flops', business: 'barong tagalog (accepted as formal businesswear)' },
    culturalElements: { architecture: 'spanish colonial churches, bahay kubo nipa hut, modern manila towers', vegetation: 'coconut palms, sampaguita jasmine, mango trees', patterns: 'jeepney art style, t\'nalak weave, banig mat patterns', symbolism: ['jeepney', 'carabao', 'sampaguita garland', 'karaoke microphone'], avoidSymbols: ['colonial exploitation'] },
    music: { genre: 'OPM meets ballad pop', instruments: ['guitar', 'ukulele', 'drums', 'keyboard', 'bamboo instruments'], bpmRange: { min: 90, max: 130 }, moodDescription: 'heartfelt and melodic with fiesta energy' },
    narrative: { storytellingApproach: 'warm_family_fiesta', humorStyle: 'self-deprecating and joyful (hugot)', formalityLevel: 2, emotionalTone: 'warm, family-centered, resilient' },
  }),
  INDIA_WEST: v({
    regionCode: 'INDIA_WEST', regionName: 'West India (Maharashtra, Gujarat, Rajasthan)',
    colorOverrides: ['#FF6B00', '#FFD700', '#DC143C', '#4A7C59'],
    lightingOverride: 'warm_desert_sunset_to_vibrant_market',
    environmentStyle: 'rajasthani desert palace meets bustling mumbai street, vibrant textiles everywhere',
    wardrobe: { traditional: 'rajasthani pagri turban, bandhani saree, ghagra choli', modern: 'bollywood-influenced casual, cotton kurta', business: 'bandhgala/nehru jacket, formal saree' },
    companionCreature: { name: 'Mor', species: 'Peacock', description: 'Magnificent peacock with iridescent feathers, proud and beautiful', culturalSignificance: 'The peacock is India\'s national bird' },
    culturalElements: { architecture: 'rajasthani havelis, marine drive art deco, stepwells, temple complexes', vegetation: 'desert scrub, neem trees, jasmine, cotton fields, mango orchards', patterns: 'bandhani tie-dye, block print, warli tribal art, meenakari enamel', symbolism: ['ganpati/ganesha', 'dandiya sticks', 'dabba lunch box', 'autorickshaw'], avoidSymbols: ['communal tension imagery'] },
    music: { genre: 'Rajasthani folk meets Bollywood pop', instruments: ['ravanhatta', 'dholak', 'harmonium', 'manjeera', 'morchang'], bpmRange: { min: 100, max: 145 }, moodDescription: 'colorful and celebratory with desert mystique' },
    narrative: { storytellingApproach: 'entrepreneurial_with_heritage', humorStyle: 'warm business humor with food references', formalityLevel: 3, emotionalTone: 'entrepreneurial, colorful, community-driven' },
  }),
  INDIA_EAST: v({
    regionCode: 'INDIA_EAST', regionName: 'East India (Bengal, Odisha, Northeast)',
    colorOverrides: ['#FFFFFF', '#DC143C', '#FFD700', '#006400'],
    lightingOverride: 'soft_bengali_monsoon_light',
    environmentStyle: 'kolkata literary café meets tea gardens, durga puja pandals, and riverside ghats',
    wardrobe: { traditional: 'dhoti-kurta with shawl, tant/jamdani saree, mekhela chador', modern: 'intellectual casual — cotton kurta, kolhapuri sandals', business: 'formal dhoti-kurta or western suit' },
    companionCreature: { name: 'Bagha', species: 'Royal Bengal Tiger Cub', description: 'Small bengal tiger with wise eyes', culturalSignificance: 'The Royal Bengal Tiger represents eastern India\'s fierce beauty' },
    culturalElements: { architecture: 'colonial kolkata, terracotta temples, durga puja pandals', vegetation: 'tea gardens, rice paddies, sundari trees, bamboo groves', patterns: 'kantha embroidery, baluchari silk weave, patachitra scroll art', symbolism: ['durga idol', 'rosogolla', 'adda conversation', 'boat on river'], avoidSymbols: ['partition trauma', 'flood disaster imagery'] },
    music: { genre: 'Rabindra Sangeet meets baul folk', instruments: ['ektara', 'dotara', 'tabla', 'flute', 'harmonium'], bpmRange: { min: 80, max: 120 }, moodDescription: 'intellectual and poetic with deep emotional undercurrent' },
    narrative: { storytellingApproach: 'literary_intellectual', humorStyle: 'cerebral and satirical', formalityLevel: 3, emotionalTone: 'intellectual, artistic, passionately cultured' },
  }),
  SOUTH_ASIA_BANGLADESH: v({
    regionCode: 'SOUTH_ASIA_BANGLADESH', regionName: 'Bangladesh',
    colorOverrides: ['#006A4E', '#F42A41', '#FFD700', '#FFFFFF'],
    lightingOverride: 'monsoon_green_diffused_light',
    environmentStyle: 'dhaka garment district meets riverine landscape with green rice paddies',
    wardrobe: { traditional: 'jamdani saree, lungi, panjabi kurta', modern: 'casual with local fabric accents', business: 'formal panjabi or western suit' },
    culturalElements: { architecture: 'louis kahn national assembly, mughal mosques, tin-roof villages', vegetation: 'rice paddies, water lily, mango trees, jute fields, mangroves', patterns: 'jamdani muslin weave, nakshi kantha embroidery, rickshaw art', symbolism: ['water lily', 'rickshaw art', 'hilsa fish', 'cricket bat'], avoidSymbols: ['flood disaster exploitation', 'garment tragedy imagery'] },
    music: { genre: 'Baul folk meets Bengali modern', instruments: ['ektara', 'dotara', 'dhol', 'flute', 'harmonium'], bpmRange: { min: 85, max: 120 }, moodDescription: 'resilient and melodic with river-flowing grace' },
    narrative: { storytellingApproach: 'resilient_poetic', humorStyle: 'gentle and community-focused', formalityLevel: 3, emotionalTone: 'resilient, poetic, hardworking' },
  }),
  SOUTH_ASIA_PAKISTAN: v({
    regionCode: 'SOUTH_ASIA_PAKISTAN', regionName: 'Pakistan',
    colorOverrides: ['#006233', '#FFFFFF', '#C4A35A', '#1C3D5A'],
    lightingOverride: 'warm_lahori_evening_glow',
    environmentStyle: 'lahore food street with mughal architecture, truck art, and bustling bazaars',
    wardrobe: { traditional: 'shalwar kameez with waistcoat, sherwani, dupatta', modern: 'western-influenced casual with shalwar kameez elements', business: 'formal shalwar kameez or western suit' },
    culturalElements: { architecture: 'mughal forts and mosques, walled city lahore, modern islamabad', vegetation: 'jasmine (motia), roses, chinar trees, apricot orchards', patterns: 'truck art style, mughal floral, sindhi ajrak, phulkari embroidery', symbolism: ['truck art', 'crescent and star', 'cricket passion', 'biryani pot'], avoidSymbols: ['terrorism stereotypes', 'india-pakistan tensions'] },
    music: { genre: 'Qawwali meets Coke Studio fusion', instruments: ['harmonium', 'tabla', 'dholak', 'rabab', 'sitar'], bpmRange: { min: 90, max: 140 }, moodDescription: 'soulful and powerful with qawwali intensity' },
    narrative: { storytellingApproach: 'poetic_passionate', humorStyle: 'warm family humor with urdu wordplay', formalityLevel: 3, emotionalTone: 'passionate, poetic, hospitable' },
  }),
  SOUTH_ASIA_SRI_LANKA: v({
    regionCode: 'SOUTH_ASIA_SRI_LANKA', regionName: 'Sri Lanka',
    colorOverrides: ['#8B0000', '#FFB300', '#006233', '#FF6B00'],
    lightingOverride: 'tropical_island_warm_glow',
    environmentStyle: 'sri lankan tea country hills with buddhist temples and ocean views',
    wardrobe: { traditional: 'sarong (sarama), osariya saree drape', modern: 'tropical casual with local batik', business: 'national dress or western suit' },
    culturalElements: { architecture: 'buddhist dagobas, colonial galle fort, kandyan architecture', vegetation: 'tea plantations, tropical rainforest, coconut palms, cinnamon trees', patterns: 'kandyan art motifs, batik prints, moonstone carvings', symbolism: ['lion symbol', 'tea leaf', 'lotus', 'mask dance'], avoidSymbols: ['civil war imagery', 'ethnic tensions'] },
    music: { genre: 'Baila meets Sinhalese pop', instruments: ['rabana drum', 'sitar', 'guitar', 'keyboard', 'percussion'], bpmRange: { min: 95, max: 130 }, moodDescription: 'warm island rhythm with Buddhist serenity' },
    narrative: { storytellingApproach: 'gentle_island_wisdom', humorStyle: 'warm and self-aware', formalityLevel: 3, emotionalTone: 'warm, spiritual, resilient' },
  }),
  OCEANIA_AUSTRALIA: v({
    regionCode: 'OCEANIA_AUSTRALIA', regionName: 'Australia',
    colorOverrides: ['#00008B', '#FFFFFF', '#FF0000', '#FFD700'],
    lightingOverride: 'harsh_outback_sun_meets_coastal_glow',
    environmentStyle: 'australian beach meets outback red desert, modern sydney skyline with indigenous art',
    wardrobe: { traditional: 'akubra hat, moleskin trousers, R.M. Williams boots', modern: 'beach casual — boardshorts, thongs, relaxed fit', business: 'smart casual, no-tie culture, open collar' },
    companionCreature: { name: 'Joey', species: 'Baby Kangaroo', description: 'Small kangaroo joey peeking from a pouch, curious and bouncy', culturalSignificance: 'The kangaroo is Australia\'s national emblem' },
    culturalElements: { architecture: 'sydney opera house, colonial verandah houses, modern glass', vegetation: 'eucalyptus, banksia, waratah, desert spinifex', patterns: 'aboriginal dot painting, indigenous line art, surf culture graphics', symbolism: ['boomerang', 'surfboard', 'harbour bridge', 'uluru silhouette'], avoidSymbols: ['stolen generation insensitivity', 'indigenous appropriation'] },
    music: { genre: 'Indie rock meets didgeridoo ambient', instruments: ['didgeridoo', 'acoustic guitar', 'drums', 'synth', 'clap sticks'], bpmRange: { min: 100, max: 130 }, moodDescription: 'laid-back confidence with ancient land energy' },
    narrative: { storytellingApproach: 'direct_no_nonsense', humorStyle: 'dry laconic humor, self-deprecating', formalityLevel: 1, emotionalTone: 'relaxed, direct, egalitarian, adventurous' },
  }),
  AFRICA_SOUTH: v({
    regionCode: 'AFRICA_SOUTH', regionName: 'South Africa',
    colorOverrides: ['#007A4D', '#FFB612', '#DE3831', '#002395'],
    lightingOverride: 'warm_cape_town_sunset',
    environmentStyle: 'cape town table mountain vista, township entrepreneurship, and modern african city',
    wardrobe: { traditional: 'madiba shirt, shweshwe dress, zulu beadwork, xhosa blanket', modern: 'trendy afro-urban fashion, local designer labels', business: 'smart casual with african fabric accents' },
    companionCreature: { name: 'Simba', species: 'Lion Cub', description: 'Young lion cub with a playful mane, courageous and proud', culturalSignificance: 'The lion represents courage, part of the Big Five' },
    culturalElements: { architecture: 'cape dutch gables, township vibrancy, modern johannesburg, ndebele painted houses', vegetation: 'protea (national flower), fynbos, jacaranda trees, vineyard rows', patterns: 'ndebele geometric, shweshwe prints, zulu beadwork, madiba motifs', symbolism: ['rainbow nation', 'protea flower', 'braai (BBQ)', 'rugby/cricket'], avoidSymbols: ['apartheid exploitation', 'crime stereotypes'] },
    music: { genre: 'Amapiano meets gqom and jazz', instruments: ['log drum', 'synth bass', 'piano', 'shaker', 'vocal chants'], bpmRange: { min: 110, max: 125 }, moodDescription: 'infectious amapiano groove with rainbow nation pride' },
    narrative: { storytellingApproach: 'ubuntu_communal', humorStyle: 'diverse multilingual humor', formalityLevel: 2, emotionalTone: 'diverse, resilient, ubuntu-spirited' },
  }),
  AFRICA_NORTH: v({
    regionCode: 'AFRICA_NORTH', regionName: 'North Africa (Morocco, Egypt, Tunisia)',
    colorOverrides: ['#C1272D', '#006233', '#FFD700', '#1E90FF'],
    lightingOverride: 'warm_medina_lantern_glow',
    environmentStyle: 'moroccan medina with zellige tiles, market spice stalls, and desert dunes beyond',
    wardrobe: { traditional: 'djellaba, kaftan, fez hat, takchita gown', modern: 'mediterranean casual with north african accents', business: 'french-influenced formal with local touches' },
    culturalElements: { architecture: 'riad courtyards, moorish arches, pyramids, blue city chefchaouen', vegetation: 'date palms, argan trees, orange groves, desert roses', patterns: 'zellige mosaic tiles, berber carpet geometric, calligraphic art', symbolism: ['hand of fatima (hamsa)', 'mint tea glass', 'tagine pot', 'desert caravan'], avoidSymbols: ['orientalist stereotypes', 'political instability'] },
    music: { genre: 'Gnawa meets rai and chaabi', instruments: ['oud', 'sintir', 'darbuka', 'bendir drum', 'ney flute'], bpmRange: { min: 90, max: 125 }, moodDescription: 'mystical and warm with desert depth' },
    narrative: { storytellingApproach: 'storytelling_through_hospitality', humorStyle: 'warm and story-based', formalityLevel: 3, emotionalTone: 'hospitable, proud, culturally rich' },
  }),
  AFRICA_CENTRAL: v({
    regionCode: 'AFRICA_CENTRAL', regionName: 'Central Africa (Congo, Cameroon)',
    colorOverrides: ['#007A4D', '#FFD700', '#CE1126', '#0033A0'],
    lightingOverride: 'lush_tropical_forest_filtered_light',
    environmentStyle: 'vibrant central african market with tropical forest backdrop, kinshasa energy, and sapeur style',
    wardrobe: { traditional: 'pagne wrapper, sapeur haute couture', modern: 'la sape — impeccable european suits with african flair', business: 'sapeur-influenced formal — immaculate suits' },
    culturalElements: { architecture: 'colonial-era buildings, tropical market stalls, modern kinshasa towers', vegetation: 'congo rainforest, tropical hardwoods, palm oil trees, banana groves', patterns: 'kuba cloth raffia weave, mangbetu geometric, pagne prints', symbolism: ['sapeur style', 'congo river', 'forest canopy', 'ndombolo dance'], avoidSymbols: ['conflict minerals imagery', 'war zone stereotypes'] },
    music: { genre: 'Congolese rumba meets ndombolo', instruments: ['likembe', 'drums', 'electric guitar', 'bass', 'brass section'], bpmRange: { min: 100, max: 135 }, moodDescription: 'irresistible congolese rumba rhythm with elegant swagger' },
    narrative: { storytellingApproach: 'communal_with_elegance', humorStyle: 'playful and dance-oriented', formalityLevel: 2, emotionalTone: 'elegant, rhythmic, communal, stylish' },
  }),
  AFRICA_HORN: v({
    regionCode: 'AFRICA_HORN', regionName: 'Horn of Africa (Ethiopia, Somalia)',
    colorOverrides: ['#009A44', '#FCDD09', '#DA121A', '#0F47AF'],
    lightingOverride: 'highland_morning_clear_light',
    environmentStyle: 'ethiopian highland with rock-hewn churches, coffee ceremony, and addis ababa modernity',
    wardrobe: { traditional: 'habesha kemis, shamma/netela shawl, gabi wrap', modern: 'casual with traditional embroidery accents', business: 'formal habesha kemis or western suit' },
    culturalElements: { architecture: 'rock-hewn lalibela churches, tukul round houses, modern addis, harar walled city', vegetation: 'coffee plants (birthplace), teff fields, eucalyptus, enset', patterns: 'ethiopian cross motifs, habesha embroidery (tilf), basket weave', symbolism: ['coffee ceremony', 'lion of judah', 'injera plate', 'ethiopian cross'], avoidSymbols: ['famine imagery', 'conflict stereotypes'] },
    music: { genre: 'Ethio-jazz meets traditional azmari', instruments: ['masinko', 'krar', 'kebero drum', 'washint flute', 'brass'], bpmRange: { min: 85, max: 120 }, moodDescription: 'soulful ethio-jazz groove with ancient highland depth' },
    narrative: { storytellingApproach: 'ancient_wisdom_modern_vision', humorStyle: 'gentle and proverb-based', formalityLevel: 3, emotionalTone: 'proud, ancient, coffee-culture warmth' },
  }),
  AFRICA_SOUTHERN: v({
    regionCode: 'AFRICA_SOUTHERN', regionName: 'Southern Africa (Zimbabwe, Mozambique, Zambia)',
    colorOverrides: ['#006400', '#FFD700', '#FF0000', '#000000'],
    lightingOverride: 'warm_savanna_afternoon',
    environmentStyle: 'victoria falls mist meets harare innovation hub and maputo coastal markets',
    wardrobe: { traditional: 'chitenge wrap, shona traditional, capulana', modern: 'casual african print with modern cuts', business: 'smart casual with african textile accents' },
    culturalElements: { architecture: 'great zimbabwe ruins, colonial buildings, thatched rondavels', vegetation: 'baobab trees, miombo woodland, mopane, flame trees', patterns: 'shona stone sculpture motifs, chitenge prints, tonga basket weave', symbolism: ['victoria falls', 'zimbabwe bird', 'copper (zambia)', 'dhow sailing'], avoidSymbols: ['political crisis stereotypes', 'hyperinflation jokes'] },
    music: { genre: 'Chimurenga meets marrabenta and kalindula', instruments: ['mbira', 'hosho shakers', 'guitar', 'drums', 'marimba'], bpmRange: { min: 95, max: 125 }, moodDescription: 'grounding mbira tones with rhythmic energy' },
    narrative: { storytellingApproach: 'heritage_resilience', humorStyle: 'warm communal humor', formalityLevel: 2, emotionalTone: 'resilient, heritage-proud, communal' },
  }),
  MENA_LEVANT: v({
    regionCode: 'MENA_LEVANT', regionName: 'Levant (Lebanon, Jordan)',
    colorOverrides: ['#C8102E', '#FFFFFF', '#006233', '#C4A35A'],
    lightingOverride: 'warm_mediterranean_levantine_glow',
    environmentStyle: 'beirut café culture meets amman ancient ruins, cedar mountains and modern startups',
    wardrobe: { traditional: 'lebanese kaftan, jordanian hatta, embroidered thobe', modern: 'french-influenced chic mediterranean fashion', business: 'european-style formal with levantine elegance' },
    culturalElements: { architecture: 'roman ruins, crusader castles, ottoman houses, beirut art deco', vegetation: 'cedar trees, olive groves, grape vines, jasmine', patterns: 'phoenician motifs, levantine embroidery, petra carvings', symbolism: ['cedar tree', 'olive branch', 'mezze spread', 'café culture'], avoidSymbols: ['conflict imagery', 'sectarian references'] },
    music: { genre: 'Arabic pop meets traditional dabke', instruments: ['oud', 'buzuq', 'tablah', 'ney', 'keyboard'], bpmRange: { min: 100, max: 140 }, moodDescription: 'sophisticated and warm with dabke energy' },
    narrative: { storytellingApproach: 'cosmopolitan_cultural', humorStyle: 'sharp and sophisticated', formalityLevel: 3, emotionalTone: 'sophisticated, resilient, cosmopolitan' },
  }),
  MENA_IRAN: v({
    regionCode: 'MENA_IRAN', regionName: 'Iran (Persia)',
    colorOverrides: ['#239F40', '#FFFFFF', '#DA0000', '#1E3F66'],
    lightingOverride: 'persian_garden_golden_light',
    environmentStyle: 'persian garden with intricate tilework, bazaar alleys, and isfahan bridges at sunset',
    wardrobe: { traditional: 'chador, aba cloak, regional tribal dress', modern: 'modest fashion-forward with persian design elements', business: 'formal suit (men), modest professional with design flair (women)' },
    culturalElements: { architecture: 'persian tile mosques, bazaar vaulted ceilings, persepolis columns, windcatchers', vegetation: 'persian roses, pomegranate trees, saffron fields, pistachio groves', patterns: 'persian miniature art, islamic tilework, paisley (boteh), carpet medallion', symbolism: ['nowruz haft-sin table', 'persian carpet', 'saffron threads', 'nightingale and rose'], avoidSymbols: ['political regime imagery', 'sanctions references'] },
    music: { genre: 'Persian classical meets modern pop', instruments: ['tar', 'setar', 'santur', 'tombak', 'ney'], bpmRange: { min: 80, max: 120 }, moodDescription: 'poetic and refined with deep emotional resonance' },
    narrative: { storytellingApproach: 'poetic_philosophical', humorStyle: 'subtle intellectual with literary references', formalityLevel: 4, emotionalTone: 'poetic, intellectually rich, hospitable' },
  }),
};

// ─── Lookup Functions ───────────────────────────────────────────────────────

export function getExpandedRegionalVariant(regionCode: string): RegionalStyleVariant | undefined {
  return REGIONAL_EXPANSION[regionCode];
}

export function getAllExpandedRegionCodes(): string[] {
  return Object.keys(REGIONAL_EXPANSION);
}

export function searchExpandedRegions(query: string): RegionalStyleVariant[] {
  const lower = query.toLowerCase();
  return Object.values(REGIONAL_EXPANSION).filter(
    v => v.regionName.toLowerCase().includes(lower) || v.regionCode.toLowerCase().includes(lower)
  );
}
