
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { 
  Component, 
  Layers, 
  Settings, 
  Eye, 
  CheckCircle, 
  AlertTriangle,
  Clock
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { moduleRegistry } from '@/utils/moduleRegistry';

export const ModulesOverviewCard: React.FC = () => {
  const navigate = useNavigate();
  const registryStats = moduleRegistry.getStats();
  const allModules = moduleRegistry.getAll();
  const recentModules = allModules
    .sort((a, b) => new Date(b.lastUpdated).getTime() - new Date(a.lastUpdated).getTime())
    .slice(0, 3);

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'active': return <CheckCircle className="h-4 w-4 text-green-500" />;
      case 'development': return <Clock className="h-4 w-4 text-yellow-500" />;
      case 'deprecated': return <AlertTriangle className="h-4 w-4 text-red-500" />;
      default: return <Component className="h-4 w-4 text-gray-500" />;
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center justify-between">
          <div className="flex items-center">
            <Layers className="h-5 w-5 mr-2" />
            System Modules Overview
          </div>
          <Button 
            variant="outline" 
            size="sm"
            onClick={() => navigate('/modules')}
          >
            <Eye className="h-4 w-4 mr-2" />
            View All
          </Button>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-6">
          {/* Module Statistics */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="text-center">
              <div className="text-2xl font-bold text-blue-600">{registryStats.total}</div>
              <div className="text-sm text-muted-foreground">Total Modules</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-green-600">{registryStats.active}</div>
              <div className="text-sm text-muted-foreground">Active</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-yellow-600">{registryStats.development}</div>
              <div className="text-sm text-muted-foreground">In Development</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-purple-600">{registryStats.autoGenerated}</div>
              <div className="text-sm text-muted-foreground">Auto-Generated</div>
            </div>
          </div>

          {/* Recent Modules */}
          <div>
            <h4 className="font-medium mb-3 flex items-center">
              <Clock className="h-4 w-4 mr-2" />
              Recently Updated Modules
            </h4>
            <div className="space-y-2">
              {recentModules.length > 0 ? (
                recentModules.map((module) => (
                  <div key={module.moduleName} className="flex items-center justify-between p-2 border rounded">
                    <div className="flex items-center space-x-3">
                      {getStatusIcon(module.status)}
                      <div>
                        <div className="font-medium">{module.moduleName}</div>
                        <div className="text-sm text-muted-foreground">
                          Table: {module.tableName}
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Badge variant={module.status === 'active' ? 'default' : 'secondary'}>
                        {module.status}
                      </Badge>
                      <div className="text-xs text-muted-foreground">
                        {new Date(module.lastUpdated).toLocaleDateString()}
                      </div>
                    </div>
                  </div>
                ))
              ) : (
                <div className="text-center py-4 text-muted-foreground">
                  No modules registered yet
                </div>
              )}
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};
