
/**
 * Module Detection Utilities - Fixed Implementation
 */

import { supabase } from '@/integrations/supabase/client';
import { moduleRegistry } from '../moduleRegistry';
import { SchemaAnalysis, analyzeTable, calculateConfidence } from './schemaAnalyzer';
import { AutoModuleConfig } from './types';

/**
 * Get all table names from the database using a safer approach
 */
const getAllTableNames = async (): Promise<string[]> => {
  try {
    console.log('🔍 Fetching table names from database...');
    
    // Get the known table names from our existing tables
    const knownTables = [
      'profiles', 'facilities', 'modules', 'permissions', 'roles',
      'user_roles', 'user_permissions', 'user_facility_access',
      'user_module_assignments', 'role_permissions', 'role_module_assignments',
      'module_permissions', 'audit_logs', 'api_keys', 'api_usage_logs',
      'api_integration_registry', 'external_api_registry', 
      'external_api_endpoints', 'api_consumption_logs'
    ];

    // Try to verify which tables actually exist by making simple queries
    const existingTables: string[] = [];
    
    for (const tableName of knownTables) {
      try {
        const { error } = await supabase
          .from(tableName as any)
          .select('*')
          .limit(1);
        
        if (!error) {
          existingTables.push(tableName);
        }
      } catch (e) {
        // Table doesn't exist or isn't accessible
        console.log(`Table ${tableName} not accessible`);
      }
    }
    
    console.log(`📊 Found ${existingTables.length} accessible tables:`, existingTables);
    return existingTables;
    
  } catch (error) {
    console.error('Failed to fetch table names:', error);
    return [];
  }
};

/**
 * Scans the database schema and returns analysis for accessible tables
 */
export const scanDatabaseSchema = async (): Promise<SchemaAnalysis[]> => {
  console.log('🔍 Scanning database schema...');
  
  try {
    const tableNames = await getAllTableNames();
    const analyses: SchemaAnalysis[] = [];
    
    for (const tableName of tableNames) {
      // Skip system/auth tables and some complex API tables
      if (tableName.startsWith('_') || 
          tableName.includes('auth') || 
          tableName.includes('storage') ||
          tableName.includes('supabase') ||
          tableName === 'audit_logs' || // Skip audit logs as they're system tables
          tableName.includes('api_consumption') ||
          tableName.includes('api_usage')) {
        continue;
      }

      const analysis = await analyzeTable(tableName);
      if (analysis) {
        analyses.push(analysis);
      }
    }
    
    console.log(`📊 Successfully analyzed ${analyses.length} tables`);
    return analyses;
    
  } catch (error) {
    console.error('❌ Schema scanning failed:', error);
    return [];
  }
};

/**
 * Auto-detects modules that need component registration or are completely new
 */
export const detectNewModules = async (): Promise<AutoModuleConfig[]> => {
  console.log('🔍 Detecting modules from database...');
  
  const analyses = await scanDatabaseSchema();
  const existingModules = moduleRegistry.getAll();
  
  const modulesToRegister: AutoModuleConfig[] = [];

  for (const analysis of analyses) {
    // Check if module exists in registry
    const existingModule = existingModules.find(m => 
      m.tableName === analysis.tableName || 
      m.moduleName === analysis.suggestedModuleName
    );

    // If module doesn't exist at all, or exists but has no components
    const needsRegistration = !existingModule || 
      (!existingModule.components?.length && 
       !existingModule.services?.length && 
       !existingModule.hooks?.length);

    if (needsRegistration) {
      // Calculate confidence score
      const confidence = calculateConfidence(analysis);

      // Generate suggested custom columns
      const suggestedCustomColumns = generateCustomColumns(analysis);

      const autoConfig: AutoModuleConfig = {
        tableName: analysis.tableName,
        moduleName: analysis.suggestedModuleName,
        requiredFields: analysis.suggestedRequiredFields,
        optionalFields: analysis.suggestedOptionalFields,
        isAutoGenerated: true,
        confidence,
        suggestedCustomColumns
      };

      modulesToRegister.push(autoConfig);
      console.log(`📝 Module ${autoConfig.moduleName} needs registration (confidence: ${Math.round(confidence * 100)}%)`);
    }
  }

  console.log(`✅ Detected ${modulesToRegister.length} modules for registration`);
  return modulesToRegister;
};

/**
 * Generates suggested custom columns based on table structure
 */
const generateCustomColumns = (analysis: SchemaAnalysis) => {
  const columns = [];

  // Add name column if exists
  if (analysis.columns.some(col => col.name === 'name' || col.name === 'title')) {
    columns.push({
      key: 'name',
      header: 'Name',
      type: 'text' as const
    });
  }

  // Add status column if exists
  if (analysis.hasStatus) {
    columns.push({
      key: 'status',
      header: 'Status',
      type: 'status' as const
    });
  }

  // Add created_at if exists
  if (analysis.hasCreatedAt) {
    columns.push({
      key: 'created_at',
      header: 'Created',
      type: 'date' as const
    });
  }

  return columns;
};
