
/**
 * Schema and Module Types
 */

export interface AutoModuleConfig {
  tableName: string;
  moduleName: string;
  requiredFields: string[];
  optionalFields: string[];
  isAutoGenerated: boolean;
  confidence: number;
  suggestedCustomColumns?: Array<{
    key: string;
    header: string;
    type: 'text' | 'status' | 'date';
  }>;
}

export interface AutoRegistrationConfig {
  enabled: boolean;
  confidenceThreshold: number;
  scanIntervalMs: number;
  autoGenerateCode: boolean;
  trackComponents: boolean;
  trackServices: boolean;
}
