
/**
 * Type definitions for schema scanning and module generation
 */

import { ModuleConfig } from '../moduleValidation';

export interface AutoModuleConfig extends ModuleConfig {
  isAutoGenerated: boolean;
  confidence: number; // 0-1 confidence score
  suggestedCustomColumns?: Array<{
    key: string;
    header: string;
    type: 'text' | 'status' | 'date' | 'boolean';
  }>;
}

export interface AutoRegistrationConfig {
  enabled: boolean;
  confidenceThreshold: number;
  scanIntervalMs: number;
  autoGenerateCode: boolean;
}
