/**
 * Content Moderation Service
 * Centralized service for content safety checks
 * Used across Genie Studio for text, images, and file uploads
 */

// Blocked words and patterns for adult/inappropriate content
const BLOCKED_PATTERNS = [
  /\b(nsfw|xxx|porn|explicit|adult\s*content|nude|naked|sex(ual)?|erotic)\b/i,
  /\b(gore|violent|murder|kill|weapon|drug|cocaine|heroin)\b/i,
  /\b(hate|racist|slur|discriminat|harass)\b/i,
];

// Sensitive topics that require extra caution
const SENSITIVE_TOPICS = [
  /\b(medical|health|diagnosis|treatment|prescription)\b/i,
  /\b(legal|lawyer|court|sue|lawsuit)\b/i,
  /\b(financial|investment|stock|trading)\b/i,
];

export interface ContentModerationResult {
  isAllowed: boolean;
  hasViolations: boolean;
  violations: string[];
  warnings: string[];
  sensitiveTopics: string[];
  safetyScore: number; // 0-100, 100 = completely safe
}

/**
 * Check text content for policy violations
 */
export function moderateTextContent(text: string): ContentModerationResult {
  const violations: string[] = [];
  const warnings: string[] = [];
  const sensitiveTopics: string[] = [];
  let safetyScore = 100;

  const lowerText = text.toLowerCase();

  // Check for blocked patterns
  for (const pattern of BLOCKED_PATTERNS) {
    if (pattern.test(lowerText)) {
      violations.push(`Prohibited content detected: ${pattern.source.replace(/[\\|()]/g, '')}`);
      safetyScore -= 50;
    }
  }

  // Check for sensitive topics
  for (const pattern of SENSITIVE_TOPICS) {
    if (pattern.test(lowerText)) {
      const topic = pattern.source.replace(/[\\|()]/g, '').replace('\\b', '');
      sensitiveTopics.push(topic);
      warnings.push(`Sensitive topic detected: ${topic} - Verify information with professionals`);
      safetyScore -= 5;
    }
  }

  // Additional safety checks
  if (text.length > 50000) {
    warnings.push('Very long content - may take longer to process');
  }

  return {
    isAllowed: violations.length === 0,
    hasViolations: violations.length > 0,
    violations,
    warnings,
    sensitiveTopics,
    safetyScore: Math.max(0, safetyScore),
  };
}

/**
 * Check file for allowed types and size
 */
export function moderateFileUpload(file: File): ContentModerationResult {
  const violations: string[] = [];
  const warnings: string[] = [];
  const sensitiveTopics: string[] = [];
  let safetyScore = 100;

  // Allowed file types
  const allowedImageTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp'];
  const allowedVideoTypes = ['video/mp4', 'video/webm', 'video/quicktime'];
  const allowedAudioTypes = ['audio/mpeg', 'audio/wav', 'audio/mp3', 'audio/ogg', 'audio/webm'];
  const allowedDocTypes = [
    'application/pdf',
    'text/plain',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ];

  const allAllowedTypes = [...allowedImageTypes, ...allowedVideoTypes, ...allowedAudioTypes, ...allowedDocTypes];

  if (!allAllowedTypes.includes(file.type)) {
    violations.push(`File type not allowed: ${file.type}`);
    safetyScore -= 100;
  }

  // Max file size: 50MB
  const maxSize = 50 * 1024 * 1024;
  if (file.size > maxSize) {
    violations.push(`File too large: ${(file.size / 1024 / 1024).toFixed(1)}MB (max 50MB)`);
    safetyScore -= 50;
  }

  // Check filename for suspicious content
  const filename = file.name.toLowerCase();
  for (const pattern of BLOCKED_PATTERNS) {
    if (pattern.test(filename)) {
      violations.push('Filename contains prohibited content');
      safetyScore -= 50;
    }
  }

  return {
    isAllowed: violations.length === 0,
    hasViolations: violations.length > 0,
    violations,
    warnings,
    sensitiveTopics,
    safetyScore: Math.max(0, safetyScore),
  };
}

/**
 * Check image generation prompt for policy violations
 */
export function moderateImagePrompt(prompt: string): ContentModerationResult {
  const result = moderateTextContent(prompt);
  
  // Additional image-specific checks
  const imageBlockedPatterns = [
    /\b(realistic\s*(photo|image)\s*of\s*(child|minor|kid))\b/i,
    /\b(deep\s*fake|fake\s*celebrity)\b/i,
    /\b(blood|gore|injury|wound)\b/i,
  ];

  for (const pattern of imageBlockedPatterns) {
    if (pattern.test(prompt.toLowerCase())) {
      result.violations.push('Image prompt contains prohibited content');
      result.hasViolations = true;
      result.isAllowed = false;
      result.safetyScore = Math.max(0, result.safetyScore - 50);
    }
  }

  return result;
}

/**
 * Get content disclaimer text
 */
export function getContentDisclaimer(): string {
  return `
⚠️ AI-GENERATED CONTENT DISCLAIMER ⚠️

This content has been generated by artificial intelligence (AI) through Genie Suite.

IMPORTANT NOTICES:
• This is purely AI-generated content and may contain inaccuracies
• Please verify all information before publishing or using
• We are not responsible for the accuracy or appropriateness of AI outputs
• Adult, explicit, or inappropriate content is strictly prohibited
• Content moderation is applied but may not catch all violations

By using this content, you acknowledge that:
1. You will verify the information independently
2. You take full responsibility for how you use this content
3. You will not use this content for harmful or illegal purposes

For questions or concerns, please contact our support team.
  `.trim();
}

/**
 * Get safety level label
 */
export function getSafetyLabel(score: number): { label: string; color: string } {
  if (score >= 90) return { label: 'Safe', color: 'text-green-600' };
  if (score >= 70) return { label: 'Caution', color: 'text-yellow-600' };
  if (score >= 50) return { label: 'Warning', color: 'text-orange-600' };
  return { label: 'Blocked', color: 'text-red-600' };
}
