/**
 * Content Safety Banner Component
 * Displays AI-generated content disclaimers and privacy terms
 * Used across all Genie Studio components for safeguarding protection
 */

import React from 'react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { 
  AlertTriangle, 
  Shield, 
  Info,
  Eye,
  Lock,
  CheckCircle
} from 'lucide-react';
import { cn } from '@/lib/utils';

interface ContentSafetyBannerProps {
  variant?: 'full' | 'compact' | 'minimal';
  showPrivacy?: boolean;
  showDisclaimer?: boolean;
  showContentPolicy?: boolean;
  className?: string;
}

export function ContentSafetyBanner({
  variant = 'compact',
  showPrivacy = true,
  showDisclaimer = true,
  showContentPolicy = true,
  className,
}: ContentSafetyBannerProps) {
  if (variant === 'minimal') {
    return (
      <div className={cn("flex items-center gap-2 text-xs text-muted-foreground", className)}>
        <Shield className="h-3 w-3" />
        <span>AI-generated content • Verify before use • No adult content permitted</span>
      </div>
    );
  }

  if (variant === 'compact') {
    return (
      <Alert className={cn("bg-muted/50 border-border/50", className)}>
        <Shield className="h-4 w-4" />
        <AlertDescription className="text-xs">
          <span className="font-medium">AI-Generated Content Notice:</span> All content is purely AI-generated. 
          Adult/inappropriate content is strictly prohibited. Verify all generated content before use. 
          We are not responsible for AI-generated outputs.
        </AlertDescription>
      </Alert>
    );
  }

  // Full variant
  return (
    <div className={cn("space-y-3", className)}>
      {showDisclaimer && (
        <Alert className="bg-amber-50 border-amber-200 dark:bg-amber-950/20 dark:border-amber-800">
          <AlertTriangle className="h-4 w-4 text-amber-600 dark:text-amber-400" />
          <AlertTitle className="text-amber-800 dark:text-amber-200 text-sm">AI-Generated Content Disclaimer</AlertTitle>
          <AlertDescription className="text-amber-700 dark:text-amber-300 text-xs space-y-1">
            <p>• All content generated through Genie Studio is <strong>purely AI-generated</strong></p>
            <p>• Please <strong>verify and review</strong> all generated content before publishing or using</p>
            <p>• We are <strong>not responsible</strong> for the accuracy, completeness, or appropriateness of AI-generated content</p>
            <p>• AI outputs may contain errors, biases, or inaccuracies - always fact-check important information</p>
          </AlertDescription>
        </Alert>
      )}

      {showContentPolicy && (
        <Alert className="bg-red-50 border-red-200 dark:bg-red-950/20 dark:border-red-800">
          <Eye className="h-4 w-4 text-red-600 dark:text-red-400" />
          <AlertTitle className="text-red-800 dark:text-red-200 text-sm">Content Policy</AlertTitle>
          <AlertDescription className="text-red-700 dark:text-red-300 text-xs space-y-1">
            <p>• <strong>Adult content is strictly prohibited</strong> - No NSFW, explicit, or inappropriate content</p>
            <p>• No violent, harmful, or dangerous content generation or uploads</p>
            <p>• No content that violates intellectual property rights</p>
            <p>• Content moderation is applied to all generations and uploads</p>
            <p>• Violations may result in account suspension or termination</p>
          </AlertDescription>
        </Alert>
      )}

      {showPrivacy && (
        <Alert className="bg-blue-50 border-blue-200 dark:bg-blue-950/20 dark:border-blue-800">
          <Lock className="h-4 w-4 text-blue-600 dark:text-blue-400" />
          <AlertTitle className="text-blue-800 dark:text-blue-200 text-sm">Privacy & Data Terms</AlertTitle>
          <AlertDescription className="text-blue-700 dark:text-blue-300 text-xs space-y-1">
            <p>• Your content may be processed by third-party AI providers</p>
            <p>• Do not upload sensitive, confidential, or personally identifiable information</p>
            <p>• All data is processed in accordance with our privacy policy</p>
            <p>• Generated content may be logged for quality improvement purposes</p>
          </AlertDescription>
        </Alert>
      )}
    </div>
  );
}

/**
 * Inline safety notice for individual generation areas
 */
export function InlineContentNotice({ className }: { className?: string }) {
  return (
    <div className={cn(
      "flex items-start gap-2 p-2 rounded-md bg-muted/30 text-xs text-muted-foreground",
      className
    )}>
      <Info className="h-3.5 w-3.5 mt-0.5 flex-shrink-0" />
      <div className="space-y-0.5">
        <p className="font-medium">Content generated by AI</p>
        <p>Verify accuracy before use. No adult/inappropriate content permitted.</p>
      </div>
    </div>
  );
}

/**
 * Upload safety notice for file uploads
 */
export function UploadSafetyNotice({ className }: { className?: string }) {
  return (
    <div className={cn(
      "flex items-center gap-2 text-xs text-muted-foreground border-t pt-2",
      className
    )}>
      <CheckCircle className="h-3 w-3 text-green-600" />
      <span>Content moderation applied • No adult/explicit content • Max 50MB</span>
    </div>
  );
}
