import { Node, Edge, MarkerType } from '@xyflow/react';
import { EnhancedNodeData } from './EnhancedWorkflowNode';

export interface ConnectionRule {
  from: string;
  to: string;
  condition?: (fromNode: Node, toNode: Node) => boolean;
  edgeStyle?: any;
  label?: string;
  type: 'sequential' | 'conditional' | 'parallel' | 'fallback';
}

export class AutoConnectEngine {
  private connectionRules: ConnectionRule[] = [];
  
  constructor() {
    this.initializeDefaultRules();
  }

  private initializeDefaultRules() {
    // Healthcare workflow connection rules
    this.connectionRules = [
      // Sequential flow rules
      {
        from: 'customer',
        to: 'touchpoint',
        type: 'sequential',
        edgeStyle: { stroke: '#8b5cf6', strokeWidth: 2 },
        label: 'initiates'
      },
      {
        from: 'touchpoint',
        to: 'decision',
        type: 'sequential',
        edgeStyle: { stroke: '#f59e0b', strokeWidth: 2 },
        label: 'routes to'
      },
      {
        from: 'touchpoint',
        to: 'agent',
        type: 'sequential',
        edgeStyle: { stroke: '#10b981', strokeWidth: 2 },
        label: 'forwards to'
      },
      {
        from: 'decision',
        to: 'agent',
        type: 'conditional',
        edgeStyle: { stroke: '#ef4444', strokeWidth: 2, strokeDasharray: '5,5' },
        label: 'when condition met'
      },
      {
        from: 'decision',
        to: 'touchpoint',
        type: 'conditional',
        edgeStyle: { stroke: '#f59e0b', strokeWidth: 2, strokeDasharray: '5,5' },
        label: 'alternative path'
      },
      {
        from: 'agent',
        to: 'action',
        type: 'sequential',
        edgeStyle: { stroke: '#8b5cf6', strokeWidth: 2 },
        label: 'triggers'
      },
      
      // Parallel processing rules
      {
        from: 'agent',
        to: 'agent',
        type: 'parallel',
        condition: (from, to) => from.id !== to.id,
        edgeStyle: { stroke: '#06b6d4', strokeWidth: 2 },
        label: 'parallel process'
      }
    ];
  }

  // Auto-suggest connections for a new node
  suggestConnections(
    newNode: Node<EnhancedNodeData>, 
    existingNodes: Node<EnhancedNodeData>[],
    existingEdges: Edge[]
  ): { suggestedEdges: Edge[]; confidence: number }[] {
    const suggestions: { suggestedEdges: Edge[]; confidence: number }[] = [];
    
    // Find applicable rules for this node type
    const applicableRules = this.connectionRules.filter(rule => 
      rule.to === newNode.data.type || rule.from === newNode.data.type
    );

    existingNodes.forEach(existingNode => {
      applicableRules.forEach(rule => {
        let shouldConnect = false;
        let sourceNode: Node, targetNode: Node;
        let confidence = 0.7;

        // Determine connection direction
        if (rule.from === existingNode.data.type && rule.to === newNode.data.type) {
          sourceNode = existingNode;
          targetNode = newNode;
          shouldConnect = true;
          confidence = 0.8; // Higher confidence for forward connections
        } else if (rule.from === newNode.data.type && rule.to === existingNode.data.type) {
          sourceNode = newNode;
          targetNode = existingNode;
          shouldConnect = true;
          confidence = 0.6; // Lower confidence for backward connections
        }

        if (shouldConnect && !this.connectionExists(sourceNode!.id, targetNode!.id, existingEdges)) {
          // Apply additional condition checks
          if (rule.condition && !rule.condition(sourceNode!, targetNode!)) {
            return;
          }

          // Create suggested edge
          const edgeId = `auto-${sourceNode!.id}-${targetNode!.id}`;
          const suggestedEdge: Edge = {
            id: edgeId,
            source: sourceNode!.id,
            target: targetNode!.id,
            type: 'smoothstep',
            markerEnd: { type: MarkerType.ArrowClosed },
            style: rule.edgeStyle,
            label: rule.label,
            data: {
              connectionType: rule.type,
              autoGenerated: true,
              confidence: confidence
            }
          };

          // Add connector-specific connections if available
          const additionalEdges = this.generateConnectorSpecificEdges(
            sourceNode! as Node<EnhancedNodeData>, 
            targetNode! as Node<EnhancedNodeData>, 
            rule
          );

          suggestions.push({
            suggestedEdges: [suggestedEdge, ...additionalEdges],
            confidence: confidence
          });
        }
      });
    });

    // Sort by confidence and remove duplicates
    return suggestions
      .sort((a, b) => b.confidence - a.confidence)
      .slice(0, 5); // Limit to top 5 suggestions
  }

  private generateConnectorSpecificEdges(
    sourceNode: Node<EnhancedNodeData>,
    targetNode: Node<EnhancedNodeData>,
    rule: ConnectionRule
  ): Edge[] {
    const additionalEdges: Edge[] = [];

    // If nodes have specific connectors, create targeted connections
    if (sourceNode.data.connectors && targetNode.data.connectors) {
      const sourceOutputs = sourceNode.data.connectors.filter(c => c.type === 'output');
      const targetInputs = targetNode.data.connectors.filter(c => c.type === 'input');

      // Smart connector matching
      sourceOutputs.forEach(output => {
        const matchingInput = targetInputs.find(input => 
          this.connectorsAreCompatible(output, input)
        );

        if (matchingInput) {
          const connectorEdgeId = `connector-${sourceNode.id}-${output.id}-${targetNode.id}-${matchingInput.id}`;
          additionalEdges.push({
            id: connectorEdgeId,
            source: sourceNode.id,
            target: targetNode.id,
            sourceHandle: output.id,
            targetHandle: matchingInput.id,
            type: 'smoothstep',
            style: { 
              ...rule.edgeStyle, 
              strokeWidth: 1,
              stroke: output.dataType === matchingInput.dataType ? '#10b981' : '#6b7280'
            },
            data: {
              connectorConnection: true,
              sourceConnector: output,
              targetConnector: matchingInput
            }
          });
        }
      });
    }

    return additionalEdges;
  }

  private connectorsAreCompatible(
    output: EnhancedNodeData['connectors'][0], 
    input: EnhancedNodeData['connectors'][0]
  ): boolean {
    // Basic compatibility check
    if (output.dataType && input.dataType) {
      return output.dataType === input.dataType || 
             input.dataType === 'any' || 
             output.dataType === 'any';
    }

    // Label-based matching
    const outputKeywords = output.label.toLowerCase().split(/[\s_]/);
    const inputKeywords = input.label.toLowerCase().split(/[\s_]/);
    
    return outputKeywords.some(keyword => 
      inputKeywords.includes(keyword) || 
      this.areSemanticallySimilar(keyword, inputKeywords)
    );
  }

  private areSemanticallySimilar(keyword: string, keywords: string[]): boolean {
    const semanticMap: Record<string, string[]> = {
      'data': ['input', 'information', 'content'],
      'result': ['output', 'response', 'outcome'],
      'error': ['failure', 'exception', 'problem'],
      'success': ['completion', 'done', 'finished']
    };

    return keywords.some(k => 
      semanticMap[keyword]?.includes(k) || 
      semanticMap[k]?.includes(keyword)
    );
  }

  private connectionExists(sourceId: string, targetId: string, edges: Edge[]): boolean {
    return edges.some(edge => 
      edge.source === sourceId && edge.target === targetId
    );
  }

  // Auto-connect based on prompt
  suggestConnectionsFromPrompt(
    prompt: string, 
    nodes: Node<EnhancedNodeData>[]
  ): Edge[] {
    const suggestions: Edge[] = [];
    const words = prompt.toLowerCase().split(/\s+/);

    // Extract connection intent from prompt
    const connectionKeywords = {
      sequential: ['then', 'next', 'after', 'followed by', 'leads to'],
      conditional: ['if', 'when', 'depending on', 'based on', 'in case'],
      parallel: ['simultaneously', 'at the same time', 'parallel', 'concurrent'],
      fallback: ['otherwise', 'else', 'alternative', 'fallback', 'backup']
    };

    // Find node references in prompt
    const nodeReferences = nodes.filter(node => 
      words.some(word => 
        node.data.label.toLowerCase().includes(word) ||
        word.includes(node.data.label.toLowerCase().split(/\s+/)[0])
      )
    );

    if (nodeReferences.length >= 2) {
      // Determine connection type from prompt
      let connectionType: 'sequential' | 'conditional' | 'parallel' | 'fallback' = 'sequential';
      
      for (const [type, keywords] of Object.entries(connectionKeywords)) {
        if (keywords.some(keyword => prompt.toLowerCase().includes(keyword))) {
          connectionType = type as any;
          break;
        }
      }

      // Create connections between referenced nodes
      for (let i = 0; i < nodeReferences.length - 1; i++) {
        const sourceNode = nodeReferences[i];
        const targetNode = nodeReferences[i + 1];
        
        const rule = this.connectionRules.find(r => 
          r.from === sourceNode.data.type && 
          r.to === targetNode.data.type &&
          r.type === connectionType
        );

        if (rule) {
          suggestions.push({
            id: `prompt-${sourceNode.id}-${targetNode.id}`,
            source: sourceNode.id,
            target: targetNode.id,
            type: 'smoothstep',
            markerEnd: { type: MarkerType.ArrowClosed },
            style: rule.edgeStyle,
            label: `${rule.label} (from prompt)`,
            data: {
              connectionType: rule.type,
              promptGenerated: true,
              confidence: 0.9
            }
          });
        }
      }
    }

    return suggestions;
  }

  // Add custom rule
  addConnectionRule(rule: ConnectionRule) {
    this.connectionRules.push(rule);
  }

  // Get all rules
  getConnectionRules(): ConnectionRule[] {
    return [...this.connectionRules];
  }
}

// Export singleton instance
export const autoConnectEngine = new AutoConnectEngine();