import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import "https://deno.land/x/xhr@0.1.0/mod.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const GOOGLE_API_KEY = Deno.env.get('GOOGLE_API_KEY');
    if (!GOOGLE_API_KEY) {
      throw new Error('GOOGLE_API_KEY is not set');
    }

    const body = await req.json();
    const { prompt, aspectRatio = '1:1', style = 'photographic', safety = 'moderate' } = body;

    if (!prompt) {
      return new Response(
        JSON.stringify({ error: 'Prompt is required' }), 
        { 
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      );
    }

    console.log('🎨 Generating image with Gemini API:', { prompt, aspectRatio, style });

    // Enhanced prompt for better image generation
    const enhancedPrompt = `Create a ${style} style image: ${prompt}. ${aspectRatio} aspect ratio. High quality, detailed, professional.`;

    const startTime = Date.now();

    // Use Google's Gemini API for image generation
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:generateImage?key=${GOOGLE_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: enhancedPrompt,
        config: {
          aspectRatio: aspectRatio,
          safetyFilterLevel: safety.toUpperCase(),
          personGeneration: 'ALLOW_ADULT',
          includeRaiInfo: false
        }
      }),
    });

    const data = await response.json();
    console.log('🔍 Gemini API response:', { status: response.status, hasImage: !!data.generatedImages });

    if (!response.ok) {
      console.error('❌ Gemini API error:', data);
      throw new Error(data.error?.message || `Gemini API error: ${response.status}`);
    }

    if (!data.generatedImages || data.generatedImages.length === 0) {
      throw new Error('No images generated by Gemini API');
    }

    const imageBase64 = data.generatedImages[0].imageBytes;
    const imageUrl = `data:image/png;base64,${imageBase64}`;
    
    const processingTime = Date.now() - startTime;

    console.log('✅ Image generated successfully in', processingTime, 'ms');

    return new Response(JSON.stringify({ 
      success: true,
      imageUrl,
      mediaUrl: imageUrl,
      processingTime,
      metadata: {
        prompt,
        aspectRatio,
        style,
        safety,
        model: 'imagen-3.0-generate-001',
        timestamp: new Date().toISOString()
      }
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('💥 Error in gemini-generate-image function:', error);
    return new Response(JSON.stringify({ 
      success: false,
      error: error.message || 'Unknown error occurred',
      timestamp: new Date().toISOString()
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});