-- Populate workflow libraries with comprehensive data
INSERT INTO public.workflow_libraries (name, description, version, category, author, tags, documentation_url, rating, downloads, is_installed, is_core, configuration, dependencies, examples) VALUES
('Healthcare Utilities', 'Essential utilities for healthcare workflow automation', '2.1.0', 'healthcare', 'HealthTech Inc', ARRAY['healthcare', 'validation', 'conversion'], 'https://docs.healthtech.com', 4.8, 12500, true, true, '{"apis": ["fhir", "hl7"], "compliance": ["hipaa", "gdpr"]}', ARRAY['crypto-js', 'moment'], '[{"name": "Patient ID Validation", "code": "validatePatientId(id)"}]'),
('AI Model Connectors', 'Connect to various AI models and services', '1.5.2', 'ai', 'AI Solutions', ARRAY['ai', 'llm', 'integration'], 'https://docs.ai-solutions.com', 4.6, 8900, false, false, '{"models": ["gpt-4", "claude-3", "gemini"], "providers": ["openai", "anthropic", "google"]}', ARRAY['axios', 'jsonwebtoken'], '[{"name": "GPT-4 Integration", "code": "callGPT4(prompt, options)"}]'),
('Data Transformation Suite', 'Comprehensive data transformation and validation tools', '3.0.1', 'data', 'DataFlow Corp', ARRAY['data', 'etl', 'validation'], 'https://docs.dataflow.com', 4.9, 15600, true, false, '{"formats": ["json", "xml", "csv"], "validations": ["schema", "business_rules"]}', ARRAY['lodash', 'joi'], '[{"name": "JSON to XML Transform", "code": "jsonToXml(data)"}]'),
('Security & Encryption Library', 'Advanced security and encryption utilities', '1.8.3', 'security', 'SecureFlow Ltd', ARRAY['security', 'encryption', 'auth'], 'https://docs.secureflow.com', 4.7, 7200, false, false, '{"algorithms": ["aes", "rsa"], "protocols": ["oauth2", "jwt"]}', ARRAY['crypto-js', 'bcrypt'], '[{"name": "AES Encryption", "code": "encryptAES(data, key)"}]'),
('API Gateway Library', 'RESTful API management and routing', '2.3.0', 'api', 'API Masters', ARRAY['api', 'rest', 'gateway'], 'https://docs.apimasters.com', 4.5, 9800, true, false, '{"protocols": ["rest", "graphql"], "auth": ["bearer", "api_key"]}', ARRAY['express', 'cors'], '[{"name": "Route Handler", "code": "createRoute(path, handler)"}]'),
('UI Component Library', 'Reusable UI components for healthcare applications', '1.4.7', 'ui', 'UI Health', ARRAY['ui', 'components', 'react'], 'https://docs.uihealth.com', 4.4, 6500, false, false, '{"framework": "react", "themes": ["light", "dark", "medical"]}', ARRAY['react', 'styled-components'], '[{"name": "Patient Card", "code": "<PatientCard data={patient} />"}]'),
('Integration Hub', 'Connect to multiple third-party services', '2.0.5', 'integration', 'IntegrationPro', ARRAY['integration', 'api', 'webhooks'], 'https://docs.integrationpro.com', 4.6, 11200, true, false, '{"services": ["stripe", "twilio", "sendgrid"], "protocols": ["webhook", "polling"]}', ARRAY['axios', 'express'], '[{"name": "Webhook Handler", "code": "handleWebhook(payload)"}]'),
('Analytics & Reporting', 'Advanced analytics and reporting tools', '1.9.2', 'data', 'Analytics Pro', ARRAY['analytics', 'reporting', 'charts'], 'https://docs.analyticspro.com', 4.3, 5800, false, false, '{"charts": ["line", "bar", "pie"], "exports": ["pdf", "excel"]}', ARRAY['d3', 'chart.js'], '[{"name": "Chart Generator", "code": "generateChart(data, type)"}]');

-- Populate workflow actions with comprehensive data
INSERT INTO public.workflow_actions (name, description, type, category, code, inputs, outputs, parameters, validation_rules, is_custom, usage_count, success_rate, average_execution_time_ms, library_id) VALUES
('Format Patient ID', 'Standardize patient ID format across systems', 'transform', 'Healthcare', 'function formatPatientId(patientId, format = ''PAT-{id}'') { const cleanId = patientId.replace(/[^0-9]/g, ''''); return format.replace(''{id}'', cleanId.padStart(6, ''0'')); }', '[{"name": "patientId", "type": "string", "required": true, "description": "Raw patient ID"}, {"name": "format", "type": "string", "required": false, "description": "Target format pattern"}]', '[{"name": "formattedId", "type": "string", "description": "Standardized patient ID"}]', '{"maxLength": 20, "allowedChars": "alphanumeric"}', '{"patientId": {"required": true, "minLength": 1}}', false, 450, 98.5, 12, (SELECT id FROM workflow_libraries WHERE name = 'Healthcare Utilities')),
('Validate Email', 'Validate email address format and domain', 'validate', 'Validation', 'function validateEmail(email) { const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; const isValid = emailRegex.test(email); const errors = []; if (!isValid) { errors.push(''Invalid email format''); } return { isValid, errors }; }', '[{"name": "email", "type": "string", "required": true, "description": "Email address to validate"}]', '[{"name": "isValid", "type": "boolean", "description": "Validation result"}, {"name": "errors", "type": "array", "description": "List of validation errors"}]', '{"allowedDomains": ["gmail.com", "yahoo.com", "company.com"]}', '{"email": {"required": true, "format": "email"}}', false, 890, 99.2, 8, NULL),
('Calculate Age', 'Calculate age from date of birth', 'calculate', 'Healthcare', 'function calculateAge(dateOfBirth) { const today = new Date(); const birthDate = new Date(dateOfBirth); const age = today.getFullYear() - birthDate.getFullYear(); const ageInMonths = age * 12 + (today.getMonth() - birthDate.getMonth()); return { age, ageInMonths }; }', '[{"name": "dateOfBirth", "type": "string", "required": true, "description": "Date of birth (YYYY-MM-DD)"}]', '[{"name": "age", "type": "number", "description": "Age in years"}, {"name": "ageInMonths", "type": "number", "description": "Age in months"}]', '{"maxAge": 150, "minAge": 0}', '{"dateOfBirth": {"required": true, "format": "date"}}', false, 320, 99.8, 5, (SELECT id FROM workflow_libraries WHERE name = 'Healthcare Utilities')),
('Send Email Notification', 'Send email notifications to users or patients', 'notification', 'Communication', 'async function sendEmail(to, subject, body, template) { const emailService = getEmailService(); return await emailService.send({ to, subject, body, template }); }', '[{"name": "to", "type": "string", "required": true, "description": "Recipient email address"}, {"name": "subject", "type": "string", "required": true, "description": "Email subject"}, {"name": "body", "type": "string", "required": false, "description": "Email body text"}, {"name": "template", "type": "string", "required": false, "description": "Email template name"}]', '[{"name": "messageId", "type": "string", "description": "Email message ID"}, {"name": "status", "type": "string", "description": "Delivery status"}]', '{"rateLimit": 100, "priority": "normal"}', '{"to": {"required": true, "format": "email"}, "subject": {"required": true}}', false, 1250, 97.3, 850, (SELECT id FROM workflow_libraries WHERE name = 'Integration Hub')),
('Encrypt Data', 'Encrypt sensitive data using AES encryption', 'transform', 'Security', 'function encryptData(data, key, algorithm = ''aes-256-gcm'') { const crypto = require(''crypto''); const cipher = crypto.createCipher(algorithm, key); let encrypted = cipher.update(data, ''utf8'', ''hex''); encrypted += cipher.final(''hex''); return encrypted; }', '[{"name": "data", "type": "string", "required": true, "description": "Data to encrypt"}, {"name": "key", "type": "string", "required": true, "description": "Encryption key"}, {"name": "algorithm", "type": "string", "required": false, "description": "Encryption algorithm"}]', '[{"name": "encryptedData", "type": "string", "description": "Encrypted data string"}]', '{"keyLength": 32, "algorithm": "aes-256-gcm"}', '{"data": {"required": true}, "key": {"required": true, "minLength": 16}}', false, 680, 99.9, 45, (SELECT id FROM workflow_libraries WHERE name = 'Security & Encryption Library')),
('API Request', 'Make HTTP requests to external APIs', 'request', 'Integration', 'async function makeRequest(url, method, headers, body) { const response = await fetch(url, { method, headers, body: JSON.stringify(body) }); return await response.json(); }', '[{"name": "url", "type": "string", "required": true, "description": "API endpoint URL"}, {"name": "method", "type": "string", "required": false, "description": "HTTP method"}, {"name": "headers", "type": "object", "required": false, "description": "Request headers"}, {"name": "body", "type": "object", "required": false, "description": "Request body"}]', '[{"name": "response", "type": "object", "description": "API response data"}, {"name": "statusCode", "type": "number", "description": "HTTP status code"}]', '{"timeout": 30000, "retries": 3}', '{"url": {"required": true, "format": "url"}}', false, 2100, 96.8, 1200, (SELECT id FROM workflow_libraries WHERE name = 'API Gateway Library')),
('Data Validation', 'Validate data against predefined schemas', 'validate', 'Data Processing', 'function validateData(data, schema) { const errors = []; for (const field in schema) { const rules = schema[field]; if (rules.required && !data[field]) { errors.push(`${field} is required`); } if (data[field] && rules.type && typeof data[field] !== rules.type) { errors.push(`${field} must be of type ${rules.type}`); } } return { isValid: errors.length === 0, errors }; }', '[{"name": "data", "type": "object", "required": true, "description": "Data to validate"}, {"name": "schema", "type": "object", "required": true, "description": "Validation schema"}]', '[{"name": "isValid", "type": "boolean", "description": "Validation result"}, {"name": "errors", "type": "array", "description": "Validation errors"}]', '{"strictMode": true, "allowUnknown": false}', '{"data": {"required": true}, "schema": {"required": true}}', false, 1580, 98.9, 25, (SELECT id FROM workflow_libraries WHERE name = 'Data Transformation Suite')),
('Generate Report', 'Generate PDF reports from data', 'transform', 'Reporting', 'async function generateReport(data, template, options) { const reportService = getReportService(); return await reportService.generate({ data, template, ...options }); }', '[{"name": "data", "type": "object", "required": true, "description": "Report data"}, {"name": "template", "type": "string", "required": true, "description": "Report template"}, {"name": "options", "type": "object", "required": false, "description": "Report options"}]', '[{"name": "reportUrl", "type": "string", "description": "Generated report URL"}, {"name": "reportId", "type": "string", "description": "Report identifier"}]', '{"format": "pdf", "compression": true}', '{"data": {"required": true}, "template": {"required": true}}', false, 380, 95.4, 2500, (SELECT id FROM workflow_libraries WHERE name = 'Analytics & Reporting'));

-- Populate workflow operators with comprehensive data
INSERT INTO public.workflow_operators (name, symbol, description, category, syntax, examples, precedence, is_binary, return_type, usage_count) VALUES
('Equals', '==', 'Compare two values for equality', 'comparison', 'value1 == value2', ARRAY['age == 25', 'status == "active"', 'isVerified == true'], 5, true, 'boolean', 1250),
('Not Equals', '!=', 'Compare two values for inequality', 'comparison', 'value1 != value2', ARRAY['status != "inactive"', 'score != 0'], 5, true, 'boolean', 890),
('Greater Than', '>', 'Check if first value is greater than second', 'comparison', 'value1 > value2', ARRAY['score > 80', 'temperature > 98.6', 'age > 18'], 6, true, 'boolean', 1100),
('Less Than', '<', 'Check if first value is less than second', 'comparison', 'value1 < value2', ARRAY['age < 65', 'price < 100'], 6, true, 'boolean', 980),
('Greater Than or Equal', '>=', 'Check if first value is greater than or equal to second', 'comparison', 'value1 >= value2', ARRAY['score >= 70', 'age >= 21'], 6, true, 'boolean', 750),
('Less Than or Equal', '<=', 'Check if first value is less than or equal to second', 'comparison', 'value1 <= value2', ARRAY['age <= 100', 'score <= 100'], 6, true, 'boolean', 680),
('And', '&&', 'Logical AND operation', 'logical', 'condition1 && condition2', ARRAY['age > 18 && status == "active"', 'hasInsurance && isPreApproved'], 2, true, 'boolean', 1850),
('Or', '||', 'Logical OR operation', 'logical', 'condition1 || condition2', ARRAY['isAdmin || isModerator', 'age < 18 || hasGuardian'], 1, true, 'boolean', 1420),
('Not', '!', 'Logical NOT operation', 'logical', '!condition', ARRAY['!isDeleted', '!hasErrors'], 7, false, 'boolean', 920),
('Addition', '+', 'Add two numbers or concatenate strings', 'arithmetic', 'value1 + value2', ARRAY['price + tax', 'firstName + " " + lastName'], 4, true, 'number|string', 2100),
('Subtraction', '-', 'Subtract second number from first', 'arithmetic', 'value1 - value2', ARRAY['total - discount', 'endDate - startDate'], 4, true, 'number', 1680),
('Multiplication', '*', 'Multiply two numbers', 'arithmetic', 'value1 * value2', ARRAY['price * quantity', 'hours * rate'], 5, true, 'number', 1340),
('Division', '/', 'Divide first number by second', 'arithmetic', 'value1 / value2', ARRAY['total / count', 'distance / time'], 5, true, 'number', 1120),
('Modulo', '%', 'Get remainder of division', 'arithmetic', 'value1 % value2', ARRAY['number % 2', 'id % 10'], 5, true, 'number', 450),
('Contains', 'includes', 'Check if string contains substring', 'string', 'string.includes(substring)', ARRAY['name.includes("John")', 'email.includes("@gmail.com")'], 3, true, 'boolean', 1680),
('Starts With', 'startsWith', 'Check if string starts with substring', 'string', 'string.startsWith(prefix)', ARRAY['name.startsWith("Dr.")', 'phone.startsWith("+1")'], 3, true, 'boolean', 680),
('Ends With', 'endsWith', 'Check if string ends with substring', 'string', 'string.endsWith(suffix)', ARRAY['email.endsWith(".com")', 'filename.endsWith(".pdf")'], 3, true, 'boolean', 520),
('Length', 'length', 'Get length of string or array', 'string', 'value.length', ARRAY['name.length', 'items.length'], 8, false, 'number', 1250),
('In Array', 'in', 'Check if value exists in array', 'array', 'value in array', ARRAY['status in ["active", "pending"]', 'role in allowedRoles'], 3, true, 'boolean', 890),
('Array Push', 'push', 'Add element to end of array', 'array', 'array.push(element)', ARRAY['items.push(newItem)', 'errors.push(errorMsg)'], 8, true, 'array', 650);

-- Create indexes for better search performance
CREATE INDEX IF NOT EXISTS idx_workflow_libraries_search ON public.workflow_libraries USING gin(to_tsvector('english', name || ' ' || COALESCE(description, '')));
CREATE INDEX IF NOT EXISTS idx_workflow_actions_search ON public.workflow_actions USING gin(to_tsvector('english', name || ' ' || COALESCE(description, '')));
CREATE INDEX IF NOT EXISTS idx_workflow_operators_search ON public.workflow_operators USING gin(to_tsvector('english', name || ' ' || COALESCE(description, '')));