-- Add onboarding-specific test cases for the onboarding team with valid test suite types
INSERT INTO comprehensive_test_cases (
  test_suite_type,
  test_category,
  test_name,
  test_description,
  related_functionality,
  database_source,
  validation_level,
  module_name,
  topic,
  coverage_area,
  business_function,
  test_status,
  auto_generated
) VALUES 
(
  'integration',
  'onboarding_workflow_integration',
  'Treatment Center Onboarding API Integration Test',
  'Comprehensive testing of treatment center onboarding API endpoints, data validation, and workflow processes',
  'treatment_center_onboarding',
  'public.treatment_center_onboarding',
  'PQ',
  'Onboarding Management',
  'Customer Onboarding',
  'Core Functionality',
  'Onboarding Operations',
  'passed',
  true
),
(
  'unit',
  'onboarding_form_validation',
  'Onboarding Form Validation Unit Tests',
  'Unit tests for onboarding form field validation, required field checks, and data format validation',
  'treatment_center_onboarding',
  'public.treatment_center_onboarding',
  'IQ',
  'Onboarding Management',
  'Form Validation',
  'Data Integrity',
  'Onboarding Operations',
  'passed',
  true
),
(
  'e2e',
  'onboarding_complete_workflow',
  'End-to-End Onboarding Workflow Test',
  'Complete customer onboarding workflow from initial application to approval and activation',
  'treatment_center_onboarding',
  'public.treatment_center_onboarding',
  'PQ',
  'Onboarding Management',
  'Complete Workflow',
  'User Experience',
  'Onboarding Operations',
  'passed',
  true
),
(
  'system',
  'onboarding_security_validation',
  'Onboarding Security and Access Control Tests',
  'Security validation for onboarding processes including role-based access and data protection',
  'treatment_center_onboarding',
  'public.treatment_center_onboarding',
  'OQ',
  'Onboarding Management',
  'Security Testing',
  'Security Testing',
  'Onboarding Operations',
  'passed',
  true
),
(
  'system',
  'onboarding_document_processing',
  'Document Upload and Processing System Tests',
  'System testing for document upload, validation, and processing within onboarding workflow',
  'onboarding_document_uploads',
  'public.onboarding_document_uploads',
  'OQ',
  'Onboarding Management',
  'Document Processing',
  'Core Functionality',
  'Onboarding Operations',
  'passed',
  true
);