-- Add missing deployment and voice configuration categories
INSERT INTO workflow_node_categories (name, display_name, description, icon, color, order_index, is_active) VALUES
('deployment_environments', 'Deployment Environments', 'Development, testing, UAT, staging, and production environment configurations', 'settings', '#7c3aed', 100, true),
('channel_deployment', 'Channel Deployment', 'Voice calls, web chat, email, messaging, Instagram and other communication channels', 'message-square', '#059669', 101, true),
('voice_config', 'Voice Configuration', 'Speech synthesis, recognition, voice models, and audio processing', 'message-circle', '#dc2626', 102, true),
('human_loop', 'Human in the Loop', 'Human handoff, escalation, transfer, and live agent integration', 'wrench', '#c2410c', 103, true),
('testing_validation', 'Testing & Validation', 'Testing workflows, validation, debugging, and simulation tools', 'search', '#0f766e', 104, true),
('code_deployment', 'Code & Deployment', 'Code snippets, Docker, Kubernetes, API endpoints, and webhooks', 'code', '#4338ca', 105, true);

-- Add deployment environment node types
INSERT INTO workflow_node_types (category_id, type_key, display_name, description, icon, color, default_config, capabilities, is_active, order_index) VALUES
((SELECT id FROM workflow_node_categories WHERE name = 'deployment_environments'), 'dev_environment', 'Development Environment', 'Local development and testing environment setup', 'laptop', '#22c55e', '{"environment": "development", "auto_deploy": true}', '["local_testing", "hot_reload", "debug_mode"]', true, 1),
((SELECT id FROM workflow_node_categories WHERE name = 'deployment_environments'), 'test_environment', 'Test Environment', 'Automated testing and quality assurance environment', 'test-tube', '#eab308', '{"environment": "test", "auto_test": true}', '["automated_testing", "qa_validation", "performance_testing"]', true, 2),
((SELECT id FROM workflow_node_categories WHERE name = 'deployment_environments'), 'uat_environment', 'UAT Environment', 'User acceptance testing and stakeholder validation', 'users', '#f97316', '{"environment": "uat", "user_feedback": true}', '["user_testing", "feedback_collection", "approval_workflows"]', true, 3),
((SELECT id FROM workflow_node_categories WHERE name = 'deployment_environments'), 'staging_environment', 'Staging Environment', 'Pre-production testing with production-like data', 'layers', '#8b5cf6', '{"environment": "staging", "production_mirror": true}', '["production_simulation", "load_testing", "final_validation"]', true, 4),
((SELECT id FROM workflow_node_categories WHERE name = 'deployment_environments'), 'production_environment', 'Production Environment', 'Live production deployment and monitoring', 'globe', '#ef4444', '{"environment": "production", "monitoring": true}', '["live_deployment", "monitoring", "rollback_capability"]', true, 5);

-- Add channel deployment node types
INSERT INTO workflow_node_types (category_id, type_key, display_name, description, icon, color, default_config, capabilities, is_active, order_index) VALUES
((SELECT id FROM workflow_node_categories WHERE name = 'channel_deployment'), 'voice_call_channel', 'Voice Call Channel', 'Deploy agents to handle voice calls and phone interactions', 'phone-call', '#059669', '{"channel_type": "voice_call", "max_concurrent": 50}', '["voice_recognition", "call_routing", "ivr_integration"]', true, 1),
((SELECT id FROM workflow_node_categories WHERE name = 'channel_deployment'), 'web_chat_channel', 'Web Chat Channel', 'Deploy agents for website chat and live support', 'message-circle', '#3b82f6', '{"channel_type": "web_chat", "widget_customization": true}', '["real_time_chat", "file_sharing", "screen_sharing"]', true, 2),
((SELECT id FROM workflow_node_categories WHERE name = 'channel_deployment'), 'email_channel', 'Email Channel', 'Automated email processing and response system', 'mail', '#6366f1', '{"channel_type": "email", "auto_categorization": true}', '["email_parsing", "auto_response", "template_management"]', true, 3),
((SELECT id FROM workflow_node_categories WHERE name = 'channel_deployment'), 'sms_messaging', 'SMS Messaging', 'Text message automation and customer communication', 'message-square', '#10b981', '{"channel_type": "sms", "two_way_messaging": true}', '["bulk_messaging", "automated_responses", "delivery_tracking"]', true, 4),
((SELECT id FROM workflow_node_categories WHERE name = 'channel_deployment'), 'instagram_channel', 'Instagram Channel', 'Social media automation and customer engagement', 'instagram', '#e11d48', '{"channel_type": "instagram", "dm_automation": true}', '["direct_messages", "story_interactions", "comment_management"]', true, 5),
((SELECT id FROM workflow_node_categories WHERE name = 'channel_deployment'), 'whatsapp_channel', 'WhatsApp Channel', 'WhatsApp Business automation and messaging', 'message-circle', '#25d366', '{"channel_type": "whatsapp", "business_api": true}', '["business_messaging", "media_sharing", "group_management"]', true, 6);

-- Add voice configuration node types
INSERT INTO workflow_node_types (category_id, type_key, display_name, description, icon, color, default_config, capabilities, is_active, order_index) VALUES
((SELECT id FROM workflow_node_categories WHERE name = 'voice_config'), 'tts_engine', 'Text-to-Speech Engine', 'Convert text responses to natural-sounding speech', 'volume-2', '#dc2626', '{"engine": "eleven_labs", "voice_id": "default", "speed": 1.0}', '["natural_speech", "voice_cloning", "emotion_control"]', true, 1),
((SELECT id FROM workflow_node_categories WHERE name = 'voice_config'), 'stt_engine', 'Speech-to-Text Engine', 'Convert spoken words to text for processing', 'mic', '#f59e0b', '{"engine": "whisper", "language": "en", "accuracy": "high"}', '["real_time_transcription", "multiple_languages", "noise_filtering"]', true, 2),
((SELECT id FROM workflow_node_categories WHERE name = 'voice_config'), 'voice_model', 'Voice Model', 'Custom voice models for specific use cases', 'user-voice', '#8b5cf6', '{"model_type": "custom", "training_data": "healthcare"}', '["custom_voices", "domain_specific", "accent_control"]', true, 3),
((SELECT id FROM workflow_node_categories WHERE name = 'voice_config'), 'audio_processor', 'Audio Processor', 'Audio enhancement, noise reduction, and quality control', 'audio-waveform', '#06b6d4', '{"noise_reduction": true, "echo_cancellation": true}', '["audio_enhancement", "quality_optimization", "format_conversion"]', true, 4),
((SELECT id FROM workflow_node_categories WHERE name = 'voice_config'), 'speech_analytics', 'Speech Analytics', 'Analyze speech patterns, sentiment, and conversation metrics', 'bar-chart', '#84cc16', '{"sentiment_analysis": true, "keyword_detection": true}', '["sentiment_analysis", "speech_metrics", "conversation_insights"]', true, 5);

-- Add human in the loop node types
INSERT INTO workflow_node_types (category_id, type_key, display_name, description, icon, color, default_config, capabilities, is_active, order_index) VALUES
((SELECT id FROM workflow_node_categories WHERE name = 'human_loop'), 'human_handoff', 'Human Handoff', 'Transfer conversations to human agents when needed', 'hand', '#c2410c', '{"trigger_conditions": ["escalation_request", "complex_query"], "priority": "normal"}', '["seamless_transfer", "context_preservation", "priority_routing"]', true, 1),
((SELECT id FROM workflow_node_categories WHERE name = 'human_loop'), 'escalation_trigger', 'Escalation Trigger', 'Automatic escalation based on conversation context', 'arrow-up', '#ef4444', '{"auto_escalate": true, "sentiment_threshold": -0.5}', '["automatic_escalation", "sentiment_monitoring", "rule_based_triggers"]', true, 2),
((SELECT id FROM workflow_node_categories WHERE name = 'human_loop'), 'agent_transfer', 'Agent Transfer', 'Route to specific human agents or departments', 'users', '#3b82f6', '{"routing_strategy": "skill_based", "queue_management": true}', '["skill_routing", "queue_management", "agent_availability"]', true, 3),
((SELECT id FROM workflow_node_categories WHERE name = 'human_loop'), 'supervision_mode', 'Supervision Mode', 'Human oversight and intervention capabilities', 'eye', '#6366f1', '{"real_time_monitoring": true, "intervention_allowed": true}', '["real_time_monitoring", "intervention_tools", "quality_assurance"]', true, 4),
((SELECT id FROM workflow_node_categories WHERE name = 'human_loop'), 'approval_workflow', 'Approval Workflow', 'Human approval for sensitive or critical actions', 'check-circle', '#10b981', '{"approval_required": true, "timeout_minutes": 30}', '["approval_routing", "timeout_handling", "audit_trail"]', true, 5);

-- Add testing and validation node types
INSERT INTO workflow_node_types (category_id, type_key, display_name, description, icon, color, default_config, capabilities, is_active, order_index) VALUES
((SELECT id FROM workflow_node_categories WHERE name = 'testing_validation'), 'flow_tester', 'Flow Tester', 'Test complete conversation flows and user journeys', 'play-circle', '#0f766e', '{"test_scenarios": [], "assertions": [], "coverage_tracking": true}', '["flow_testing", "regression_testing", "coverage_analysis"]', true, 1),
((SELECT id FROM workflow_node_categories WHERE name = 'testing_validation'), 'response_validator', 'Response Validator', 'Validate AI responses for accuracy and appropriateness', 'shield-check', '#059669', '{"validation_rules": [], "confidence_threshold": 0.8}', '["response_validation", "accuracy_checking", "compliance_validation"]', true, 2),
((SELECT id FROM workflow_node_categories WHERE name = 'testing_validation'), 'load_tester', 'Load Tester', 'Performance testing and stress testing for workflows', 'activity', '#eab308', '{"concurrent_users": 100, "duration_minutes": 10}', '["performance_testing", "stress_testing", "bottleneck_detection"]', true, 3),
((SELECT id FROM workflow_node_categories WHERE name = 'testing_validation'), 'debug_console', 'Debug Console', 'Debug and troubleshoot workflow execution', 'bug', '#f97316', '{"log_level": "debug", "trace_enabled": true}', '["debug_logging", "execution_tracing", "error_tracking"]', true, 4),
((SELECT id FROM workflow_node_categories WHERE name = 'testing_validation'), 'simulation_engine', 'Simulation Engine', 'Simulate various scenarios and edge cases', 'cpu', '#8b5cf6', '{"scenario_library": [], "randomization": true}', '["scenario_simulation", "edge_case_testing", "randomized_testing"]', true, 5);

-- Add code and deployment node types
INSERT INTO workflow_node_types (category_id, type_key, display_name, description, icon, color, default_config, capabilities, is_active, order_index) VALUES
((SELECT id FROM workflow_node_categories WHERE name = 'code_deployment'), 'code_snippet', 'Code Snippet', 'Execute custom code within workflow execution', 'code', '#4338ca', '{"language": "javascript", "timeout_seconds": 30}', '["custom_logic", "data_transformation", "external_api_calls"]', true, 1),
((SELECT id FROM workflow_node_categories WHERE name = 'code_deployment'), 'docker_container', 'Docker Container', 'Deploy workflows in containerized environments', 'container', '#2563eb', '{"image": "node:18", "resources": {"cpu": "0.5", "memory": "512Mi"}}', '["containerization", "scalability", "isolation"]', true, 2),
((SELECT id FROM workflow_node_categories WHERE name = 'code_deployment'), 'kubernetes_pod', 'Kubernetes Pod', 'Deploy and manage workflows in Kubernetes clusters', 'kubernetes', '#326ce5', '{"replicas": 3, "auto_scaling": true}', '["orchestration", "auto_scaling", "high_availability"]', true, 3),
((SELECT id FROM workflow_node_categories WHERE name = 'code_deployment'), 'api_endpoint', 'API Endpoint', 'Expose workflow as REST API endpoint', 'server', '#059669', '{"method": "POST", "authentication": "bearer_token"}', '["api_exposure", "authentication", "rate_limiting"]', true, 4),
((SELECT id FROM workflow_node_categories WHERE name = 'code_deployment'), 'webhook_listener', 'Webhook Listener', 'Receive and process webhook notifications', 'webhook', '#dc2626', '{"signature_validation": true, "retry_attempts": 3}', '["webhook_processing", "signature_validation", "retry_logic"]', true, 5),
((SELECT id FROM workflow_node_categories WHERE name = 'code_deployment'), 'deployment_pipeline', 'Deployment Pipeline', 'Automated deployment and CI/CD integration', 'git-branch', '#6366f1', '{"auto_deploy": true, "rollback_enabled": true}', '["ci_cd_integration", "automated_deployment", "rollback_capability"]', true, 6);