-- Create tables for Node Insights functionality

-- Node analytics for tracking usage and performance
CREATE TABLE IF NOT EXISTS public.node_analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  node_type TEXT NOT NULL,
  workflow_id UUID,
  node_id TEXT,
  usage_count INTEGER DEFAULT 0,
  success_count INTEGER DEFAULT 0,
  failure_count INTEGER DEFAULT 0,
  total_execution_time_ms BIGINT DEFAULT 0,
  average_execution_time_ms INTEGER DEFAULT 0,
  user_rating DECIMAL(3,2) DEFAULT 0.0,
  common_connections JSONB DEFAULT '[]'::jsonb,
  performance_metrics JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Node usage events for detailed tracking
CREATE TABLE IF NOT EXISTS public.node_usage_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  node_type TEXT NOT NULL,
  node_id TEXT NOT NULL,
  workflow_id UUID,
  user_id UUID REFERENCES auth.users(id),
  action TEXT NOT NULL CHECK (action IN ('created', 'configured', 'executed', 'removed', 'modified')),
  execution_time_ms INTEGER,
  success BOOLEAN,
  error_details JSONB,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Node suggestions generated by AI analysis
CREATE TABLE IF NOT EXISTS public.node_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workflow_id UUID,
  user_id UUID REFERENCES auth.users(id),
  node_type TEXT NOT NULL,
  suggestion_type TEXT NOT NULL CHECK (suggestion_type IN ('next_node', 'optimization', 'best_practice', 'connection')),
  title TEXT NOT NULL,
  description TEXT,
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  confidence_score DECIMAL(3,2) DEFAULT 0.0,
  config_template JSONB DEFAULT '{}'::jsonb,
  dependencies JSONB DEFAULT '[]'::jsonb,
  implementation_notes TEXT,
  is_applied BOOLEAN DEFAULT false,
  applied_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  expires_at TIMESTAMP WITH TIME ZONE
);

-- Node configuration templates for different node types
CREATE TABLE IF NOT EXISTS public.node_config_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  node_type TEXT NOT NULL,
  template_name TEXT NOT NULL,
  description TEXT,
  category TEXT DEFAULT 'general',
  config_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
  default_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  validation_rules JSONB DEFAULT '{}'::jsonb,
  is_system_template BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  created_by UUID REFERENCES auth.users(id),
  usage_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(node_type, template_name)
);

-- Workflow analysis results
CREATE TABLE IF NOT EXISTS public.workflow_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workflow_id UUID NOT NULL,
  user_id UUID REFERENCES auth.users(id),
  analysis_type TEXT NOT NULL CHECK (analysis_type IN ('performance', 'optimization', 'suggestions', 'validation')),
  current_nodes JSONB NOT NULL DEFAULT '[]'::jsonb,
  analysis_results JSONB NOT NULL DEFAULT '{}'::jsonb,
  suggestions_generated INTEGER DEFAULT 0,
  performance_score DECIMAL(3,2) DEFAULT 0.0,
  complexity_score DECIMAL(3,2) DEFAULT 0.0,
  optimization_opportunities JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS on all tables
ALTER TABLE public.node_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.node_usage_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.node_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.node_config_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workflow_analysis ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Node Analytics
CREATE POLICY "Users can view their own node analytics" ON public.node_analytics
  FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY "System can insert node analytics" ON public.node_analytics
  FOR INSERT WITH CHECK (true);

CREATE POLICY "System can update node analytics" ON public.node_analytics
  FOR UPDATE USING (true);

-- Node Usage Events
CREATE POLICY "Users can view their own usage events" ON public.node_usage_events
  FOR SELECT USING (user_id = auth.uid() OR auth.uid() IS NOT NULL);

CREATE POLICY "Users can create usage events" ON public.node_usage_events
  FOR INSERT WITH CHECK (user_id = auth.uid());

-- Node Suggestions
CREATE POLICY "Users can view their own suggestions" ON public.node_suggestions
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can manage their own suggestions" ON public.node_suggestions
  FOR ALL USING (user_id = auth.uid());

-- Node Config Templates
CREATE POLICY "Users can view active templates" ON public.node_config_templates
  FOR SELECT USING (is_active = true);

CREATE POLICY "Users can create their own templates" ON public.node_config_templates
  FOR INSERT WITH CHECK (created_by = auth.uid());

CREATE POLICY "Users can update their own templates" ON public.node_config_templates
  FOR UPDATE USING (created_by = auth.uid() OR is_system_template = false);

-- Workflow Analysis
CREATE POLICY "Users can view their own workflow analysis" ON public.workflow_analysis
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can create workflow analysis" ON public.workflow_analysis
  FOR INSERT WITH CHECK (user_id = auth.uid());

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_node_analytics_node_type ON public.node_analytics(node_type);
CREATE INDEX IF NOT EXISTS idx_node_analytics_workflow_id ON public.node_analytics(workflow_id);
CREATE INDEX IF NOT EXISTS idx_node_usage_events_user_id ON public.node_usage_events(user_id);
CREATE INDEX IF NOT EXISTS idx_node_usage_events_node_type ON public.node_usage_events(node_type);
CREATE INDEX IF NOT EXISTS idx_node_suggestions_user_id ON public.node_suggestions(user_id);
CREATE INDEX IF NOT EXISTS idx_node_suggestions_workflow_id ON public.node_suggestions(workflow_id);
CREATE INDEX IF NOT EXISTS idx_node_config_templates_node_type ON public.node_config_templates(node_type);
CREATE INDEX IF NOT EXISTS idx_workflow_analysis_user_id ON public.workflow_analysis(user_id);

-- Insert some default system templates
INSERT INTO public.node_config_templates (node_type, template_name, description, category, default_config, is_system_template, is_active) VALUES
('agent', 'Basic AI Agent', 'Standard AI agent configuration', 'ai', '{"model": "gpt-4o-mini", "temperature": 0.7, "maxTokens": 1000, "systemPrompt": "You are a helpful AI assistant.", "capabilities": ["conversation", "reasoning"], "conversationMemory": true}', true, true),
('decision', 'Rule-Based Decision', 'Basic rule-based decision logic', 'logic', '{"conditions": [{"field": "", "operator": "equals", "value": "", "logicalOperator": "AND"}], "defaultPath": "continue", "evaluationType": "rule-based", "timeout": 30}', true, true),
('escalation', 'Basic Escalation', 'Standard escalation configuration', 'workflow', '{"triggers": [{"condition": "timeout", "value": 300, "action": "escalate"}], "escalationLevels": [{"level": 1, "assignTo": "supervisor", "timeout": 600}], "notificationChannels": ["email"]}', true, true),
('api', 'REST API Call', 'Standard REST API integration', 'integration', '{"endpoint": "", "method": "GET", "headers": {"Content-Type": "application/json"}, "authentication": "none", "timeout": 30, "retryPolicy": {"attempts": 3, "backoff": "linear"}}', true, true),
('notification', 'Email Notification', 'Basic email notification', 'communication', '{"channels": ["email"], "template": "default", "recipients": [], "priority": "normal", "deliveryOptions": {"retry": 3, "backoff": "exponential"}}', true, true),
('validation', 'Data Validation', 'Input data validation rules', 'utility', '{"validationRules": [{"field": "email", "type": "email", "required": true}], "errorHandling": "stop", "sanitization": true}', true, true)
ON CONFLICT (node_type, template_name) DO NOTHING;

-- Create trigger for updating node analytics
CREATE OR REPLACE FUNCTION update_node_analytics()
RETURNS TRIGGER AS $$
BEGIN
  -- Update or insert analytics based on usage events
  INSERT INTO public.node_analytics (node_type, node_id, workflow_id, usage_count, success_count, failure_count)
  VALUES (NEW.node_type, NEW.node_id, NEW.workflow_id, 1, 
          CASE WHEN NEW.success = true THEN 1 ELSE 0 END,
          CASE WHEN NEW.success = false THEN 1 ELSE 0 END)
  ON CONFLICT (node_type, COALESCE(node_id, ''), COALESCE(workflow_id::text, ''))
  DO UPDATE SET
    usage_count = node_analytics.usage_count + 1,
    success_count = node_analytics.success_count + CASE WHEN NEW.success = true THEN 1 ELSE 0 END,
    failure_count = node_analytics.failure_count + CASE WHEN NEW.success = false THEN 1 ELSE 0 END,
    total_execution_time_ms = node_analytics.total_execution_time_ms + COALESCE(NEW.execution_time_ms, 0),
    average_execution_time_ms = CASE 
      WHEN node_analytics.usage_count > 0 THEN 
        (node_analytics.total_execution_time_ms + COALESCE(NEW.execution_time_ms, 0)) / (node_analytics.usage_count + 1)
      ELSE COALESCE(NEW.execution_time_ms, 0)
    END,
    updated_at = now();
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Add unique constraint to node_analytics for proper conflict resolution
ALTER TABLE public.node_analytics ADD CONSTRAINT unique_node_analytics 
  UNIQUE (node_type, COALESCE(node_id, ''), COALESCE(workflow_id::text, ''));

-- Create trigger
CREATE TRIGGER update_node_analytics_trigger
  AFTER INSERT ON public.node_usage_events
  FOR EACH ROW EXECUTE FUNCTION update_node_analytics();

-- Create trigger for updating updated_at timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_node_analytics_updated_at
  BEFORE UPDATE ON public.node_analytics
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_node_config_templates_updated_at
  BEFORE UPDATE ON public.node_config_templates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();