
-- Seed regional_landing_content using correct check-constraint codes
INSERT INTO public.regional_landing_content (region_code, headline, subheadline, cta_primary_text, cta_secondary_text, language_code, rtl_enabled, version, status)
VALUES
('NAM', 'From coast to coast, North America is buzzing with innovation — but are we truly maximizing our potential in healthcare?', 'We''re pushing boundaries with cutting-edge tech, but healthcare still faces serious challenges with AI integration, data silos, and HIPAA compliance.', 'Explore the Genie Suite', 'Watch Demo', 'en', false, 1, 'active'),
('LATAM', '¡Oye, mi gente! Latin America isn''t just vibrant — we ARE the future!', 'When the world talks about innovation, do they hear OUR voices? Do they see OUR solutions?', 'Únete a la revolución', 'Ver Demo', 'es', false, 1, 'active'),
('MENA', 'Picture a world where every digital tool is an authentic extension of your culture and language.', 'Most AI tools treat Arabic as an afterthought — RTL rendering, dialectal variation, and medical terminology remain unsolved.', 'ابدأ الآن', 'Watch Demo', 'ar', true, 1, 'active'),
('IND', 'One billion hearts, a symphony of languages. Yet most content tools treat India like a single, flat note.', 'With 22 official languages and 700+ dialects, patient education must go beyond Hindi-English to truly reach Bharat.', 'Explore Genie Suite', 'Watch Demo', 'en', false, 1, 'active'),
('SEA', '11 countries, 1,000+ languages — Southeast Asia is the ultimate test for multilingual content platforms.', '90%+ mobile internet penetration means all healthcare content must be mobile-native, not desktop-adapted.', 'Get Started', 'Watch Demo', 'en', false, 1, 'active'),
('CJK', 'In a world where China, Japan, and Korea set the standard for global excellence, every piece of content is a testament to your brand.', 'Pixel-perfect localization is not optional — machine translation is considered disrespectful to CJK audiences.', 'Explore Suite', 'Watch Demo', 'en', false, 1, 'active'),
('AFR', 'Africa''s rising! Our digital hustle is real, but are we really being heard?', 'The continent''s 1.4 billion people deserve AI tools that speak their languages and understand their markets.', 'Explore Tools', 'Watch Demo', 'en', false, 1, 'active'),
('CARIB', 'Caribbean innovation is on the rise — but is our voice truly being heard?', 'Island nations need resilient, offline-capable content tools that celebrate Caribbean culture and creativity.', 'Explore Suite', 'Watch Demo', 'en', false, 1, 'active'),
('WESTERN', 'Transform Your Content Pipeline with 206 AI-Powered Engines', 'From mind to media in minutes — the complete AI content suite for healthcare, enterprise, and creative teams.', 'Start Free Trial', 'Watch Demo', 'en', false, 1, 'active')
ON CONFLICT DO NOTHING;

-- Seed challenge cards (transcreated_content = english_source for English base)
INSERT INTO public.regional_content_cache (region_slug, sub_region_code, language_code, content_type, content_key, english_source, transcreated_content, cultural_tone, status, version)
VALUES
('nam', 'NAM_US', 'en', 'challenges', 'hipaa_compliance', 'Navigating HIPAA & regulatory compliance across 50 states while adopting AI-powered workflows remains the #1 barrier for healthcare innovation.', 'Navigating HIPAA & regulatory compliance across 50 states while adopting AI-powered workflows remains the #1 barrier for healthcare innovation.', 'professional-direct', 'approved', 1),
('nam', 'NAM_US', 'en', 'challenges', 'emr_integration', 'Legacy EMR systems create data silos that block interoperability, slowing research collaboration and patient care coordination.', 'Legacy EMR systems create data silos that block interoperability, slowing research collaboration and patient care coordination.', 'professional-direct', 'approved', 1),
('nam', 'NAM_US', 'en', 'challenges', 'content_velocity', 'Marketing teams struggle to produce compliant, multilingual content at the speed patients and providers demand across digital channels.', 'Marketing teams struggle to produce compliant, multilingual content at the speed patients and providers demand across digital channels.', 'professional-direct', 'approved', 1),
('nam', 'NAM_US', 'en', 'challenges', 'cost_pressure', 'Rising healthcare costs force organizations to do more with less — AI tools must prove ROI within weeks, not quarters.', 'Rising healthcare costs force organizations to do more with less — AI tools must prove ROI within weeks, not quarters.', 'professional-direct', 'approved', 1),
('nam', 'NAM_US', 'en', 'challenges', 'telehealth_scale', 'Post-pandemic telehealth adoption requires scalable video, training, and patient education content that existing tools cannot deliver fast enough.', 'Post-pandemic telehealth adoption requires scalable video, training, and patient education content that existing tools cannot deliver fast enough.', 'professional-direct', 'approved', 1),
('eu', 'EU_DACH', 'en', 'challenges', 'gdpr_compliance', 'GDPR and cross-border data sovereignty make AI adoption in healthcare a legal minefield across 27 member states.', 'GDPR and cross-border data sovereignty make AI adoption in healthcare a legal minefield across 27 member states.', 'formal-precise', 'approved', 1),
('eu', 'EU_DACH', 'en', 'challenges', 'language_fragmentation', '24 official languages mean every campaign, training video, and patient resource must be culturally adapted — not just translated.', '24 official languages mean every campaign, training video, and patient resource must be culturally adapted — not just translated.', 'formal-precise', 'approved', 1),
('eu', 'EU_DACH', 'en', 'challenges', 'digital_transformation', 'European healthcare institutions lag in digital adoption, with fragmented IT systems and resistance to cloud-based AI solutions.', 'European healthcare institutions lag in digital adoption, with fragmented IT systems and resistance to cloud-based AI solutions.', 'formal-precise', 'approved', 1),
('eu', 'EU_DACH', 'en', 'challenges', 'talent_shortage', 'Chronic shortage of content creators who understand both medical accuracy and cultural nuance across European markets.', 'Chronic shortage of content creators who understand both medical accuracy and cultural nuance across European markets.', 'formal-precise', 'approved', 1),
('eu', 'EU_DACH', 'en', 'challenges', 'reimbursement_complexity', 'Each country has unique reimbursement models, requiring localized marketing materials that reflect local payer landscapes.', 'Each country has unique reimbursement models, requiring localized marketing materials that reflect local payer landscapes.', 'formal-precise', 'approved', 1),
('mena', 'MENA_GCC', 'en', 'challenges', 'arabization_gap', 'Most AI tools lack proper Arabic NLP support — RTL rendering, dialectal variation, and medical terminology remain unsolved.', 'Most AI tools lack proper Arabic NLP support — RTL rendering, dialectal variation, and medical terminology remain unsolved.', 'respectful-warm', 'approved', 1),
('mena', 'MENA_GCC', 'en', 'challenges', 'telemedicine_growth', 'Rapid telemedicine expansion across GCC demands culturally sensitive video content at scale — in Arabic, Urdu, and Hindi.', 'Rapid telemedicine expansion across GCC demands culturally sensitive video content at scale — in Arabic, Urdu, and Hindi.', 'respectful-warm', 'approved', 1),
('mena', 'MENA_GCC', 'en', 'challenges', 'vision_2030', 'Saudi Vision 2030 and UAE digital health strategies require localized AI solutions that align with national transformation agendas.', 'Saudi Vision 2030 and UAE digital health strategies require localized AI solutions that align with national transformation agendas.', 'respectful-warm', 'approved', 1),
('mena', 'MENA_GCC', 'en', 'challenges', 'workforce_diversity', 'Healthcare workforce spanning 50+ nationalities needs training content in multiple languages with cultural sensitivity.', 'Healthcare workforce spanning 50+ nationalities needs training content in multiple languages with cultural sensitivity.', 'respectful-warm', 'approved', 1),
('mena', 'MENA_GCC', 'en', 'challenges', 'data_localization', 'Strict data residency laws in GCC require on-region processing — most global AI platforms cannot comply.', 'Strict data residency laws in GCC require on-region processing — most global AI platforms cannot comply.', 'respectful-warm', 'approved', 1),
('india', 'IND_NORTH', 'en', 'challenges', 'language_diversity', 'With 22 official languages and 700+ dialects, patient education content must go beyond Hindi-English to truly reach Bharat.', 'With 22 official languages and 700+ dialects, patient education content must go beyond Hindi-English to truly reach Bharat.', 'warm-aspirational', 'approved', 1),
('india', 'IND_NORTH', 'en', 'challenges', 'rural_access', 'Rural healthcare reaches only 30% of the population — offline-capable AI tools are essential, not optional.', 'Rural healthcare reaches only 30% of the population — offline-capable AI tools are essential, not optional.', 'warm-aspirational', 'approved', 1),
('india', 'IND_NORTH', 'en', 'challenges', 'ayushman_bharat', 'Ayushman Bharat Digital Mission demands interoperable, scalable content systems that most startups cannot afford to build.', 'Ayushman Bharat Digital Mission demands interoperable, scalable content systems that most startups cannot afford to build.', 'warm-aspirational', 'approved', 1),
('india', 'IND_NORTH', 'en', 'challenges', 'cost_sensitivity', 'Price-sensitive market requires enterprise-grade AI at startup-friendly pricing — global tools are 10x too expensive.', 'Price-sensitive market requires enterprise-grade AI at startup-friendly pricing — global tools are 10x too expensive.', 'warm-aspirational', 'approved', 1),
('india', 'IND_NORTH', 'en', 'challenges', 'doctor_ratio', '1 doctor per 1,000 patients means AI-assisted training and telehealth content must scale exponentially.', '1 doctor per 1,000 patients means AI-assisted training and telehealth content must scale exponentially.', 'warm-aspirational', 'approved', 1),
('sea', 'SEA_SG', 'en', 'challenges', 'multilingual_markets', '11 countries, 1,000+ languages — Southeast Asia is the ultimate stress test for multilingual content platforms.', '11 countries, 1,000+ languages — Southeast Asia is the ultimate stress test for multilingual content platforms.', 'friendly-pragmatic', 'approved', 1),
('sea', 'SEA_SG', 'en', 'challenges', 'mobile_first', '90%+ mobile internet penetration means all healthcare content must be mobile-native, not desktop-adapted.', '90%+ mobile internet penetration means all healthcare content must be mobile-native, not desktop-adapted.', 'friendly-pragmatic', 'approved', 1),
('sea', 'SEA_SG', 'en', 'challenges', 'regulatory_patchwork', 'Each ASEAN nation has different health data regulations — one solution must flex across Singapore, Thailand, Indonesia, and beyond.', 'Each ASEAN nation has different health data regulations — one solution must flex across Singapore, Thailand, Indonesia, and beyond.', 'friendly-pragmatic', 'approved', 1),
('sea', 'SEA_SG', 'en', 'challenges', 'traditional_medicine', 'Integrating traditional medicine knowledge with modern AI content requires cultural sensitivity that Western tools lack.', 'Integrating traditional medicine knowledge with modern AI content requires cultural sensitivity that Western tools lack.', 'friendly-pragmatic', 'approved', 1),
('sea', 'SEA_SG', 'en', 'challenges', 'island_connectivity', 'Archipelago nations like Indonesia and Philippines need offline-first content tools for remote island healthcare delivery.', 'Archipelago nations like Indonesia and Philippines need offline-first content tools for remote island healthcare delivery.', 'friendly-pragmatic', 'approved', 1),
('cjk', 'CJK_JP', 'en', 'challenges', 'quality_standards', 'Japan, Korea, and China demand pixel-perfect localization — machine translation is considered disrespectful to audiences.', 'Japan, Korea, and China demand pixel-perfect localization — machine translation is considered disrespectful to audiences.', 'refined-precise', 'approved', 1),
('cjk', 'CJK_JP', 'en', 'challenges', 'character_systems', 'Kanji, Hangul, and Simplified/Traditional Chinese require specialized rendering, typography, and NLP that most AI tools botch.', 'Kanji, Hangul, and Simplified/Traditional Chinese require specialized rendering, typography, and NLP that most AI tools botch.', 'refined-precise', 'approved', 1),
('cjk', 'CJK_JP', 'en', 'challenges', 'data_sovereignty', 'China''s PIPL, Japan''s APPI, and Korea''s PIPA create a complex web of data residency requirements for AI platforms.', 'China''s PIPL, Japan''s APPI, and Korea''s PIPA create a complex web of data residency requirements for AI platforms.', 'refined-precise', 'approved', 1),
('cjk', 'CJK_JP', 'en', 'challenges', 'aging_population', 'Rapidly aging populations in Japan and Korea demand accessible, elder-friendly healthcare content at unprecedented scale.', 'Rapidly aging populations in Japan and Korea demand accessible, elder-friendly healthcare content at unprecedented scale.', 'refined-precise', 'approved', 1),
('cjk', 'CJK_JP', 'en', 'challenges', 'platform_ecosystem', 'WeChat, LINE, KakaoTalk — each market has its own digital ecosystem that content must be natively formatted for.', 'WeChat, LINE, KakaoTalk — each market has its own digital ecosystem that content must be natively formatted for.', 'refined-precise', 'approved', 1)
ON CONFLICT DO NOTHING;
