
-- Seed regional holidays with correct array/jsonb syntax
INSERT INTO public.cast_regional_holidays (name, local_name, region_code, sub_region_code, holiday_date, holiday_type, description, color_palette, style_keywords, greeting_templates, suggested_capabilities, suggested_style_ids, music_mood, is_recurring, confidence_score, source) VALUES
('New Year', NULL, 'global', NULL, '2026-01-01', 'cultural', 'New Year celebrations worldwide', '["#FFD700","#C0C0C0","#000080","#FFFFFF"]'::jsonb, ARRAY['celebration','fireworks','countdown','sparkle'], '[{"language":"en","greeting":"Happy New Year!"},{"language":"es","greeting":"¡Feliz Año Nuevo!"},{"language":"hi","greeting":"नया साल मुबारक!"}]'::jsonb, ARRAY['ai_music','ai_sfx','captions','motion_graphics'], ARRAY[]::uuid[], 'upbeat_celebratory', true, 0.99, 'ai_generated'),
('Valentine''s Day', NULL, 'global', NULL, '2026-02-14', 'commercial', 'Day of love and romance', '["#FF1493","#FF69B4","#DC143C","#FFB6C1"]'::jsonb, ARRAY['romantic','hearts','love','pink','red'], '[{"language":"en","greeting":"Happy Valentine''s Day!"}]'::jsonb, ARRAY['ai_music','captions','motion_graphics'], ARRAY[]::uuid[], 'romantic_soft', true, 0.95, 'ai_generated'),
('International Women''s Day', NULL, 'global', NULL, '2026-03-08', 'awareness', 'Celebrating women worldwide', '["#800080","#FFD700","#FFFFFF","#FF69B4"]'::jsonb, ARRAY['empowerment','equality','purple','bold'], '[{"language":"en","greeting":"Happy International Women''s Day!"}]'::jsonb, ARRAY['captions','motion_graphics'], ARRAY[]::uuid[], 'empowering_upbeat', true, 0.90, 'ai_generated'),
('Earth Day', NULL, 'global', NULL, '2026-04-22', 'awareness', 'Environmental awareness day', '["#228B22","#87CEEB","#8B4513","#32CD32"]'::jsonb, ARRAY['nature','green','earth','eco'], '[{"language":"en","greeting":"Happy Earth Day! 🌍"}]'::jsonb, ARRAY['ai_music','captions'], ARRAY[]::uuid[], 'calm_nature', true, 0.88, 'ai_generated'),
('Halloween', NULL, 'global', NULL, '2026-10-31', 'cultural', 'Spooky season celebrations', '["#FF6600","#000000","#800080","#FFD700"]'::jsonb, ARRAY['spooky','halloween','gothic','dark','fun'], '[{"language":"en","greeting":"Happy Halloween! 🎃"}]'::jsonb, ARRAY['ai_music','ai_sfx','green_screen','ar_filters'], ARRAY[]::uuid[], 'spooky_fun', true, 0.95, 'ai_generated'),
('Christmas', NULL, 'global', NULL, '2026-12-25', 'religious', 'Christmas celebration', '["#C41E3A","#228B22","#FFD700","#FFFFFF"]'::jsonb, ARRAY['christmas','festive','winter','snow','santa','gifts'], '[{"language":"en","greeting":"Merry Christmas!"},{"language":"es","greeting":"¡Feliz Navidad!"},{"language":"fr","greeting":"Joyeux Noël!"}]'::jsonb, ARRAY['ai_music','ai_sfx','captions','motion_graphics','ar_filters'], ARRAY[]::uuid[], 'festive_joyful', true, 0.99, 'ai_generated'),
('Easter', NULL, 'global', NULL, '2026-04-05', 'religious', 'Christian Easter celebration', '["#FFD700","#FF69B4","#87CEEB","#FFFFFF"]'::jsonb, ARRAY['easter','spring','eggs','bunny'], '[{"language":"en","greeting":"Happy Easter!"}]'::jsonb, ARRAY['ai_music','captions','motion_graphics'], ARRAY[]::uuid[], 'joyful_spring', true, 0.94, 'ai_generated'),
('Mother''s Day', NULL, 'global', NULL, '2026-05-10', 'commercial', 'Celebrating mothers worldwide', '["#FF69B4","#FFB6C1","#FFFFFF","#FF1493"]'::jsonb, ARRAY['mother','love','family','gratitude'], '[{"language":"en","greeting":"Happy Mother''s Day!"}]'::jsonb, ARRAY['ai_music','captions'], ARRAY[]::uuid[], 'emotional_warm', true, 0.93, 'ai_generated'),
('Father''s Day', NULL, 'global', NULL, '2026-06-21', 'commercial', 'Celebrating fathers worldwide', '["#003366","#FFD700","#FFFFFF","#8B4513"]'::jsonb, ARRAY['father','family','gratitude','strength'], '[{"language":"en","greeting":"Happy Father''s Day!"}]'::jsonb, ARRAY['ai_music','captions'], ARRAY[]::uuid[], 'warm_strong', true, 0.93, 'ai_generated'),
('Black Friday', NULL, 'global', NULL, '2026-11-27', 'commercial', 'Major shopping event', '["#000000","#FFD700","#FF0000","#FFFFFF"]'::jsonb, ARRAY['sale','discount','shopping','deals','bold'], '[{"language":"en","greeting":"Black Friday Deals!"}]'::jsonb, ARRAY['captions','motion_graphics'], ARRAY[]::uuid[], 'energetic_urgent', true, 0.88, 'ai_generated'),
-- India
('Holi', 'होली', 'IN', 'IN-N', '2026-03-17', 'religious', 'Festival of colors', '["#FF0000","#FFFF00","#00FF00","#FF00FF","#0000FF"]'::jsonb, ARRAY['colors','festive','vibrant','splash','joy','spring'], '[{"language":"hi","greeting":"होली की शुभकामनाएं!"},{"language":"en","greeting":"Happy Holi!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics','ar_filters'], ARRAY[]::uuid[], 'energetic_festive', true, 0.97, 'ai_generated'),
('Diwali', 'दीवाली', 'IN', NULL, '2026-10-20', 'religious', 'Festival of lights', '["#FFD700","#FF6600","#8B0000","#FFFFFF","#800080"]'::jsonb, ARRAY['lights','diya','festive','gold','sparkle','rangoli'], '[{"language":"hi","greeting":"दीवाली की शुभकामनाएं! 🪔"},{"language":"en","greeting":"Happy Diwali!"},{"language":"ta","greeting":"தீபாவளி நல்வாழ்த்துக்கள்!"}]'::jsonb, ARRAY['ai_music','ai_sfx','captions','motion_graphics','ar_filters'], ARRAY[]::uuid[], 'festive_grand', true, 0.99, 'ai_generated'),
('Pongal', 'பொங்கல்', 'IN', 'IN-S', '2026-01-15', 'cultural', 'Tamil harvest festival', '["#FFD700","#FF6600","#228B22","#8B4513"]'::jsonb, ARRAY['harvest','traditional','south_india','kolam'], '[{"language":"ta","greeting":"இனிய பொங்கல் நல்வாழ்த்துக்கள்!"},{"language":"en","greeting":"Happy Pongal!"}]'::jsonb, ARRAY['ai_music','captions'], ARRAY[]::uuid[], 'traditional_festive', true, 0.92, 'ai_generated'),
('Onam', 'ഓണം', 'IN', 'IN-S', '2026-09-04', 'cultural', 'Kerala harvest festival', '["#FFD700","#FF6600","#228B22","#FFFFFF"]'::jsonb, ARRAY['traditional','kerala','boat_race','pookalam'], '[{"language":"ml","greeting":"ഓണാശംസകൾ!"},{"language":"en","greeting":"Happy Onam!"}]'::jsonb, ARRAY['ai_music','captions','motion_graphics'], ARRAY[]::uuid[], 'traditional_joyful', true, 0.90, 'ai_generated'),
('Raksha Bandhan', 'रक्षाबंधन', 'IN', 'IN-N', '2026-08-11', 'cultural', 'Brother-sister bond festival', '["#FF69B4","#FFD700","#FF6600","#FFFFFF"]'::jsonb, ARRAY['family','siblings','rakhi','love'], '[{"language":"hi","greeting":"रक्षाबंधन की शुभकामनाएं!"},{"language":"en","greeting":"Happy Raksha Bandhan!"}]'::jsonb, ARRAY['ai_music','captions'], ARRAY[]::uuid[], 'emotional_warm', true, 0.91, 'ai_generated'),
('Ganesh Chaturthi', 'गणेश चतुर्थी', 'IN', 'IN-W', '2026-08-22', 'religious', 'Lord Ganesha festival', '["#FF6600","#FFD700","#FF0000","#228B22"]'::jsonb, ARRAY['ganpati','festive','procession','devotion'], '[{"language":"hi","greeting":"गणेश चतुर्थी की शुभकामनाएं!"},{"language":"en","greeting":"Happy Ganesh Chaturthi!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics'], ARRAY[]::uuid[], 'devotional_festive', true, 0.93, 'ai_generated'),
('Navratri', 'नवरात्रि', 'IN', NULL, '2026-10-01', 'religious', 'Nine nights of divine feminine', '["#FF0000","#FFD700","#FF6600","#228B22","#800080"]'::jsonb, ARRAY['garba','dandiya','nine_nights','divine','dance'], '[{"language":"hi","greeting":"नवरात्रि की शुभकामनाएं!"},{"language":"en","greeting":"Happy Navratri!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics','ar_filters'], ARRAY[]::uuid[], 'energetic_devotional', true, 0.94, 'ai_generated'),
('Eid al-Fitr', 'عيد الفطر', 'IN', NULL, '2026-03-21', 'religious', 'End of Ramadan celebration', '["#228B22","#FFD700","#FFFFFF","#C0C0C0"]'::jsonb, ARRAY['eid','crescent','iftar','family'], '[{"language":"ar","greeting":"عيد مبارك!"},{"language":"en","greeting":"Eid Mubarak!"}]'::jsonb, ARRAY['ai_music','captions'], ARRAY[]::uuid[], 'peaceful_festive', true, 0.95, 'ai_generated'),
('Durga Puja', 'দুর্গা পূজা', 'IN', 'IN-E', '2026-10-01', 'religious', 'Bengali Goddess Durga festival', '["#FF0000","#FFD700","#FFFFFF","#FF6600"]'::jsonb, ARRAY['durga','bengali','pandal','dhunuchi'], '[{"language":"bn","greeting":"শুভ দুর্গাপূজা!"},{"language":"en","greeting":"Happy Durga Puja!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics'], ARRAY[]::uuid[], 'devotional_grand', true, 0.92, 'ai_generated'),
('Baisakhi', 'ਵਿਸਾਖੀ', 'IN', 'IN-N', '2026-04-14', 'cultural', 'Punjabi harvest and new year', '["#FF6600","#FFD700","#228B22","#FF0000"]'::jsonb, ARRAY['punjabi','harvest','bhangra','new_year'], '[{"language":"pa","greeting":"ਵਿਸਾਖੀ ਦੀਆਂ ਲੱਖ ਲੱਖ ਵਧਾਈਆਂ!"},{"language":"en","greeting":"Happy Baisakhi!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics'], ARRAY[]::uuid[], 'energetic_bhangra', true, 0.91, 'ai_generated'),
('Ugadi', 'ಉಗಾದಿ', 'IN', 'IN-S', '2026-03-19', 'cultural', 'Telugu/Kannada new year', '["#FFD700","#228B22","#FF6600","#FFFFFF"]'::jsonb, ARRAY['new_year','south_india','traditional'], '[{"language":"te","greeting":"ఉగాది శుభాకాంక్షలు!"},{"language":"en","greeting":"Happy Ugadi!"}]'::jsonb, ARRAY['ai_music','captions'], ARRAY[]::uuid[], 'traditional_spring', true, 0.88, 'ai_generated'),
('Makar Sankranti', 'मकर संक्रांति', 'IN', 'IN-W', '2026-01-14', 'cultural', 'Kite festival and harvest', '["#FF6600","#87CEEB","#FFD700","#FF0000"]'::jsonb, ARRAY['kites','harvest','winter','festive'], '[{"language":"hi","greeting":"मकर संक्रांति की शुभकामनाएं!"},{"language":"en","greeting":"Happy Makar Sankranti!"}]'::jsonb, ARRAY['ai_music','motion_graphics'], ARRAY[]::uuid[], 'festive_cheerful', true, 0.91, 'ai_generated'),
('Lohri', 'ਲੋਹੜੀ', 'IN', 'IN-N', '2026-01-13', 'cultural', 'Punjabi winter bonfire festival', '["#FF6600","#FFD700","#FF0000","#8B4513"]'::jsonb, ARRAY['bonfire','punjabi','winter','dance'], '[{"language":"pa","greeting":"ਲੋਹੜੀ ਦੀਆਂ ਲੱਖ ਲੱਖ ਵਧਾਈਆਂ!"},{"language":"en","greeting":"Happy Lohri!"}]'::jsonb, ARRAY['ai_music','ai_sfx'], ARRAY[]::uuid[], 'warm_festive', true, 0.89, 'ai_generated'),
-- MENA
('Ramadan', 'رمضان', 'MENA', NULL, '2026-02-18', 'religious', 'Holy month of fasting', '["#004225","#FFD700","#C0C0C0","#FFFFFF"]'::jsonb, ARRAY['ramadan','crescent','lantern','fasting','prayer'], '[{"language":"ar","greeting":"رمضان كريم!"},{"language":"en","greeting":"Ramadan Kareem!"}]'::jsonb, ARRAY['ai_music','captions','motion_graphics'], ARRAY[]::uuid[], 'peaceful_reflective', true, 0.97, 'ai_generated'),
('Eid al-Adha', 'عيد الأضحى', 'MENA', NULL, '2026-05-27', 'religious', 'Festival of sacrifice', '["#228B22","#FFD700","#FFFFFF","#8B4513"]'::jsonb, ARRAY['eid','sacrifice','family','devotion'], '[{"language":"ar","greeting":"عيد أضحى مبارك!"},{"language":"en","greeting":"Eid al-Adha Mubarak!"}]'::jsonb, ARRAY['ai_music','captions','motion_graphics'], ARRAY[]::uuid[], 'devotional_peaceful', true, 0.96, 'ai_generated'),
('Saudi National Day', 'اليوم الوطني', 'SA', NULL, '2026-09-23', 'national', 'Saudi Arabia National Day', '["#006C35","#FFFFFF"]'::jsonb, ARRAY['national','saudi','pride','heritage'], '[{"language":"ar","greeting":"اليوم الوطني السعودي!"},{"language":"en","greeting":"Happy Saudi National Day!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics'], ARRAY[]::uuid[], 'patriotic_grand', true, 0.90, 'ai_generated'),
('UAE National Day', 'اليوم الوطني الإماراتي', 'AE', NULL, '2026-12-02', 'national', 'UAE founding celebration', '["#FF0000","#228B22","#FFFFFF","#000000"]'::jsonb, ARRAY['national','uae','pride','heritage'], '[{"language":"ar","greeting":"يوم الإمارات الوطني!"},{"language":"en","greeting":"Happy UAE National Day!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics'], ARRAY[]::uuid[], 'patriotic_modern', true, 0.90, 'ai_generated'),
('Kuwait National Day', NULL, 'KW', NULL, '2026-02-25', 'national', 'Kuwait National Day', '["#007A33","#FFFFFF","#CE1126","#000000"]'::jsonb, ARRAY['kuwait','national','pride'], '[{"language":"ar","greeting":"العيد الوطني الكويتي!"},{"language":"en","greeting":"Happy Kuwait National Day!"}]'::jsonb, ARRAY['ai_music','motion_graphics'], ARRAY[]::uuid[], 'patriotic_modern', true, 0.85, 'ai_generated'),
-- East Asia
('Chinese New Year', '春节', 'CN', NULL, '2026-02-17', 'cultural', 'Lunar New Year — Year of the Horse', '["#FF0000","#FFD700","#FF6600","#800020"]'::jsonb, ARRAY['lunar','dragon','lantern','red_envelope','fireworks'], '[{"language":"zh","greeting":"新年快乐! 恭喜发财!"},{"language":"en","greeting":"Happy Chinese New Year!"}]'::jsonb, ARRAY['ai_music','ai_sfx','captions','motion_graphics','ar_filters'], ARRAY[]::uuid[], 'festive_traditional', true, 0.98, 'ai_generated'),
('Mid-Autumn Festival', '中秋节', 'CN', NULL, '2026-10-03', 'cultural', 'Mooncake festival', '["#FFD700","#FFA500","#8B4513"]'::jsonb, ARRAY['moon','mooncake','lantern','family'], '[{"language":"zh","greeting":"中秋节快乐!"},{"language":"en","greeting":"Happy Mid-Autumn Festival!"}]'::jsonb, ARRAY['ai_music','captions','motion_graphics'], ARRAY[]::uuid[], 'warm_nostalgic', true, 0.92, 'ai_generated'),
('Cherry Blossom Season', '桜', 'JP', NULL, '2026-04-01', 'seasonal', 'Sakura bloom season', '["#FFB7C5","#FFFFFF","#FF69B4","#228B22"]'::jsonb, ARRAY['sakura','spring','nature','pink','zen'], '[{"language":"ja","greeting":"お花見の季節です!"},{"language":"en","greeting":"Cherry Blossom Season!"}]'::jsonb, ARRAY['ai_music','captions','motion_graphics'], ARRAY[]::uuid[], 'peaceful_spring', true, 0.88, 'ai_generated'),
('Chuseok', '추석', 'KR', NULL, '2026-10-03', 'cultural', 'Korean harvest festival', '["#FFD700","#8B4513","#228B22"]'::jsonb, ARRAY['harvest','korean','traditional','family'], '[{"language":"ko","greeting":"추석 잘 보내세요!"},{"language":"en","greeting":"Happy Chuseok!"}]'::jsonb, ARRAY['ai_music','captions'], ARRAY[]::uuid[], 'traditional_warm', true, 0.90, 'ai_generated'),
-- Americas
('Thanksgiving', NULL, 'US', NULL, '2026-11-26', 'cultural', 'American Thanksgiving', '["#FF6600","#8B4513","#FFD700","#800020"]'::jsonb, ARRAY['harvest','family','gratitude','autumn'], '[{"language":"en","greeting":"Happy Thanksgiving!"}]'::jsonb, ARRAY['ai_music','captions'], ARRAY[]::uuid[], 'warm_family', true, 0.95, 'ai_generated'),
('Independence Day', NULL, 'US', NULL, '2026-07-04', 'national', 'US Independence Day', '["#002868","#BF0A30","#FFFFFF"]'::jsonb, ARRAY['patriotic','fireworks','freedom','stars'], '[{"language":"en","greeting":"Happy 4th of July!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics'], ARRAY[]::uuid[], 'patriotic_upbeat', true, 0.95, 'ai_generated'),
('Día de los Muertos', 'Día de Muertos', 'MX', NULL, '2026-11-01', 'cultural', 'Day of the Dead', '["#FF6600","#FFD700","#800080","#FF1493"]'::jsonb, ARRAY['calavera','marigold','ancestors','colorful'], '[{"language":"es","greeting":"¡Feliz Día de Muertos!"},{"language":"en","greeting":"Happy Day of the Dead!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics','ar_filters'], ARRAY[]::uuid[], 'festive_cultural', true, 0.93, 'ai_generated'),
('Carnival', 'Carnaval', 'BR', NULL, '2026-02-14', 'cultural', 'Brazilian Carnival', '["#FFD700","#228B22","#0000FF","#FF69B4"]'::jsonb, ARRAY['samba','dance','carnival','feathers','vibrant'], '[{"language":"pt","greeting":"Feliz Carnaval!"},{"language":"en","greeting":"Happy Carnival!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics','ar_filters'], ARRAY[]::uuid[], 'energetic_samba', true, 0.92, 'ai_generated'),
-- Europe
('Oktoberfest', NULL, 'DE', NULL, '2026-09-19', 'cultural', 'German beer festival', '["#003DA5","#FFFFFF","#FFD700","#8B4513"]'::jsonb, ARRAY['bavarian','beer','traditional','germany'], '[{"language":"de","greeting":"O zapft is! Prost!"},{"language":"en","greeting":"Happy Oktoberfest!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics'], ARRAY[]::uuid[], 'festive_bavarian', true, 0.88, 'ai_generated'),
('St. Patrick''s Day', NULL, 'IE', NULL, '2026-03-17', 'cultural', 'Irish cultural celebration', '["#228B22","#FFD700","#FFFFFF","#006400"]'::jsonb, ARRAY['irish','green','shamrock','lucky','celtic'], '[{"language":"en","greeting":"Happy St. Patrick''s Day! ☘️"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics','ar_filters'], ARRAY[]::uuid[], 'celtic_festive', true, 0.90, 'ai_generated'),
-- Southeast Asia
('Songkran', 'สงกรานต์', 'TH', NULL, '2026-04-13', 'cultural', 'Thai New Year water festival', '["#0000FF","#87CEEB","#FFD700","#FF6600"]'::jsonb, ARRAY['water','thai','new_year','splash','fun'], '[{"language":"th","greeting":"สุขสันต์วันสงกรานต์!"},{"language":"en","greeting":"Happy Songkran!"}]'::jsonb, ARRAY['ai_music','ai_sfx','motion_graphics','ar_filters'], ARRAY[]::uuid[], 'energetic_fun', true, 0.90, 'ai_generated'),
-- Africa
('Africa Day', NULL, 'AF', NULL, '2026-05-25', 'cultural', 'Pan-African unity celebration', '["#FFD700","#228B22","#FF0000","#000000"]'::jsonb, ARRAY['africa','unity','heritage','culture'], '[{"language":"en","greeting":"Happy Africa Day!"},{"language":"sw","greeting":"Siku ya Afrika!"}]'::jsonb, ARRAY['ai_music','captions','motion_graphics'], ARRAY[]::uuid[], 'upbeat_cultural', true, 0.85, 'ai_generated');

-- Update character thumbnails
UPDATE public.cast_style_characters SET thumbnail_url = 
  CASE name
    WHEN 'chibi_warrior' THEN 'https://api.dicebear.com/9.x/adventurer/svg?seed=warrior&backgroundColor=b6e3f4'
    WHEN 'chibi_wizard' THEN 'https://api.dicebear.com/9.x/adventurer/svg?seed=wizard&backgroundColor=d1d4f9'
    WHEN 'chibi_robot' THEN 'https://api.dicebear.com/9.x/bottts/svg?seed=robot&backgroundColor=b6e3f4'
    WHEN 'chibi_custom' THEN 'https://api.dicebear.com/9.x/adventurer/svg?seed=custom&backgroundColor=ffd5dc'
    WHEN 'wise_owl' THEN 'https://api.dicebear.com/9.x/bottts/svg?seed=owl&backgroundColor=c0aede'
    WHEN 'clever_fox' THEN 'https://api.dicebear.com/9.x/adventurer/svg?seed=fox&backgroundColor=ffdfbf'
    WHEN 'brave_bear' THEN 'https://api.dicebear.com/9.x/adventurer/svg?seed=bear&backgroundColor=d1d4f9'
    WHEN 'squirrel' THEN 'https://api.dicebear.com/9.x/adventurer/svg?seed=squirrel&backgroundColor=ffd5dc'
    WHEN 'custom_animal' THEN 'https://api.dicebear.com/9.x/adventurer/svg?seed=animal&backgroundColor=b6e3f4'
    WHEN 'brand_mascot' THEN 'https://api.dicebear.com/9.x/bottts/svg?seed=mascot&backgroundColor=ffdfbf'
    WHEN 'tech_buddy' THEN 'https://api.dicebear.com/9.x/bottts/svg?seed=techbuddy&backgroundColor=b6e3f4'
    WHEN 'health_hero' THEN 'https://api.dicebear.com/9.x/bottts/svg?seed=health&backgroundColor=c0aede'
    WHEN 'shonen_hero' THEN 'https://api.dicebear.com/9.x/adventurer/svg?seed=shonen&backgroundColor=ffd5dc'
    WHEN 'rival' THEN 'https://api.dicebear.com/9.x/adventurer/svg?seed=rival&backgroundColor=ffdfbf'
    ELSE 'https://api.dicebear.com/9.x/adventurer/svg?seed=' || name || '&backgroundColor=b6e3f4'
  END
WHERE thumbnail_url IS NULL;
