-- Insert EP04 "Beyond AI Hype" as an internal blueprint in video_blueprints
INSERT INTO video_blueprints (
  name,
  description,
  category,
  thumbnail_url,
  estimated_duration_seconds,
  target_platform,
  industry_tags,
  default_settings,
  style_preset,
  is_system_default,
  is_active,
  is_public,
  usage_count,
  style_intent,
  target_regions,
  tone_modifier,
  aesthetic_keywords,
  status
) VALUES (
  'EP04 — Beyond AI Hype',
  'Internal 12-scene cinematic documentary exploring AI beyond the hype. Features narration, screen recordings, and cinematic visuals across 104 script lines.',
  'technology',
  'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=640&h=360&fit=crop',
  780,
  ARRAY['youtube', 'internal', 'website'],
  ARRAY['technology', 'ai', 'documentary', 'internal'],
  '{"quality": "cinematic", "episodeId": "ep04"}'::jsonb,
  '{"styles": ["cinematic", "pixar-3d", "disney-2d"]}'::jsonb,
  false,
  true,
  false,
  0,
  'brand-documentary',
  ARRAY['global'],
  'authoritative',
  ARRAY['cinematic', 'futuristic', 'professional'],
  'draft'
);