-- ============================================================================
-- SEED cast_video_styles (43 styles from master registry)
-- ============================================================================
INSERT INTO public.cast_video_styles (value, label, icon, style_group, description, base_token_cost, is_active, is_system_default, sort_order) VALUES
('smart_storytelling', 'Smart Storytelling', 'BookOpen', 'storytelling', 'Narrative-driven content with emotional arcs', 150, true, true, 1),
('hook_videos', 'Hook Videos', 'Zap', 'storytelling', 'Fast-paced, attention-grabbing openings', 140, true, true, 2),
('micro_drama', 'Micro Drama', 'Film', 'storytelling', 'Short cinematic drama scenes', 160, true, true, 3),
('documentary', 'Documentary', 'Camera', 'storytelling', 'Long-form documentary style content', 180, true, false, 4),
('narrative_arc', 'Narrative Arc', 'TrendingUp', 'storytelling', 'Story with clear beginning, middle, end', 155, true, false, 5),
('testimonial', 'Testimonial', 'MessageCircle', 'storytelling', 'Customer/user testimonial videos', 130, true, false, 6),
('ugc_avatar_photorealistic', 'Photorealistic Avatar', 'User', 'avatar', 'Lifelike human avatar presenter', 200, true, true, 10),
('ugc_avatar_3d_pixar', '3D Pixar Avatar', 'Box', 'avatar', '3D animated character', 250, true, true, 11),
('ugc_avatar_2d_animated', '2D Animated Avatar', 'Palette', 'avatar', '2D cartoon style character', 190, true, true, 12),
('talking_photos', 'Talking Photos', 'Image', 'avatar', 'Animate static photos into talking avatars', 170, true, false, 13),
('full_body_avatar', 'Full Body Avatar', 'Users', 'avatar', 'Full-body animated presenter', 220, true, false, 14),
('digital_twin', 'Digital Twin', 'Layers', 'avatar', 'AI replica of real person', 280, true, false, 15),
('mascot_character', 'Mascot Character', 'Sparkles', 'avatar', 'Brand mascot or character', 200, true, false, 16),
('anime', 'Anime', 'Wand2', 'animation', 'Japanese anime-style animation', 210, true, true, 20),
('image_to_life', 'Image to Life', 'Image', 'animation', 'Animate static images with parallax', 160, true, true, 21),
('explainer_3d', '3D Explainer', 'Box', 'animation', '3D motion graphics explainer', 240, true, true, 22),
('motion_graphics', 'Motion Graphics', 'Layers', 'animation', 'Dynamic text and shape animations', 150, true, false, 23),
('kinetic_typography', 'Kinetic Typography', 'Type', 'animation', 'Animated text effects', 120, true, false, 24),
('whiteboard', 'Whiteboard Animation', 'PenTool', 'animation', 'Hand-drawn whiteboard style', 140, true, false, 25),
('educational', 'Educational', 'GraduationCap', 'interactive', 'Learning content with voiceover', 140, true, true, 30),
('interactive_quiz', 'Interactive Quiz', 'MousePointer', 'interactive', 'Embedded quiz overlays and interactions', 180, true, true, 31),
('cta_videos', 'CTA Videos', 'ShoppingCart', 'interactive', 'Call-to-action focused videos', 150, true, true, 32),
('shoppable_video', 'Shoppable Video', 'ShoppingCart', 'interactive', 'Clickable product links in video', 200, true, false, 33),
('branching_narrative', 'Branching Narrative', 'GitBranch', 'interactive', 'User-choice interactive storytelling', 220, true, false, 34),
('social', 'Social Media', 'Share2', 'marketing', 'Optimized for TikTok, Instagram, Reels', 130, true, true, 40),
('video_ads', 'Video Ads', 'Megaphone', 'marketing', 'Advertising campaign videos', 160, true, true, 41),
('product_demo', 'Product Demo', 'Monitor', 'marketing', 'Product feature showcase', 140, true, true, 42),
('comparison', 'Comparison', 'Scale', 'marketing', 'Side-by-side product comparison', 170, true, false, 43),
('case_study', 'Case Study', 'FileText', 'marketing', 'Success story and results showcase', 180, true, false, 44),
('event_promo', 'Event Promo', 'Calendar', 'marketing', 'Event promotion and announcements', 140, true, false, 45),
('behind_scenes', 'Behind the Scenes', 'Eye', 'marketing', 'BTS content for authenticity', 130, true, false, 46),
('news_update', 'News Update', 'Newspaper', 'marketing', 'Company news and announcements', 140, true, false, 47),
('corporate_training', 'Corporate Training', 'Building', 'enterprise', 'Employee onboarding and training', 160, true, true, 50),
('internal_comms', 'Internal Comms', 'Users', 'enterprise', 'Internal company announcements', 130, true, true, 51),
('investor_update', 'Investor Update', 'TrendingUp', 'enterprise', 'Shareholder and investor communications', 190, true, false, 52),
('compliance_training', 'Compliance Training', 'Shield', 'enterprise', 'Regulatory and compliance training', 170, true, false, 53),
('patient_education', 'Patient Education', 'Heart', 'healthcare', 'Patient-facing medical education', 160, true, true, 60),
('provider_training', 'Provider Training', 'Activity', 'healthcare', 'Clinical staff training', 180, true, true, 61),
('medical_explainer', 'Medical Explainer', 'Heart', 'healthcare', 'Medical procedure and condition explainer', 170, true, false, 62),
('gaming_trailer', 'Gaming Trailer', 'Gamepad', 'entertainment', 'Game launch and promo trailers', 200, true, false, 70),
('music_video', 'Music Video', 'Music', 'entertainment', 'Music video production', 220, true, false, 71),
('short_film', 'Short Film', 'Clapperboard', 'entertainment', 'Short narrative film', 240, true, false, 72),
('podcast_video', 'Podcast Video', 'Mic', 'entertainment', 'Podcast with video accompaniment', 150, true, false, 73);

-- ============================================================================
-- SEED cast_ai_capabilities (10 capabilities)
-- ============================================================================
INSERT INTO public.cast_ai_capabilities (value, label, icon, description, base_token_cost, is_active) VALUES
('video_generation', 'Video Generation', 'Film', 'AI video synthesis from text/images', 200, true),
('avatar_generation', 'Avatar Generation', 'User', 'Create AI-powered avatars', 250, true),
('lip_sync', 'Lip Sync', 'Mic2', 'Synchronize avatar mouth to audio', 100, true),
('tts', 'Text-to-Speech', 'Volume2', 'Convert text to natural audio', 50, true),
('animation', 'Animation', 'Wand2', 'Motion graphics and effects', 150, true),
('3d_generation', '3D Generation', 'Box', 'Create 3D models and scenes', 300, true),
('image_generation', 'Image Generation', 'Image', 'AI image synthesis', 80, true),
('voice_cloning', 'Voice Cloning', 'Mic', 'Clone voice from sample', 120, true),
('translation', 'Translation', 'Languages', 'Translate content to multiple languages', 60, true),
('transcription', 'Transcription', 'FileText', 'Convert audio to text', 40, true);

-- ============================================================================
-- SEED cast_style_capability_map (style → capability mappings)
-- ============================================================================
INSERT INTO public.cast_style_capability_map (style_value, capability_value, is_required, token_multiplier) VALUES
('smart_storytelling', 'video_generation', true, 1.0),
('smart_storytelling', 'tts', true, 0.8),
('smart_storytelling', 'animation', false, 0.5),
('hook_videos', 'video_generation', true, 1.0),
('hook_videos', 'tts', true, 0.8),
('hook_videos', 'animation', false, 0.6),
('micro_drama', 'video_generation', true, 1.0),
('micro_drama', 'animation', false, 0.7),
('micro_drama', 'tts', true, 0.8),
('ugc_avatar_photorealistic', 'avatar_generation', true, 1.0),
('ugc_avatar_photorealistic', 'lip_sync', true, 0.8),
('ugc_avatar_photorealistic', 'tts', true, 0.8),
('ugc_avatar_3d_pixar', 'avatar_generation', true, 1.2),
('ugc_avatar_3d_pixar', '3d_generation', true, 1.5),
('ugc_avatar_3d_pixar', 'animation', true, 1.0),
('ugc_avatar_3d_pixar', 'lip_sync', true, 0.8),
('ugc_avatar_3d_pixar', 'tts', true, 0.8),
('ugc_avatar_2d_animated', 'avatar_generation', true, 1.0),
('ugc_avatar_2d_animated', 'animation', true, 0.8),
('ugc_avatar_2d_animated', 'tts', true, 0.8),
('talking_photos', 'avatar_generation', true, 0.8),
('talking_photos', 'lip_sync', true, 0.8),
('talking_photos', 'tts', true, 0.8),
('anime', 'animation', true, 1.0),
('anime', 'tts', true, 0.8),
('anime', 'video_generation', false, 0.5),
('image_to_life', 'animation', true, 0.8),
('image_to_life', 'video_generation', true, 0.8),
('image_to_life', 'tts', false, 0.5),
('explainer_3d', '3d_generation', true, 1.5),
('explainer_3d', 'animation', true, 1.0),
('explainer_3d', 'tts', true, 0.8),
('educational', 'video_generation', true, 1.0),
('educational', 'tts', true, 0.8),
('educational', 'animation', false, 0.5),
('interactive_quiz', 'video_generation', true, 1.0),
('interactive_quiz', 'animation', false, 0.6),
('interactive_quiz', 'tts', true, 0.8),
('cta_videos', 'video_generation', true, 1.0),
('cta_videos', 'animation', false, 0.5),
('cta_videos', 'tts', true, 0.8),
('social', 'video_generation', true, 1.0),
('social', 'animation', false, 0.5),
('social', 'tts', false, 0.4),
('video_ads', 'video_generation', true, 1.0),
('video_ads', 'avatar_generation', false, 0.5),
('video_ads', 'tts', true, 0.8),
('product_demo', 'video_generation', true, 1.0),
('product_demo', 'tts', true, 0.8),
('corporate_training', 'video_generation', true, 1.0),
('corporate_training', 'avatar_generation', false, 0.5),
('corporate_training', 'tts', true, 0.8),
('corporate_training', 'transcription', false, 0.3),
('internal_comms', 'video_generation', true, 1.0),
('internal_comms', 'tts', true, 0.8),
('patient_education', 'video_generation', true, 1.0),
('patient_education', 'animation', false, 0.5),
('patient_education', 'tts', true, 0.8),
('provider_training', 'video_generation', true, 1.0),
('provider_training', 'tts', true, 0.8);

-- ============================================================================
-- SEED cast_capability_provider_map (correct columns: provider_value, provider_label)
-- ============================================================================
INSERT INTO public.cast_capability_provider_map (capability_value, provider_value, provider_label, fallback_order, zone, is_active) VALUES
('video_generation', 'vertex-veo', 'Google Vertex Veo', 1, 'any', true),
('video_generation', 'alibaba-wan', 'Alibaba Wan', 2, 'asia', true),
('video_generation', 'modelslab', 'ModelsLab', 3, 'any', true),
('video_generation', 'replicate', 'Replicate', 4, 'any', true),
('avatar_generation', 'alibaba-wan2.2', 'Alibaba Wan 2.2', 1, 'any', true),
('avatar_generation', 'alibaba-omniavatar', 'Alibaba OmniAvatar', 2, 'asia', true),
('avatar_generation', 'meshy-3d', 'Meshy 3D', 3, 'any', true),
('lip_sync', 'alibaba-wan2.2', 'Alibaba Wan 2.2', 1, 'asia', true),
('lip_sync', 'alibaba-mach', 'Alibaba MACH', 2, 'asia', true),
('lip_sync', 'vertex-lip-sync', 'Vertex Lip Sync', 3, 'any', true),
('tts', 'elevenlabs', 'ElevenLabs', 1, 'any', true),
('tts', 'google-tts', 'Google TTS', 2, 'any', true),
('tts', 'azure-tts', 'Azure Neural TTS', 3, 'any', true),
('animation', 'modelslab', 'ModelsLab', 1, 'any', true),
('animation', 'alibaba-wan', 'Alibaba Wan', 2, 'asia', true),
('animation', 'replicate', 'Replicate', 3, 'any', true),
('3d_generation', 'meshy-3d', 'Meshy 3D', 1, 'any', true),
('3d_generation', 'tripo3d', 'Tripo3D', 2, 'any', true),
('3d_generation', 'alibaba-richdreamer', 'Alibaba RichDreamer', 3, 'asia', true),
('image_generation', 'midjourney', 'Midjourney', 1, 'any', true),
('image_generation', 'dall-e', 'DALL-E', 2, 'any', true),
('image_generation', 'stability-ai', 'Stability AI', 3, 'any', true),
('voice_cloning', 'elevenlabs', 'ElevenLabs', 1, 'any', true),
('voice_cloning', 'descript', 'Descript', 2, 'any', true),
('translation', 'google-translate', 'Google Translate', 1, 'any', true),
('translation', 'deepl', 'DeepL', 2, 'any', true),
('translation', 'azure-translator', 'Azure Translator', 3, 'any', true),
('transcription', 'whisper-api', 'Whisper API', 1, 'any', true),
('transcription', 'assembly-ai', 'AssemblyAI', 2, 'any', true),
('transcription', 'google-stt', 'Google STT', 3, 'any', true);

-- ============================================================================
-- SEED cast_style_platform_map (correct columns: platform_id, is_recommended)
-- ============================================================================
INSERT INTO public.cast_style_platform_map (style_value, platform_id, is_recommended, sort_order) VALUES
('smart_storytelling', 'youtube', true, 1),
('smart_storytelling', 'blog', false, 2),
('smart_storytelling', 'email', false, 3),
('hook_videos', 'tiktok', true, 1),
('hook_videos', 'instagram', true, 2),
('hook_videos', 'reels', true, 3),
('micro_drama', 'youtube', true, 1),
('micro_drama', 'vimeo', false, 2),
('ugc_avatar_photorealistic', 'website', true, 1),
('ugc_avatar_photorealistic', 'sales-page', false, 2),
('ugc_avatar_photorealistic', 'email', false, 3),
('ugc_avatar_3d_pixar', 'youtube', true, 1),
('ugc_avatar_3d_pixar', 'website', false, 2),
('ugc_avatar_2d_animated', 'tiktok', true, 1),
('ugc_avatar_2d_animated', 'instagram', true, 2),
('anime', 'youtube', true, 1),
('anime', 'tiktok', false, 2),
('image_to_life', 'social-media', true, 1),
('explainer_3d', 'website', true, 1),
('explainer_3d', 'youtube', false, 2),
('educational', 'lms', true, 1),
('educational', 'website', false, 2),
('interactive_quiz', 'website', true, 1),
('cta_videos', 'landing-page', true, 1),
('social', 'tiktok', true, 1),
('social', 'instagram', true, 2),
('social', 'reels', true, 3),
('video_ads', 'youtube', true, 1),
('video_ads', 'facebook', true, 2),
('product_demo', 'website', true, 1),
('product_demo', 'sales-page', false, 2),
('corporate_training', 'lms', true, 1),
('corporate_training', 'internal-portal', false, 2),
('internal_comms', 'slack', true, 1),
('internal_comms', 'email', false, 2),
('patient_education', 'patient-portal', true, 1),
('patient_education', 'website', false, 2),
('provider_training', 'lms', true, 1);

-- ============================================================================
-- SEED cast_intent_style_map (correct columns: relevance_score, sort_order)
-- ============================================================================
INSERT INTO public.cast_intent_style_map (intent_value, style_value, relevance_score, sort_order) VALUES
('product-demo', 'product_demo', 1.0, 1),
('product-demo', 'video_ads', 0.8, 2),
('product-demo', 'comparison', 0.7, 3),
('customer-engagement', 'testimonial', 1.0, 1),
('customer-engagement', 'case_study', 0.8, 2),
('customer-engagement', 'hook_videos', 0.7, 3),
('educational', 'educational', 1.0, 1),
('educational', 'explainer_3d', 0.8, 2),
('educational', 'corporate_training', 0.7, 3),
('brand-awareness', 'social', 1.0, 1),
('brand-awareness', 'behind_scenes', 0.8, 2),
('brand-awareness', 'hook_videos', 0.7, 3),
('sales', 'video_ads', 1.0, 1),
('sales', 'product_demo', 0.9, 2),
('sales', 'cta_videos', 0.8, 3),
('storytelling', 'smart_storytelling', 1.0, 1),
('storytelling', 'micro_drama', 0.8, 2),
('storytelling', 'narrative_arc', 0.7, 3),
('internal-comms', 'internal_comms', 1.0, 1),
('internal-comms', 'corporate_training', 0.8, 2);
