
-- Update the blueprint with accurate metadata from EP04 production config
UPDATE video_blueprints SET
  description = 'Internal 12-scene cinematic documentary exploring AI beyond the hype. Features narration, screen recordings, and cinematic visuals across 104 script lines. 5 characters: Host (Sai Dasika), Atlas (Claude), Nova (Lovable), Allaudin (Genie), Squirrel. Pixar 3D + Disney 2D animation styles.',
  estimated_duration_seconds = 1620,
  style_preset = '"cinematic"'::jsonb,
  style_intent = 'product-hero',
  capability_tags = ARRAY['avatar_talking_head', 'lip_sync', 'scene_voiceover', 'screen_recording', 'text_to_video'],
  target_platform = ARRAY['youtube', 'internal', 'website'],
  industry_tags = ARRAY['technology', 'ai', 'documentary', 'internal'],
  default_settings = jsonb_build_object(
    'characters', jsonb_build_object(
      'host', jsonb_build_object('name', 'Host (Sai Dasika)', 'role', 'Product Owner', 'tts_provider', 'elevenlabs', 'voice_id', 'nPczCjzI2devNBz1zQrb', 'style', 'conversational'),
      'atlas', jsonb_build_object('name', 'Atlas (Claude)', 'role', 'Backend Tech Lead', 'tts_provider', 'azure', 'voice_id', 'en-US-GuyNeural', 'style', 'professional'),
      'nova', jsonb_build_object('name', 'Nova (Lovable)', 'role', 'Frontend Dev', 'tts_provider', 'elevenlabs', 'voice_id', 'pFZP5JQG7iQjIQuC4Bku', 'style', 'energetic'),
      'allaudin', jsonb_build_object('name', 'Allaudin (Genie)', 'role', 'Narrator', 'tts_provider', 'elevenlabs', 'voice_id', 'JBFqnCBsd6RMkjVDRZzb', 'style', 'theatrical'),
      'squirrel', jsonb_build_object('name', 'Squirrel', 'role', 'Comic Relief', 'tts_provider', 'elevenlabs', 'voice_id', 'iP95p4xoKVk53GoZ742B', 'style', 'chaotic')
    ),
    'visual_styles', to_jsonb(ARRAY['pixar-3d', 'disney-2d', 'hybrid-2.5d']),
    'resolution', '1920x1080',
    'aspect_ratio', '16:9',
    'production_quality', 'cinematic'
  ),
  status = 'active',
  updated_at = now()
WHERE id = 'cafcd78a-7957-4021-ba8f-c20daba331b2';

-- Insert all 11 scenes from EP04 production config
INSERT INTO blueprint_scenes (blueprint_id, scene_key, title, description, order_index, scene_type, duration_seconds, min_duration_seconds, max_duration_seconds, is_optional, visual_config, audio_config) VALUES
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-1-cold-open', 'Cold Open — The Hook', '41 tasks. 5 days. 2 AI developers. Kinetic text reveal with sprint dashboard montage.', 1, 'intro', 25, 20, 35, false, '{"pipelines":["kinetic-text","screen-capture","motion-graphics"],"screen_ids":["po-mission-control"],"kinetic_text":"41 tasks. 5 days. 2 AI developers."}'::jsonb, '{"voice":"host","script_key":"cold-open-narration","music_style":"dramatic","music_bpm":100,"sfx":["countdown-beeps","whoosh-reveal"]}'::jsonb),
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-2-meet-team', 'Meet the Team — Atlas, Nova & Host', 'Character introductions with Pixar 3D avatars, lip-sync, and personality reveals.', 2, 'character-intro', 60, 50, 75, false, '{"pipelines":["avatar-3d","avatar-lipsync","screen-capture","kinetic-text"],"characters":["host","atlas","nova"],"avatar_styles":{"host":"pixar-3d","atlas":"pixar-3d","nova":"disney-2d"},"screen_ids":["po-actions"]}'::jsonb, '{"voices":["host","atlas","nova"],"script_keys":["meet-host","atlas-847-lines","host-847-response","nova-waiting-suboptimal"],"music_style":"cinematic","music_bpm":110,"sfx":["character-sparkle","text-slam","typing-rapid"]}'::jsonb),
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-3-governance', 'Governance — Territory Rules', 'Sprint charter with AI-enhanced screen captures and territory map flyover.', 3, 'exposition', 45, 35, 55, false, '{"pipelines":["screen-capture","ai-screen-enhance","alibaba-video","alibaba-image","avatar-lipsync"],"screen_ids":["sprint-charter","governance-guide"],"enhance_mode":"highlight","characters":["atlas","nova"]}'::jsonb, '{"voices":["host","atlas","nova"],"script_keys":["governance-narration","atlas-merge-conflict","host-governance-not-overkill","nova-read-relevant-sections"],"music_style":"corporate","music_bpm":95}'::jsonb),
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-4-day1', 'Day 1 — The Sprint Begins', '12 tasks started. Atlas diagnoses 847-line session instructions. Scope creep detected.', 4, 'narrative', 50, 40, 65, false, '{"pipelines":["screen-capture","ai-screen-enhance","avatar-3d","avatar-lipsync","kinetic-text"],"screen_ids":["day-1-view","findings-qa"],"characters":["atlas","nova"]}'::jsonb, '{"voices":["host","nova"],"script_keys":["day1-narration","nova-refactored-nav","host-not-in-scope","nova-works-better"],"music_style":"upbeat","music_bpm":115}'::jsonb),
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-5-day2', 'Day 2 — The Blocker', 'Nova blocked 6 hours. Velocity dip. Frozen task animation. PO Actions dashboard built.', 5, 'conflict', 55, 45, 70, false, '{"pipelines":["screen-capture","ai-screen-enhance","alibaba-video","avatar-lipsync"],"screen_ids":["day-2-view","po-actions"],"characters":["nova","atlas"]}'::jsonb, '{"voices":["host","nova","atlas"],"script_keys":["day2-velocity-narration","nova-blocked-six-hours","host-in-a-meeting","atlas-human-meetings","host-po-actions-built"],"music_style":"dramatic","music_bpm":90}'::jsonb),
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-6-day3', 'Day 3 — Velocity Mismatch', 'Claude 8 tasks/day vs Lovable 3. Velocity chart diverging lines.', 6, 'rising-action', 40, 30, 50, false, '{"pipelines":["screen-capture","ai-screen-enhance","avatar-3d","avatar-lipsync","alibaba-video"],"screen_ids":["day-3-view","velocity-metrics"],"characters":["atlas","nova"],"avatar_styles":{"atlas":"pixar-3d","nova":"disney-2d"}}'::jsonb, '{"voices":["host","nova"],"script_keys":["day3-velocity-mismatch","nova-scope-now"],"music_style":"electronic","music_bpm":125}'::jsonb),
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-7-mission-control', 'Mission Control — Async Standups', 'PO Mission Control as async standup replacement. Standup entries, QA sign-off, EOD handoff.', 7, 'showcase', 60, 50, 75, false, '{"pipelines":["screen-capture","ai-screen-enhance","alibaba-video","avatar-lipsync"],"screen_ids":["po-mission-control","standup-entries","qa-signoff","eod-handoff"],"characters":["atlas","nova","host"]}'::jsonb, '{"voices":["host","atlas","nova"],"script_keys":["mission-control-narration","atlas-context-loss","nova-200k-window","host-forgot-breakfast"],"music_style":"cinematic","music_bpm":100}'::jsonb),
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-8-dashboard-tour', 'Dashboard Tour — 18 Screens', 'Rapid montage of all 18 sprint tracker screens with Ken Burns animation.', 8, 'montage', 50, 40, 65, false, '{"pipelines":["screen-capture","alibaba-video","avatar-lipsync"],"screen_ids":["po-mission-control","po-actions","day-1-view","day-2-view","day-3-view","day-4-view","day-5-view","backlog-view","velocity-metrics","effort-tracking","project-plan","findings-qa","qa-signoff","eod-handoff","sprint-charter","governance-guide","shared-infra-feed","territory-guardrails"],"multi_capture":true,"characters":["host"]}'::jsonb, '{"voices":["host"],"script_keys":["tour-narration"],"music_style":"electronic","music_bpm":130}'::jsonb),
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-9-numbers', 'The Numbers — 5x Results', 'Grand reveal: 41 tasks, 5x speed, zero blockers. Animated infographic.', 9, 'climax', 40, 30, 50, false, '{"pipelines":["alibaba-image","alibaba-video","screen-capture","ai-screen-enhance","avatar-lipsync"],"screen_ids":["velocity-metrics"],"characters":["host"]}'::jsonb, '{"voices":["host"],"script_keys":["numbers-narration"],"music_style":"epic","music_bpm":105}'::jsonb),
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-10-whats-next', 'What''s Next — Vision', 'Multi-language zones, MCP network, velocity prediction. World map animations.', 10, 'vision', 55, 45, 70, false, '{"pipelines":["alibaba-video","avatar-lipsync"],"characters":["atlas"]}'::jsonb, '{"voices":["host","atlas"],"script_keys":["whats-next-narration","atlas-language-foundational","atlas-data-quality","host-atlas-said"],"music_style":"inspirational","music_bpm":90}'::jsonb),
('cafcd78a-7957-4021-ba8f-c20daba331b2', 'scene-11-close', 'Close — Takeaway & CTA', 'All three characters in Pixar finale. End card with holographic text.', 11, 'outro', 35, 25, 45, false, '{"pipelines":["avatar-3d","avatar-lipsync","screen-capture","alibaba-video"],"screen_ids":["day-5-view"],"characters":["host","atlas","nova"],"avatar_styles":{"host":"pixar-3d","atlas":"pixar-3d","nova":"disney-2d"}}'::jsonb, '{"voices":["host","atlas","nova"],"script_keys":["close-takeaway","atlas-final","nova-final","close-cta"],"music_style":"cinematic","music_bpm":95}'::jsonb);
