// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read credentials from Vite env variables.
// Define them in your `.env` (not committed) or `.env.local`:
//  VITE_SUPABASE_URL="https://xxxx.supabase.co"
//  VITE_SUPABASE_ANON_KEY="your_anon_public_key"

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "[Supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY env vars.\n" +
    "Auth hooks will remain unauthenticated until these are provided."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    headers: {
      // Use the new-style Authorization header so the project can keep
      // "legacy API key headers" disabled in Supabase settings.
      Authorization: `Bearer ${SUPABASE_PUBLISHABLE_KEY}`,
    },
  },
});