name: CI & CD

on:
  push:
    branches: [dev, test, uat, main]
  pull_request:
    branches: [dev, test, uat, main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID:   ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Unit tests
        run: npm run test:unit -- --run

      - name: Build (static assets)
        run: npm run build

      # ------------------------------------------------------------------
      # Database migrations
      # ------------------------------------------------------------------
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.169.0

      - name: Determine schema based on branch
        id: schema
        run: |
          BRANCH=${{ github.ref_name }}
          case "$BRANCH" in
            main)
              echo "schema=public" >> $GITHUB_OUTPUT
              ;;
            dev)
              echo "schema=public_dev" >> $GITHUB_OUTPUT
              ;;
            test)
              echo "schema=public_test" >> $GITHUB_OUTPUT
              ;;
            uat)
              echo "schema=public_uat" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "schema=public_tmp" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Push migrations to branch schema
        run: supabase db push --schema "${{ steps.schema.outputs.schema }}" --remote