name: Supabase Migrate

# Run on every push to long-lived branches
on:
  push:
    branches: [ main, dev, test ]

permissions:
  contents: read

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID:   ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.169.0

      - name: Pick schema based on branch
        id: schema
        run: |
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            echo "schema=public"   >> "$GITHUB_OUTPUT"
          elif [ "$GITHUB_REF_NAME" = "dev" ]; then
            echo "schema=public_dev"   >> "$GITHUB_OUTPUT"
          else
            echo "schema=public_test"  >> "$GITHUB_OUTPUT"
          fi

      - name: Push migrations to remote project
        run: supabase db push --schema "${{ steps.schema.outputs.schema }}" --remote